// Game Mode — Multiple Choice Question Bank
// Each question: question, 4 answer choices, correct answer index (0-3), category
export type MCQ = { q: string; choices: string[]; correct: number; cat: string };

export const IB_QUESTIONS: MCQ[] = [
  // ── Accounting ──
  {q:"Net income is $100. Depreciation is $20. Change in AR is +$15. Change in AP is +$10. What is cash flow from operations?",choices:["$115","$95","$125","$105"],correct:0,cat:"Accounting"},
  {q:"A company records $50 of depreciation. Tax rate is 40%. What is the net impact on cash?",choices:["+$20","-$30","+$50","-$50"],correct:0,cat:"Accounting"},
  {q:"Which financial statement is most useful for evaluating a company's liquidity?",choices:["Income Statement","Balance Sheet","Cash Flow Statement","Statement of Equity"],correct:2,cat:"Accounting"},
  {q:"Inventory increases by $10, paid in cash. What happens to net income?",choices:["Decreases by $10","No change","Increases by $10","Decreases by $6"],correct:1,cat:"Accounting"},
  {q:"Accounts receivable increases by $20. What does this indicate on the cash flow statement?",choices:["Cash inflow of $20","Cash outflow of $20","No impact on cash","Cash inflow of $12"],correct:1,cat:"Accounting"},
  {q:"Which of these is NOT a non-cash expense?",choices:["Depreciation","Amortization","Stock-based compensation","Interest expense"],correct:3,cat:"Accounting"},
  {q:"A company issues $100 in debt. Where does this appear on the cash flow statement?",choices:["Operating activities","Investing activities","Financing activities","It doesn't appear"],correct:2,cat:"Accounting"},
  {q:"Deferred revenue increases by $30. What is the cash flow impact?",choices:["Cash inflow of $30","Cash outflow of $30","No impact","Cash inflow of $18"],correct:0,cat:"Accounting"},
  {q:"Capital expenditures of $50 appear in which section of the cash flow statement?",choices:["Operating","Investing","Financing","None — CapEx is non-cash"],correct:1,cat:"Accounting"},
  {q:"What does a negative change in working capital mean for cash flow?",choices:["Cash is being consumed","Cash is being generated","No impact on cash","It depends on the tax rate"],correct:1,cat:"Accounting"},
  {q:"Goodwill is created when:",choices:["A company buys back stock","Purchase price exceeds fair value of net assets acquired","A company writes down an asset","Revenue exceeds expenses"],correct:1,cat:"Accounting"},
  {q:"Goodwill impairment affects which statements?",choices:["Only the income statement","Income statement and balance sheet","Only the balance sheet","All three statements"],correct:3,cat:"Accounting"},
  {q:"A company sells equipment for $80 that has a book value of $60. Tax rate is 25%. What is the cash impact?",choices:["$80","$75","$60","$85"],correct:1,cat:"Accounting"},
  {q:"Which is true about operating leases under ASC 842?",choices:["They don't appear on the balance sheet","They create a right-of-use asset and lease liability","They are treated the same as finance leases","They only affect the income statement"],correct:1,cat:"Accounting"},
  {q:"Prepaid expenses decrease by $15. What is the cash flow impact?",choices:["Cash outflow of $15","Cash inflow of $15","No impact","Cash outflow of $9"],correct:1,cat:"Accounting"},
  {q:"Accrued expenses increase by $25. This represents:",choices:["Cash paid for expenses","Expenses incurred but not yet paid","Revenue earned but not collected","Prepaid amounts"],correct:1,cat:"Accounting"},
  {q:"Stock-based compensation is added back on the cash flow statement because:",choices:["It increases cash","It's a non-cash expense that reduced net income","It's not a real expense","The company received cash from options"],correct:1,cat:"Accounting"},
  {q:"Which of these increases shareholders' equity?",choices:["Issuing dividends","Net loss","Issuing new shares","Share buyback"],correct:2,cat:"Accounting"},
  {q:"A $100 write-down of inventory (25% tax rate) does what to cash?",choices:["Decreases cash by $100","Increases cash by $25","Decreases cash by $75","No direct cash impact"],correct:1,cat:"Accounting"},
  {q:"Revenue recognition under ASC 606 has how many steps?",choices:["3","4","5","6"],correct:2,cat:"Accounting"},
  // ── Valuation ──
  {q:"Enterprise Value equals:",choices:["Market Cap + Cash - Debt","Market Cap + Net Debt + Minority Interest + Preferred","Market Cap only","Market Cap - Net Debt"],correct:1,cat:"Valuation"},
  {q:"Why do we add debt and subtract cash when calculating Enterprise Value?",choices:["Because debt increases a company's value","Because EV represents value to all capital providers, and an acquirer assumes debt but gets the cash","Because cash is not an operating asset","Because debt is cheaper than equity"],correct:1,cat:"Valuation"},
  {q:"A company has a market cap of $500M, debt of $200M, cash of $50M, and no preferred/minority. What is EV?",choices:["$650M","$750M","$550M","$700M"],correct:0,cat:"Valuation"},
  {q:"Which valuation methodology typically yields the highest value?",choices:["Trading comps","DCF","Precedent transactions","Book value"],correct:2,cat:"Valuation"},
  {q:"Why do precedent transactions typically show higher multiples?",choices:["They use forward estimates","They include control premiums and synergies","They exclude debt","They use revenue instead of EBITDA"],correct:1,cat:"Valuation"},
  {q:"In a DCF, which discount rate do you use for unlevered free cash flows?",choices:["Cost of equity","Cost of debt","WACC","Risk-free rate"],correct:2,cat:"Valuation"},
  {q:"Terminal value in a DCF typically represents what percentage of total value?",choices:["10-20%","30-40%","50-80%","90-100%"],correct:2,cat:"Valuation"},
  {q:"If WACC increases, what happens to the DCF valuation?",choices:["Increases","Decreases","No change","Depends on the terminal growth rate"],correct:1,cat:"Valuation"},
  {q:"EV/EBITDA is preferred over P/E for comparison because:",choices:["It's simpler to calculate","It's capital structure neutral","It always gives higher values","It uses net income"],correct:1,cat:"Valuation"},
  {q:"A company trades at 8x EV/EBITDA with $100M EBITDA. What is Enterprise Value?",choices:["$800M","$80M","$1B","$100M"],correct:0,cat:"Valuation"},
  {q:"Unlevered Free Cash Flow is calculated as:",choices:["Net Income + D&A - CapEx","EBIT × (1-T) + D&A - CapEx - ΔWC","Revenue - Expenses","EBITDA - Interest - Taxes"],correct:1,cat:"Valuation"},
  {q:"Which is NOT an input to WACC?",choices:["Cost of equity","Cost of debt","Tax rate","Revenue growth rate"],correct:3,cat:"Valuation"},
  {q:"The terminal growth rate in a DCF should generally be:",choices:["Higher than GDP growth","Equal to or below long-term GDP growth","Equal to the company's current growth rate","Zero"],correct:1,cat:"Valuation"},
  {q:"Levered Free Cash Flow represents cash available to:",choices:["All capital providers","Equity holders only","Debt holders only","The government"],correct:1,cat:"Valuation"},
  {q:"Beta in the CAPM formula measures:",choices:["Total risk","Systematic/market risk","Company-specific risk","Credit risk"],correct:1,cat:"Valuation"},
  // ── M&A ──
  {q:"An acquisition is accretive when:",choices:["The buyer pays a premium","Pro forma EPS exceeds the buyer's standalone EPS","The target's revenue grows","The buyer uses all cash"],correct:1,cat:"M&A"},
  {q:"Which financing method is most likely to be accretive?",choices:["All stock deal at high P/E","All cash deal funded by debt","50/50 stock and cash","It depends on relative P/E ratios and cost of debt"],correct:3,cat:"M&A"},
  {q:"In a stock-for-stock merger, what determines accretion/dilution?",choices:["The size of the companies","The relative P/E ratios of buyer and target","The industry they're in","Total revenue"],correct:1,cat:"M&A"},
  {q:"A buyer with a higher P/E acquires a target with a lower P/E using all stock. The deal is likely:",choices:["Dilutive","Accretive","Neutral","Cannot determine"],correct:1,cat:"M&A"},
  {q:"Synergies in M&A typically include:",choices:["Revenue synergies only","Cost synergies only","Both revenue and cost synergies","Neither — synergies are theoretical"],correct:2,cat:"M&A"},
  {q:"Purchase price allocation assigns value to:",choices:["Only goodwill","Identifiable tangible and intangible assets, with residual as goodwill","Only the target's book value","The buyer's existing assets"],correct:1,cat:"M&A"},
  {q:"A fairness opinion is issued by:",choices:["The acquiring company's management","An independent investment bank","The SEC","The target's auditor"],correct:1,cat:"M&A"},
  {q:"In a merger model, what creates goodwill?",choices:["Revenue synergies","The premium paid over the fair value of identifiable net assets","Cost savings","Debt assumption"],correct:1,cat:"M&A"},
  // ── LBO ──
  {q:"The three main return drivers in an LBO are:",choices:["Revenue, EBITDA, and cash flow","EBITDA growth, multiple expansion, and deleveraging","Entry price, exit price, and synergies","Debt, equity, and mezzanine"],correct:1,cat:"LBO"},
  {q:"A typical LBO uses what ratio of debt to equity?",choices:["90% debt / 10% equity","30% debt / 70% equity","50-70% debt / 30-50% equity","100% equity"],correct:2,cat:"LBO"},
  {q:"Which characteristic does NOT make a good LBO candidate?",choices:["Stable cash flows","High capital expenditure requirements","Strong market position","Low cyclicality"],correct:1,cat:"LBO"},
  {q:"In an LBO, IRR increases if the holding period:",choices:["Increases","Decreases","Stays the same","Has no impact"],correct:1,cat:"LBO"},
  {q:"PIK interest in an LBO means:",choices:["Interest is paid in cash each period","Interest accrues and is added to the principal","Interest is paid by issuing equity","There is no interest"],correct:1,cat:"LBO"},
  {q:"An LBO fund buys a company at 8x EBITDA and exits at 10x. This is an example of:",choices:["Deleveraging","EBITDA growth","Multiple expansion","Financial engineering"],correct:2,cat:"LBO"},
  {q:"Paper LBO: $100M EBITDA, 7x entry, 4x leverage. Sponsor equity check is:",choices:["$300M","$400M","$700M","$100M"],correct:0,cat:"LBO"},
  {q:"A dividend recapitalization involves:",choices:["The company paying a special dividend funded by new debt","The company issuing new equity","The sponsor injecting more capital","Refinancing existing debt at lower rates"],correct:0,cat:"LBO"},
  {q:"MOIC of 2.5x over 5 years is approximately what IRR?",choices:["~10%","~20%","~30%","~40%"],correct:1,cat:"LBO"},
  // ── Markets / General ──
  {q:"The yield curve inverts when:",choices:["Long-term rates exceed short-term rates","Short-term rates exceed long-term rates","All rates are equal","The Fed cuts rates"],correct:1,cat:"Markets"},
  {q:"When the Fed raises interest rates, bond prices generally:",choices:["Increase","Decrease","Stay the same","It depends on the term"],correct:1,cat:"Markets"},
  {q:"The risk-free rate is typically represented by:",choices:["S&P 500 return","10-year US Treasury yield","LIBOR","Corporate bond yields"],correct:1,cat:"Markets"},
  {q:"Higher interest rates generally cause equity valuations to:",choices:["Increase","Decrease","Stay the same","Increase for growth stocks only"],correct:1,cat:"Markets"},
  {q:"A basis point is equal to:",choices:["1%","0.1%","0.01%","10%"],correct:2,cat:"Markets"},
  {q:"The P/E ratio represents:",choices:["Price relative to revenue","How much investors pay per dollar of earnings","Total debt to equity","Book value per share"],correct:1,cat:"Markets"},
  {q:"EBITDA stands for:",choices:["Earnings Before Interest, Taxes, Debt, and Amortization","Earnings Before Interest, Taxes, Depreciation, and Amortization","Earnings Before Income Tax Deductions and Adjustments","Enterprise Before Interest, Taxes, Depreciation, Amortization"],correct:1,cat:"Markets"},
  {q:"Working capital is defined as:",choices:["Total assets minus total liabilities","Current assets minus current liabilities","Cash minus debt","Revenue minus expenses"],correct:1,cat:"Markets"},
  {q:"If a company's current ratio is below 1.0, it means:",choices:["The company is profitable","Current liabilities exceed current assets","The company has too much cash","The company's stock is undervalued"],correct:1,cat:"Markets"},
  {q:"Diluted shares outstanding includes:",choices:["Only common shares","Common shares plus in-the-money options, RSUs, and convertibles","Only preferred shares","Treasury shares"],correct:1,cat:"Markets"},
];
