import { MCQ } from './ib-questions';

export const PE_QUESTIONS: MCQ[] = [
  {q:"The three main return drivers in an LBO are:",choices:["Revenue, margins, multiples","EBITDA growth, multiple expansion, deleveraging","Entry price, synergies, cost cuts","Debt, equity, mezzanine"],correct:1,cat:"LBO Mechanics"},
  {q:"A PE fund buys a company for $500M using 60% debt. Sponsor equity is:",choices:["$300M","$200M","$500M","$100M"],correct:1,cat:"LBO Mechanics"},
  {q:"IRR measures:",choices:["Total money returned","Annualized return accounting for timing","Revenue growth rate","EBITDA margin"],correct:1,cat:"LBO Mechanics"},
  {q:"MOIC stands for:",choices:["Margin On Invested Capital","Multiple On Invested Capital","Market Offering Initial Cost","Management Of Internal Controls"],correct:1,cat:"LBO Mechanics"},
  {q:"2.5x MOIC over 3 years is approximately what IRR?",choices:["~15%","~25%","~36%","~50%"],correct:2,cat:"LBO Mechanics"},
  {q:"Which is NOT a characteristic of a good LBO candidate?",choices:["Predictable cash flows","High capex requirements","Strong market position","Experienced management"],correct:1,cat:"LBO Mechanics"},
  {q:"PIK interest means:",choices:["Interest paid in cash quarterly","Interest accrues and adds to the debt principal","Interest is waived","Interest is paid with equity"],correct:1,cat:"LBO Mechanics"},
  {q:"A dividend recapitalization is when:",choices:["A portfolio company issues new debt to pay a dividend to the sponsor","The sponsor injects more equity","The company cuts its dividend","Debt is converted to equity"],correct:0,cat:"LBO Mechanics"},
  {q:"Which type of due diligence examines a company's competitive position?",choices:["Financial DD","Legal DD","Commercial DD","Tax DD"],correct:2,cat:"Deal Process"},
  {q:"In a typical PE fund structure, the GP contributes what percentage of capital?",choices:["0%","1-5%","20-30%","50%"],correct:1,cat:"Fund Economics"},
  {q:"Carried interest is typically:",choices:["2% of committed capital","20% of profits above a hurdle rate","A fixed annual fee","10% of revenue"],correct:1,cat:"Fund Economics"},
  {q:"A management fee is typically:",choices:["20% of profits","2% of committed capital annually","5% of revenue","1% of exit proceeds"],correct:1,cat:"Fund Economics"},
  {q:"Enterprise Value in an LBO context is:",choices:["Just the equity value","The total purchase price for the business","Market cap minus cash","Book value of assets"],correct:1,cat:"LBO Mechanics"},
  {q:"Debt covenants in an LBO serve to:",choices:["Increase the company's revenue","Protect lenders by restricting certain actions","Reduce the tax rate","Eliminate interest payments"],correct:1,cat:"LBO Mechanics"},
  {q:"A bolt-on acquisition is:",choices:["A completely unrelated acquisition","A smaller acquisition added to an existing portfolio company","Selling a division","An IPO"],correct:1,cat:"Deal Process"},
  {q:"Which metric best measures a PE firm's ability to generate cash for debt repayment?",choices:["Revenue","EBITDA","Net income","Gross profit"],correct:1,cat:"LBO Mechanics"},
  {q:"A PE fund typically holds an investment for:",choices:["6 months","1-2 years","3-7 years","10+ years"],correct:2,cat:"Fund Economics"},
  {q:"Operational value creation in PE includes all EXCEPT:",choices:["Improving pricing strategy","Reducing SG&A","Increasing leverage","Upgrading management team"],correct:2,cat:"Value Creation"},
  {q:"Multiple expansion means:",choices:["Growing the company's revenue","Selling at a higher EV/EBITDA multiple than you paid","Taking on more debt","Acquiring more companies"],correct:1,cat:"LBO Mechanics"},
  {q:"A purchase price of 10x EBITDA is considered:",choices:["Very cheap","Below average","Average to above-average for a quality asset","Extremely overpriced"],correct:2,cat:"LBO Mechanics"},
  {q:"If EBITDA grows from $50M to $75M over 5 years, the CAGR is approximately:",choices:["5%","8%","10%","15%"],correct:1,cat:"LBO Mechanics"},
  {q:"Senior secured debt has priority over:",choices:["Nothing - it's the lowest priority","Equity only","Subordinated debt, mezzanine, and equity","Only preferred stock"],correct:2,cat:"Capital Structure"},
  {q:"Mezzanine debt typically:",choices:["Has the lowest interest rate","Sits between senior debt and equity in the capital structure","Is always secured","Has no interest"],correct:1,cat:"Capital Structure"},
  {q:"Revenue synergies are generally considered:",choices:["More reliable than cost synergies","Less reliable than cost synergies","Equally reliable","Not relevant in PE"],correct:1,cat:"Value Creation"},
  {q:"A 'club deal' in PE means:",choices:["The GP invests alone","Multiple PE firms co-invest in the same deal","The deal involves a country club company","Management does a buyout alone"],correct:1,cat:"Deal Process"},
];

export const CONSULTING_QUESTIONS: MCQ[] = [
  {q:"A profitability framework should first break down:",choices:["Revenue and costs","Market size and share","Customer segments only","Competitive landscape"],correct:0,cat:"Frameworks"},
  {q:"Market sizing is also known as:",choices:["Due diligence","Fermi estimation","Financial modeling","Competitive analysis"],correct:1,cat:"Case"},
  {q:"When estimating a market size, which approach uses total population as a starting point?",choices:["Bottom-up","Top-down","Supply-side","Demand-side"],correct:1,cat:"Case"},
  {q:"A company's same-store sales declined 15%. Which is the FIRST thing to investigate?",choices:["Whether to launch a new product","Traffic vs ticket size","CEO compensation","Social media strategy"],correct:1,cat:"Case"},
  {q:"Revenue growth can be decomposed into:",choices:["Price × Volume","Assets × Turnover","Debt × Equity","Fixed × Variable costs"],correct:0,cat:"Frameworks"},
  {q:"In a market entry case, which factor is LEAST important?",choices:["Market size and growth","Competitive landscape","The CEO's personal preferences","Regulatory environment"],correct:2,cat:"Case"},
  {q:"A 'MECE' framework means:",choices:["Maximum Efficiency, Cost Effectiveness","Mutually Exclusive, Collectively Exhaustive","Market Entry, Competitive Evaluation","Most Effective, Customer Engaged"],correct:1,cat:"Frameworks"},
  {q:"If profit = revenue - costs, and revenue is flat but profit declined, the issue is:",choices:["Revenue","Costs increased","Market share","Volume"],correct:1,cat:"Frameworks"},
  {q:"Estimate: ~330M US population, ~40% are working adults with smartphones. How many smartphone users?",choices:["~50M","~130M","~200M","~330M"],correct:1,cat:"Case"},
  {q:"A company should enter a new market if:",choices:["It's large","The company has a right to win and the market is attractive","Competitors are already there","The CEO wants to"],correct:1,cat:"Case"},
  {q:"The 80/20 rule (Pareto principle) suggests:",choices:["80% of costs are fixed","80% of revenue comes from 20% of customers","80% of employees are productive","80% of markets are saturated"],correct:1,cat:"Frameworks"},
  {q:"In a cost reduction case, the first step is:",choices:["Cut headcount","Understand the cost structure - fixed vs variable, by category","Outsource everything","Raise prices instead"],correct:1,cat:"Case"},
  {q:"What does a 'breakeven analysis' determine?",choices:["Maximum profit","The volume at which total revenue equals total costs","Optimal pricing","Market share"],correct:1,cat:"Frameworks"},
  {q:"Contribution margin is defined as:",choices:["Revenue minus all costs","Revenue minus variable costs","Revenue minus fixed costs","Net income divided by revenue"],correct:1,cat:"Frameworks"},
  {q:"In a pricing case, willingness to pay is primarily determined by:",choices:["The company's costs","Customer-perceived value relative to alternatives","Competitor stock prices","The company's profit target"],correct:1,cat:"Case"},
  {q:"A two-by-two matrix is useful for:",choices:["Financial modeling","Prioritizing options along two dimensions","Calculating market size","Building a DCF"],correct:1,cat:"Frameworks"},
  {q:"When presenting a recommendation in a case, you should:",choices:["Give a long preamble before the answer","Lead with the answer, then support with evidence","Ask the interviewer what they think first","List every option without recommending one"],correct:1,cat:"Communication"},
  {q:"Which consulting firm is NOT part of MBB?",choices:["McKinsey","Bain","Deloitte","BCG"],correct:2,cat:"Industry"},
  {q:"The typical consulting engagement lasts:",choices:["1 day","2-4 weeks","3-6 months","2 years"],correct:2,cat:"Industry"},
  {q:"Porter's Five Forces does NOT include:",choices:["Threat of new entrants","Bargaining power of suppliers","Management quality","Rivalry among competitors"],correct:2,cat:"Frameworks"},
  {q:"Switching costs affect which of Porter's Five Forces?",choices:["Threat of new entrants","Bargaining power of buyers","Supplier power","Rivalry"],correct:1,cat:"Frameworks"},
  {q:"A hypothesis-driven approach means:",choices:["You guess the answer randomly","You form an initial answer and test it with data","You avoid having opinions","You only use qualitative data"],correct:1,cat:"Communication"},
  {q:"Growth strategy options typically include:",choices:["Only organic growth","Organic growth, M&A, partnerships, and new market entry","Only acquisitions","Only cost cutting"],correct:1,cat:"Frameworks"},
];

export const ACCOUNTING_QUESTIONS: MCQ[] = [
  {q:"The audit opinion that states financials are fairly presented is called:",choices:["Qualified","Unqualified","Adverse","Disclaimer"],correct:1,cat:"Audit"},
  {q:"A qualified audit opinion means:",choices:["Everything is fine","There is a material misstatement in a specific area","Financials are completely unreliable","The auditor couldn't get enough evidence"],correct:1,cat:"Audit"},
  {q:"Materiality in auditing is best defined as:",choices:["Any error over $1,000","A threshold above which misstatements could influence user decisions","Only quantitative errors","Fraud"],correct:1,cat:"Audit"},
  {q:"The five management assertions include all EXCEPT:",choices:["Existence","Completeness","Profitability","Valuation"],correct:2,cat:"Audit"},
  {q:"ASC 606 revenue recognition has how many steps?",choices:["3","4","5","7"],correct:2,cat:"Revenue Recognition"},
  {q:"Under ASC 606, the first step is:",choices:["Determine the transaction price","Identify the contract","Recognize revenue","Allocate the price"],correct:1,cat:"Revenue Recognition"},
  {q:"Accounts payable differs from accrued expenses because:",choices:["AP is for services, accrued is for goods","AP has a specific invoice, accrued does not yet","AP is long-term, accrued is short-term","There is no difference"],correct:1,cat:"Financial Reporting"},
  {q:"Deferred revenue is classified as a:",choices:["Asset","Liability","Equity","Expense"],correct:1,cat:"Financial Reporting"},
  {q:"An operating lease under ASC 842 creates:",choices:["No balance sheet impact","A right-of-use asset and lease liability","Only a liability","Only an asset"],correct:1,cat:"Financial Reporting"},
  {q:"The going concern assumption means:",choices:["The company is being liquidated","The company will continue operating for the foreseeable future","Profits will increase","The audit is complete"],correct:1,cat:"Audit"},
  {q:"Internal controls over financial reporting are evaluated under:",choices:["ASC 606","SOX Section 404","GAAP only","SEC Rule 10b-5"],correct:1,cat:"Audit"},
  {q:"A Big Four firm includes all EXCEPT:",choices:["Deloitte","PwC","Goldman Sachs","EY"],correct:2,cat:"Industry"},
  {q:"Substantive testing involves:",choices:["Testing internal controls only","Directly testing account balances and transactions","Only interviewing management","Reviewing the company's strategy"],correct:1,cat:"Audit"},
  {q:"Goodwill impairment testing is required:",choices:["Monthly","Quarterly","At least annually","Only when selling the company"],correct:2,cat:"Financial Reporting"},
  {q:"IFRS and US GAAP differ in that IFRS:",choices:["Is rules-based","Is principles-based compared to GAAP's more rules-based approach","Only applies to US companies","Is no longer used"],correct:1,cat:"Financial Reporting"},
  {q:"A liability is best defined as:",choices:["Something the company owns","A present obligation to transfer resources in the future","Cash in the bank","Revenue not yet earned"],correct:1,cat:"Financial Reporting"},
  {q:"The matching principle requires:",choices:["Matching assets to liabilities","Recognizing expenses in the same period as the related revenue","Matching debits to credits only","Recording transactions when cash is received"],correct:1,cat:"Financial Reporting"},
  {q:"Which method of depreciation allocates the same expense each year?",choices:["Double declining balance","Units of production","Straight-line","Sum of years' digits"],correct:2,cat:"Financial Reporting"},
  {q:"An asset is impaired when:",choices:["Its market value increases","Its carrying value exceeds its recoverable amount","It is fully depreciated","It is sold at a gain"],correct:1,cat:"Financial Reporting"},
  {q:"The statement of cash flows begins with:",choices:["Revenue","Total assets","Net income","Cash balance"],correct:2,cat:"Financial Reporting"},
];

export const AM_QUESTIONS: MCQ[] = [
  {q:"A value investor primarily looks for:",choices:["High-growth companies at any price","Companies trading below intrinsic value","Only tech stocks","Companies with the highest P/E ratios"],correct:1,cat:"Investment Philosophy"},
  {q:"The Sharpe Ratio measures:",choices:["Total return","Risk-adjusted return relative to the risk-free rate","Beta only","Revenue growth"],correct:1,cat:"Portfolio Management"},
  {q:"Alpha represents:",choices:["Market return","Excess return above what's expected given the level of risk","Total portfolio value","The risk-free rate"],correct:1,cat:"Portfolio Management"},
  {q:"Beta of 1.5 means the stock:",choices:["Moves opposite to the market","Is 50% more volatile than the market","Is 50% less volatile","Has no correlation to the market"],correct:1,cat:"Portfolio Management"},
  {q:"A stock with a P/E of 12 and earnings growth of 15% has a PEG ratio of:",choices:["0.5","0.8","1.25","180"],correct:1,cat:"Valuation"},
  {q:"Diversification reduces:",choices:["Systematic risk","Unsystematic/company-specific risk","All risk entirely","Market risk"],correct:1,cat:"Portfolio Management"},
  {q:"The efficient market hypothesis states:",choices:["Markets always crash","Stock prices fully reflect available information","Technical analysis always works","Value investing is the best strategy"],correct:1,cat:"Theory"},
  {q:"Active management aims to:",choices:["Match the benchmark","Outperform the benchmark through security selection","Minimize all risk","Only buy index funds"],correct:1,cat:"Investment Philosophy"},
  {q:"Net Revenue Retention of 120% means:",choices:["The company lost 20% of revenue","Existing customers expanded spending by 20% net of churn","Revenue grew 120%","The company has 120 customers"],correct:1,cat:"Metrics"},
  {q:"A DCF terminal value using a perpetuity growth method assumes:",choices:["The company stops growing","Cash flows grow at a constant rate forever","The company is acquired","Revenue doubles each year"],correct:1,cat:"Valuation"},
  {q:"In a stock pitch, the most critical element is:",choices:["The company description","The catalyst - why the market is wrong NOW","The company's history","The CEO's background"],correct:1,cat:"Investment Philosophy"},
  {q:"Gross margin is calculated as:",choices:["Revenue - COGS, divided by Revenue","Net Income / Revenue","EBITDA / Revenue","Revenue - All Expenses"],correct:0,cat:"Metrics"},
  {q:"Free cash flow yield is:",choices:["FCF / Revenue","FCF / Enterprise Value (or Market Cap)","Revenue / FCF","EBITDA / Debt"],correct:1,cat:"Metrics"},
  {q:"A company with negative working capital is likely:",choices:["Going bankrupt","Collecting cash from customers before paying suppliers","Overpaying for inventory","Losing money on every sale"],correct:1,cat:"Metrics"},
  {q:"Dollar cost averaging involves:",choices:["Investing a lump sum all at once","Investing fixed amounts at regular intervals regardless of price","Only buying when prices drop","Timing the market precisely"],correct:1,cat:"Investment Philosophy"},
];

export const ST_QUESTIONS: MCQ[] = [
  {q:"If the Fed unexpectedly raises rates by 50bps, bond prices will:",choices:["Increase","Decrease","Stay the same","Double"],correct:1,cat:"Fixed Income"},
  {q:"The VIX measures:",choices:["S&P 500 price level","Implied volatility of S&P 500 options","Interest rates","Corporate bond spreads"],correct:1,cat:"Equities"},
  {q:"A basis point equals:",choices:["1%","0.1%","0.01%","10%"],correct:2,cat:"General"},
  {q:"Duration measures a bond's sensitivity to:",choices:["Credit risk","Changes in interest rates","Inflation","Currency fluctuations"],correct:1,cat:"Fixed Income"},
  {q:"When the yield curve steepens, it typically signals:",choices:["Economic contraction","Expected economic expansion","A recession","Deflation"],correct:1,cat:"Fixed Income"},
  {q:"A put option gives the holder the right to:",choices:["Buy the underlying at the strike price","Sell the underlying at the strike price","Receive dividends","Vote on corporate matters"],correct:1,cat:"Derivatives"},
  {q:"Delta of a call option is between:",choices:["-1 and 0","0 and 1","0 and 100","-100 and 100"],correct:1,cat:"Derivatives"},
  {q:"Credit spreads widen when:",choices:["The economy is improving","Default risk increases or risk appetite decreases","Interest rates fall","Stocks rally"],correct:1,cat:"Credit"},
  {q:"A short squeeze occurs when:",choices:["A stock price drops rapidly","Heavily shorted stock rises, forcing short sellers to buy","A company misses earnings","The Fed cuts rates"],correct:1,cat:"Equities"},
  {q:"Market making involves:",choices:["Only buying securities","Providing liquidity by quoting bid and ask prices","Long-term investing","Only trading for your own account"],correct:1,cat:"General"},
  {q:"The bid-ask spread represents:",choices:["The market maker's profit opportunity","The stock's daily range","Total trading volume","The dividend yield"],correct:0,cat:"General"},
  {q:"A carry trade involves:",choices:["Borrowing in a low-yield currency and investing in a high-yield currency","Buying and holding stocks long-term","Short selling only","Trading options exclusively"],correct:0,cat:"FX"},
  {q:"Convexity in bonds refers to:",choices:["The linear relationship between price and yield","The curvature of the price-yield relationship","Credit risk","Maturity date"],correct:1,cat:"Fixed Income"},
  {q:"If the dollar strengthens, US exporters generally:",choices:["Benefit","Are hurt because their goods become more expensive abroad","Are unaffected","See higher domestic demand"],correct:1,cat:"FX"},
  {q:"P&L responsibility in trading means:",choices:["Managing a portfolio with direct profit/loss accountability","Only analyzing trades","Writing research reports","Managing client relationships"],correct:0,cat:"General"},
];

export const ER_QUESTIONS: MCQ[] = [
  {q:"Sell-side equity research primarily serves:",choices:["The company being analyzed","Institutional investor clients","Retail investors only","Regulators"],correct:1,cat:"Industry"},
  {q:"An 'Overweight' rating generally means:",choices:["Sell the stock","The stock is expected to outperform its sector","The company is overvalued","Hold the position"],correct:1,cat:"Ratings"},
  {q:"The most important component of a stock pitch is:",choices:["Company description","Why the stock is mispriced and what catalyst will correct it","Historical performance","Management bios"],correct:1,cat:"Analysis"},
  {q:"EV/Revenue is useful for valuing companies that:",choices:["Have high profit margins","Have negative or volatile earnings","Are highly leveraged","Are being liquidated"],correct:1,cat:"Valuation"},
  {q:"Consensus estimates refer to:",choices:["Management guidance only","The average of analyst forecasts","Historical averages","Index returns"],correct:1,cat:"Analysis"},
  {q:"An earnings surprise occurs when:",choices:["A company reports exactly as expected","Actual earnings differ from consensus estimates","Revenue declines","The CEO resigns"],correct:1,cat:"Analysis"},
  {q:"Sum-of-the-parts valuation is used when:",choices:["A company operates in a single segment","A company has diverse business segments that deserve different multiples","Calculating working capital","A company has no earnings"],correct:1,cat:"Valuation"},
  {q:"When initiating coverage, an analyst typically provides:",choices:["Only a price target","A full report with thesis, model, valuation, risks, and rating","Only a buy/sell rating","A one-page summary"],correct:1,cat:"Analysis"},
  {q:"Same-store sales growth measures:",choices:["Total company revenue growth","Revenue growth from stores open at least one year","Only new store revenue","Online sales only"],correct:1,cat:"Metrics"},
  {q:"TAM/SAM/SOM framework is used to analyze:",choices:["Cost structure","Market opportunity sizing","Debt capacity","Management quality"],correct:1,cat:"Analysis"},
];

export const RE_QUESTIONS: MCQ[] = [
  {q:"NOI stands for:",choices:["Net Operating Income","Net Overhead Investment","New Offering Index","None of the above"],correct:0,cat:"Fundamentals"},
  {q:"Cap rate is calculated as:",choices:["NOI ÷ Property Value","Property Value ÷ NOI","Revenue ÷ Expenses","Debt ÷ Equity"],correct:0,cat:"Fundamentals"},
  {q:"A lower cap rate indicates:",choices:["Higher risk","Lower price","Higher price relative to income (lower yield)","Distressed property"],correct:2,cat:"Fundamentals"},
  {q:"Debt Service Coverage Ratio (DSCR) measures:",choices:["Property value growth","NOI relative to debt payments","Total revenue","Cap rate trends"],correct:1,cat:"Financing"},
  {q:"A REIT must distribute what percentage of taxable income?",choices:["50%","75%","90%","100%"],correct:2,cat:"Structures"},
  {q:"Class A office space refers to:",choices:["The cheapest office space","Premium, well-located, highest-quality buildings","Suburban offices only","Government buildings"],correct:1,cat:"Fundamentals"},
  {q:"In a real estate waterfall, the preferred return typically goes to:",choices:["The GP first","The LP first","Split equally","The bank"],correct:1,cat:"Structures"},
  {q:"Loan-to-Value (LTV) of 70% means:",choices:["The loan is 70% of the property's value","The equity is 70%","The cap rate is 7%","The property is 70% occupied"],correct:0,cat:"Financing"},
  {q:"Interest-only loans in real estate:",choices:["Require no payments","Only require interest payments with no principal amortization during the IO period","Are illegal","Always have lower rates"],correct:1,cat:"Financing"},
  {q:"Effective gross income equals:",choices:["Gross potential rent only","Gross potential rent - vacancy + other income","NOI + expenses","Cap rate × property value"],correct:1,cat:"Fundamentals"},
  {q:"A triple-net (NNN) lease means the tenant pays:",choices:["Only rent","Rent plus property taxes, insurance, and maintenance","Three times market rent","Rent for three properties"],correct:1,cat:"Fundamentals"},
  {q:"Value-add real estate investing involves:",choices:["Buying stabilized properties for yield","Buying properties below potential and improving them","Only ground-up development","Lending money for construction"],correct:1,cat:"Strategy"},
  {q:"When interest rates rise, cap rates generally:",choices:["Fall","Rise","Stay the same","Are unrelated"],correct:1,cat:"Fundamentals"},
  {q:"Vacancy rate of 5% is considered:",choices:["Very high","Moderate","Low/healthy","Normal for a distressed market"],correct:2,cat:"Fundamentals"},
];

export const VC_QUESTIONS: MCQ[] = [
  {q:"Pre-money valuation is:",choices:["Company value after the investment","Company value before the new investment","Revenue run rate","Total funding raised to date"],correct:1,cat:"Fundamentals"},
  {q:"A company raises $10M at a $40M pre-money valuation. The investor owns:",choices:["10%","20%","25%","40%"],correct:1,cat:"Fundamentals"},
  {q:"The power law in VC means:",choices:["All investments return the same","A small number of investments generate the majority of fund returns","Larger funds always outperform","Later-stage is safer"],correct:1,cat:"Fund Economics"},
  {q:"ARR stands for:",choices:["Annual Revenue Rate","Annual Recurring Revenue","Average Return Rate","Adjusted Revenue Ratio"],correct:1,cat:"SaaS Metrics"},
  {q:"Net Revenue Retention above 120% indicates:",choices:["High customer churn","Existing customers are expanding faster than others are churning","The company is losing money","Revenue is declining"],correct:1,cat:"SaaS Metrics"},
  {q:"CAC payback period measures:",choices:["How long until the company is profitable","Months to recover customer acquisition cost from gross margin","Total marketing spend","Customer lifetime"],correct:1,cat:"SaaS Metrics"},
  {q:"A down round means:",choices:["The company raised at a higher valuation","The company raised at a lower valuation than the previous round","Revenue grew","The founder sold shares"],correct:1,cat:"Fundamentals"},
  {q:"Anti-dilution provisions protect:",choices:["Founders from losing control","Earlier investors from excessive dilution in down rounds","Employees only","The company from bankruptcy"],correct:1,cat:"Term Sheets"},
  {q:"Liquidation preference of 1x means:",choices:["Investors get 1% of proceeds","Investors get their money back before common shareholders receive anything","Founders get paid first","All shareholders split equally"],correct:1,cat:"Term Sheets"},
  {q:"Product-market fit is indicated by:",choices:["Having a product","Strong organic growth, high retention, and users pulling the product from you","Raising a large round","Having a famous investor"],correct:1,cat:"Evaluation"},
  {q:"A typical VC fund life is:",choices:["2-3 years","5-7 years","10 years with possible extensions","20 years"],correct:2,cat:"Fund Economics"},
  {q:"Series A typically refers to:",choices:["The first money a company raises","The first institutional round after seed, typically $5-20M","An IPO","A debt round"],correct:1,cat:"Fundamentals"},
  {q:"Burn multiple is calculated as:",choices:["Revenue ÷ Expenses","Net Burn ÷ Net New ARR","ARR ÷ Employees","Total Funding ÷ Revenue"],correct:1,cat:"SaaS Metrics"},
  {q:"A convertible note converts to equity:",choices:["Never","At the next priced round, typically at a discount to the new price","Immediately upon signing","Only at IPO"],correct:1,cat:"Fundamentals"},
  {q:"The most important metric for an early-stage SaaS company is:",choices:["Net income","Revenue growth rate","Total headcount","Office size"],correct:1,cat:"SaaS Metrics"},
];
