export const RE_FUNDAMENTALS_SECTIONS = [
  { title: '1.1 Real Estate Finance Basics', content: `<p>Real estate investing is fundamentally about buying income-producing properties, improving their cash flow, and selling at a profit. The core metric is <strong>Net Operating Income (NOI)</strong>: rental revenue minus operating expenses (excluding debt service).</p><p><strong>Cap Rate</strong> = NOI / Property Value. It's the real estate equivalent of a yield. A 6% cap rate means you earn 6% annually on the property's value from operations.</p><p><strong>Key relationship:</strong> Lower cap rate = higher price = lower risk. A Class A office building in Manhattan might trade at a 4% cap rate; a suburban retail strip center at 8%.</p>` },
  { title: '1.2 Property Types & Sectors', content: `<ul><li><strong>Multifamily:</strong> Apartments. Most recession-resistant. People always need housing. Stable cash flows. Largest REPE sector.</li><li><strong>Industrial:</strong> Warehouses, logistics, data centers. Booming from e-commerce and cloud computing.</li><li><strong>Office:</strong> Class A (premium towers) to Class C (older, less desirable). Post-COVID remote work has challenged this sector.</li><li><strong>Retail:</strong> Malls, grocery-anchored centers, single-tenant net lease. Challenged but selectively attractive.</li><li><strong>Hospitality:</strong> Hotels and resorts. Highest volatility. Revenue fluctuates daily (RevPAR = Revenue Per Available Room).</li><li><strong>Specialty:</strong> Self-storage, student housing, senior living, life sciences. Niche but growing.</li></ul>` },
  { title: '1.3 REPE vs. REITs vs. Development', content: `<p><strong>Real Estate Private Equity (REPE):</strong> Buy properties using leverage, improve NOI through renovations or better management, sell at a profit. Same LBO logic as PE but with real assets. Firms: Blackstone, Brookfield, Starwood.</p><p><strong>REITs (Real Estate Investment Trusts):</strong> Publicly traded companies that own portfolios of properties. Must distribute 90% of taxable income as dividends. More liquid but less control. Firms: Prologis, Equity Residential, Simon Property Group.</p><p><strong>Development:</strong> Ground-up construction. Highest risk (construction risk, lease-up risk) but highest returns. Firms: Related Companies, Tishman Speyer, Hines.</p>` },
];

export const RE_MODELING_SECTIONS = [
  { title: '2.1 The Real Estate Pro Forma', content: `<p>The pro forma is the core financial model in real estate — it projects a property's cash flows over a hold period (typically 5-10 years).</p><h4>Key line items:</h4><ol><li><strong>Gross Potential Rent (GPR):</strong> Total rent if 100% occupied at market rates.</li><li><strong>Vacancy & Credit Loss:</strong> Typically 5-10% of GPR.</li><li><strong>Effective Gross Income (EGI):</strong> GPR - vacancy + other income (parking, laundry).</li><li><strong>Operating Expenses:</strong> Property taxes, insurance, maintenance, management fees, utilities.</li><li><strong>Net Operating Income (NOI):</strong> EGI - Operating Expenses. The most important line.</li><li><strong>Debt Service:</strong> Mortgage payments (principal + interest).</li><li><strong>Cash Flow to Equity:</strong> NOI - Debt Service.</li></ol>` },
  { title: '2.2 Key Metrics You Must Know', content: `<p><strong>Cap Rate</strong> = NOI / Purchase Price. Used for valuation and comparison.</p><p><strong>Cash-on-Cash Return</strong> = Annual Cash Flow to Equity / Total Equity Invested. Measures yield on your actual cash.</p><p><strong>Debt Service Coverage Ratio (DSCR)</strong> = NOI / Annual Debt Service. Lenders typically require 1.25x minimum — meaning NOI must be 25% above debt payments.</p><p><strong>Loan-to-Value (LTV)</strong> = Loan Amount / Property Value. Typical REPE deals use 60-75% LTV.</p><p><strong>IRR:</strong> Same concept as PE — time-weighted return on equity including the exit sale.</p>` },
  { title: '2.3 The Waterfall Structure', content: `<p>REPE deals use <strong>waterfall distributions</strong> to split profits between the GP (fund manager) and LPs (investors).</p><h4>Typical structure:</h4><ol><li><strong>Return of Capital:</strong> LPs get their initial investment back first.</li><li><strong>Preferred Return (Pref):</strong> LPs receive a preferred return (usually 8%) before the GP gets any promote.</li><li><strong>Catch-up:</strong> The GP receives distributions until they've caught up to their promote percentage.</li><li><strong>Carried Interest Split:</strong> Above the pref, profits are split (e.g., 80/20 LP/GP).</li></ol><p>Understanding waterfall math is essential for REPE interviews.</p>` },
  { title: '2.4 Interview Questions & Drills', content: `<p><strong>"Walk me through how you'd evaluate an apartment building acquisition."</strong></p><p><em>"I'd start by analyzing the property's current NOI — reviewing the rent roll, vacancy rate, and operating expenses. Then I'd compare the in-place rents to market rents to identify upside. I'd build a 5-year pro forma projecting rent growth, expense inflation, and any capital improvements needed. On the debt side, I'd model the loan terms (LTV, interest rate, amortization) to calculate cash-on-cash returns. Finally, I'd assume an exit cap rate to calculate the sale price and compute the levered IRR. I'd target a 15%+ IRR and 1.8x+ equity multiple for a core-plus deal."</em></p><p><strong>"What's the difference between a 5% and 7% cap rate?"</strong></p><p><em>"A lower cap rate implies lower risk and higher price — the buyer is willing to accept a lower yield because the asset is more stable (e.g., a Class A apartment building in a top market). A 7% cap rate implies more risk — maybe it's a secondary market, older building, or has vacancy issues — so the buyer demands a higher yield to compensate."</em></p>` },
];

export const RE_BEHAVIORAL_SECTIONS = [
  { title: '3.1 "Why Real Estate?"', content: `<p><strong>Elite answer:</strong> "I'm drawn to real estate because it's one of the few areas of investing where you can physically walk through your asset, identify operational improvements, and directly drive value creation. Unlike public equities where you're a passive observer, in REPE you're making tangible decisions — renovating units, renegotiating leases, repositioning properties — and you can see the impact on NOI and cash flow in real time. I also love that real estate requires understanding both macro trends (interest rates, demographics, migration patterns) and hyper-local knowledge (specific neighborhoods, zoning, tenant demand)."</em></p>` },
  { title: '3.2 Market Knowledge', content: `<p>Before any RE interview, know:</p><ul><li>Current 10-year Treasury yield (drives mortgage rates and cap rates)</li><li>Direction of cap rates in major markets</li><li>Which property sectors are performing well/poorly and why</li><li>2-3 recent notable transactions in the firm's target sector</li><li>Key trends: remote work impact on office, industrial demand from e-commerce, housing affordability, interest rate environment</li></ul>` },
  { title: '3.3 Practice Drills', content: `<p><strong>Weekly:</strong> Pull a real deal from Real Capital Analytics or a press release and build a back-of-envelope pro forma (estimate NOI, apply cap rate, model debt, calculate equity return).</p><p><strong>Daily:</strong> Follow CBRE, JLL, or Cushman & Wakefield research reports for market data.</p><p><strong>Before interviews:</strong> Have 1-2 investment ideas — properties or markets you'd invest in and why, with specific numbers (cap rate, NOI growth, target IRR).</p>` },
];
