// Investment Banking Technical Mastery Manual — Module 3.3 (DCF) + Module 4 (Advanced Valuation)
export const DCF_SECTIONS = [
  {
    title: '3.3.1–3.3.2 What a DCF Is & The DCF Process',
    content: `<h3>What a DCF Is</h3>
<p>A DCF values a company based on the present value of its future cash flows.</p>
<p><strong>Why it exists:</strong> A business is worth the cash it can generate for investors over time.</p>
<p><strong>Why it is used:</strong> Because it is conceptually the most intrinsic method. It asks: what are the company's cash flows worth today after accounting for risk and time value of money?</p>
<p><strong>Intuition:</strong> A dollar received next year is worth less than a dollar today because: you could invest today's dollar elsewhere, future cash flows are uncertain, inflation erodes value over time.</p>

<h3>The DCF Process</h3>
<p>A standard unlevered DCF usually involves:</p>
<ol><li>Project operating performance for 5–10 years</li><li>Calculate Unlevered Free Cash Flow (UFCF)</li><li>Estimate a discount rate using WACC</li><li>Estimate Terminal Value</li><li>Discount forecast cash flows and terminal value back to present</li><li>Sum present values to get Enterprise Value</li><li>Bridge from Enterprise Value to Equity Value if needed</li><li>Divide by diluted shares to get implied share price if relevant</li></ol>`,
  },
  {
    title: '3.3.3–3.3.4 Unlevered Free Cash Flow (UFCF)',
    content: `<p><strong>Definition:</strong> Cash flow generated by the business's operations after taxes and required reinvestment, before interest and debt-related cash flows.</p>
<p><strong>Standard formula:</strong> UFCF = EBIT × (1 - Tax Rate) + D&amp;A - CapEx - Change in Net Working Capital</p>
<p><strong>Why EBIT and not Net Income?</strong> Because UFCF is capital structure neutral.</p>
<p><strong>Why add back D&amp;A?</strong> Because they are non-cash expenses.</p>
<p><strong>Why subtract CapEx?</strong> Because maintaining and growing assets requires real cash spending.</p>
<p><strong>Why subtract increases in NWC?</strong> Because more cash tied up in working capital means less cash available to investors.</p>
<p><strong>Strong explanation:</strong> "Unlevered free cash flow measures the cash generated by the company's core operations after taxes and reinvestment needs, but before interest expense, debt repayment, or other financing decisions. That makes it appropriate for valuing the entire firm using enterprise value."</p>

<h3>Example UFCF Walkthrough</h3>
<p>Suppose: Revenue = 500, EBITDA = 100, D&amp;A = 20, EBIT = 80, Tax rate = 25%, CapEx = 25, Increase in NWC = 10</p>
<p>Then: EBIT × (1 - tax) = 80 × 75% = 60. Add D&amp;A = +20. Subtract CapEx = -25. Subtract increase in NWC = -10. <strong>UFCF = 45</strong></p>
<p><strong>Interview insight:</strong> If a candidate produces the number but cannot explain why each term is there, that is weak. Interviewers care about the reasoning.</p>`,
  },
  {
    title: '3.3.5–3.3.6 Why Unlevered & WACC',
    content: `<h3>Why We Use Unlevered, Not Levered, Cash Flow in Most DCFs</h3>
<p>Because the DCF is usually designed to value the business independent of financing decisions. If you used levered cash flow: interest expense would affect the numerator, debt would implicitly affect value, comparability across companies would decline. Using UFCF with WACC is the standard firm valuation framework.</p>

<h3>WACC: Weighted Average Cost of Capital</h3>
<p><strong>What it is:</strong> The blended opportunity cost required by the company's capital providers, weighted by their share of the capital structure.</p>
<p><strong>Why it exists:</strong> If the company generates cash flows, those cash flows must compensate both debt holders and equity holders for the risk they bear.</p>
<p><strong>Standard formula:</strong> WACC = (E / V) × Cost of Equity + (D / V) × Cost of Debt × (1 - Tax Rate)</p>
<p>Where: E = market value of equity, D = market value of debt, V = E + D</p>
<p><strong>Why cost of debt is tax-affected:</strong> Interest expense is tax-deductible in most contexts, which lowers the effective cost of debt.</p>
<p><strong>Why WACC matters:</strong> It is the discount rate used for UFCF because UFCF belongs to all capital providers.</p>`,
  },
  {
    title: '3.3.7–3.3.10 Cost of Equity, Beta, Cost of Debt, Capital Structure',
    content: `<h3>Cost of Equity and CAPM</h3>
<p><strong>Common formula:</strong> Cost of Equity = Risk-Free Rate + Beta × Equity Risk Premium</p>
<p><strong>Risk-Free Rate:</strong> Usually the yield on a long-dated government bond, often 10-year or 20-year depending on context.</p>
<p><strong>Equity Risk Premium:</strong> The extra return investors require for owning equities instead of risk-free securities.</p>
<p><strong>Beta:</strong> Measures how sensitive the stock is to market movements.</p>
<p><strong>Intuition:</strong> Equity holders take residual risk. Their required return is generally higher than debt holders' because they get paid after debt holders and face more uncertainty.</p>
<p><strong>Banker nuance:</strong> In practice, bankers often use a target ERP, normalized risk-free rate assumptions, and beta derived from comparable companies.</p>

<h3>Unlevering and Relevering Beta</h3>
<p>This is a frequent interview topic.</p>
<p><strong>Why we do it:</strong> Observed stock beta reflects both business risk and capital structure. To estimate a company's beta for WACC, we often: 1) take comparable companies' betas, 2) unlever them to remove debt impact, 3) average the unlevered betas, 4) relever based on the target company's capital structure.</p>
<p><strong>Basic logic:</strong> More debt generally increases equity beta because debt amplifies equity risk.</p>
<p><strong>High-level formulas:</strong></p>
<p>Unlevered Beta = Levered Beta / [1 + (1 - tax) × D / E]</p>
<p>Relevered Beta = Unlevered Beta × [1 + (1 - tax) × D / E]</p>
<p><strong>Interview insight:</strong> You do not always need the exact formula memorized perfectly if you can explain the concept clearly, but at elite level you should know both.</p>

<h3>Cost of Debt</h3>
<p><strong>What it is:</strong> The rate the company would pay to borrow today.</p>
<p><strong>How it is estimated:</strong> Current yield on existing debt, Interest rate implied by credit spreads and leverage, Market rates for similar borrowers.</p>
<p><strong>Why bankers use pre-tax debt cost then multiply by (1 - tax):</strong> Because the tax shield reduces the effective cost.</p>

<h3>Capital Structure Weights</h3>
<p>Use market values, not book values, in most cases.</p>
<p><strong>Why market values?</strong> Because WACC reflects current investor opportunity costs and market expectations.</p>
<p><strong>Common interview trap:</strong> Candidates say "use book value because it is on the Balance Sheet." That is usually not how WACC is constructed in valuation work.</p>`,
  },
  {
    title: '3.3.11–3.3.14 Terminal Value, Discounting, EV to Equity Bridge, Sensitivity',
    content: `<h3>Terminal Value</h3>
<p>Terminal Value captures the value of the business beyond the explicit forecast period. This is usually a very large portion of DCF value, often the largest single component.</p>
<p><strong>Two primary methods:</strong></p>
<p><strong>1. Gordon Growth Method:</strong> Terminal Value = Final Year UFCF × (1 + g) / (WACC - g), where g = perpetual growth rate. Assumes the company's cash flow grows at a stable perpetual rate forever. Good perpetual growth rate range: Usually tied to long-term GDP growth or inflation expectations. Common ranges are 2–3% in many mature-market DCFs, though context matters.</p>
<p><strong>Interview nuance:</strong> A perpetual growth rate higher than long-term nominal GDP growth is usually hard to justify indefinitely.</p>
<p><strong>2. Exit Multiple Method:</strong> Terminal Value = Final Year Metric × Exit Multiple. Common metric: EBITDA. Assumes the company can be sold at the end of the projection period at a market-based multiple similar to peers.</p>
<p><strong>Pros and cons:</strong> More market anchored, Easier for many practitioners to relate to. But can embed current market mispricing and may be circular if comps already reflect the same market conditions.</p>
<p><strong>Interview insight:</strong> Elite candidates understand that neither method is "more correct" universally. Gordon Growth is theoretically cleaner; Exit Multiple is market-based and often easier to benchmark.</p>

<h3>Discounting Cash Flows and Terminal Value</h3>
<p>Each forecast UFCF is discounted by: PV = Cash Flow / (1 + WACC)^n</p>
<p>Terminal Value is discounted from the terminal year back to present as well.</p>
<p><strong>Mid-year convention:</strong> In practice, some models discount cash flows assuming they arrive throughout the year rather than at year-end. This slightly increases valuation.</p>
<p><strong>Why interviewers ask about it:</strong> Because it shows whether you understand that timing matters.</p>

<h3>From Enterprise Value to Equity Value in a DCF</h3>
<p>After summing discounted cash flows and terminal value, you get Enterprise Value. Then bridge to Equity Value: Add cash and non-operating assets, Subtract debt, Subtract preferred stock, Subtract minority interest if relevant, Adjust for other claims or non-core items. Then divide by diluted shares outstanding to get implied share price.</p>

<h3>DCF Sensitivity Analysis</h3>
<p>Because DCF output is highly assumption-sensitive, bankers use sensitivity tables.</p>
<p><strong>Common sensitivities:</strong> WACC, Terminal growth rate, Exit multiple.</p>
<p><strong>Why it matters:</strong> A DCF is not about false precision. It is about building a valuation range and understanding how assumptions affect value.</p>
<p><strong>Interview insight:</strong> If asked what matters most in a DCF, strong candidates mention: WACC, terminal value assumptions, margin assumptions, revenue growth, capital intensity / reinvestment, working capital.</p>`,
  },
  {
    title: '3.3.15 Common DCF Interview Questions',
    content: `<p><strong>Why does increasing WACC lower valuation?</strong> Because future cash flows are discounted more heavily, reducing present value.</p>
<p><strong>Why does increasing terminal growth increase valuation?</strong> Because the company is assumed to generate a larger stream of future cash flows in perpetuity.</p>
<p><strong>Which method tends to produce the highest valuation?</strong> There is no universal answer, but precedent transactions often give higher values than trading comps due to control premium, while DCF depends on assumptions.</p>
<p><strong>When is a DCF less useful?</strong> Highly unpredictable cash flows, Early-stage companies with no steady-state economics, Financial institutions where debt is operational rather than purely financing-related.</p>`,
  },
  {
    title: '4.1–4.3 Why Advanced Valuation Matters, Interest Rates, Depreciation & Cash Flow',
    content: `<h3>4.1 Why Advanced Valuation Matters</h3>
<p>Basic valuation formulas get you through average interviews. Advanced nuance is what separates top 1% candidates.</p>
<p>Interviewers at stronger groups often push beyond definitions and ask: What actually drives this valuation? What assumptions are dangerous? Why might two bankers disagree? What breaks standard formulas in the real world?</p>

<h3>4.2 Why Interest Rates Affect Valuation</h3>
<p>This is one of the most frequently tested macro-valuation questions.</p>
<p><strong>Direct DCF effect:</strong> Higher interest rates usually increase the risk-free rate, which often increases cost of equity and cost of debt, which increases WACC, which lowers valuation.</p>
<p><strong>Market multiple effect:</strong> Higher rates can compress valuation multiples because future cash flows are worth less in present value terms and financing becomes more expensive.</p>
<p><strong>Business-specific effect:</strong> The effect is not uniform. High-growth companies are often more sensitive because more of their value is in distant future cash flows. Heavily levered companies may be hurt more by refinancing costs. Some financial companies may benefit from higher rates depending on net interest margins.</p>
<p><strong>Strong answer:</strong> "Higher interest rates usually reduce valuation through both DCF and market multiple channels. In a DCF, the risk-free rate tends to increase the discount rate, lowering the present value of cash flows. In the market, higher rates can compress valuation multiples because investors can earn more from lower-risk alternatives and because financing becomes more expensive. The impact tends to be especially pronounced for long-duration, high-growth assets."</p>

<h3>4.3 Why Increasing Depreciation Can Increase Cash Flow</h3>
<p>This is a classic interview favorite.</p>
<p><strong>Mechanics:</strong> Higher depreciation lowers pre-tax income. Lower pre-tax income lowers taxes. Because depreciation is non-cash, it is added back. So: Net income falls, cash taxes fall, cash flow can rise due to the tax shield.</p>
<p><strong>Important nuance:</strong> This does not mean the business is "better." It means accounting expense timing can reduce taxes and improve near-term cash flow.</p>
<p><strong>Real-world nuance:</strong> If the company eventually needs more CapEx, the economic benefit may be temporary or offset later.</p>`,
  },
  {
    title: '4.4–4.6 Working Capital Edge Cases, Circular References, Maintenance vs Growth CapEx',
    content: `<h3>4.4 Working Capital Edge Cases</h3>
<p><strong>Deferred Revenue:</strong> Increase in deferred revenue is a source of cash. Why? The company got cash before recognizing revenue.</p>
<p><strong>Negative Working Capital Businesses:</strong> Some great businesses have negative operating working capital. Examples may include: subscription software with upfront billing, certain retailers with strong supplier terms and fast inventory turnover.</p>
<p><strong>Why negative working capital can be attractive:</strong> The business effectively gets financed by customers or suppliers.</p>
<p><strong>But candidate caution:</strong> Negative working capital is not automatically good. You need to understand why it exists and whether it is sustainable.</p>

<h3>4.5 Circular References Conceptually</h3>
<p>Circular references happen when one part of the model depends on another, which in turn depends back on the first.</p>
<p><strong>Common examples:</strong> Interest expense depends on debt balance, Debt balance depends on cash flow, Cash flow depends on interest expense.</p>
<p><strong>Why this matters in interviews:</strong> Even without Excel, interviewers want to know you understand why modeling can require iterative solving.</p>
<p><strong>Simple explanation:</strong> "You get a circular reference when interest expense depends on ending debt, but ending debt depends on cash flow, and cash flow depends on interest expense. In practice, models solve this with either iteration or simplifying assumptions such as average debt balances."</p>

<h3>4.6 Maintenance CapEx vs Growth CapEx</h3>
<p><strong>Maintenance CapEx:</strong> Spending required to sustain current operations.</p>
<p><strong>Growth CapEx:</strong> Spending intended to expand capacity or growth.</p>
<p><strong>Why interviewers care:</strong> Because EBITDA and even EBIT may overstate economic profitability if maintenance CapEx is high.</p>
<p><strong>Advanced answer:</strong> "In a DCF, total CapEx is usually subtracted, but from an economic perspective it can be useful to distinguish maintenance CapEx from growth CapEx because a business with low maintenance CapEx can convert more earnings into free cash flow than one that must constantly reinvest just to stand still."</p>`,
  },
  {
    title: '4.7–4.10 Why Multiples Differ, Sector Nuance, Control & Synergies, Terminal Value Dominance',
    content: `<h3>4.7 Why Multiples Differ Across Companies</h3>
<p>Valuation multiples are driven by more than just industry membership.</p>
<p><strong>Major drivers:</strong> Growth, Margins, ROIC, Risk, Capital intensity, Cash conversion, Market sentiment.</p>
<p><strong>Strong intuition:</strong> Higher-growth, higher-margin, higher-ROIC businesses with defensible advantages usually deserve higher multiples.</p>

<h3>4.8 Sector-Specific Valuation Nuance</h3>
<p><strong>Banks and Insurance:</strong> Traditional DCF and EV / EBITDA are less useful because debt is operational rather than purely financing-related. Common metrics include: P / Book, ROE, P / Earnings.</p>
<p><strong>REITs:</strong> Use metrics like EV / EBITDA sometimes, but more commonly AFFO / FFO-based metrics depending on context.</p>
<p><strong>Early-Stage / High-Growth Tech:</strong> Revenue multiples may matter more if EBITDA is negative. But interviewers will want you to explain what must happen for a revenue-multiple valuation to make sense over time.</p>

<h3>4.9 Control Value, Synergies, and Strategic Value</h3>
<p>A company may be worth more to an acquirer than to public shareholders because the buyer can generate synergies.</p>
<p><strong>Types of synergies:</strong> Cost synergies, Revenue synergies, Tax synergies, Financing synergies in some cases.</p>
<p><strong>Interview nuance:</strong> Strategic value is not the same as standalone intrinsic value. This is why sell-side valuation often includes precedent transactions.</p>

<h3>4.10 Why Terminal Value Dominates Many DCFs</h3>
<p>In many DCFs, terminal value is the majority of the valuation.</p>
<p><strong>Why this happens:</strong> Because many businesses are expected to continue operating long after the explicit forecast period.</p>
<p><strong>Why interviewers ask about it:</strong> Because it highlights one of the weaknesses of DCFs: much of the value often depends on assumptions far into the future.</p>
<p><strong>Strong answer:</strong> "Terminal value often represents the majority of a DCF because the explicit forecast period may only capture 5–10 years, while the business is assumed to generate cash flows indefinitely beyond that. This makes terminal assumptions highly important and a reason why DCFs should be triangulated with market-based methods."</p>

<h3>Module 4 Practice Drills</h3>
<p><strong>Technical drills:</strong></p>
<ol><li>Explain how interest rates affect valuation</li><li>Explain why higher depreciation can increase cash flow</li><li>Explain circular references conceptually</li><li>Explain why terminal value often dominates a DCF</li><li>Explain maintenance vs growth CapEx</li><li>Explain why a high-growth company usually trades at a higher multiple</li><li>Explain why banks are valued differently from industrial companies</li></ol>
<p><strong>Interview-style questions:</strong> What happens to valuation if interest rates increase? Why is terminal value so important? Why might EV / EBITDA not work well for banks? Why could two companies in the same industry trade at different multiples?</p>
<p><strong>Explain-out-loud exercise:</strong> Take a high-growth tech company and a mature industrial company and explain why their valuation frameworks differ.</p>
<p><strong>Self-testing framework — When a valuation question gets harder, ask:</strong></p>
<ol><li>Is this a formula question or a business-logic question?</li><li>What are the first-order effects?</li><li>What are the second-order effects?</li><li>Are there sector-specific nuances?</li><li>What assumptions are hidden in the question?</li></ol>`,
  },
];
