export type QuizQuestion = {
  id: number;
  category: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {id:1,category:"Core Concepts",question:"Why is money today worth more than money tomorrow?",options:["Because of inflation","Because you could invest it today and earn a return","Because the government prints more money over time","Because interest rates are always positive"],correct:1,explanation:"While inflation also reduces future money's value, the real reason is that you could invest money today and earn something with it. This is the core principle of the Time Value of Money."},
  {id:2,category:"Core Concepts",question:"A company generates $200 of cash flow per year, growing at 4% annually. Your discount rate is 10%. What is the company worth?",options:["$2,000","$2,857","$3,333","$5,000"],correct:2,explanation:"Company Value = Cash Flow / (Discount Rate - Growth Rate) = $200 / (10% - 4%) = $200 / 6% = $3,333."},
  {id:3,category:"Core Concepts",question:"What does WACC represent?",options:["The average rate of return a company must earn to satisfy all investors","The total cash flow generated per year","The cost of maintaining company assets","How much debt a company can take on"],correct:0,explanation:"WACC is the blended cost of a company's debt and equity financing. It represents the minimum return a company must earn on its existing assets to satisfy its creditors and owners."},
  {id:4,category:"Core Concepts",question:"If a project's IRR is 15% and the company's WACC is 12%, should the company pursue it?",options:["No, because the IRR is too high","Yes, because IRR exceeds WACC","No, because you should always use NPV instead","It depends on the payback period"],correct:1,explanation:"When IRR > WACC, the project earns more than the company's cost of capital, creating value. This is equivalent to the project having a positive NPV."},
  {id:5,category:"Core Concepts",question:"What happens to a company's Present Value if its Discount Rate increases?",options:["Present Value increases","Present Value stays the same","Present Value decreases","It depends on the growth rate"],correct:2,explanation:"A higher Discount Rate means you have better investment options elsewhere, so you'd pay less for this company's future cash flows."},
  {id:6,category:"Accounting",question:"Which financial statement would you look at first to assess profitability?",options:["Balance Sheet","Cash Flow Statement","Income Statement","Statement of Stockholders' Equity"],correct:2,explanation:"The Income Statement shows revenue, expenses, and profit over a period. It's the first place to assess whether a company is profitable."},
  {id:7,category:"Accounting",question:"Depreciation increases by $10. Assuming a 25% tax rate, what is the net effect on cash flow?",options:["Decreases by $10","Increases by $10","Increases by $2.50","Decreases by $7.50"],correct:2,explanation:"Depreciation is non-cash. It reduces pre-tax income by $10, saving $2.50 in taxes. Net Income falls by $7.50, but you add back $10 depreciation on the CFS. Net cash increase = $2.50 (the tax shield)."},
  {id:8,category:"Accounting",question:"A company purchases $100 of inventory with cash. How does this affect the Balance Sheet?",options:["Total assets increase by $100","Total assets decrease by $100","Total assets stay the same — cash down, inventory up","Total liabilities increase by $100"],correct:2,explanation:"Purchasing inventory with cash is an asset swap: Cash decreases by $100 and Inventory increases by $100. Total assets remain unchanged."},
  {id:9,category:"Accounting",question:"What is Working Capital?",options:["Total Assets minus Total Liabilities","Current Assets minus Current Liabilities","Cash minus Debt","Revenue minus Expenses"],correct:1,explanation:"Working Capital = Current Assets - Current Liabilities. It measures a company's short-term liquidity. Key components include Accounts Receivable, Inventory, and Accounts Payable."},
  {id:10,category:"Accounting",question:"A company has positive Net Income but negative cash flow. What could explain this?",options:["The company is paying too much in dividends","Large non-cash revenues, heavy capex, or working capital increases","This situation is impossible","The company has too much debt"],correct:1,explanation:"Net Income includes non-cash items and doesn't account for capex or working capital changes. A company can be profitable on paper while burning cash."},
  {id:11,category:"EV & Valuation",question:"What is the formula for Enterprise Value?",options:["Market Cap + Cash - Debt","Market Cap + Debt - Cash","Market Cap + Debt + Cash","Total Assets - Total Liabilities"],correct:1,explanation:"Enterprise Value = Equity Value (Market Cap) + Debt + Preferred Stock + Minority Interest - Cash. You add debt because an acquirer assumes it, and subtract cash because the acquirer gets it."},
  {id:12,category:"EV & Valuation",question:"Why do we add Debt and subtract Cash when calculating Enterprise Value?",options:["Because debt makes a company more valuable","Because an acquirer assumes debt obligations and receives the company's cash","Because we want to inflate the company's value","Because GAAP requires it"],correct:1,explanation:"Enterprise Value represents what you'd pay to acquire the entire business. You assume the debt (add it) but get the cash (subtract it). EV measures the value of core operations."},
  {id:13,category:"EV & Valuation",question:"A company raises $50M in debt. How does this affect Equity Value and Enterprise Value?",options:["Both increase by $50M","Equity Value up $50M, Enterprise Value unchanged","Equity Value unchanged, Enterprise Value up $50M","Both stay the same"],correct:3,explanation:"Raising debt increases Cash by $50M and Debt by $50M. Equity Value is unchanged. EV = Equity + Debt - Cash, so +$50M debt and +$50M cash cancel out. EV is unchanged."},
  {id:14,category:"EV & Valuation",question:"Which valuation multiple uses Enterprise Value in the numerator?",options:["P/E Ratio","Price to Book","EV/EBITDA","Dividend Yield"],correct:2,explanation:"EV/EBITDA uses Enterprise Value because EBITDA is available to all capital providers. P/E uses Equity Value because Net Income belongs to equity holders only."},
  {id:15,category:"EV & Valuation",question:"Why is EV/EBITDA often preferred over P/E for comparisons?",options:["Because it is always higher","Because it is capital structure-neutral and unaffected by depreciation or tax differences","Because EBITDA equals cash flow","Because P/E is outdated"],correct:1,explanation:"EV/EBITDA allows comparison regardless of capital structure, D&A policies, and tax situations. P/E is distorted by all of these factors."},
  {id:16,category:"DCF Analysis",question:"What are the two main components of a DCF analysis?",options:["Revenue and Expenses","Projection period cash flows and Terminal Value","Equity Value and Enterprise Value","EBITDA and Net Income"],correct:1,explanation:"A DCF has two parts: (1) PV of projected Free Cash Flows during the forecast period (5-10 years), and (2) Terminal Value capturing value beyond the projection period."},
  {id:17,category:"DCF Analysis",question:"What discount rate do you use for Unlevered Free Cash Flow?",options:["Cost of Equity","Cost of Debt","WACC","Risk-Free Rate"],correct:2,explanation:"Unlevered FCF is available to all capital providers, so you discount it at WACC, which blends the cost of equity and after-tax cost of debt."},
  {id:18,category:"DCF Analysis",question:"How do you calculate Unlevered Free Cash Flow?",options:["Net Income + D&A - CapEx - Changes in WC","EBIT x (1 - Tax Rate) + D&A - CapEx - Changes in WC","EBITDA - Taxes - CapEx","Revenue - All Expenses"],correct:1,explanation:"UFCF = EBIT x (1 - Tax Rate) + D&A - CapEx +/- Changes in Working Capital. Start with after-tax operating income, add back non-cash charges, subtract capex, adjust for WC."},
  {id:19,category:"DCF Analysis",question:"What are the two methods for calculating Terminal Value?",options:["Book Value and Market Value methods","Gordon Growth Model and Exit Multiple method","Top-down and Bottom-up methods","Comparable Companies and Transactions"],correct:1,explanation:"Terminal Value uses either (1) Gordon Growth Model: TV = FCF x (1+g) / (WACC-g), or (2) Exit Multiple: TV = Final Year EBITDA x Exit Multiple."},
  {id:20,category:"DCF Analysis",question:"A DCF using UFCF and WACC produces what type of value?",options:["Equity Value per share","Enterprise Value","Book Value","Liquidation Value"],correct:1,explanation:"A DCF using UFCF and WACC produces Enterprise Value. To get Equity Value, subtract net debt and other claims, then divide by shares outstanding."},
  {id:21,category:"M&A Models",question:"What does it mean for an acquisition to be 'accretive'?",options:["The acquirer's stock price goes up","Combined EPS is higher than acquirer's standalone EPS","The target company is profitable","The deal is paid with cash"],correct:1,explanation:"An accretive deal increases the acquirer's EPS. This happens when the target's earnings yield exceeds the cost of financing the deal."},
  {id:22,category:"M&A Models",question:"Company A (P/E 20x) acquires Company B (P/E 10x) using 100% stock. Accretive or dilutive?",options:["Accretive — target has lower P/E","Dilutive — acquirer has higher P/E","Neutral","Cannot determine"],correct:0,explanation:"When a higher-P/E company acquires a lower-P/E company in all-stock, it is accretive. The target's earnings yield (10%) exceeds the acquirer's (5%)."},
  {id:23,category:"M&A Models",question:"What are the three main ways to fund an acquisition?",options:["Cash, Debt, and Revenue","Cash, Stock, and Debt","Stock, Bonds, and Options","Cash, Preferred Stock, and Warrants"],correct:1,explanation:"Acquisitions are funded with Cash, Stock (issuing new shares), Debt (borrowing), or a combination of all three."},
  {id:24,category:"M&A Models",question:"What is Goodwill in M&A?",options:["The target's brand value","Premium paid above fair market value of net identifiable assets","The target's total assets","Expected synergies from the deal"],correct:1,explanation:"Goodwill = Purchase Price - Fair Market Value of Net Identifiable Assets. It represents the premium paid above what the target's assets are worth."},
  {id:25,category:"LBO Models",question:"What is a Leveraged Buyout (LBO)?",options:["A company buys back its own shares","A financial sponsor acquires a company using significant debt","A company issues new equity for an acquisition","A hostile takeover by a competitor"],correct:1,explanation:"In an LBO, a PE firm acquires a company using a combination of debt (60-80% of purchase price) and equity. The company's cash flows repay the debt over time."},
  {id:26,category:"LBO Models",question:"What makes a company a good LBO candidate?",options:["High growth, unprofitable, heavy R&D","Stable cash flows, low capex, strong market position","Highly cyclical with no recurring revenue","Early-stage startup"],correct:1,explanation:"Good LBO candidates have predictable cash flows (to service debt), low capex, strong competitive position, and improvement opportunities."},
  {id:27,category:"LBO Models",question:"What are the three main ways a PE firm generates returns in an LBO?",options:["Revenue growth, cost cutting, tax optimization","Debt paydown, EBITDA growth, and multiple expansion","Dividends, buybacks, interest income","IPO, secondary offering, merger"],correct:1,explanation:"PE returns come from: (1) Debt paydown increasing equity value, (2) EBITDA growth through revenue or margin improvement, (3) Multiple expansion at exit."},
  {id:28,category:"LBO Models",question:"PE firm buys company for $500M ($200M equity, $300M debt). Sells for $800M with $100M debt remaining. What is the MOIC?",options:["1.6x","2.5x","3.5x","4.0x"],correct:2,explanation:"Exit equity = $800M - $100M = $700M. MOIC = $700M / $200M = 3.5x. Leverage amplified returns — company grew 60% but equity returned 3.5x."},
  {id:29,category:"LBO Models",question:"What does IRR measure in an LBO context?",options:["Total dollar profit","Annualized return on the PE firm's equity investment","Company's revenue growth rate","Interest rate on the debt"],correct:1,explanation:"IRR is the annualized, compounded return on equity. A 3.5x return over 5 years is roughly 28% IRR. Most PE firms target 20-25%+."},
  {id:30,category:"LBO Models",question:"What is a 'Paper LBO'?",options:["An LBO analysis done on paper/mentally without Excel in 10-15 minutes","A fake LBO for practice only","An LBO involving a publishing company","A theoretical LBO that never closes"],correct:0,explanation:"A Paper LBO is an interview exercise where you build a simplified LBO by hand — purchase price, debt/equity split, cash flows, debt paydown, and exit returns."},
];
