export const ST_BEHAVIORAL_SECTIONS = [
  {
    title: 'Why S&T, and Sales vs Trading',
    content: `<p>The behavioral side of an S&T interview is not a formality; on a trading floor, fit and temperament matter as much as technical skill, because the work is high-pressure, collaborative in tight quarters, and unforgiving of people who crack or cannot communicate. Two questions anchor everything: why S&T, and which seat.</p>

<div class="key-concept">Your <strong>"why S&T"</strong> must be specific and personal, because generic answers are transparent and common. The strong themes: a genuine fascination with markets (and evidence of it, you follow them, you have views), attraction to real-time decision-making and immediate feedback, comfort with risk and uncertainty, and enjoyment of fast, quantitative thinking. Tie these to something real about you, a time you traded or followed markets, a way you naturally think, rather than reciting that the work is "fast-paced and exciting." The interviewer is asking whether you actually want <em>this</em> job, with its particular rhythm and pressures, or just a prestigious finance role. Show you understand what the day is really like and want it specifically.</div>

<div class="framework-box"><div class="fw-label">SALES VS TRADING: PICK AND JUSTIFY</div><strong>Sales</strong> fits you if you are outgoing and articulate, energized by relationships, good at translating complex markets into clear ideas, and motivated by serving clients and being the trusted voice they call.<br/><strong>Trading</strong> fits you if you are decisive, comfortable owning risk and being wrong, quick with numbers, and able to stay calm when money moves against you in real time.<br/>There is no better answer; there is only the honest, well-justified one. Connect the seat to how you actually operate.</div>

<div class="takeaway-box">Prepare a "why S&T" that names markets fascination, real-time decisions, and risk comfort, anchored to genuine evidence about you, and a clear "sales or trading" choice justified by your real temperament. Avoid clichés everyone uses ("fast-paced," "I love markets" with nothing behind it). Specificity and self-awareness are what land.</div>`,
  },
  {
    title: 'The Temperament They Are Screening For',
    content: `<p>Behind every behavioral question on a trading floor is an assessment of temperament. The floor has a specific personality profile it trusts, and your stories and demeanor should demonstrate it.</p>

<div class="key-concept">The traits desks screen for: <strong>composure under pressure</strong> (you stay clear-headed when stakes are high and things go wrong), <strong>comfort with being wrong</strong> (you can take a loss or a mistake, own it, learn, and move on without spiraling), <strong>decisiveness</strong> (you can commit to a decision with incomplete information rather than freezing), <strong>intellectual honesty</strong> (you do not bluff or hide errors), and <strong>resilience</strong> (you bounce back from setbacks). These are not generic "good employee" traits; they are specifically what keeps a trader functional. A trader who cannot handle being wrong, or who freezes under pressure, or who hides a losing position, is dangerous. Your behavioral answers should consistently illustrate these qualities through real stories.</div>

<div class="key-concept"><strong>The "tell me about a time you were wrong / failed / lost" question is pivotal in S&T</strong>, more than in most fields, because handling loss is the job. The wrong answer is a humble-brag or a refusal to admit real failure. The right answer shows a genuine mistake, that you took ownership without excessive self-flagellation, that you learned something specific, and that you applied it. Crucially, it shows you can lose without falling apart, exactly the resilience a desk needs. Traders are wrong constantly; what matters is the relationship with being wrong. Demonstrating a healthy, learning-oriented, non-fragile response to failure is one of the most valuable things you can convey.</div>

<div class="takeaway-box">Build your behavioral stories to showcase composure, comfort with being wrong, decisiveness, honesty, and resilience, because those are what the floor actually screens for. Especially nail the "time you failed or were wrong" story: a real mistake, clean ownership, a specific lesson, and evidence you did not crumble. That answer often matters more than any technical question.</div>`,
  },
  {
    title: 'Composure, Curiosity, and Questions to Ask',
    content: `<p>Two more behavioral dimensions round out a strong showing: how you carry yourself in the room, and the curiosity you signal.</p>

<div class="key-concept"><strong>Composure in the interview itself is part of the test.</strong> Interviewers often apply pressure deliberately, rapid math, a hard brainteaser, pushback on your views, even mild stress or interruption, to see how you respond, because that pressure simulates the floor. The content of your answer matters, but so does your demeanor: staying calm, not getting flustered or defensive, keeping your reasoning clear when challenged, and recovering gracefully from a stumble. If you blank on a question, the composed response (acknowledge it, reason aloud, attempt it) beats panic every time. They are watching whether you would keep your head when a position moves against you, and the interview is a live audition for exactly that.</div>

<div class="key-concept"><strong>Genuine market curiosity is the trait that cannot be faked and most distinguishes candidates.</strong> The people who thrive in S&T are intrinsically fascinated by markets, they read about them for fun, they have opinions, they notice connections. Conveying real, demonstrated curiosity, through the views you hold, the questions you ask, and the way you talk about markets, signals you will keep learning and stay engaged for a career. This is why following markets beforehand pays off twice: it equips your answers and it proves your curiosity is real.</div>

<div class="framework-box"><div class="fw-label">SMART QUESTIONS TO ASK THEM</div>Ask things that show genuine interest in the work and markets, not logistics: how the desk has adapted to electronic and systematic trading; what they think is most misunderstood about the job; how a typical day flows on their desk; what separates analysts who thrive from those who struggle; what market theme they find most interesting right now. Avoid questions easily answered by a website, and avoid asking only about hours or pay.</div>

<div class="takeaway-box">Carry yourself with calm under the interview's deliberate pressure, treat stumbles as something to recover from gracefully rather than panic over, and let genuine market curiosity show through your views and your questions. Composure and authentic interest are the behavioral qualities that most reliably separate offers from rejections on the floor.</div>`,
  },
];
