export const ST_MARKETS_SECTIONS = [
  { title: '1.1 Market Fundamentals', content: `<p>S&T interviews require you to demonstrate <strong>real-time market awareness</strong>. You must know: where the S&P 500 is trading, the 10-year Treasury yield, recent Fed decisions, oil prices, and major FX moves.</p><p>Build a daily habit: every morning, check Bloomberg or CNBC for the top 5 market movers. Know <strong>why</strong> they moved, not just that they did.</p>` },
  { title: '1.2 Asset Classes', content: `<h4>Equities</h4><p>Stocks represent ownership. Key metrics: P/E, EV/EBITDA, earnings growth, dividend yield. Understand market cap (large/mid/small), growth vs. value, and sector rotations.</p><h4>Fixed Income</h4><p>Bonds represent debt. Key concepts: yield, coupon, duration, credit spreads, yield curve (normal/inverted/flat). The 10-year Treasury is the benchmark risk-free rate.</p><h4>Currencies (FX)</h4><p>Exchange rates are driven by interest rate differentials, trade balances, and central bank policy. Key pairs: EUR/USD, USD/JPY, GBP/USD.</p><h4>Commodities</h4><p>Oil (WTI, Brent), gold, natural gas. Driven by supply/demand, geopolitics, and macro sentiment.</p><h4>Derivatives</h4><p>Options (calls/puts), futures, swaps. Understand basic option payoff diagrams and concepts like delta, implied volatility, and hedging.</p>` },
  { title: '1.3 How Trading Desks Make Money', content: `<p><strong>Market Making:</strong> The desk provides liquidity by quoting bid and ask prices. Profit comes from the bid-ask spread. Example: buy a bond at 99.50, sell at 100.00, pocket 0.50.</p><p><strong>Flow Trading:</strong> Executing client orders and managing the resulting inventory risk.</p><p><strong>Proprietary Positioning:</strong> Taking directional bets based on the desk's view (limited post-Volcker Rule).</p><p><strong>Structuring Revenue:</strong> Custom derivative products designed for client hedging needs generate premium income.</p>` },
  { title: '1.4 Sales vs. Trading vs. Structuring', content: `<p><strong>Sales:</strong> Client-facing. Pitches trade ideas, manages relationships with institutional investors (hedge funds, pensions). Success = client revenue generated.</p><p><strong>Trading:</strong> Execution and risk management. Makes markets, manages inventory. Success = desk P&L.</p><p><strong>Structuring:</strong> Designs complex derivative products. Highly quantitative. Success = product innovation and client solutions.</p><p><strong>Interview tip:</strong> You MUST know which of the three you want and why. "I want to be in S&T" is not specific enough.</p>` },
];

export const ST_QUANT_SECTIONS = [
  { title: '2.1 Mental Math & Speed', content: `<p>S&T interviews test mental math more aggressively than any other finance role. Practice:</p><ul><li>Multiplying 2-digit numbers quickly (37 x 24)</li><li>Percentage changes (stock goes from 84 to 91 — what's the % change?)</li><li>Compounding / discounting in your head</li><li>Converting fractions to decimals instantly (3/8 = 0.375)</li></ul><p>Speed matters. Practice with a timer daily.</p>` },
  { title: '2.2 Probability & Expected Value', content: `<p><strong>Expected Value (EV)</strong> = sum of (probability x payoff) for all outcomes.</p><h4>Classic Interview Question:</h4><p>"I flip a fair coin. Heads, I pay you $10. Tails, you pay me $6. Would you play?"</p><p>EV = (0.5 x $10) + (0.5 x -$6) = $5 - $3 = <strong>+$2</strong>. Yes, you should play — positive expected value.</p><h4>Follow-up:</h4><p>"What if I change it to $10 heads, $11 tails?" EV = $5 - $5.50 = <strong>-$0.50</strong>. Do not play.</p><p>Know: Bayes' theorem basics, conditional probability, combinatorics (choose/permute), and the difference between independent and dependent events.</p>` },
  { title: '2.3 Brainteasers', content: `<p><strong>"How many golf balls fit in a school bus?"</strong></p><p>Process: Estimate bus interior volume (~2.5m x 2m x 6m = 30 cubic meters = 30,000,000 cm³). Golf ball volume ≈ 40 cm³. 30M / 40 = ~750,000. Account for packing efficiency (~64%) = ~480,000 golf balls.</p><p><strong>"You have 100 coins on a table, 30 are heads up, 70 are tails. Blindfolded, split them into 2 groups so each group has the same number of heads."</strong></p><p>Answer: Take any 30 coins and flip them all. Group 1 = those 30 (flipped). Group 2 = the remaining 70. Both groups now have the same number of heads.</p>` },
  { title: '2.4 Trading Games & Risk', content: `<p>Interviewers may run a live trading game. Key principles:</p><ul><li><strong>Manage position size:</strong> Never bet everything on one trade.</li><li><strong>Update on new information:</strong> Bayesian thinking — how does each new data point change your view?</li><li><strong>Know your edge:</strong> Only trade when you have an informational or analytical advantage.</li><li><strong>Cut losses:</strong> Don't hold losing positions hoping they'll recover.</li></ul><p><strong>"I'm thinking of a number between 1 and 100. You can bid. If you bid over, you pay me your bid. If you bid under, nothing happens. What do you bid?"</strong></p><p>This tests your understanding of adverse selection and winner's curse. You should bid conservatively — around 30-35.</p>` },
];

export const ST_BEHAVIORAL_SECTIONS = [
  { title: '3.1 "Why Sales & Trading?"', content: `<p><strong>Weak:</strong> "I like the fast-paced environment and markets are exciting."</p><p><strong>Elite:</strong> "I'm drawn to S&T because I want to be in a role where my performance is measured objectively every day through P&L. I've been actively trading in a personal portfolio for two years, and what I've learned is that I thrive under the pressure of making decisions with incomplete information. The intellectual challenge of synthesizing macro data, positioning, and risk management in real time is what excites me — it's not about the adrenaline, it's about the problem-solving."</p>` },
  { title: '3.2 "Why Trading Over Sales?" (Or Vice Versa)', content: `<p><strong>For Trading:</strong> "I'm drawn to the quantitative rigor and the direct accountability of a P&L. I want my career to be measured by the quality of my risk decisions, not the strength of my relationships."</p><p><strong>For Sales:</strong> "I want to combine market knowledge with client relationships. I'm energized by understanding what institutional investors need and crafting solutions that serve those needs while generating revenue for the desk."</p>` },
  { title: '3.3 "Give Me a Trade Idea"', content: `<p>Structure your answer like this:</p><ol><li><strong>The Thesis:</strong> What is your view and why? (1-2 sentences)</li><li><strong>The Trade:</strong> Specifically how you'd express it. (Long X, short Y, buy Z options)</li><li><strong>The Catalyst:</strong> What event will prove you right? (Earnings, Fed meeting, data release)</li><li><strong>The Risk:</strong> What could go wrong and how you'd manage it.</li></ol><p><em>"I'm long 10-year Treasuries because I believe the market is underpricing recession risk. The inverted yield curve and weakening labor data suggest the Fed will be forced to cut rates faster than consensus expects. My catalyst is the next FOMC meeting. The risk is sticky inflation data — if CPI comes in hot, I'd cut the position immediately."</em></p>` },
  { title: '3.4 Market Questions You Must Know', content: `<p>Before every S&T interview, know:</p><ul><li>S&P 500 level and recent direction</li><li>10-year Treasury yield</li><li>Fed funds rate and next meeting date</li><li>Oil price (WTI)</li><li>EUR/USD</li><li>VIX level</li><li>Most recent major economic data release (jobs, CPI, GDP)</li><li>Top 2-3 market stories from this week</li></ul>` },
];

export const ST_TECHNICALS_SECTIONS = [
  { title: '4.1 Options Basics', content: `<p><strong>Call option:</strong> Right to BUY at strike price. Profitable when stock > strike + premium.</p><p><strong>Put option:</strong> Right to SELL at strike price. Profitable when stock < strike - premium.</p><p><strong>Key Greeks:</strong></p><ul><li><strong>Delta:</strong> How much the option price changes for a $1 move in the underlying.</li><li><strong>Gamma:</strong> Rate of change of delta.</li><li><strong>Theta:</strong> Time decay — options lose value as expiration approaches.</li><li><strong>Vega:</strong> Sensitivity to changes in implied volatility.</li></ul>` },
  { title: '4.2 Bond Math', content: `<p><strong>Price and yield move inversely.</strong> If yields rise, bond prices fall (and vice versa).</p><p><strong>Duration:</strong> A measure of interest rate sensitivity. A bond with 5-year duration loses ~5% in value for every 1% rise in rates.</p><p><strong>Convexity:</strong> The curvature of the price-yield relationship. Higher convexity = more upside when rates fall.</p><p><strong>Credit Spread:</strong> The additional yield a corporate bond pays over the risk-free Treasury. Wider spreads = more perceived risk.</p>` },
  { title: '4.3 FX & Macro Concepts', content: `<p><strong>Interest Rate Parity:</strong> Currency exchange rates adjust so that an investor earns the same return regardless of which country they invest in.</p><p><strong>Carry Trade:</strong> Borrow in a low-interest-rate currency, invest in a high-interest-rate currency. Profitable if the FX rate doesn't move against you.</p><p><strong>Central Bank Policy:</strong> Hawkish (raising rates, tightening) = currency strengthens. Dovish (cutting rates, easing) = currency weakens.</p>` },
  { title: '4.4 Practice Drills', content: `<h4>Daily Drill:</h4><p>Every morning, write down: S&P level, 10Y yield, oil price, EUR/USD, VIX. Note the direction from yesterday and write one sentence explaining why.</p><h4>Mental Math Drill:</h4><p>Set a 5-minute timer. Do 20 multiplication problems (2-digit x 2-digit). Track your accuracy and speed over time.</p><h4>Probability Drill:</h4><p>Work through 5 expected value problems daily. Sources: "Heard on the Street" by Timothy Crack, or "A Practical Guide to Quantitative Finance Interviews" (the Green Book).</p>` },
];
