export const ST_STRATEGIES_SECTIONS = [
  {
    title: 'Market-Making, Up Close',
    content: `<p>Market-making is the core activity of most modern bank trading desks, so understanding it deeply is essential. It is a genuinely different way of making money than "betting on the market," and candidates who grasp the distinction stand out.</p>

<div class="key-concept"><strong>A market maker continuously quotes both a price to buy (bid) and a price to sell (ask), and earns the spread by transacting with clients on both sides over time, while trying to stay roughly market-neutral.</strong> The maker does not primarily want the price to go up or down; it wants flow, a steady stream of buyers and sellers, so it can repeatedly buy at the bid and sell at the ask and bank the difference. The skill is in quoting well: tight enough to win business, wide enough to be compensated for risk, and adjusting quotes as inventory and conditions change. This is fundamentally a volume-and-spread business, not a directional-bet business, which is why it is the backbone of regulated bank desks.</div>

<div class="framework-box"><div class="fw-label">THE MARKET MAKER'S CHALLENGES</div><strong>Inventory risk:</strong> after buying from a client, the maker holds a position and is exposed to the price moving before it can sell it on. Managing this inventory (and hedging it) is central.<br/><strong>Adverse selection:</strong> the danger that the person trading with you knows something you do not. If informed traders consistently sell to you right before the price drops, your "spread" income is eaten by losses on inventory. Makers widen spreads when they suspect informed flow.<br/><strong>Skewing quotes:</strong> when holding too much of something, the maker shades its quotes to encourage trades that reduce the position (lower both bid and ask to attract buyers and discourage sellers).</div>

<div class="key-concept"><strong>Adverse selection</strong> is the subtle risk that makes market-making hard and is a favorite advanced interview topic. The market maker offers to trade with everyone, but some counterparties are better informed. If a flood of sellers hits your bid because they know bad news is coming, you accumulate inventory right before it falls, and the spread you earned does not cover the loss. Makers defend against this by widening spreads in uncertain or fast markets, by managing inventory actively, and by reading their flow for signs of informed trading. Understanding adverse selection, and that the spread must compensate the maker for it, shows you grasp why market-making is a real skill and not a free lunch.</div>

<div class="takeaway-box">Explain market-making as: quote both sides, earn the spread on two-way flow, stay roughly neutral, and manage inventory risk and adverse selection. The maker is paid for providing liquidity and bearing those risks, not for predicting direction. If you can articulate adverse selection (the risk that your counterparty knows more than you), you are demonstrating genuine depth.</div>`,
  },
  {
    title: 'Relative Value and Arbitrage',
    content: `<p>A second family of strategies profits not from predicting market direction but from relationships between prices, betting that two related things are mispriced relative to each other. These are intellectually central to trading and common interview territory.</p>

<div class="key-concept"><strong>Relative value</strong> trading bets on the relationship between two (or more) securities rather than the outright direction of either. A classic example is a <strong>pairs trade</strong>: go long one stock and short a closely related one (two competitors in the same industry), profiting if the gap between them moves as expected, regardless of whether the whole market rises or falls. Because you are long one thing and short another, much of the broad market risk cancels out, leaving a bet purely on the relative performance. This "market-neutral" quality is the appeal: you isolate a specific view (this company will outperform that one) from the noise of the overall market. Relative value is a huge part of how sophisticated desks and hedge funds operate.</div>

<div class="key-concept"><strong>Arbitrage</strong>, in its pure form, is a riskless profit from the same asset trading at different prices in two places, buy low in one, sell high in the other, lock in the difference. True riskless arbitrage is rare and fleeting because it is competed away instantly, but the concept underpins much of trading: prices that should be linked (by put-call parity, by the relationship between a future and its underlying, between an ETF and its basket) are kept in line by arbitrageurs who pounce on any gap. Most real-world "arbitrage" is actually low-risk relative-value trading rather than truly riskless, but the unifying idea is exploiting pricing relationships that should hold, profiting when they break and betting they will reconverge.</div>

<div class="example-box">
<div class="example-label">A pairs trade in shape</div>
<p>Two similar airlines normally trade in step, but one has lagged the other recently for no fundamental reason. A relative-value trader goes long the laggard and short the leader, betting the gap closes. If the whole airline sector rises or falls, both legs move together and roughly cancel; the profit comes only from the spread between them narrowing. The trader has isolated a relative view and hedged out the market and sector direction.</p>
</div>`,
  },
  {
    title: 'Flow, Directional, and Systematic Strategies',
    content: `<p>The remaining strategy families round out how desks and trading firms make money, and knowing the landscape lets you speak to the breadth of the business.</p>

<div class="framework-box"><div class="fw-label">THE STRATEGY LANDSCAPE</div><strong>Flow trading:</strong> serving client order flow and earning the spread, the franchise business of bank desks. Information from seeing flow is valuable in itself.<br/><strong>Directional / macro:</strong> taking outright positions based on a view about a market or the economy (rates will rise, a currency will fall). This is the classic "have a view and bet on it" approach, more common at hedge funds than at regulated bank desks today.<br/><strong>Relative value / arbitrage:</strong> betting on price relationships rather than direction (the previous section).<br/><strong>Systematic / quantitative:</strong> using models and algorithms to trade automatically, from high-frequency market-making to statistical arbitrage that exploits subtle patterns across many securities.</div>

<div class="key-concept">The big structural shift to understand is the rise of <strong>systematic and electronic trading</strong>. Huge portions of markets, especially liquid equities and futures, are now traded by algorithms rather than humans shouting prices, whether that is high-frequency market-making (quoting and managing inventory at microsecond speed) or statistical arbitrage (models finding and exploiting tiny, fleeting mispricings across thousands of securities). This has made markets faster, tighter-spread, and more technology-driven, and it has changed the skills desks hire for, with more emphasis on quantitative and programming ability. You do not need to be a quant to work in S&T, but acknowledging that technology and systematic strategies now dominate large parts of trading shows you understand where the industry is, not where it was twenty years ago.</div>

<div class="takeaway-box">Hold the landscape in four buckets: flow (serve clients, earn the spread, the bank franchise), directional/macro (bet on a view, more a hedge fund game now), relative value/arbitrage (bet on price relationships, market-neutral), and systematic/quant (models and algorithms, an ever-growing share). Knowing that flow and market-making define bank desks while electronic and systematic strategies increasingly dominate liquid markets is exactly the current, informed view interviewers want to hear.</div>`,
  },
];
