export const AM_TECH_SECTIONS = [
  {
    title: `1. Core Valuation: Relative vs. Intrinsic`,
    content: `<p>In Asset Management, you are constantly evaluating whether a stock is cheap or expensive compared to its intrinsic value or its peers.</p>
<br/>
<p><strong>Intrinsic Valuation (DCF):</strong><br/>
A Discounted Cash Flow analysis values a company based on the present value of its future Free Cash Flows. In public markets, investors rely heavily on this to find a "target price." If the DCF outputs a value of $120/share, and the stock is trading at $90, the stock is undervalued.</p>
<br/>
<p><strong>Relative Valuation (Multiples):</strong><br/>
This compares a company's valuation to similar public peers. The most common multiples are:</p>
<p>• <strong>P/E (Price-to-Earnings):</strong> Equity Value / Net Income. Best for banks, insurance, and stable companies.</p>
<p>• <strong>EV/EBITDA (Enterprise Value to EBITDA):</strong> Capital structure neutral. Best for comparing companies with different leverage profiles or capital intensities (e.g., industrials, telecom).</p>
<p>• <strong>EV/Sales:</strong> Used for high-growth tech or SaaS companies with negative earnings.</p>`
  },
  {
    title: `2. Free Cash Flow (FCFF vs. FCFE)`,
    content: `<p>Understanding the actual cash generated by a business is vital for a public markets investor.</p>
<br/>
<p><strong>Free Cash Flow to Firm (FCFF):</strong><br/>
Cash available to ALL investors (both debt and equity holders) before debt payments are made. <br/>
<em>Formula:</em> EBIT * (1 - Tax Rate) + D&A - CapEx - Changes in NWC. <br/>
Discounting FCFF by the WACC (Weighted Average Cost of Capital) gets you the <em>Enterprise Value</em>.</p>
<br/>
<p><strong>Free Cash Flow to Equity (FCFE):</strong><br/>
Cash available ONLY to equity shareholders after debt payments and debt issuance/repayment have been accounted for. <br/>
<em>Formula:</em> Net Income + D&A - CapEx - Changes in NWC + Net Borrowing. <br/>
Discounting FCFE by the Cost of Equity gets you the <em>Equity Value</em>.</p>`
  },
  {
    title: `3. The Dividend Discount Model (DDM)`,
    content: `<p>While IB focuses on LBOs or sum-of-the-parts, Asset Management heavily relies on the Dividend Discount Model (DDM) for mature, stable, dividend-paying companies (e.g., utility companies, REITs, consumer staples).</p>
<br/>
<p><strong>The Gordon Growth Model:</strong><br/>
Values a stock by assuming dividends will grow at a constant rate in perpetuity.</p>
<p><em>Formula:</em> Value of Stock = Expected Dividend next year / (Cost of Equity - Expected Growth Rate)</p>
<br/>
<p>If a bank pays a $2 dividend next year, your required return (Cost of Equity) is 10%, and you expect dividends to grow at 2% forever, the stock is worth: $2 / (0.10 - 0.02) = $25. If the stock is trading at $20, it's a Buy.</p>`
  },
  {
    title: `4. Return on Invested Capital (ROIC)`,
    content: `<p>Portfolio managers obsess over ROIC. It measures how efficiently a company allocates capital to generate profitable returns.</p>
<br/>
<p><em>Formula:</em> NOPAT (Net Operating Profit After Tax) / Invested Capital.</p>
<br/>
<p><strong>Why AM cares:</strong><br/>
If a company's ROIC > WACC (Weighted Average Cost of Capital), the company is creating value as it grows. If ROIC < WACC, growth actually destroys value. Great long-term investments ("compounders") have high, sustainable ROICs and wide economic moats.</p>`
  }
];
