export const ACCT_STATEMENTS_SECTIONS = [
  {
    title: 'The Three Financial Statements',
    content: `<p>A complete set of financial statements comprises the <strong>Balance Sheet</strong> (Statement of Financial Position), the <strong>Income Statement</strong> (Statement of Operations), and the <strong>Cash Flow Statement</strong> (Statement of Cash Flows). Together, they tell the full story of a company's financial position and performance. Understanding how they link is the single most important conceptual foundation in accounting.</p>

<div class="key-concept">
<strong>The Accounting Equation:</strong> Assets = Liabilities + Equity. This equation must always balance. Every transaction affects at least two accounts (double-entry bookkeeping), and the net effect always preserves the equation. When a company borrows $1M, cash (an asset) increases by $1M and debt (a liability) increases by $1M. When a company earns revenue, cash or receivables (assets) increase and retained earnings (equity) increases through net income.
</div>

<h4>The Balance Sheet</h4>

<p>The balance sheet is a <strong>snapshot</strong> of the company's financial position at a single point in time. It lists assets (what the company owns or controls), liabilities (what the company owes), and equity (the residual interest of shareholders). Assets are presented in order of liquidity (current assets first, then long-term). Liabilities are presented in order of maturity (current liabilities first, then long-term).</p>

<p>Key distinctions: <strong>current</strong> items are expected to be realized, consumed, or settled within one year (or the operating cycle, if longer). <strong>Non-current</strong> items extend beyond one year. Working capital (current assets minus current liabilities) is a critical measure of short-term liquidity.</p>

<h4>The Income Statement</h4>

<p>The income statement reports revenues, expenses, and the resulting net income (or loss) over a <strong>period of time</strong> (a quarter or fiscal year). It follows the matching principle: expenses are recognized in the same period as the revenues they help generate, not necessarily when cash changes hands. Depreciation on a factory is recognized over the factory's useful life, matching the cost against the revenue generated over that period.</p>

<div class="formula-box">
Revenue − Cost of Goods Sold = Gross Profit<br>
Gross Profit − Operating Expenses = EBIT (Operating Income)<br>
EBIT − Interest Expense + Interest Income ± Other = EBT (Pre-Tax Income)<br>
EBT − Income Tax Expense = Net Income
</div>

<h4>The Cash Flow Statement</h4>

<p>The cash flow statement reconciles the beginning and ending cash balances by explaining the <strong>actual cash movements</strong> during the period. It is divided into three sections: <strong>Operating Activities</strong> (cash from the core business), <strong>Investing Activities</strong> (cash used for or generated by long-term asset transactions), and <strong>Financing Activities</strong> (cash from borrowing, repaying debt, or issuing/repurchasing equity).</p>

<p>The indirect method of presenting operating cash flows starts with net income and adjusts for non-cash items (depreciation, amortization, stock-based compensation) and changes in working capital. The direct method presents actual cash receipts and payments but is rarely used in practice. Understanding the indirect method reconciliation is essential for both accounting and interview purposes.</p>

<div class="example-box">
<div class="example-label">Linkage Example</div>
<p>A company records $100 in revenue but collects only $80 in cash (the remaining $20 is in accounts receivable). On the income statement, revenue is $100. On the balance sheet, accounts receivable increases by $20. On the cash flow statement (indirect method), net income includes the $100, but the $20 increase in AR is a working capital use of cash, reducing operating cash flow. Cash collected = $80.</p>
<p>This illustrates the fundamental distinction between <strong>accrual accounting</strong> (income statement) and <strong>cash accounting</strong> (cash flow statement).</p>
</div>`,
  },
  {
    title: 'GAAP vs. IFRS',
    content: `<p>U.S. Generally Accepted Accounting Principles (GAAP), issued by the Financial Accounting Standards Board (FASB), govern financial reporting for U.S. public and private companies. International Financial Reporting Standards (IFRS), issued by the International Accounting Standards Board (IASB), are used in over 140 countries and required for most non-U.S. public companies.</p>

<table class="comparison-table">
<tr><th>Topic</th><th>U.S. GAAP</th><th>IFRS</th></tr>
<tr><td>Inventory Costing</td><td>LIFO permitted</td><td>LIFO prohibited</td></tr>
<tr><td>Development Costs</td><td>Expensed as incurred</td><td>Capitalized when criteria met</td></tr>
<tr><td>Investment Property</td><td>Carried at cost less depreciation</td><td>Fair value option available</td></tr>
<tr><td>Revaluation of PP&amp;E</td><td>Not permitted</td><td>Permitted (revaluation model)</td></tr>
<tr><td>Impairment Testing</td><td>Two-step test (U.S. GAAP ASC 350)</td><td>One-step test (IAS 36)</td></tr>
<tr><td>Presentation Framework</td><td>Rules-based</td><td>Principles-based</td></tr>
</table>`,
  },
];
