export const PE_DEAL_PROCESS_SECTIONS = [
  {
    title: 'Sourcing: Finding Deals',
    content: `<p>Before a PE firm can model or close anything, it has to find opportunities. Sourcing, the process of generating deal leads, is where it all starts, and it shapes the kind of returns a firm can earn.</p>

<div class="key-concept">Deals come from two broad channels, and the distinction matters. <strong>Intermediated (auction) deals</strong> are run by investment bankers who shop a company to many buyers in a competitive process, this is efficient and common, but competition tends to drive up the price, compressing returns. <strong>Proprietary (off-market) deals</strong> are sourced directly by the PE firm through its own relationships, networks, and outreach, often before the company is widely for sale. Proprietary deals are prized because less competition means a better entry price and therefore higher potential returns. A firm's ability to source proprietary deals, especially in the middle market, where owner-founders may sell to a trusted relationship rather than run an auction, is a genuine competitive advantage. This is why sourcing and relationships matter so much, and why "how would you source deals?" is a real interview question, particularly at smaller firms.</div>

<div class="pro-tip">If asked about sourcing, show you understand the auction-versus-proprietary tradeoff: auctions are efficient but competitive (higher prices, lower returns), while proprietary deals won through relationships and direct outreach offer better entry prices. Mentioning that you would build relationships with industry executives, bankers, and owners to find off-market opportunities signals you understand where PE alpha actually comes from.</div>`,
  },
  {
    title: 'Screening and the Investment Thesis',
    content: `<p>A firm sees far more opportunities than it can pursue, so screening, quickly filtering leads down to the few worth deep work, is essential. The output of screening is an initial investment thesis.</p>

<div class="key-concept"><strong>Screening</strong> is the disciplined filtering of opportunities against the firm's criteria: the right size, the right sector, stable cash flows that can support leverage, a defensible market position, a sensible valuation, and a plausible path to improve the business and exit. Most opportunities fail one of these tests and are passed on quickly, the skill is saying no fast so the team's deep effort goes only to the genuinely promising few. For the ones that pass, the firm forms a preliminary <strong>investment thesis</strong>: a clear hypothesis for why this is a good investment, how the firm will create value (the operational and financial plan), what the risks are, and how it will exit. The thesis is the spine of everything that follows; due diligence is essentially the process of testing whether the thesis holds up.</div>

<div class="takeaway-box">Screening is about saying no efficiently: filter against size, sector, cash-flow stability, market position, valuation, and exitability, so deep work is reserved for the best few. Each survivor gets a preliminary investment thesis, why this is a good deal, how value gets created, the risks, and the exit, which becomes the hypothesis that due diligence then stress-tests.</div>`,
  },
  {
    title: 'Due Diligence',
    content: `<p>Due diligence is the deep investigation a PE firm conducts before committing capital, the rigorous testing of the investment thesis from every angle. It is where a deal is truly understood and where many deals die.</p>

<div class="framework-box"><div class="fw-label">THE DILIGENCE WORKSTREAMS</div><strong>Commercial / market:</strong> is the market attractive, is the company's position defensible, are the growth assumptions realistic?<br/><strong>Financial:</strong> are the financials accurate and is the EBITDA real (quality of earnings), with no one-time items dressing up the numbers?<br/><strong>Operational:</strong> can the business actually be improved as the thesis assumes, and how?<br/><strong>Legal / regulatory:</strong> are there liabilities, contracts, or compliance issues lurking?<br/><strong>Management:</strong> is the leadership team capable and aligned, or does it need to change?</div>

<div class="key-concept">The single most important diligence concept for interviews is <strong>quality of earnings (QoE)</strong>: verifying that the company's reported EBITDA is real, sustainable, and not inflated by one-time gains, aggressive accounting, or unsustainable cost-cutting. Because the entire purchase price is a multiple of EBITDA, if the EBITDA is overstated, the firm overpays, so confirming the true, normalized earnings power is critical. Diligence also tests every key assumption in the thesis: the market's growth, the company's competitive moat, the achievability of the planned improvements, and any hidden risks. A firm that does diligence well avoids the costly mistakes, the deal that looked great until the numbers turned out to be propped up, or the market turned out to be shrinking. Diligence is where the firm earns the right to be confident in its model.</div>

<div class="key-concept">Diligence culminates in the <strong>investment committee (IC) memo and decision</strong>. The deal team synthesizes everything, the thesis, the diligence findings, the model and returns, the risks and mitigants, into a memo for the firm's investment committee (its senior partners), who decide whether to proceed. The IC is the firm's internal gatekeeper, and the associate's analysis is what informs that decision. Understanding that the whole process funnels toward a reasoned recommendation to the IC, and that your job as an associate is to build the rigorous case the IC relies on, frames the deal process correctly.</div>

<div class="takeaway-box">Due diligence stress-tests the thesis across commercial, financial, operational, legal, and management workstreams, with quality of earnings (confirming EBITDA is real and sustainable) the most critical because the price is a multiple of it. It all funnels into the IC memo, where the deal team makes a reasoned recommendation to the senior partners who make the final call.</div>`,
  },
];
