export const PE_FUND_SECTIONS = [
  {
    title: 'GPs, LPs, and the Fund as a Vehicle',
    content: `<p>A private equity fund is a pool of money with a clear division of labor: the people who run it and the people who provide most of the capital. Understanding this split is the foundation for everything about PE economics.</p>

<div class="key-concept">The <strong>General Partner (GP)</strong> is the PE firm itself, the team that raises the fund, finds and makes the investments, manages the portfolio companies, and decides when to exit. The <strong>Limited Partners (LPs)</strong> are the outside investors who supply the vast majority of the capital: pension funds, endowments, sovereign wealth funds, insurance companies, and wealthy individuals. The LPs are "limited" because they are passive, they commit money and share in the returns, but they do not run the investments and their liability is limited to what they invest. The GP runs everything and also invests some of its own money (the "GP commitment") so its interests align with the LPs. This GP-LP structure is the skeleton of the entire industry: the GP supplies the skill and a little capital, the LPs supply most of the capital, and they share the gains by a formula.</div>

<div class="framework-box"><div class="fw-label">THE FUND LIFECYCLE</div><strong>Fundraising:</strong> the GP raises commitments from LPs, typically targeting a fixed fund size, over months.<br/><strong>Investment period (roughly years 1-5):</strong> the GP sources and makes investments, "calling" capital from LPs as deals close.<br/><strong>Harvest / holding period (roughly years 4-10):</strong> the GP improves the portfolio companies and exits them, returning capital and profits to LPs.<br/>A typical fund has a roughly 10-year life. GPs raise a new fund every few years, so a firm runs several overlapping funds at once.</div>

<div class="key-concept"><strong>Committed capital is not handed over upfront.</strong> LPs commit a total amount, but the GP "calls" (draws down) that capital only as it is needed to fund specific deals, through <strong>capital calls</strong>. This is why a fund's early years can show negative returns even when things are going fine: fees and early costs are drawn before any company has been sold. That dip-then-rise pattern is the famous <strong>J-curve</strong>, returns look negative early (fees paid, nothing sold yet) and turn positive later as investments mature and exit. Knowing the J-curve and why it happens is a classic fund-structure interview point.</div>`,
  },
  {
    title: 'The Economics: Fees, Carry, and the Hurdle',
    content: `<p>How GPs get paid is one of the most tested topics in PE interviews, because it reveals whether you understand what actually drives the business and aligns incentives. The shorthand is "2 and 20," but you need the real mechanics.</p>

<div class="key-concept">PE firms earn money two ways. The <strong>management fee</strong> (classically around 2 percent of committed or invested capital per year) covers salaries and operating costs, it keeps the lights on regardless of performance. The <strong>carried interest</strong> ("carry," classically 20 percent of the fund's profits) is the GP's share of the gains, and it is where the real wealth is made. The crucial distinction: the management fee is steady and not very performance-sensitive, while carry is the performance upside that only pays off if the fund actually makes money for its LPs. Carry is what aligns the GP with the LPs, the GP only gets rich if the LPs do well, and it is why PE is a high-stakes, performance-driven business rather than a steady fee business.</div>

<div class="framework-box"><div class="fw-label">THE KEY TERMS</div><strong>Management fee:</strong> ~2% per year of committed/invested capital, covers operations.<br/><strong>Carried interest (carry):</strong> ~20% of profits to the GP, the performance share.<br/><strong>Hurdle rate (preferred return):</strong> a minimum return (often ~8%) that LPs must receive <em>before</em> the GP earns any carry. Below the hurdle, no carry.<br/><strong>GP commitment:</strong> the GP invests its own money in the fund (often 1-5%) so it has real skin in the game.<br/><strong>Clawback:</strong> a provision letting LPs recover carry if the GP was overpaid earlier relative to the fund's final performance.</div>

<div class="key-concept">The <strong>hurdle rate</strong> is the concept that most separates a prepared candidate. It is a minimum return the LPs must earn before the GP collects any carry, often around 8 percent. The logic: LPs should not pay the GP a performance bonus for returns they could have gotten passively, so the GP only shares in profits <em>above</em> that threshold. This protects LPs and sharpens the GP's incentive to clear a real bar, not just any positive return. Combined with the clawback (which recovers carry if early winners were paid out but the fund later underperforms), the hurdle is part of how the structure keeps the GP honest and aligned over the fund's full life.</div>`,
  },
  {
    title: 'The Distribution Waterfall and Fundraising',
    content: `<p>When a fund makes money, the order in which that money is split between LPs and the GP is called the distribution waterfall. It ties the fee, carry, and hurdle together into a sequence, and walking through it cleanly is impressive in an interview.</p>

<div class="framework-box"><div class="fw-label">THE DISTRIBUTION WATERFALL (typical order)</div><strong>1. Return of capital:</strong> LPs first get back the capital they invested.<br/><strong>2. Preferred return (hurdle):</strong> LPs then receive their minimum return (e.g. 8%) on that capital.<br/><strong>3. GP catch-up:</strong> the GP then receives a chunk to "catch up" toward its share of total profits.<br/><strong>4. Carried interest split:</strong> remaining profits are split, typically 80% to LPs and 20% to the GP (the carry).</div>

<div class="key-concept">The waterfall exists to enforce the principle that <strong>LPs get made whole and earn their minimum return before the GP shares in the upside.</strong> Money flows "down the steps": capital back to LPs, then the preferred return to LPs, then the GP catches up, then the 80/20 split on the rest. This sequencing is why the hurdle and carry are not just numbers but an ordered priority, the GP is genuinely last in line for the profit share, which is exactly the alignment LPs are paying for. Being able to recite the waterfall in order (return of capital, preferred return, catch-up, carry split) demonstrates real command of PE economics.</div>

<div class="key-concept"><strong>Fundraising</strong> is the GP's lifeblood, because no fund means no fees, no deals, and no carry. GPs raise a new fund every few years by convincing LPs (pensions, endowments, sovereign wealth funds, fund-of-funds) to commit capital, and the pitch rests on <strong>track record</strong>: the returns of prior funds, the quality and stability of the team, and a differentiated strategy. A strong track record makes the next fund easier and larger to raise; a weak one can end a firm. This is why GPs are so focused on realized returns and on demonstrating value to LPs, the ability to raise the next, bigger fund depends on it. Understanding that fundraising is continuous and track-record-driven explains a lot of GP behavior.</div>

<div class="takeaway-box">Tie fund structure together: GPs run the fund and earn a steady management fee plus performance-based carry; LPs supply most of the capital and, via the hurdle and waterfall, get their capital and a preferred return back before the GP shares in profits. The whole structure is built to align the GP with the LPs, and the GP's ability to raise the next fund depends entirely on delivering a strong, realized track record.</div>`,
  },
];
