export const PE_LBO_SECTIONS = [
  {
    title: 'What an LBO Is and Why Leverage Works',
    content: `<p>The leveraged buyout is the central technique of private equity, and understanding it deeply, not just mechanically, is the most important thing you can do for a PE interview. Start with the concept before any math.</p>

<div class="key-concept">A <strong>leveraged buyout</strong> is the acquisition of a company using a significant amount of borrowed money (debt) alongside a smaller amount of the firm's own money (equity), where the company's own cash flows and assets support that debt. The "leverage" is the debt. The magic, and the risk, is that debt <strong>amplifies the equity return</strong>. Because the firm puts in less of its own equity (the rest is borrowed), any gain in the company's value is spread over a smaller equity base, multiplying the percentage return to the equity. The same leverage magnifies losses if things go badly. This is why PE targets stable, cash-generative companies: predictable cash flow can safely carry debt, making leverage a powerful amplifier rather than a fatal risk.</div>

<div class="example-box">
<div class="example-label">Why leverage amplifies returns</div>
<p>Buy a company for 100. <strong>Case A (all equity):</strong> you put in 100, sell later for 150, you made 50 on 100, a 50 percent gain. <strong>Case B (leveraged):</strong> you put in 40 of equity and borrow 60. You sell for 150, repay the 60 of debt, and keep 90. You made 50 on just 40 of equity, a 125 percent gain. Same company, same sale price, but leverage turned a 50 percent return into 125 percent by shrinking the equity you risked. (If instead the company fell to 80, the all-equity investor loses 20 percent while the leveraged investor, after repaying 60, has only 20 left on 40 invested, a 50 percent loss. Leverage cuts both ways.)</p>
</div>

<div class="pro-tip">When asked "why use leverage in an LBO?" the complete answer is: it amplifies the equity return by reducing how much of your own capital is at risk, and the debt gets paid down over the hold using the company's cash flow, transferring value to the equity holders. Then add the caveat that it also amplifies downside, which is why PE targets stable, cash-generative businesses that can safely carry it.</p></div>`,
  },
  {
    title: 'The Sources of LBO Return',
    content: `<p>An LBO makes money in three distinct ways, and being able to name and explain all three, then say which matters most, is a hallmark of a strong candidate. Everything in PE value creation maps to these levers.</p>

<div class="framework-box"><div class="fw-label">THE THREE RETURN DRIVERS</div><strong>1. EBITDA growth:</strong> making the company earn more, by growing revenue, expanding margins, or both. The healthiest, most sustainable driver.<br/><strong>2. Debt paydown (deleveraging):</strong> using the company's cash flow to pay down the acquisition debt over the hold, which shifts value from lenders to equity holders even if the company's total value is flat.<br/><strong>3. Multiple expansion:</strong> selling the company at a higher EV/EBITDA multiple than you paid, whether through improving the business, timing the market, or repositioning it.</div>

<div class="key-concept">These three drivers combine to produce the equity return, and the distinction between them matters. <strong>EBITDA growth</strong> is the gold standard, it means you genuinely made the business bigger and better, and it is the most defensible source of return. <strong>Debt paydown</strong> is reliable and somewhat mechanical: as long as the company generates cash and uses it to retire debt, the equity grows even if the enterprise value is unchanged, because the equity slice of the pie expands as the debt slice shrinks. <strong>Multiple expansion</strong> is the least controllable, you may sell at a higher multiple, but that often depends on market conditions and is not something you fully control, so relying on it is riskier. The strongest PE theses lead with operational EBITDA growth, treat debt paydown as a steady contributor, and do not bank on multiple expansion.</div>

<div class="key-concept">An ideal <strong>LBO candidate</strong> follows directly from these drivers and from the need to carry debt. The classic profile: <strong>stable, predictable cash flows</strong> (to service debt safely), a <strong>mature business in a defensible market position</strong> (low risk of disruption), <strong>opportunities to improve</strong> (margin expansion, growth, operational fixes, so there is EBITDA upside), a <strong>reasonable entry price</strong>, low existing debt, and a clear path to exit. Companies that are too volatile, too capital-intensive, or already optimized make poor LBO targets. When an interviewer asks "what makes a good LBO target?", reciting this profile and tying each trait back to the return drivers and debt capacity shows real understanding.</div>

<div class="takeaway-box">Memorize the three return drivers, EBITDA growth, debt paydown, and multiple expansion, and the hierarchy among them: lead with operational EBITDA growth (most sustainable), count on debt paydown (reliable), and never rely on multiple expansion (least controllable). The ideal LBO target is a stable, cash-generative, improvable business at a fair price, every trait of which traces back to carrying debt safely and driving those three returns.</div>`,
  },
  {
    title: 'The Capital Structure of an LBO',
    content: `<p>The "debt" in a buyout is not one thing, it is a stack of different loans with different risk, cost, and priority. Understanding the capital structure matters because it determines how much leverage a deal can carry and how the returns and risks are split.</p>

<div class="framework-box"><div class="fw-label">THE DEBT STACK (top = safest, cheapest, paid first)</div><strong>Senior secured debt (e.g. a term loan / revolver):</strong> the lowest-risk layer, secured by the company's assets, lowest interest rate, first in line to be repaid.<br/><strong>Subordinated / high-yield debt:</strong> ranks below senior, higher interest rate to compensate for more risk, repaid after senior.<br/><strong>Mezzanine debt:</strong> the riskiest debt layer, often with equity-like features (such as warrants), highest cost, sits just above equity.<br/><strong>Equity:</strong> the PE firm's own capital, last in line, takes the first losses but captures the upside.</div>

<div class="key-concept">The capital structure is a <strong>priority ladder</strong>: in good times everyone gets paid and the equity captures the amplified upside; in bad times losses hit the bottom of the stack first (equity, then mezzanine, then subordinated), while senior secured lenders are protected by being first in line and backed by collateral. This is why senior debt is cheapest (least risk) and each layer down is more expensive (more risk). The amount of total debt a deal can carry is usually expressed as a <strong>leverage multiple</strong>, total debt divided by EBITDA, so "5x leverage" means debt equals five times EBITDA. How much leverage is prudent depends on how stable the company's cash flows are: steadier cash flow safely supports more debt. Knowing the debt tranches in order, and that leverage is quoted as a multiple of EBITDA, is core LBO fluency.</div>

<div class="takeaway-box">An LBO's financing is a stack: senior secured debt (cheapest, safest, first paid), then subordinated and high-yield, then mezzanine (riskiest debt, sometimes with equity kickers), then the PE firm's equity (last in line, first to lose, captures the upside). Total leverage is measured as debt / EBITDA, and a company's cash-flow stability determines how many turns of leverage it can safely carry.</div>`,
  },
];
