export const PE_OPERATIONS_SECTIONS = [
  {
    title: 'How PE Creates Value After the Buy',
    content: `<p>Buying a company is only the start. The real work, and increasingly the real source of returns, is improving the business during the hold. Modern PE is far more operationally hands-on than the leverage-driven caricature of decades past.</p>

<div class="key-concept">Because relying on leverage and multiple expansion alone is no longer enough in a competitive market, today's PE returns increasingly come from <strong>operational value creation</strong>: genuinely making the company bigger, better, and more efficient. This connects directly to the return drivers, operational improvement is how a firm grows EBITDA, the most sustainable driver. The firm acts as an active owner, working with (or replacing) management to execute a value creation plan. The levers fall into a few categories: growing revenue, expanding margins, improving cash flow, and making smart add-on acquisitions. A firm's edge is increasingly its ability to actually execute these improvements, not just to financially engineer a deal.</div>

<div class="framework-box"><div class="fw-label">THE VALUE CREATION LEVERS</div><strong>Revenue growth:</strong> new products, new markets, better pricing, stronger sales and marketing.<br/><strong>Margin / cost improvement:</strong> operational efficiency, procurement, eliminating waste, professionalizing the cost base.<br/><strong>Cash flow / working capital:</strong> tightening inventory and receivables to free up cash for debt paydown.<br/><strong>Add-on acquisitions ("buy and build"):</strong> acquiring smaller companies to bolt onto the platform, growing scale and often at a lower multiple than the platform.<br/><strong>Management and strategy:</strong> upgrading leadership, sharpening strategy, improving incentives and reporting.</div>

<div class="takeaway-box">Value creation is how PE grows EBITDA, the best return driver, by pulling levers across revenue growth, margin and cost improvement, cash flow and working capital, add-on acquisitions, and management and strategy. Modern PE wins less through financial engineering and more through actually executing these operational improvements as an active owner.</div>`,
  },
  {
    title: 'The 100-Day Plan and Active Ownership',
    content: `<p>PE firms move fast after closing, because the hold period is finite and the clock on returns is ticking. The first stretch of ownership sets the tone.</p>

<div class="key-concept">The <strong>100-day plan</strong> is the firm's blueprint for the first months of ownership: a prioritized set of actions to stabilize the business, establish control and reporting, and launch the highest-impact value creation initiatives. The logic is urgency, because returns are time-sensitive (IRR rewards speed), the firm cannot afford a slow start, so it front-loads the critical moves: installing rigorous financial reporting and KPIs, aligning management incentives with the value creation plan, and kicking off the biggest revenue and cost initiatives. The 100-day plan turns the abstract investment thesis into a concrete, sequenced operating agenda, and it reflects the broader truth that PE ownership is active and intentional, not passive.</div>

<div class="key-concept"><strong>Active ownership</strong> means the PE firm is deeply involved in steering the company, but typically through governance and strategy rather than running daily operations itself. The firm controls the board, sets strategic direction, holds management accountable to the plan, allocates capital, and brings resources (operating partners, industry experts, its network) to bear. Crucially, it aligns management through equity incentives, giving leaders a meaningful ownership stake so they are motivated to drive the same value creation the firm wants. This alignment, management with real skin in the game, working toward a clear plan, under an engaged board, is a defining feature of how PE drives performance that public companies often struggle to match.</div>

<div class="pro-tip">If asked how PE firms add value, go beyond "cut costs." Describe active ownership: a 100-day plan to launch the highest-impact initiatives quickly, rigorous reporting and KPIs, board-level strategic direction, and aligning management through equity so leaders are personally invested in the outcome. That portrays the modern, operationally engaged PE model accurately.</div>`,
  },
  {
    title: 'Buy-and-Build and the GP-Management Relationship',
    content: `<p>Two further dimensions round out value creation: a powerful growth strategy and the human relationship at the center of it all.</p>

<div class="key-concept"><strong>Buy-and-build (the platform strategy)</strong> is one of the most important value creation playbooks in modern PE. The firm acquires a solid "platform" company, then makes a series of smaller "add-on" or "bolt-on" acquisitions to grow it. This works for several reasons: add-ons are usually bought at lower multiples than the platform (smaller companies command lower valuations), so simply combining them creates value through <strong>multiple arbitrage</strong>, the blended entity is worth a higher multiple than the pieces; scale brings cost synergies and competitive strength; and the larger, more diversified business often commands a premium multiple at exit. Buy-and-build lets a firm deploy more capital and grow EBITDA quickly through acquisition, and it is a favorite strategy because it combines operational growth, multiple arbitrage, and scale into one repeatable engine.</div>

<div class="example-box">
<div class="example-label">Multiple arbitrage in buy-and-build</div>
<p>A firm buys a platform company at 10x EBITDA. It then acquires several smaller competitors at 6x EBITDA each and integrates them. The acquired earnings, bought at 6x, are now part of a larger business that the market values at 10x (or more). Buying at 6x and having it valued at 10x instantly creates value on every add-on, before any operational improvement. Layer in cost synergies and a larger company commanding an even higher exit multiple, and the strategy compounds.</p>
</div>

<div class="key-concept">Underneath all of this is the <strong>GP-management relationship</strong>, which can make or break a deal. The PE firm depends on the management team to execute the plan day to day, so getting management right, keeping strong leaders, replacing weak ones, and aligning everyone through equity ownership and clear targets, is one of the most consequential things a firm does. The best outcomes come when management and the PE firm are true partners pulling toward the same goal, with leaders motivated by a real equity stake. Tension or misalignment with management is a common reason deals underperform. Recognizing that PE is ultimately a people business, that returns depend on the management team executing, adds a mature dimension to your understanding.</div>

<div class="takeaway-box">Buy-and-build grows a platform through add-on acquisitions, creating value via multiple arbitrage (buying small at low multiples, valued within a larger high-multiple business), synergies, and scale. And remember the human core: PE relies on management to execute, so selecting, aligning (through equity), and partnering well with leadership is one of the most decisive factors in whether a deal succeeds.</div>`,
  },
];
