export const PE_PITCH_SECTIONS = [
  {
    title: 'The Investment Thesis Framework',
    content: `<p>The "pitch me a company you would buy" question is one of the most important in any PE interview, and it cannot be faked. It tests whether you can think like an investor: identify an attractive target and articulate a complete, structured case for buying it. The fix is to follow markets and companies, and to have a ready framework.</p>

<div class="framework-box"><div class="fw-label">THE PE INVESTMENT THESIS</div><strong>1. The business:</strong> what the company does and why it is a quality business (stable cash flows, market position, defensibility).<br/><strong>2. Why it is a good LBO target:</strong> the traits that make it suitable, predictable cash flow to carry debt, room to improve, reasonable valuation.<br/><strong>3. The value creation plan:</strong> specifically how you would make it more valuable, the EBITDA growth, operational improvements, or add-ons you would pursue.<br/><strong>4. The returns:</strong> roughly how the deal could work, entry multiple, leverage, growth, exit, and the resulting return.<br/><strong>5. The risks and the exit:</strong> what could go wrong and how you would exit.</div>

<div class="key-concept">A strong PE pitch is fundamentally different from a stock pitch, and the difference is the giveaway of real understanding. A stock pitcher asks "will this go up?"; a PE investor asks "is this a business I would want to <em>own and control</em> for five years, can I improve it, can it carry debt, and can I exit at a profit?" So your pitch must cover not just why the company is good, but why it is a good <em>buyout</em> specifically (cash flow to service debt, a concrete value creation plan, a path to exit). The most impressive pitches lead with the quality and stability of the business, lay out a specific operational plan to grow EBITDA, show a rough sense of the returns math, and honestly address the risks. Generic enthusiasm ("it's a great company") fails; a structured, ownership-minded case succeeds.</div>

<div class="pro-tip">Prepare one or two real companies you could pitch as LBO targets, ideally stable, cash-generative, improvable businesses at sensible valuations, and rehearse the full thesis: the business, why it suits an LBO, your value creation plan, rough returns, and the risks and exit. Having this ready turns a feared question into a chance to show you think like an owner.</div>`,
  },
  {
    title: 'Discussing a Deal and Talking Markets',
    content: `<p>Beyond pitching a hypothetical target, you will be asked to discuss real deals, the market environment, and (if you are lateraling from banking) deals you worked on. These conversations test genuine engagement with the industry.</p>

<div class="key-concept">When discussing <strong>a recent PE deal</strong> (one in the news or one a firm did), structure your thoughts the same way you would a thesis: what is the company, why did the firm likely buy it, how could they create value, what is the return logic, and what are the risks. This shows you can reverse-engineer an investor's thinking. When discussing <strong>your own deals</strong> (for lateral candidates), be ready to go deep: your specific role, the thesis, the model, the diligence, what you learned, and how you would evaluate it as an investor (not just as a banker executing a transaction). The shift in framing, from "I executed this deal" to "here is how I would judge this as an investment", is exactly the mindset transition PE is screening for in bankers.</div>

<div class="key-concept">Staying current matters. You should follow the PE landscape: major recent deals, the financing and interest rate environment (which heavily affects leverage and returns), exit and fundraising conditions, and trends in the firm's sectors. PE does not happen in a vacuum, when interest rates rise, debt is costlier and deals harder to finance; when exit markets are slow, holds lengthen and returns compress. Being able to speak to the current environment, and what it means for doing deals right now, demonstrates that you understand PE as a living business shaped by markets, not just a set of mechanics. As with any markets-facing role, this engagement is impossible to cram and immediately visible when present.</div>

<div class="takeaway-box">For deal discussions, use the thesis structure to reverse-engineer any deal (the business, the buy rationale, the value plan, the returns, the risks), and for your own deals, reframe from executor to investor (how would I judge this as an investment?). Follow the current environment, rates, financing, exits, fundraising, since it directly shapes whether and how deals get done. Genuine, current engagement with the industry is what separates real candidates from those reciting mechanics.</div>`,
  },
];
