export const PE_STATEMENTS_SECTIONS = [
  {
    title: `2.1 The EBITDA to FCF Bridge`,
    content: `<p>In investment banking, analysts often stop at EBITDA. In Private Equity, <strong>EBITDA is just the starting line</strong>.</p>
<p><strong>EBITDA:</strong> Earnings Before Interest, Taxes, Depreciation, and Amortization. It is a proxy for core operational profitability.</p>
<p><strong>Unlevered Free Cash Flow (UFCF):</strong> The cash generated by operations that is available to all providers of capital (both debt and equity), before interest is paid.</p>
<h4>Why EBITDA is Flawed</h4>
<p>EBITDA ignores two massive uses of cash:</p>
<ol>
<li><strong>Capital Expenditures (CapEx):</strong> The money required to maintain physical assets (trucks, servers, machinery).</li>
<li><strong>Working Capital Requirements:</strong> The cash trapped in operations.</li>
</ol>
<p>If you buy a logistics company with $100M in EBITDA, but they have to spend $80M a year replacing old delivery trucks (CapEx), your actual cash to pay off LBO debt is practically zero.</p>
<h4>The Formula (Memorize This)</h4>
<p>EBITDA<br/>- Depreciation & Amortization<br/>= EBIT (Operating Income)<br/>- Taxes (EBIT x Tax Rate)<br/>= NOPAT (Net Operating Profit After Tax)<br/>+ D&A (Added back)<br/>- Capital Expenditures<br/>- Change in Net Working Capital<br/>= <strong>Unlevered Free Cash Flow (UFCF)</strong></p>
<p><em>Note: In an LBO, we will eventually shift to Levered Free Cash Flow (subtracting mandatory debt amortization and interest), but UFCF is the baseline for valuation.</em></p>`
  },
  {
    title: `2.2 Net Debt & Capital Structure`,
    content: `<p>When a PE firm buys a company, they usually acquire it on a <strong>"Cash-Free, Debt-Free" basis</strong>. The seller keeps the cash, but must use proceeds to pay off existing debt.</p>
<h4>Enterprise Value vs. Equity Value</h4>
<p><strong>Equity Value:</strong> What the shares are worth (Share Price x Shares Outstanding).</p>
<p><strong>Enterprise Value (EV):</strong> The total value of core business operations.</p>
<p>EV = Equity Value + Total Debt + Preferred Stock + Non-Controlling Interests - Cash</p>
<h4>Why do we subtract Cash?</h4>
<p><strong>Weak Answer:</strong> Because the formula says so.</p>
<p><strong>Elite Answer:</strong> "Enterprise Value represents the true cost to acquire the business. If I buy a company for $100 in Equity Value with $50 in Debt but $20 in Cash, I can immediately use that $20 to pay down debt. My true net cost for the operations is $130. We subtract cash because it is a non-operating asset that offsets our debt burden."</p>`
  },
  {
    title: `2.3 Advanced Drill: The Triple Linkage`,
    content: `<p><strong>Prompt:</strong> "A company buys equipment for $100 using Debt. Walk me through the 3 statements at end of Year 1. Assume 10% interest rate, 10-year life, straight-line depreciation, no salvage value, 20% tax rate."</p>
<h4>Step 1: Scratchpad Math</h4>
<ul>
<li>Depreciation = $100 / 10 years = $10/year</li>
<li>Interest Expense = $100 x 10% = $10/year</li>
<li>Total pre-tax expense = $20</li>
</ul>
<h4>Step 2: The Delivery</h4>
<p><strong>Income Statement:</strong> "Depreciation $10 and Interest $10 reduce pre-tax income by $20. At 20% tax rate, we save $4 in taxes. Net Income is down $16."</p>
<p><strong>Cash Flow Statement:</strong> "Net Income down $16. Add back $10 non-cash Depreciation. Net Change in Cash is down $6."</p>
<p><em>(Why down $6? We paid $10 in cash interest but saved $4 in cash taxes.)</em></p>
<p><strong>Balance Sheet:</strong> "Cash down $6. PP&E down $10. Total Assets down $16. Debt remains $100. Retained Earnings down $16. The Balance Sheet balances."</p>`
  },
];
