import { Flashcard } from './ib-flashcard-data';
export const ACCT_FLASHCARDS: Flashcard[] = [
  // FOUNDATIONS (35)
  { q: "What is accounting?", a: "The structured process of identifying, measuring, recording, classifying, summarizing, and communicating economic activity.", category: "Foundations" },
  { q: "What is the accounting equation?", a: "Assets = Liabilities + Equity. Every transaction must preserve this equation.", category: "Foundations" },
  { q: "What are debits and credits?", a: "Double-entry mechanism. Assets/expenses increase with debits. Liabilities/equity/revenue increase with credits.", category: "Foundations" },
  { q: "Why do expenses have debit balances?", a: "Expenses reduce equity (retained earnings). Since equity is credit-normal, its reduction is a debit.", category: "Foundations" },
  { q: "What is accrual accounting?", a: "Revenue recorded when earned, expenses when incurred — regardless of cash timing. Better performance measurement.", category: "Foundations" },
  { q: "What is cash accounting?", a: "Records transactions when cash moves. Simpler but can distort performance measurement.", category: "Foundations" },
  { q: "Why is accrual preferred?", a: "It matches economic activity to the period it occurs, producing more meaningful performance representation than cash timing alone.", category: "Foundations" },
  { q: "What is an adjusting entry?", a: "Period-end corrections: accruals, deferrals, depreciation, allowances. Without them, statements may be materially misstated.", category: "Foundations" },
  { q: "What is the general ledger?", a: "Collection of all accounts and their balances. The central record from which financial statements are built.", category: "Foundations" },
  { q: "What is a trial balance?", a: "Listing of all accounts to verify total debits equal total credits. Used before and after adjusting entries.", category: "Foundations" },
  { q: "What are closing entries?", a: "Move temporary accounts (revenue, expenses) into retained earnings at period end. Reset for next period.", category: "Foundations" },
  { q: "What is materiality?", a: "Threshold above which misstatement could influence user decisions. Both quantitative and qualitative.", category: "Foundations" },
  { q: "What is the matching principle?", a: "Expenses recognized in the same period as the revenues they help generate. COGS matched to sale.", category: "Foundations" },
  { q: "What is revenue recognition?", a: "Revenue recognized when control transfers and entity is entitled to consideration — not necessarily when cash is received.", category: "Foundations" },
  { q: "What is conservatism in accounting?", a: "When uncertain, recognize losses early but defer gains. Prevents overstatement of financial health.", category: "Foundations" },
  { q: "What is the going concern assumption?", a: "Assumption the entity will continue operating. If doubt exists, disclosures and possible measurement changes required.", category: "Foundations" },
  // JOURNAL ENTRIES (30)
  { q: "Entry: borrow $50K from bank.", a: "Dr Cash 50,000 / Cr Notes Payable 50,000. Asset up, liability up.", category: "Journal Entries" },
  { q: "Entry: sell goods $1,000 on credit.", a: "Dr AR 1,000 / Cr Revenue 1,000. Revenue recognized, cash not collected.", category: "Journal Entries" },
  { q: "Entry: collect $1,000 cash from customer.", a: "Dr Cash 1,000 / Cr AR 1,000. No income statement impact.", category: "Journal Entries" },
  { q: "Entry: purchase inventory $500 on credit.", a: "Dr Inventory 500 / Cr AP 500. No immediate expense.", category: "Journal Entries" },
  { q: "Entry: sell inventory costing $400 for $1,000 cash.", a: "Dr Cash 1,000 / Cr Revenue 1,000. Dr COGS 400 / Cr Inventory 400.", category: "Journal Entries" },
  { q: "Entry: prepay $1,200 annual insurance.", a: "Dr Prepaid Insurance 1,200 / Cr Cash 1,200. Monthly: Dr Insurance Exp 100 / Cr Prepaid 100.", category: "Journal Entries" },
  { q: "Entry: accrue $800 unpaid wages.", a: "Dr Wage Expense 800 / Cr Accrued Wages Payable 800.", category: "Journal Entries" },
  { q: "Entry: record depreciation of $2,400.", a: "Dr Depreciation Expense 2,400 / Cr Accumulated Depreciation 2,400.", category: "Journal Entries" },
  { q: "Entry: record bad debt allowance $300.", a: "Dr Bad Debt Expense 300 / Cr Allowance for Doubtful Accounts 300.", category: "Journal Entries" },
  { q: "Entry: write off specific $100 uncollectible.", a: "Dr Allowance 100 / Cr AR 100. No income statement impact (already estimated).", category: "Journal Entries" },
  { q: "Entry: collect $2,400 for 12-month service.", a: "Dr Cash 2,400 / Cr Deferred Revenue 2,400. Monthly: Dr Deferred Rev 200 / Cr Revenue 200.", category: "Journal Entries" },
  { q: "Entry: issue stock for $10,000.", a: "Dr Cash 10,000 / Cr Common Stock (par) + Cr APIC (excess over par).", category: "Journal Entries" },
  { q: "Entry: pay dividend of $5,000.", a: "Dr Retained Earnings 5,000 / Cr Cash 5,000. Not an expense.", category: "Journal Entries" },
  { q: "Entry: purchase equipment $20,000 cash.", a: "Dr Equipment 20,000 / Cr Cash 20,000. CapEx — no immediate IS impact.", category: "Journal Entries" },
  { q: "Entry: accrue interest on $50K note at 6%/year, 1 month.", a: "Dr Interest Expense 250 / Cr Interest Payable 250. ($50K × 6% / 12).", category: "Journal Entries" },
  { q: "Entry: record inventory shrinkage of $200.", a: "Dr COGS (or Loss) 200 / Cr Inventory 200.", category: "Journal Entries" },
  { q: "Entry: record unearned rent revenue received $6,000.", a: "Dr Cash 6,000 / Cr Unearned Rent Revenue 6,000. Recognize monthly.", category: "Journal Entries" },
  { q: "Entry: repurchase 100 shares at $50.", a: "Dr Treasury Stock 5,000 / Cr Cash 5,000. Contra-equity.", category: "Journal Entries" },
  { q: "Entry: record warranty expense estimate $1,500.", a: "Dr Warranty Expense 1,500 / Cr Warranty Liability 1,500.", category: "Journal Entries" },
  { q: "Entry: dispose of fully depreciated equipment.", a: "Dr Accumulated Depreciation (full cost) / Cr Equipment (full cost). If sold for cash, Dr Cash too, and record gain/loss.", category: "Journal Entries" },
  // FINANCIAL STATEMENTS (25)
  { q: "What does the income statement show?", a: "Financial performance over a period: revenue, expenses, and net income under accrual accounting.", category: "Statements" },
  { q: "What does the balance sheet show?", a: "Financial position at a point in time: assets, liabilities, equity. Assets = Liabilities + Equity.", category: "Statements" },
  { q: "What does the cash flow statement show?", a: "How cash changed: operating, investing, and financing activities.", category: "Statements" },
  { q: "How do the statements link?", a: "NI → retained earnings (BS) and CFO start (CFS). Ending cash (CFS) → BS. Many BS items drive IS/CFS effects.", category: "Statements" },
  { q: "What is deferred revenue?", a: "Cash collected before earned. Liability until performance occurs.", category: "Statements" },
  { q: "Why is deferred revenue a liability?", a: "Company owes goods/services. Until delivered, it's an obligation, not revenue.", category: "Statements" },
  { q: "What is depreciation?", a: "Non-cash allocation of tangible asset cost over useful life. Reduces earnings and PP&E but doesn't use cash.", category: "Statements" },
  { q: "Why does depreciation increase cash flow?", a: "Non-cash expense → reduces taxes (tax shield) → added back on CFS. Net cash increases by tax savings.", category: "Statements" },
  { q: "What is retained earnings?", a: "Cumulative net income minus cumulative dividends. Links IS to BS.", category: "Statements" },
  { q: "What is working capital?", a: "Current operating assets minus current operating liabilities. Cash tied up in operations.", category: "Statements" },
  { q: "Why can NI be negative while cash flow is positive?", a: "Non-cash charges (D&A, impairments) reduce NI. Favorable working capital or deferred revenue can boost cash.", category: "Statements" },
  { q: "What is EBITDA?", a: "Earnings Before Interest, Taxes, Depreciation, Amortization. Operating proxy, but not cash flow.", category: "Statements" },
  { q: "What is goodwill?", a: "Excess of purchase price over fair value of net assets in an acquisition.", category: "Statements" },
  { q: "What is the allowance method?", a: "Estimate credit losses upfront (allowance), then write off specific accounts later. Separates estimation from realization.", category: "Statements" },
  { q: "What is accumulated other comprehensive income?", a: "Equity items bypassing the IS: unrealized gains/losses on securities, foreign currency translation, pension adjustments.", category: "Statements" },
  // AUDIT (40)
  { q: "What is an audit?", a: "Independent examination providing reasonable assurance that statements are free of material misstatement from error or fraud.", category: "Audit" },
  { q: "What is reasonable assurance?", a: "High but not absolute. Limited by sampling, judgment, estimates, collusion risk, and cost constraints.", category: "Audit" },
  { q: "Management vs auditor responsibility?", a: "Management: prepares statements, maintains controls. Auditor: plans/performs audit, obtains evidence, issues opinion.", category: "Audit" },
  { q: "What are audit assertions?", a: "Management's claims: existence, completeness, valuation, rights/obligations, occurrence, cut-off, classification, accuracy.", category: "Audit" },
  { q: "Why do assertions matter?", a: "They connect risk to procedures. Auditors design tests targeting specific assertions at risk for specific accounts.", category: "Audit" },
  { q: "What is the audit risk model?", a: "Audit Risk = Inherent Risk × Control Risk × Detection Risk. High IR/CR → lower acceptable DR → more testing.", category: "Audit" },
  { q: "What is inherent risk?", a: "Susceptibility of assertion to misstatement assuming no controls. Complex estimates and significant transactions have higher IR.", category: "Audit" },
  { q: "What is control risk?", a: "Risk that controls fail to prevent or detect misstatement.", category: "Audit" },
  { q: "What is detection risk?", a: "Risk that audit procedures fail to detect material misstatement. The only risk auditors can directly control.", category: "Audit" },
  { q: "What is professional skepticism?", a: "Questioning mind, critical assessment of evidence. Don't assume management is wrong, but don't assume they're right.", category: "Audit" },
  { q: "Test of controls vs substantive test?", a: "Controls: evaluates if controls work. Substantive: detects misstatements directly via tests of details or analytics.", category: "Audit" },
  { q: "What is sufficient appropriate evidence?", a: "Sufficient = enough quantity. Appropriate = relevant and reliable quality. External > internal, auditor-generated > client-generated.", category: "Audit" },
  { q: "Types of audit procedures?", a: "Inquiry, observation, inspection, reperformance, recalculation, confirmation, analytical procedures.", category: "Audit" },
  { q: "How would you test AR existence?", a: "Send external confirmations to customers. Vouch recorded sales to invoices and shipping docs.", category: "Audit" },
  { q: "How would you test AP completeness?", a: "Review post-year-end disbursements, inspect unmatched receiving reports, inspect vendor statements.", category: "Audit" },
  { q: "How would you test inventory existence?", a: "Attend and observe physical count. Test count sheets to actual inventory and vice versa.", category: "Audit" },
  { q: "Why is revenue high-risk?", a: "Key performance metric, susceptible to manipulation, complex timing/measurement, often presumed fraud risk.", category: "Audit" },
  { q: "What is cut-off testing?", a: "Verifying transactions are recorded in the correct period. Critical for revenue and inventory around year-end.", category: "Audit" },
  { q: "What is the fraud triangle?", a: "Incentive/pressure + opportunity + rationalization. Explains why fraud risk increases in certain environments.", category: "Audit" },
  { q: "Error vs fraud?", a: "Error: unintentional misstatement. Fraud: intentional misstatement to deceive. Both can cause material misstatement.", category: "Audit" },
  { q: "What is management bias?", a: "Estimates persistently biased in one direction — optimistic allowances, delayed impairment, aggressive forecasts.", category: "Audit" },
  { q: "What is a subsequent event?", a: "Event after period-end. Type 1: evidence of year-end conditions (adjust). Type 2: new condition (disclose only).", category: "Audit" },
  { q: "What is going concern?", a: "Whether entity can continue operating. Auditor evaluates: recurring losses, debt defaults, liquidity issues.", category: "Audit" },
  { q: "What is analytical procedures?", a: "Evaluating financial info through analysis of plausible relationships. Used in planning, testing, and final review.", category: "Audit" },
  { q: "What is sampling risk?", a: "Risk that conclusions from a sample differ from conclusions if the entire population were tested.", category: "Audit" },
  { q: "What is a walkthrough?", a: "Tracing a transaction through the entire process to understand where errors can occur and where controls operate.", category: "Audit" },
  { q: "What are internal controls?", a: "System providing reasonable assurance on: reliable reporting, efficient operations, legal compliance.", category: "Audit" },
  { q: "What is segregation of duties?", a: "Separating authorization, custody, and recording functions to prevent fraud. Key preventive control.", category: "Audit" },
  { q: "What is a management representation letter?", a: "Written confirmation from management about statements and disclosures. Required but not sufficient evidence alone.", category: "Audit" },
  { q: "What makes confirmations unreliable?", a: "Wrong addresses, management interception, customer doesn't verify carefully, outdated balances.", category: "Audit" },
  // BEHAVIORAL (20)
  { q: "Why accounting?", a: "Translates complex business activity into structured, decision-useful information. Combines structure, analysis, and responsibility.", category: "Behavioral" },
  { q: "Why audit?", a: "Develops accounting judgment, broad industry exposure, analytical thinking + skepticism, strong career foundation.", category: "Behavioral" },
  { q: "Why this firm?", a: "Training environment, culture, client base, industry exposure, people you've spoken with. Be specific, not generic.", category: "Behavioral" },
  { q: "Tell me about a time you caught an error.", a: "STAR: context, identification, verification steps, impact, attention to detail demonstrated.", category: "Behavioral" },
  { q: "What if client explanation doesn't match evidence?", a: "Maintain skepticism, seek corroborating evidence, discuss with senior, expand testing. Resolve with evidence.", category: "Behavioral" },
  { q: "What if you found an error late in the audit?", a: "Escalate to senior/manager immediately. Assess materiality. Document findings. Don't ignore or bury it.", category: "Behavioral" },
  { q: "How do you handle repetitive work?", a: "Show maturity. Building skills requires repetition. Focus on accuracy and learning from patterns.", category: "Behavioral" },
  { q: "Tell me about teamwork.", a: "Show collaboration, communication, taking feedback, asking questions, reliability under pressure.", category: "Behavioral" },
  { q: "What is your greatest strength?", a: "Pick something relevant: attention to detail, organization, analytical thinking. Back with specific example.", category: "Behavioral" },
  { q: "Tell me about yourself.", a: "Present → relevant experiences → what you learned → why accounting/audit. Concise and directed.", category: "Behavioral" },
  // ═══ ADDITIONAL FOUNDATIONS (40) ═══
  {q:"What is the purpose of GAAP?",a:"Provide a consistent framework for financial reporting so users can compare companies and make informed decisions.",category:"Foundations"},
  {q:"What is IFRS and how does it differ from GAAP?",a:"International standards, principles-based vs GAAP's rules-based approach. Key differences in revenue, leases, inventory (no LIFO under IFRS).",category:"Foundations"},
  {q:"What is the historical cost principle?",a:"Assets recorded at original acquisition cost. Reliable but may not reflect current market value.",category:"Foundations"},
  {q:"What is fair value accounting?",a:"Recording assets/liabilities at current market value. More relevant but less reliable for illiquid items.",category:"Foundations"},
  {q:"What is the full disclosure principle?",a:"Financial statements must include all information necessary for user decision-making, including notes.",category:"Foundations"},
  {q:"What is the periodicity assumption?",a:"Economic life can be divided into artificial time periods (quarters, years) for reporting purposes.",category:"Foundations"},
  {q:"What is the economic entity assumption?",a:"Business activities are separate from the owner's personal activities and from other entities.",category:"Foundations"},
  {q:"What is the monetary unit assumption?",a:"Only transactions expressible in money are recorded. Ignores inflation effects (in most frameworks).",category:"Foundations"},
  {q:"What is substance over form?",a:"Transactions recorded based on economic reality, not just legal form. Example: finance lease is really a purchase.",category:"Foundations"},
  {q:"What are the four types of adjusting entries?",a:"Accrued revenues (earned, not received), accrued expenses (incurred, not paid), prepaid expenses (paid, not used), unearned revenue (received, not earned).",category:"Foundations"},
  {q:"What is a reversing entry?",a:"Optional entry at start of new period that reverses a prior adjusting entry. Simplifies recording the actual transaction.",category:"Foundations"},
  {q:"What is a contra account?",a:"Account that offsets another: accumulated depreciation offsets PP&E, allowance offsets AR, treasury stock offsets equity.",category:"Foundations"},
  {q:"What is a subsidiary ledger?",a:"Detailed records supporting a general ledger control account. AR subsidiary shows each customer's balance.",category:"Foundations"},
  {q:"What is a chart of accounts?",a:"Organized listing of all accounts in the general ledger. Provides structure for recording transactions.",category:"Foundations"},
  {q:"What is materiality in accounting?",a:"An amount is material if its omission or misstatement would influence user decisions. Requires judgment.",category:"Foundations"},
  {q:"What is the cost-benefit constraint?",a:"Cost of providing information should not exceed its benefit to users. Why immaterial items aren't tracked precisely.",category:"Foundations"},
  {q:"What is comparability?",a:"Users can identify similarities and differences across companies. Achieved through consistent standards application.",category:"Foundations"},
  {q:"What is verifiability?",a:"Different knowledgeable observers could reach consensus that the representation is faithful.",category:"Foundations"},
  {q:"What is timeliness?",a:"Information available to users in time to influence their decisions. Stale information loses relevance.",category:"Foundations"},
  {q:"What is a special purpose framework?",a:"Non-GAAP basis: cash basis, tax basis, regulatory basis. Used when full GAAP isn't required.",category:"Foundations"},
  // ═══ ADDITIONAL JOURNAL ENTRIES (30) ═══
  {q:"Entry: record sales returns of $500.",a:"Dr Sales Returns & Allowances 500 / Cr AR (or Cash) 500. Contra-revenue account.",category:"Journal Entries"},
  {q:"Entry: purchase supplies for $300 cash.",a:"Dr Supplies 300 / Cr Cash 300. Adjust at period end for supplies used.",category:"Journal Entries"},
  {q:"Entry: adjust supplies — $200 used during period.",a:"Dr Supplies Expense 200 / Cr Supplies 200. Remaining supplies stay as asset.",category:"Journal Entries"},
  {q:"Entry: record payroll taxes payable $1,500.",a:"Dr Payroll Tax Expense 1,500 / Cr Payroll Taxes Payable 1,500. Employer portion.",category:"Journal Entries"},
  {q:"Entry: pay off accounts payable of $2,000.",a:"Dr Accounts Payable 2,000 / Cr Cash 2,000. Liability decreases, cash decreases.",category:"Journal Entries"},
  {q:"Entry: record estimated warranty liability $3,000.",a:"Dr Warranty Expense 3,000 / Cr Estimated Warranty Liability 3,000. Matching principle.",category:"Journal Entries"},
  {q:"Entry: customer exercises warranty — repair costs $500.",a:"Dr Estimated Warranty Liability 500 / Cr Cash (or Parts) 500. No new expense — uses existing estimate.",category:"Journal Entries"},
  {q:"Entry: declare cash dividend $10,000.",a:"Dr Retained Earnings 10,000 / Cr Dividends Payable 10,000. Liability created at declaration.",category:"Journal Entries"},
  {q:"Entry: pay previously declared dividend.",a:"Dr Dividends Payable 10,000 / Cr Cash 10,000. Settles the liability.",category:"Journal Entries"},
  {q:"Entry: record stock split 2-for-1.",a:"No journal entry needed. Shares double, par value halves. Memo entry only.",category:"Journal Entries"},
  {q:"Entry: issue bonds at a premium ($105,000 for $100,000 face).",a:"Dr Cash 105,000 / Cr Bonds Payable 100,000 / Cr Premium on Bonds Payable 5,000.",category:"Journal Entries"},
  {q:"Entry: issue bonds at a discount ($97,000 for $100,000 face).",a:"Dr Cash 97,000 / Dr Discount on Bonds Payable 3,000 / Cr Bonds Payable 100,000.",category:"Journal Entries"},
  {q:"Entry: amortize bond premium $500.",a:"Dr Premium on Bonds Payable 500 / Cr Interest Expense 500. Reduces effective interest cost.",category:"Journal Entries"},
  {q:"Entry: amortize bond discount $300.",a:"Dr Interest Expense 300 / Cr Discount on Bonds Payable 300. Increases effective interest cost.",category:"Journal Entries"},
  {q:"Entry: capitalize development costs $50,000 (if criteria met under IFRS).",a:"Dr Intangible Asset (Development) 50,000 / Cr Cash 50,000. Only if technical/commercial feasibility demonstrated.",category:"Journal Entries"},
  {q:"Entry: record stock-based compensation expense $8,000.",a:"Dr Stock Compensation Expense 8,000 / Cr Additional Paid-In Capital 8,000. Non-cash equity expense.",category:"Journal Entries"},
  {q:"Entry: record impairment of goodwill $25,000.",a:"Dr Impairment Loss 25,000 / Cr Goodwill 25,000. Non-cash charge, reduces asset and earnings.",category:"Journal Entries"},
  {q:"Entry: record unrealized gain on available-for-sale security $2,000.",a:"Dr Investment 2,000 / Cr OCI (Unrealized Gain) 2,000. Bypasses income statement.",category:"Journal Entries"},
  {q:"Entry: record foreign currency translation loss $1,500.",a:"Dr OCI (Translation Loss) 1,500 / Cr Investment in Foreign Sub 1,500. Equity impact, not IS.",category:"Journal Entries"},
  {q:"Entry: capitalize a finance lease — PV of payments $80,000.",a:"Dr Right-of-Use Asset 80,000 / Cr Lease Liability 80,000. Both asset and liability on BS.",category:"Journal Entries"},
  {q:"Entry: record lease payment $2,000 (finance lease).",a:"Dr Interest Expense (liability × rate) / Dr Lease Liability (remainder) / Cr Cash 2,000.",category:"Journal Entries"},
  {q:"Entry: record grant of stock options (fair value $12,000, 4yr vest).",a:"Expense $3,000/year: Dr Stock Comp Expense 3,000 / Cr APIC 3,000 each year.",category:"Journal Entries"},
  {q:"Entry: convert bonds to stock (book value method).",a:"Dr Bonds Payable (face) / Dr Premium or Cr Discount / Cr Common Stock / Cr APIC. No gain/loss.",category:"Journal Entries"},
  {q:"Entry: record income tax expense $15,000 (current $12,000, deferred $3,000).",a:"Dr Income Tax Expense 15,000 / Cr Income Tax Payable 12,000 / Cr Deferred Tax Liability 3,000.",category:"Journal Entries"},
  // ═══ ADDITIONAL STATEMENTS (25) ═══
  {q:"What is the indirect vs direct method for cash flows?",a:"Indirect: starts with NI, adjusts for non-cash and WC. Direct: shows actual cash receipts/payments. Indirect is most common.",category:"Statements"},
  {q:"What is a classified balance sheet?",a:"Separates current from non-current assets and liabilities. Helps assess liquidity and long-term solvency.",category:"Statements"},
  {q:"What is a multi-step vs single-step income statement?",a:"Multi-step: shows gross profit, operating income, then NI. Single-step: total revenue minus total expenses. Multi-step more useful.",category:"Statements"},
  {q:"What is comprehensive income?",a:"Net income plus OCI items: unrealized investment gains/losses, FX translation, pension adjustments, hedge gains/losses.",category:"Statements"},
  {q:"What is other comprehensive income (OCI)?",a:"Gains/losses that bypass the income statement and go directly to equity. Accumulated OCI is a BS equity component.",category:"Statements"},
  {q:"What is the difference between operating and non-operating income?",a:"Operating: from core business (revenue minus COGS minus OpEx). Non-operating: interest, gains/losses, other peripheral items.",category:"Statements"},
  {q:"What is earnings per share (basic vs diluted)?",a:"Basic: NI / weighted avg shares. Diluted: includes potential dilution from options, convertibles. Diluted is more conservative.",category:"Statements"},
  {q:"What is a pro forma financial statement?",a:"Projected or hypothetical statements showing expected future results or the impact of a proposed transaction.",category:"Statements"},
  {q:"What is a common-size income statement?",a:"Each line item as a percentage of revenue. Enables comparison across companies of different sizes.",category:"Statements"},
  {q:"What is a common-size balance sheet?",a:"Each line item as percentage of total assets. Shows composition and structure regardless of size.",category:"Statements"},
  {q:"What is horizontal analysis?",a:"Comparing financial data over time. Shows trends, growth rates, and directional changes.",category:"Statements"},
  {q:"What is vertical analysis?",a:"Each item as percentage of a base (revenue for IS, total assets for BS). Same as common-size.",category:"Statements"},
  {q:"What is the cash conversion cycle?",a:"DSO + DIO - DPO. Measures days between paying suppliers and collecting from customers. Lower = better.",category:"Statements"},
  {q:"What is EBIT vs EBITDA?",a:"EBIT includes D&A (better for capital-intensive). EBITDA excludes it (rough operating proxy but not cash flow).",category:"Statements"},
  {q:"What is free cash flow?",a:"CFO minus CapEx. Cash available for debt repayment, dividends, buybacks, or investment after maintaining assets.",category:"Statements"},
  {q:"What is the quality of earnings?",a:"How sustainable and cash-backed earnings are. High quality: earnings close to cash flow. Low quality: aggressive accruals, one-time items.",category:"Statements"},
  {q:"What is a non-cash charge?",a:"Expense reducing earnings but not using cash: depreciation, amortization, impairment, SBC, deferred taxes.",category:"Statements"},
  {q:"How do stock buybacks affect financial statements?",a:"BS: cash down, treasury stock up (equity down). IS: no direct impact. EPS: increases because fewer shares outstanding.",category:"Statements"},
  {q:"What is a contingent asset?",a:"Potential asset depending on future event. Not recorded, but may be disclosed if probable. Conservative treatment.",category:"Statements"},
  {q:"What is segment reporting?",a:"Breaking out results by business segment or geography. Required for public companies. Helps assess diversified businesses.",category:"Statements"},
  // ═══ ADDITIONAL AUDIT (50) ═══
  {q:"What is an unqualified (clean) opinion?",a:"Auditor's conclusion that statements are presented fairly in all material respects. The best outcome.",category:"Audit"},
  {q:"What is a qualified opinion?",a:"Statements are fairly presented except for a specific matter. 'Except for' language. Less severe than adverse.",category:"Audit"},
  {q:"What is an adverse opinion?",a:"Statements are NOT fairly presented. Material and pervasive misstatement. Worst opinion type.",category:"Audit"},
  {q:"What is a disclaimer of opinion?",a:"Auditor cannot form an opinion due to scope limitation. Does not express any opinion.",category:"Audit"},
  {q:"What is an emphasis of matter paragraph?",a:"Draws attention to a matter properly presented/disclosed. Does not modify opinion. Example: going concern.",category:"Audit"},
  {q:"What is a key audit matter (KAM)?",a:"Matters of most significance in the audit. Communicated in the report. Enhances transparency.",category:"Audit"},
  {q:"What is audit planning?",a:"Understanding the entity, assessing risk, determining materiality, designing audit approach. Foundation for everything.",category:"Audit"},
  {q:"What is performance materiality?",a:"Amount set below overall materiality to reduce probability that aggregate uncorrected misstatements exceed materiality.",category:"Audit"},
  {q:"What is tolerable misstatement?",a:"Materiality applied at the account level. Guides sample sizes and testing extent.",category:"Audit"},
  {q:"What is clearly trivial?",a:"Amount below which misstatements need not be accumulated. Much lower than materiality.",category:"Audit"},
  {q:"What is an integrated audit?",a:"Audit of both financial statements and internal controls over financial reporting. Required for SEC registrants.",category:"Audit"},
  {q:"What is SOX Section 404?",a:"Requires management assessment and auditor attestation of internal controls over financial reporting for public companies.",category:"Audit"},
  {q:"What is a significant deficiency?",a:"Control weakness less severe than material weakness but important enough to merit attention.",category:"Audit"},
  {q:"What is a material weakness?",a:"Control deficiency where a material misstatement could occur and not be prevented/detected timely. Must be reported.",category:"Audit"},
  {q:"What is IT general controls (ITGC)?",a:"Controls over IT environment: access, change management, operations, backup. Foundation for application controls.",category:"Audit"},
  {q:"What is an application control?",a:"Controls within specific applications: input validation, processing accuracy, output completeness.",category:"Audit"},
  {q:"What is a management override of controls?",a:"Management can bypass controls (e.g., override journal entries). Always a fraud risk. Cannot be fully controlled.",category:"Audit"},
  {q:"How do you test journal entries for fraud?",a:"Select entries based on risk criteria: unusual amounts, off-hours, manual, to unusual accounts. Test supporting docs.",category:"Audit"},
  {q:"What is a confirmation?",a:"External verification: bank confirms cash, customer confirms AR, lender confirms debt. Strong evidence because external.",category:"Audit"},
  {q:"Positive vs negative confirmation?",a:"Positive: recipient asked to respond whether they agree or disagree. Negative: respond only if they disagree. Positive is stronger.",category:"Audit"},
  {q:"What is vouching?",a:"Tracing from recorded amount back to source document. Tests occurrence/existence — did this transaction really happen?",category:"Audit"},
  {q:"What is tracing?",a:"Following from source document to recorded amount. Tests completeness — was this transaction actually recorded?",category:"Audit"},
  {q:"What is reperformance?",a:"Auditor independently re-executes a procedure or control. Strong evidence of control effectiveness.",category:"Audit"},
  {q:"What is recalculation?",a:"Checking mathematical accuracy. Simple but important. Depreciation, interest, amortization schedules.",category:"Audit"},
  {q:"What is inquiry as audit evidence?",a:"Asking management or staff questions. Weakest form of evidence alone. Must be corroborated with other procedures.",category:"Audit"},
  {q:"What is observation as audit evidence?",a:"Watching a process or procedure being performed. Useful for inventory counts, segregation of duties.",category:"Audit"},
  {q:"What is the search for unrecorded liabilities?",a:"Review post-year-end payments, unmatched receiving reports, vendor statements. Liabilities are more at risk of understatement.",category:"Audit"},
  {q:"What is a bank reconciliation test?",a:"Verify that book and bank balances reconcile. Test outstanding checks, deposits in transit, bank charges.",category:"Audit"},
  {q:"What is accounts receivable confirmation?",a:"Send letters to customers asking them to verify balance owed. Tests existence and accuracy.",category:"Audit"},
  {q:"What is inventory observation?",a:"Attend physical count, test counting procedures, perform test counts, reconcile to final inventory listing.",category:"Audit"},
  {q:"What is cut-off testing for revenue?",a:"Test transactions around period-end to ensure recorded in correct period. Check shipping docs, invoices, timing.",category:"Audit"},
  {q:"What is cut-off testing for purchases?",a:"Verify goods received before year-end are in inventory and AP. Goods received after are excluded.",category:"Audit"},
  {q:"What is the roll-forward procedure?",a:"Testing a balance at an interim date and updating/roll-forward to year-end. Efficient for low-risk areas.",category:"Audit"},
  {q:"What is a legal letter (attorney letter)?",a:"Sent to client's lawyers asking about pending/threatened litigation. Key evidence for contingent liabilities.",category:"Audit"},
  {q:"What is the management representation letter?",a:"Written confirmations from management about the statements. Required but never sufficient evidence alone.",category:"Audit"},
  {q:"What is a related party transaction?",a:"Transaction with parties that have special relationships (officers, affiliates). Higher risk because not arm's-length.",category:"Audit"},
  {q:"Why are estimates difficult to audit?",a:"Subjective, forward-looking, depend on assumptions and models. Range of reasonable values makes precision impossible.",category:"Audit"},
  {q:"How do you audit fair value estimates?",a:"Test underlying data, evaluate assumptions, compare to independent estimates, check prior estimates vs actual outcomes.",category:"Audit"},
  {q:"What is an auditor's specialist?",a:"Expert engaged to assist auditor (actuary, appraiser, IT specialist). Auditor is still responsible for conclusions.",category:"Audit"},
  {q:"What is analytical procedures as substantive test?",a:"Develop expectation based on relationships (revenue vs prior year, payroll vs headcount). Investigate significant differences.",category:"Audit"},
  {q:"What is the final analytical review?",a:"Overall review of statements before issuing opinion. Big-picture assessment of whether statements make sense.",category:"Audit"},
  {q:"What is a misstatement summary (SAD schedule)?",a:"Summary of Audit Differences: all identified misstatements evaluated for materiality individually and in aggregate.",category:"Audit"},
  {q:"What is a going concern evaluation?",a:"Assess whether entity can continue for 12 months. Look at losses, negative cash flow, covenant issues, maturity walls.",category:"Audit"},
  {q:"What is a subsequent events review?",a:"Evaluate events between year-end and audit report date. Type 1: adjust. Type 2: disclose.",category:"Audit"},
  {q:"What is an engagement letter?",a:"Agreement between auditor and client defining scope, responsibilities, fees, and terms of the audit engagement.",category:"Audit"},
  {q:"What is predecessor/successor auditor communication?",a:"New auditor contacts prior auditor about reasons for change, disagreements, and significant matters. Required.",category:"Audit"},
  {q:"What is audit documentation (workpapers)?",a:"Record of procedures performed, evidence obtained, and conclusions reached. Must support the opinion.",category:"Audit"},
  {q:"What is the audit committee?",a:"Board subcommittee overseeing financial reporting and audit. Auditor's primary governance communication channel.",category:"Audit"},
  {q:"What must be communicated to those charged with governance?",a:"Significant findings, control deficiencies, fraud indicators, scope changes, independence matters, audit disagreements.",category:"Audit"},
  {q:"What is auditor independence?",a:"Auditor must be independent in fact and appearance. Cannot have financial interest, close relationships, or provide prohibited services.",category:"Audit"},
  // ═══ ADDITIONAL BEHAVIORAL (25) ═══
  {q:"How do you handle tight deadlines during busy season?",a:"Prioritize, communicate, focus on high-risk areas first, maintain quality. Show you understand busy season reality.",category:"Behavioral"},
  {q:"Tell me about a time you worked with a difficult team member.",a:"Show professional resolution: listening, finding common ground, maintaining productivity, escalating if needed.",category:"Behavioral"},
  {q:"What is your understanding of the CPA exam?",a:"Four sections: AUD, BEC/BAR, FAR, REG/TCP/ISC. Most states require 150 credit hours. Show you've researched.",category:"Behavioral"},
  {q:"How do you ensure accuracy in your work?",a:"Checklists, self-review, cross-referencing, asking questions when unsure. Give a specific example.",category:"Behavioral"},
  {q:"What interests you about public accounting vs industry?",a:"Public: variety of clients, broad exposure, fast learning. Industry: deeper focus, business impact, work-life. Be genuine.",category:"Behavioral"},
  {q:"Tell me about a time you improved a process.",a:"Identified inefficiency, proposed solution, implemented it, measured improvement. Show initiative.",category:"Behavioral"},
  {q:"How would you handle discovering a potential fraud indicator?",a:"Don't investigate alone. Document what you found, inform the senior/manager immediately, follow firm protocols.",category:"Behavioral"},
  {q:"What soft skills matter most in audit?",a:"Communication (with clients and team), organization, time management, professional skepticism, coachability.",category:"Behavioral"},
  {q:"Why Big 4 vs mid-tier vs small firm?",a:"Big 4: training, brand, complex clients. Mid-tier: more responsibility earlier, still large clients. Small: diverse exposure. Know your preference.",category:"Behavioral"},
  {q:"Tell me about a time you received constructive criticism.",a:"Show you listened, understood, implemented the feedback, and improved. Coachability is critical.",category:"Behavioral"},
  {q:"How do you stay current on accounting standards?",a:"CPE, firm training, FASB/IASB updates, professional publications, peer discussions.",category:"Behavioral"},
  {q:"What do you think is the most challenging area of accounting?",a:"Pick something specific (revenue recognition, fair value, leases) and explain why with nuance.",category:"Behavioral"},
  {q:"Describe a time you had to learn something quickly.",a:"Show adaptability: what it was, how you approached it, resources used, outcome.",category:"Behavioral"},
  {q:"What would you do if you disagreed with a senior's accounting treatment?",a:"Research the issue, present your reasoning with standards support, discuss professionally, defer if appropriate.",category:"Behavioral"},
  {q:"Tell me about a time you worked under pressure.",a:"STAR: specific situation, task, actions you took, result. Show composure and quality output.",category:"Behavioral"},
  {q:"What questions do you have for us?",a:"Ask about training, client mix, team culture, career development, what makes someone successful. Show curiosity.",category:"Behavioral"},
  {q:"How do you organize multiple client engagements?",a:"Priority matrix, checklists, communication with teams, managing expectations, asking for help early when needed.",category:"Behavioral"},
  {q:"What do you know about our firm's clients/industries?",a:"Research the firm's industry specializations. Mention specific practice areas or clients that interest you.",category:"Behavioral"},
  {q:"Where do you see yourself in 5 years?",a:"Senior/manager in public accounting, or transitioning to industry with a strong foundation. Show thought, not just ambition.",category:"Behavioral"},
  {q:"Tell me about a time you demonstrated integrity.",a:"Doing the right thing even when difficult: reporting an error, being honest about a mistake, standing by your work.",category:"Behavioral"},
];

