import { Flashcard } from './ib-flashcard-data';
export const ACCT_FLASHCARDS: Flashcard[] = [
  { q: "What is the accounting equation?", a: "Assets = Liabilities + Equity. Every transaction must preserve this equation.", category: "Foundations" },
  { q: "What are debits and credits?", a: "A double-entry mechanism. Assets/expenses increase with debits. Liabilities/equity/revenue increase with credits.", category: "Foundations" },
  { q: "What is accrual accounting?", a: "Revenue recorded when earned, expenses when incurred — regardless of cash timing. Produces better performance measurement than cash accounting.", category: "Foundations" },
  { q: "What is an adjusting entry?", a: "Period-end corrections for timing: accruals, deferrals, depreciation, allowances. Without them, statements may be materially misstated.", category: "Foundations" },
  { q: "What is deferred revenue and why is it a liability?", a: "Cash collected before revenue is earned. The company owes goods/services — that obligation is a liability until performance occurs.", category: "Foundations" },
  { q: "What is depreciation?", a: "Non-cash allocation of a tangible asset's cost over its useful life. Reduces earnings and asset value but doesn't use cash.", category: "Foundations" },
  { q: "What is the bad debt allowance?", a: "Estimate of receivables that won't be collected. Dr Bad Debt Expense / Cr Allowance. Separates estimation from write-off.", category: "Foundations" },
  { q: "Journal entry: borrow $50K from bank.", a: "Dr Cash 50,000 / Cr Notes Payable 50,000. Asset up, liability up. No income statement impact.", category: "Journal Entries" },
  { q: "Journal entry: sell goods for $1,000 on credit.", a: "Dr Accounts Receivable 1,000 / Cr Revenue 1,000. Revenue recognized, cash not yet collected.", category: "Journal Entries" },
  { q: "Journal entry: prepay $1,200 annual insurance.", a: "Initial: Dr Prepaid Insurance 1,200 / Cr Cash 1,200. Monthly: Dr Insurance Expense 100 / Cr Prepaid Insurance 100.", category: "Journal Entries" },
  { q: "Journal entry: accrue $800 unpaid wages.", a: "Dr Wage Expense 800 / Cr Accrued Wages Payable 800. Expense recognized before cash payment.", category: "Journal Entries" },
  { q: "Journal entry: record depreciation of $2,400.", a: "Dr Depreciation Expense 2,400 / Cr Accumulated Depreciation 2,400. Non-cash expense, PP&E net value decreases.", category: "Journal Entries" },
  { q: "What is the purpose of an audit?", a: "Provide independent reasonable assurance that financial statements are free of material misstatement, whether from error or fraud.", category: "Audit" },
  { q: "What is reasonable assurance?", a: "High but not absolute level of assurance. Audits are limited by sampling, judgment, estimates, and inherent risk.", category: "Audit" },
  { q: "What are audit assertions?", a: "Management's claims about transactions/balances: existence, completeness, valuation, rights/obligations, occurrence, cut-off, classification, accuracy.", category: "Audit" },
  { q: "What is materiality?", a: "Threshold above which misstatement could influence user decisions. Both quantitative and qualitative — a small error can be material if it hides fraud.", category: "Audit" },
  { q: "What is professional skepticism?", a: "A questioning mind and critical assessment of evidence. Don't assume management is wrong, but don't assume they're right either.", category: "Audit" },
  { q: "What is the audit risk model?", a: "Audit Risk = Inherent Risk × Control Risk × Detection Risk. If IR and CR are high, auditors reduce DR by testing more.", category: "Audit" },
  { q: "Test of controls vs substantive test?", a: "Controls test: evaluates if controls operated effectively. Substantive test: detects misstatements directly through tests of details or analytics.", category: "Audit" },
  { q: "How would you test AP completeness?", a: "Review post-year-end cash disbursements, inspect unmatched receiving reports, inspect vendor statements. Liabilities are more likely understated.", category: "Audit" },
  { q: "What is the fraud triangle?", a: "Three elements: incentive/pressure, opportunity, rationalization. Explains why fraud risk increases in certain environments.", category: "Audit" },
  { q: "Why is revenue a high-risk audit area?", a: "Key performance metric, susceptible to manipulation, complex timing/measurement with contracts, returns, variable consideration, and cut-off issues.", category: "Audit" },
  { q: "What is a subsequent event?", a: "Event after period-end. Type 1: provides evidence about conditions at year-end (adjust). Type 2: new condition requiring disclosure only.", category: "Audit" },
  { q: "What is going concern?", a: "Whether the entity can continue operating for a reasonable period. Auditors evaluate indicators like recurring losses, debt defaults, or liquidity problems.", category: "Audit" },
  { q: "Why accounting / why audit?", a: "Accounting translates business activity into decision-useful information. Audit combines technical accounting, business understanding, risk assessment, and professional judgment.", category: "Behavioral" },
  { q: "Tell me about a time you caught an error.", a: "Use STAR: context, how you identified it, steps to verify, impact, what it showed about your attention to detail.", category: "Behavioral" },
  { q: "What would you do if a client explanation doesn't match the evidence?", a: "Maintain skepticism, seek corroborating evidence, discuss with senior team, expand testing. Resolve with evidence, not just management explanation.", category: "Behavioral" },
];
