import { Flashcard } from './ib-flashcard-data';
export const ACCT_FLASHCARDS: Flashcard[] = [
  // FOUNDATIONS (35)
  { q: "What is accounting?", a: "The structured process of identifying, measuring, recording, classifying, summarizing, and communicating economic activity.", category: "Foundations" },
  { q: "What is the accounting equation?", a: "Assets = Liabilities + Equity. Every transaction must preserve this equation.", category: "Foundations" },
  { q: "What are debits and credits?", a: "Double-entry mechanism. Assets/expenses increase with debits. Liabilities/equity/revenue increase with credits.", category: "Foundations" },
  { q: "Why do expenses have debit balances?", a: "Expenses reduce equity (retained earnings). Since equity is credit-normal, its reduction is a debit.", category: "Foundations" },
  { q: "What is accrual accounting?", a: "Revenue recorded when earned, expenses when incurred — regardless of cash timing. Better performance measurement.", category: "Foundations" },
  { q: "What is cash accounting?", a: "Records transactions when cash moves. Simpler but can distort performance measurement.", category: "Foundations" },
  { q: "Why is accrual preferred?", a: "It matches economic activity to the period it occurs, producing more meaningful performance representation than cash timing alone.", category: "Foundations" },
  { q: "What is an adjusting entry?", a: "Period-end corrections: accruals, deferrals, depreciation, allowances. Without them, statements may be materially misstated.", category: "Foundations" },
  { q: "What is the general ledger?", a: "Collection of all accounts and their balances. The central record from which financial statements are built.", category: "Foundations" },
  { q: "What is a trial balance?", a: "Listing of all accounts to verify total debits equal total credits. Used before and after adjusting entries.", category: "Foundations" },
  { q: "What are closing entries?", a: "Move temporary accounts (revenue, expenses) into retained earnings at period end. Reset for next period.", category: "Foundations" },
  { q: "What is materiality?", a: "Threshold above which misstatement could influence user decisions. Both quantitative and qualitative.", category: "Foundations" },
  { q: "What is the matching principle?", a: "Expenses recognized in the same period as the revenues they help generate. COGS matched to sale.", category: "Foundations" },
  { q: "What is revenue recognition?", a: "Revenue recognized when control transfers and entity is entitled to consideration — not necessarily when cash is received.", category: "Foundations" },
  { q: "What is conservatism in accounting?", a: "When uncertain, recognize losses early but defer gains. Prevents overstatement of financial health.", category: "Foundations" },
  { q: "What is the going concern assumption?", a: "Assumption the entity will continue operating. If doubt exists, disclosures and possible measurement changes required.", category: "Foundations" },
  // JOURNAL ENTRIES (30)
  { q: "Entry: borrow $50K from bank.", a: "Dr Cash 50,000 / Cr Notes Payable 50,000. Asset up, liability up.", category: "Journal Entries" },
  { q: "Entry: sell goods $1,000 on credit.", a: "Dr AR 1,000 / Cr Revenue 1,000. Revenue recognized, cash not collected.", category: "Journal Entries" },
  { q: "Entry: collect $1,000 cash from customer.", a: "Dr Cash 1,000 / Cr AR 1,000. No income statement impact.", category: "Journal Entries" },
  { q: "Entry: purchase inventory $500 on credit.", a: "Dr Inventory 500 / Cr AP 500. No immediate expense.", category: "Journal Entries" },
  { q: "Entry: sell inventory costing $400 for $1,000 cash.", a: "Dr Cash 1,000 / Cr Revenue 1,000. Dr COGS 400 / Cr Inventory 400.", category: "Journal Entries" },
  { q: "Entry: prepay $1,200 annual insurance.", a: "Dr Prepaid Insurance 1,200 / Cr Cash 1,200. Monthly: Dr Insurance Exp 100 / Cr Prepaid 100.", category: "Journal Entries" },
  { q: "Entry: accrue $800 unpaid wages.", a: "Dr Wage Expense 800 / Cr Accrued Wages Payable 800.", category: "Journal Entries" },
  { q: "Entry: record depreciation of $2,400.", a: "Dr Depreciation Expense 2,400 / Cr Accumulated Depreciation 2,400.", category: "Journal Entries" },
  { q: "Entry: record bad debt allowance $300.", a: "Dr Bad Debt Expense 300 / Cr Allowance for Doubtful Accounts 300.", category: "Journal Entries" },
  { q: "Entry: write off specific $100 uncollectible.", a: "Dr Allowance 100 / Cr AR 100. No income statement impact (already estimated).", category: "Journal Entries" },
  { q: "Entry: collect $2,400 for 12-month service.", a: "Dr Cash 2,400 / Cr Deferred Revenue 2,400. Monthly: Dr Deferred Rev 200 / Cr Revenue 200.", category: "Journal Entries" },
  { q: "Entry: issue stock for $10,000.", a: "Dr Cash 10,000 / Cr Common Stock (par) + Cr APIC (excess over par).", category: "Journal Entries" },
  { q: "Entry: pay dividend of $5,000.", a: "Dr Retained Earnings 5,000 / Cr Cash 5,000. Not an expense.", category: "Journal Entries" },
  { q: "Entry: purchase equipment $20,000 cash.", a: "Dr Equipment 20,000 / Cr Cash 20,000. CapEx — no immediate IS impact.", category: "Journal Entries" },
  { q: "Entry: accrue interest on $50K note at 6%/year, 1 month.", a: "Dr Interest Expense 250 / Cr Interest Payable 250. ($50K × 6% / 12).", category: "Journal Entries" },
  { q: "Entry: record inventory shrinkage of $200.", a: "Dr COGS (or Loss) 200 / Cr Inventory 200.", category: "Journal Entries" },
  { q: "Entry: record unearned rent revenue received $6,000.", a: "Dr Cash 6,000 / Cr Unearned Rent Revenue 6,000. Recognize monthly.", category: "Journal Entries" },
  { q: "Entry: repurchase 100 shares at $50.", a: "Dr Treasury Stock 5,000 / Cr Cash 5,000. Contra-equity.", category: "Journal Entries" },
  { q: "Entry: record warranty expense estimate $1,500.", a: "Dr Warranty Expense 1,500 / Cr Warranty Liability 1,500.", category: "Journal Entries" },
  { q: "Entry: dispose of fully depreciated equipment.", a: "Dr Accumulated Depreciation (full cost) / Cr Equipment (full cost). If sold for cash, Dr Cash too, and record gain/loss.", category: "Journal Entries" },
  // FINANCIAL STATEMENTS (25)
  { q: "What does the income statement show?", a: "Financial performance over a period: revenue, expenses, and net income under accrual accounting.", category: "Statements" },
  { q: "What does the balance sheet show?", a: "Financial position at a point in time: assets, liabilities, equity. Assets = Liabilities + Equity.", category: "Statements" },
  { q: "What does the cash flow statement show?", a: "How cash changed: operating, investing, and financing activities.", category: "Statements" },
  { q: "How do the statements link?", a: "NI → retained earnings (BS) and CFO start (CFS). Ending cash (CFS) → BS. Many BS items drive IS/CFS effects.", category: "Statements" },
  { q: "What is deferred revenue?", a: "Cash collected before earned. Liability until performance occurs.", category: "Statements" },
  { q: "Why is deferred revenue a liability?", a: "Company owes goods/services. Until delivered, it's an obligation, not revenue.", category: "Statements" },
  { q: "What is depreciation?", a: "Non-cash allocation of tangible asset cost over useful life. Reduces earnings and PP&E but doesn't use cash.", category: "Statements" },
  { q: "Why does depreciation increase cash flow?", a: "Non-cash expense → reduces taxes (tax shield) → added back on CFS. Net cash increases by tax savings.", category: "Statements" },
  { q: "What is retained earnings?", a: "Cumulative net income minus cumulative dividends. Links IS to BS.", category: "Statements" },
  { q: "What is working capital?", a: "Current operating assets minus current operating liabilities. Cash tied up in operations.", category: "Statements" },
  { q: "Why can NI be negative while cash flow is positive?", a: "Non-cash charges (D&A, impairments) reduce NI. Favorable working capital or deferred revenue can boost cash.", category: "Statements" },
  { q: "What is EBITDA?", a: "Earnings Before Interest, Taxes, Depreciation, Amortization. Operating proxy, but not cash flow.", category: "Statements" },
  { q: "What is goodwill?", a: "Excess of purchase price over fair value of net assets in an acquisition.", category: "Statements" },
  { q: "What is the allowance method?", a: "Estimate credit losses upfront (allowance), then write off specific accounts later. Separates estimation from realization.", category: "Statements" },
  { q: "What is accumulated other comprehensive income?", a: "Equity items bypassing the IS: unrealized gains/losses on securities, foreign currency translation, pension adjustments.", category: "Statements" },
  // AUDIT (40)
  { q: "What is an audit?", a: "Independent examination providing reasonable assurance that statements are free of material misstatement from error or fraud.", category: "Audit" },
  { q: "What is reasonable assurance?", a: "High but not absolute. Limited by sampling, judgment, estimates, collusion risk, and cost constraints.", category: "Audit" },
  { q: "Management vs auditor responsibility?", a: "Management: prepares statements, maintains controls. Auditor: plans/performs audit, obtains evidence, issues opinion.", category: "Audit" },
  { q: "What are audit assertions?", a: "Management's claims: existence, completeness, valuation, rights/obligations, occurrence, cut-off, classification, accuracy.", category: "Audit" },
  { q: "Why do assertions matter?", a: "They connect risk to procedures. Auditors design tests targeting specific assertions at risk for specific accounts.", category: "Audit" },
  { q: "What is the audit risk model?", a: "Audit Risk = Inherent Risk × Control Risk × Detection Risk. High IR/CR → lower acceptable DR → more testing.", category: "Audit" },
  { q: "What is inherent risk?", a: "Susceptibility of assertion to misstatement assuming no controls. Complex estimates and significant transactions have higher IR.", category: "Audit" },
  { q: "What is control risk?", a: "Risk that controls fail to prevent or detect misstatement.", category: "Audit" },
  { q: "What is detection risk?", a: "Risk that audit procedures fail to detect material misstatement. The only risk auditors can directly control.", category: "Audit" },
  { q: "What is professional skepticism?", a: "Questioning mind, critical assessment of evidence. Don't assume management is wrong, but don't assume they're right.", category: "Audit" },
  { q: "Test of controls vs substantive test?", a: "Controls: evaluates if controls work. Substantive: detects misstatements directly via tests of details or analytics.", category: "Audit" },
  { q: "What is sufficient appropriate evidence?", a: "Sufficient = enough quantity. Appropriate = relevant and reliable quality. External > internal, auditor-generated > client-generated.", category: "Audit" },
  { q: "Types of audit procedures?", a: "Inquiry, observation, inspection, reperformance, recalculation, confirmation, analytical procedures.", category: "Audit" },
  { q: "How would you test AR existence?", a: "Send external confirmations to customers. Vouch recorded sales to invoices and shipping docs.", category: "Audit" },
  { q: "How would you test AP completeness?", a: "Review post-year-end disbursements, inspect unmatched receiving reports, inspect vendor statements.", category: "Audit" },
  { q: "How would you test inventory existence?", a: "Attend and observe physical count. Test count sheets to actual inventory and vice versa.", category: "Audit" },
  { q: "Why is revenue high-risk?", a: "Key performance metric, susceptible to manipulation, complex timing/measurement, often presumed fraud risk.", category: "Audit" },
  { q: "What is cut-off testing?", a: "Verifying transactions are recorded in the correct period. Critical for revenue and inventory around year-end.", category: "Audit" },
  { q: "What is the fraud triangle?", a: "Incentive/pressure + opportunity + rationalization. Explains why fraud risk increases in certain environments.", category: "Audit" },
  { q: "Error vs fraud?", a: "Error: unintentional misstatement. Fraud: intentional misstatement to deceive. Both can cause material misstatement.", category: "Audit" },
  { q: "What is management bias?", a: "Estimates persistently biased in one direction — optimistic allowances, delayed impairment, aggressive forecasts.", category: "Audit" },
  { q: "What is a subsequent event?", a: "Event after period-end. Type 1: evidence of year-end conditions (adjust). Type 2: new condition (disclose only).", category: "Audit" },
  { q: "What is going concern?", a: "Whether entity can continue operating. Auditor evaluates: recurring losses, debt defaults, liquidity issues.", category: "Audit" },
  { q: "What is analytical procedures?", a: "Evaluating financial info through analysis of plausible relationships. Used in planning, testing, and final review.", category: "Audit" },
  { q: "What is sampling risk?", a: "Risk that conclusions from a sample differ from conclusions if the entire population were tested.", category: "Audit" },
  { q: "What is a walkthrough?", a: "Tracing a transaction through the entire process to understand where errors can occur and where controls operate.", category: "Audit" },
  { q: "What are internal controls?", a: "System providing reasonable assurance on: reliable reporting, efficient operations, legal compliance.", category: "Audit" },
  { q: "What is segregation of duties?", a: "Separating authorization, custody, and recording functions to prevent fraud. Key preventive control.", category: "Audit" },
  { q: "What is a management representation letter?", a: "Written confirmation from management about statements and disclosures. Required but not sufficient evidence alone.", category: "Audit" },
  { q: "What makes confirmations unreliable?", a: "Wrong addresses, management interception, customer doesn't verify carefully, outdated balances.", category: "Audit" },
  // BEHAVIORAL (20)
  { q: "Why accounting?", a: "Translates complex business activity into structured, decision-useful information. Combines structure, analysis, and responsibility.", category: "Behavioral" },
  { q: "Why audit?", a: "Develops accounting judgment, broad industry exposure, analytical thinking + skepticism, strong career foundation.", category: "Behavioral" },
  { q: "Why this firm?", a: "Training environment, culture, client base, industry exposure, people you've spoken with. Be specific, not generic.", category: "Behavioral" },
  { q: "Tell me about a time you caught an error.", a: "STAR: context, identification, verification steps, impact, attention to detail demonstrated.", category: "Behavioral" },
  { q: "What if client explanation doesn't match evidence?", a: "Maintain skepticism, seek corroborating evidence, discuss with senior, expand testing. Resolve with evidence.", category: "Behavioral" },
  { q: "What if you found an error late in the audit?", a: "Escalate to senior/manager immediately. Assess materiality. Document findings. Don't ignore or bury it.", category: "Behavioral" },
  { q: "How do you handle repetitive work?", a: "Show maturity. Building skills requires repetition. Focus on accuracy and learning from patterns.", category: "Behavioral" },
  { q: "Tell me about teamwork.", a: "Show collaboration, communication, taking feedback, asking questions, reliability under pressure.", category: "Behavioral" },
  { q: "What is your greatest strength?", a: "Pick something relevant: attention to detail, organization, analytical thinking. Back with specific example.", category: "Behavioral" },
  { q: "Tell me about yourself.", a: "Present → relevant experiences → what you learned → why accounting/audit. Concise and directed.", category: "Behavioral" },
];
