import { Flashcard } from './ib-flashcard-data';
export const AM_FLASHCARDS: Flashcard[] = [
  // FOUNDATIONS (20)
  { q: "What is asset management?", a: "Professional management of capital to achieve specific return and risk outcomes over a defined time horizon for clients/institutions.", category: "Foundations" },
  { q: "Good business vs good investment?", a: "A great business can be poor if overpriced. A mediocre business can be good if expectations are too low. Price vs value.", category: "Foundations" },
  { q: "What is variant perception?", a: "A view that is both different from consensus and correct often enough to matter. The source of alpha.", category: "Foundations" },
  { q: "How does AM differ from banking?", a: "AM: disciplined capital allocation, portfolio construction, benchmark-relative performance. Banking: transactions, advisory, capital raising.", category: "Foundations" },
  { q: "How does AM differ from hedge funds?", a: "AM: usually benchmark-aware, longer horizon, constrained mandates. HF: more flexible, shorter horizon, leverage, absolute return.", category: "Foundations" },
  { q: "What are sources of edge?", a: "Superior analysis, better industry knowledge, longer horizon, behavioral discipline, better portfolio construction, better risk management.", category: "Foundations" },
  { q: "What is process over prediction?", a: "Consistently good process matters more than pretending to forecast every data point. Discipline beats brilliance.", category: "Foundations" },
  { q: "What is the institutional investment process?", a: "Universe → idea gen → research → valuation → risk analysis → portfolio fit → decision → monitoring → exit discipline.", category: "Foundations" },
  { q: "Active vs passive investing?", a: "Active aims to outperform through selection/timing. Passive replicates an index. Active requires edge to justify fees.", category: "Foundations" },
  { q: "What are the core investor questions?", a: "1) What is it worth? 2) What is priced in? 3) Why is market wrong? 4) Catalyst? 5) Key risks? 6) Portfolio fit?", category: "Foundations" },
  // MARKETS & ASSET CLASSES (25)
  { q: "What drives equity returns?", a: "Earnings growth, multiple expansion/contraction, dividends/buybacks, balance sheet changes, discount rate shifts.", category: "Markets" },
  { q: "What drives bond prices?", a: "Interest rates, inflation expectations, credit spreads, duration, convexity, default risk, liquidity.", category: "Markets" },
  { q: "Why do discount rates matter?", a: "Every asset's price depends on discounting future cash flows. Rising rates hurt long-duration assets most.", category: "Markets" },
  { q: "What is a benchmark?", a: "Reference portfolio for measuring active performance. Shapes sector weights, tracking error, risk budget.", category: "Markets" },
  { q: "What is market efficiency?", a: "Prices reflect information quickly. Active opportunities come from behavioral biases, complexity, forced flows, horizon differences.", category: "Markets" },
  { q: "What role does cash play in portfolios?", a: "Liquidity reserve, tactical allocation, benchmark-relative choice, optionality in volatile markets. Holding cash is an active decision.", category: "Markets" },
  { q: "How do higher rates affect equities?", a: "Increase discount rates → lower PV of cash flows. Compress multiples. Hurt long-duration/growth stocks most.", category: "Markets" },
  { q: "What is credit spread?", a: "Yield premium over risk-free rate compensating for default risk, liquidity, etc. Widening signals stress.", category: "Markets" },
  { q: "What is duration?", a: "Measure of interest rate sensitivity. Longer duration = more price sensitivity to rate changes.", category: "Markets" },
  { q: "Why does a stock rise?", a: "Not because earnings are good absolutely — because outcomes are better than what was priced in, or multiples expand.", category: "Markets" },
  // FUNDAMENTAL ANALYSIS (30)
  { q: "How do you analyze a business model?", a: "What does it sell? Who pays? Why? What drives volume/price/mix? Major costs? What's defensible or vulnerable?", category: "Analysis" },
  { q: "What are revenue drivers?", a: "Units × price, customers × spend, subscribers × ARPU, transactions × take rate, assets × fee rate.", category: "Analysis" },
  { q: "Why do margins matter?", a: "Reveal pricing power, scale benefits, input sensitivity, operating leverage, quality of growth.", category: "Analysis" },
  { q: "What is ROIC?", a: "Return on Invested Capital. Growth only creates value if ROIC > cost of capital.", category: "Analysis" },
  { q: "Why do returns on capital matter?", a: "High-ROIC businesses compound value faster when reinvesting. Growth without returns destroys value.", category: "Analysis" },
  { q: "What is free cash flow conversion?", a: "How much of earnings turns into cash. Weak conversion (rising AR, heavy CapEx) is a red flag.", category: "Analysis" },
  { q: "Why does balance sheet matter?", a: "A great business model can still create bad investment if leverage, liquidity, or refinancing risk is severe.", category: "Analysis" },
  { q: "What is operating leverage?", a: "High fixed costs: revenue growth drives disproportionate profit growth (or decline). Amplifies both up and down.", category: "Analysis" },
  { q: "What are red flags in analysis?", a: "Revenue growth with deteriorating cash flow, repeated one-time adjustments, weak balance sheet hidden by adjusted metrics, opaque disclosures.", category: "Analysis" },
  { q: "How do you evaluate management?", a: "Capital allocation track record, incentive alignment, M&A discipline, buyback timing, operational execution, candor.", category: "Analysis" },
  { q: "What is competitive advantage?", a: "Sustainable edge: brand, scale, network effects, switching costs, IP, regulatory barriers, cost leadership.", category: "Analysis" },
  { q: "What is industry structure?", a: "Rivalry, entry barriers, substitutes, buyer/supplier power. Great teams can struggle in structurally poor industries.", category: "Analysis" },
  { q: "What is pricing power?", a: "Ability to raise prices without losing customers. Sign of competitive strength and margin durability.", category: "Analysis" },
  { q: "Recurring vs transactional revenue?", a: "Recurring (subscriptions, contracts) is more predictable and valuable. Transactional is lumpier and less certain.", category: "Analysis" },
  { q: "What is asset-light vs capital-intensive?", a: "Asset-light: low CapEx, high returns (software). Capital-intensive: heavy CapEx, assets drive revenue (manufacturing).", category: "Analysis" },
  // VALUATION (25)
  { q: "What is intrinsic vs relative value?", a: "Intrinsic = DCF-based worth from cash flows. Relative = comparison to peer multiples. Triangulate both.", category: "Valuation" },
  { q: "What is margin of safety?", a: "Buying with enough cushion that even if assumptions are wrong, downside is limited vs upside.", category: "Valuation" },
  { q: "Common valuation methods?", a: "DCF, trading comps, sum-of-parts, DDM, NAV, replacement cost, depending on business type.", category: "Valuation" },
  { q: "How do AM professionals use DCF?", a: "Less for precision, more to understand what assumptions are embedded in price and whether differentiated view matters.", category: "Valuation" },
  { q: "What is FCF yield?", a: "Free Cash Flow / Market Cap (or EV). Measures cash return on price paid. Higher = cheaper.", category: "Valuation" },
  { q: "Why can cheap stocks be dangerous?", a: "Value traps: deteriorating industry, leverage, governance, no catalyst, earnings collapse. Cheap isn't enough.", category: "Valuation" },
  { q: "How do you reverse-engineer expectations?", a: "What growth, margin, ROIC does current multiple imply? Is reality likely better or worse than implied?", category: "Valuation" },
  { q: "What is EV/EBITDA?", a: "Enterprise Value / EBITDA. Capital-structure neutral, widely used for comparing companies.", category: "Valuation" },
  { q: "Why can P/E be misleading?", a: "Affected by capital structure, non-operating items, tax differences, accounting distortions.", category: "Valuation" },
  { q: "How do you value a bank?", a: "P/Book, P/E, ROTCE-based. Traditional DCF/EV-EBITDA less useful since debt is operational.", category: "Valuation" },
  { q: "How do you value a REIT?", a: "FFO/AFFO multiples, cap rates, NAV. Depreciation overstates expense for real estate.", category: "Valuation" },
  { q: "What is growth-duration sensitivity?", a: "High-growth = long-duration asset. More value in distant future → more sensitive to discount rate changes.", category: "Valuation" },
  // PORTFOLIO CONSTRUCTION (20)
  { q: "Why does portfolio construction matter?", a: "Can be right on ideas but underperform due to poor sizing, concentration, factor exposure, or benchmark mismatch.", category: "Portfolio" },
  { q: "How would you size a position?", a: "Conviction, downside risk, balance sheet, correlation with holdings, liquidity, benchmark context, catalyst visibility.", category: "Portfolio" },
  { q: "What is true diversification?", a: "Not just many names — diversity across sectors, factors, business models, geographies, durations.", category: "Portfolio" },
  { q: "Concentrated vs diversified?", a: "Concentrated: more upside if right, more downside if wrong. Diversified: lower idiosyncratic risk. Right level depends on edge and mandate.", category: "Portfolio" },
  { q: "What is tracking error?", a: "Volatility of excess return vs benchmark. Measures how much active risk.", category: "Portfolio" },
  { q: "What is active share?", a: "How different portfolio is from benchmark by holdings. Higher = more differentiated.", category: "Portfolio" },
  { q: "What types of risk exist?", a: "Business, valuation, balance sheet, liquidity, factor, macro, currency, duration, regulatory, thesis, behavioral risk.", category: "Portfolio" },
  { q: "Is volatility = risk?", a: "Volatility is a proxy but true risk = permanent capital impairment, forced selling, inability to meet liabilities.", category: "Portfolio" },
  { q: "What is sell discipline?", a: "Thesis broken, price ≥ fair value, better opportunity, risk-reward deteriorated, portfolio needs rebalance.", category: "Portfolio" },
  { q: "What is capacity?", a: "How much capital a strategy absorbs before edge deteriorates. $10M idea may fail at $10B.", category: "Portfolio" },
  // STOCK PITCH (15)
  { q: "Walk me through a stock pitch.", a: "1) Recommendation, 2) Business overview, 3) Why market is wrong, 4) Valuation, 5) Catalysts, 6) Risks.", category: "Stock Pitch" },
  { q: "What makes a pitch weak?", a: "Good business + no valuation. Valuation + no thesis. Thesis + no catalyst. Upside only. No consensus awareness.", category: "Stock Pitch" },
  { q: "What is a catalyst?", a: "Event that causes the market to close the gap between price and value: earnings, product cycle, M&A, deleveraging.", category: "Stock Pitch" },
  { q: "How do you handle pushback?", a: "Don't get defensive. Show you've considered opposing views. Acknowledge risks. Defend with evidence.", category: "Stock Pitch" },
  { q: "Long vs short pitch?", a: "Long: market underestimates upside. Short: market overestimates durability/growth. Short requires stronger timing discipline.", category: "Stock Pitch" },
  { q: "How do you compare two stocks?", a: "Business quality, valuation, balance sheet, catalyst path, expected return distribution, portfolio fit.", category: "Stock Pitch" },
  { q: "What is downside analysis?", a: "Bear case assumptions, balance sheet risk, margin pressure, multiple downside, thesis invalidation. Think about losses before gains.", category: "Stock Pitch" },
  // MACRO (15)
  { q: "Why does macro matter for bottom-up investors?", a: "Macro affects discount rates, demand, credit conditions, earnings, valuations, currency, sector leadership.", category: "Macro" },
  { q: "How does inflation affect businesses differently?", a: "Companies with pricing power pass it through. Those without see margin compression. Input costs, labor, etc.", category: "Macro" },
  { q: "What do credit spreads tell you?", a: "Widening = stress, tightening financial conditions, risk-off. Credit often leads equity signals.", category: "Macro" },
  { q: "What is top-down vs bottom-up?", a: "Top-down: start with macro/sectors. Bottom-up: start with companies. Best investors integrate both.", category: "Macro" },
  { q: "How do different regimes favor different exposures?", a: "Falling rates → growth/duration. Strong growth → cyclicals/value. Recession → defensives/quality/duration (depends on inflation).", category: "Macro" },
  // PERFORMANCE (10)
  { q: "What is alpha?", a: "Return beyond benchmark/factor exposure. True security selection skill, net of factor bets and luck.", category: "Performance" },
  { q: "Sharpe vs information ratio?", a: "Sharpe: return per total vol. IR: excess return per tracking error. IR measures active management efficiency.", category: "Performance" },
  { q: "What is attribution analysis?", a: "Decomposing returns: sector allocation, security selection, factor exposure, currency. Explains where performance came from.", category: "Performance" },
  { q: "Gross vs net returns?", a: "Gross ignores costs. Net includes commissions, spreads, impact, taxes. Strategies must survive real implementation.", category: "Performance" },
  { q: "How should a manager discuss underperformance?", a: "Honestly. Was it bad process or temporary headwind? Show accountability and evidence the process remains sound.", category: "Performance" },
  // BEHAVIORAL (15)
  { q: "Why asset management?", a: "Business analysis + valuation + psychology + decision-making under uncertainty. Accountable for outcomes. Independent thinking + discipline.", category: "Behavioral" },
  { q: "How do you think about risk?", a: "Probability and severity of permanent capital loss. Includes leverage, liquidity, factor concentration, thesis risk. Not just vol.", category: "Behavioral" },
  { q: "Tell me about changing your mind on an investment.", a: "Show humility, evidence-based adaptation, no ego attachment. Good investors revise when facts change.", category: "Behavioral" },
  { q: "What is your investment philosophy?", a: "Be genuine. Value vs growth vs quality? Concentrated vs diversified? What edge do you believe in?", category: "Behavioral" },
  { q: "What do you think about the market right now?", a: "Frame regime (growth, inflation, rates). What matters most. What's priced in. Positioning implications. Not just headlines.", category: "Behavioral" },
  { q: "What makes a stock cheap?", a: "Not just low multiple. Cheap if price understates conservative future value and implied expectations are too pessimistic.", category: "Behavioral" },
  { q: "Tell me about yourself.", a: "Academic foundation → market interest → relevant experience → why AM is natural next step. Sound like an investor.", category: "Behavioral" },
  { q: "How would you build a portfolio?", a: "Mandate/benchmark → objective/risk budget → best ideas with diversification → sizing by conviction and risk → monitoring → sell discipline.", category: "Behavioral" },
  { q: "What would make you sell a winner?", a: "Price reaches/exceeds fair value, better opportunity elsewhere, thesis changes, risk-reward deteriorates.", category: "Behavioral" },
  { q: "What would make you add to a loser?", a: "Only if thesis intact, price more attractive, and risk is manageable. Never average into denial.", category: "Behavioral" },
  // ═══ ADDITIONAL ANALYSIS (40) ═══
  {q:"What is a DuPont analysis?",a:"Decomposes ROE into: profit margin × asset turnover × equity multiplier. Shows whether returns come from margins, efficiency, or leverage.",category:"Analysis"},
  {q:"What is working capital intensity?",a:"WC as % of revenue. Low intensity = less cash tied up. Negative WC (deferred revenue businesses) is favorable.",category:"Analysis"},
  {q:"What is CapEx intensity?",a:"CapEx / Revenue. High intensity means more reinvestment required, less FCF conversion from EBITDA.",category:"Analysis"},
  {q:"What is the reinvestment rate?",a:"(CapEx - D&A + ΔWC) / NOPAT. How much of earnings must be reinvested. Lower = more cash available for shareholders.",category:"Analysis"},
  {q:"What is incremental ROIC?",a:"Change in NOPAT / change in invested capital. Shows return on new capital deployed. More forward-looking than average ROIC.",category:"Analysis"},
  {q:"What is the difference between gross and net debt?",a:"Gross = total debt. Net = total debt minus cash. Net debt is more relevant for leverage and EV calculations.",category:"Analysis"},
  {q:"What is debt maturity profile?",a:"Schedule of when debt comes due. Concentrated maturities create refinancing risk. Staggered is healthier.",category:"Analysis"},
  {q:"What is a credit rating?",a:"Assessment of default risk by agencies (S&P, Moody's, Fitch). Investment grade (BBB-/Baa3+) vs high yield.",category:"Analysis"},
  {q:"What is interest coverage?",a:"EBITDA / Interest. Measures ability to service debt. Below 2x is concerning. Critical for leveraged companies.",category:"Analysis"},
  {q:"What is the payout ratio?",a:"Dividends / Net Income. Shows how much earnings are returned vs retained. Sustainable if consistent with FCF.",category:"Analysis"},
  {q:"What is dividend yield?",a:"Annual dividend / share price. Income metric. High yield can signal value or distress — must investigate.",category:"Analysis"},
  {q:"What is a share buyback yield?",a:"Value of shares repurchased / market cap. Combined with dividend yield = total shareholder yield.",category:"Analysis"},
  {q:"What is total shareholder return (TSR)?",a:"Capital appreciation + dividends over a period. The complete return to equity holders.",category:"Analysis"},
  {q:"What is economic value added (EVA)?",a:"NOPAT - (Invested Capital × WACC). Positive EVA = company creates value above cost of capital.",category:"Analysis"},
  {q:"What is a quality screen?",a:"Filtering for high ROIC, stable margins, low leverage, strong cash conversion, consistent earnings. Identifies high-quality businesses.",category:"Analysis"},
  {q:"What is a value trap?",a:"Stock that looks cheap but keeps getting cheaper. Deteriorating business, structural decline, or governance issues.",category:"Analysis"},
  {q:"What is earnings yield?",a:"EPS / Price (inverse of P/E). Useful for comparing to bond yields and assessing relative value.",category:"Analysis"},
  {q:"What is the equity risk premium?",a:"Extra return investors demand for stocks over risk-free bonds. Historically ~5-6%. Varies with market conditions.",category:"Analysis"},
  {q:"What is a factor model?",a:"Decomposes returns into systematic factors: market, value, size, momentum, quality, volatility. Identifies what drives returns.",category:"Analysis"},
  {q:"What is smart beta?",a:"Index strategies weighted by factors (value, quality, low vol) rather than market cap. Between pure passive and active.",category:"Analysis"},
  {q:"What is ESG investing?",a:"Environmental, Social, Governance factors in investment decisions. Growing mandate constraint. Debate on alpha vs values.",category:"Analysis"},
  {q:"How do you analyze a bank?",a:"NIM, credit quality (NPLs, provisions), capital ratios (CET1), ROE, efficiency ratio. Different from industrial companies.",category:"Analysis"},
  {q:"How do you analyze an insurance company?",a:"Combined ratio, loss ratio, investment income, reserve adequacy, capital strength. Underwriting + investing.",category:"Analysis"},
  {q:"How do you analyze a REIT?",a:"FFO/AFFO, cap rates, occupancy, NOI growth, NAV premium/discount, leverage, dividend coverage.",category:"Analysis"},
  {q:"How do you analyze a commodity producer?",a:"Cost curve position, reserve quality, capital discipline, balance sheet, commodity price sensitivity.",category:"Analysis"},
  {q:"What is channel stuffing?",a:"Shipping excess product to distributors to inflate revenue. Red flag: revenue growth without corresponding sell-through.",category:"Analysis"},
  {q:"What is cookie jar reserves?",a:"Over-accruing reserves in good years and releasing in bad years to smooth earnings. Manipulation concern.",category:"Analysis"},
  {q:"What is bill-and-hold revenue?",a:"Recording revenue before shipping. Can be legitimate but is a common fraud mechanism. Requires scrutiny.",category:"Analysis"},
  {q:"What is same-store sales growth?",a:"Revenue growth from locations open at least a year. Strips out new store effects. Shows organic health.",category:"Analysis"},
  {q:"What is organic vs inorganic growth?",a:"Organic: internal growth. Inorganic: M&A-driven. Organic is generally more sustainable and higher quality.",category:"Analysis"},
  // ═══ ADDITIONAL VALUATION (25) ═══
  {q:"What is a normalized earnings approach?",a:"Adjust for cyclicality, one-time items, and unsustainable factors to estimate mid-cycle earning power. Better for cyclicals.",category:"Valuation"},
  {q:"What is replacement cost valuation?",a:"What it would cost to recreate the business from scratch. Provides a floor. Used for asset-heavy industries.",category:"Valuation"},
  {q:"What is a private market valuation?",a:"What PE or strategic buyers have paid for similar assets. Can reveal discount between public and private markets.",category:"Valuation"},
  {q:"What is EV/invested capital?",a:"Compares market value to capital employed. Premium to 1x suggests market expects returns above cost of capital.",category:"Valuation"},
  {q:"What is a cap rate?",a:"NOI / property value. Used for real assets. Lower cap rate = higher valuation relative to income.",category:"Valuation"},
  {q:"What is a dividend discount model?",a:"Equity value = PV of future dividends. Gordon Growth: P = D₁ / (r - g). Best for mature, stable dividend payers.",category:"Valuation"},
  {q:"What is a two-stage DDM?",a:"High growth for n years, then stable growth forever. More realistic than perpetual constant growth.",category:"Valuation"},
  {q:"What is implied growth rate?",a:"Growth rate embedded in current valuation. Reverse-engineer from P/E or DCF. Check if realistic.",category:"Valuation"},
  {q:"What is justified P/E?",a:"P/E = payout ratio / (r - g). Links P/E to fundamentals: growth, cost of equity, and payout. Not arbitrary.",category:"Valuation"},
  {q:"What is the EV/EBITDA vs P/E relationship?",a:"EV/EBITDA is pre-leverage, pre-D&A. P/E is post-everything. EV/EBITDA better for comparing across capital structures.",category:"Valuation"},
  {q:"When would you use EV/Revenue?",a:"Unprofitable companies, early-stage, high growth. Also useful when margins are expected to change significantly.",category:"Valuation"},
  {q:"What is a breakup value?",a:"SOTP value if company were split into pieces. If > trading value, suggests conglomerate discount exists.",category:"Valuation"},
  {q:"What is a scarcity premium?",a:"Higher multiple for assets that are rare, hard to replicate, or have limited comparable opportunities.",category:"Valuation"},
  {q:"Why do growth stocks trade at higher multiples?",a:"More future value relative to current earnings. Longer duration = more sensitive to rates but higher potential.",category:"Valuation"},
  {q:"What is multiple compression?",a:"When a stock's valuation multiple declines. Can happen from rising rates, slowing growth, or shifting sentiment.",category:"Valuation"},
  // ═══ ADDITIONAL PORTFOLIO (20) ═══
  {q:"What is a factor tilt?",a:"Intentional portfolio bias toward a factor (value, momentum, quality). May be by design or unintentional.",category:"Portfolio"},
  {q:"What is style drift?",a:"Manager deviating from stated investment style. Growth manager buying deep value stocks. Concerning for clients.",category:"Portfolio"},
  {q:"What is rebalancing?",a:"Periodically adjusting portfolio back to target weights. Contrarian by nature — trim winners, add losers.",category:"Portfolio"},
  {q:"What is a core-satellite approach?",a:"Core: passive/index allocation. Satellite: active positions for alpha. Balances cost efficiency with alpha potential.",category:"Portfolio"},
  {q:"What is tax-loss harvesting?",a:"Selling losing positions to realize capital losses, offsetting gains. Improves after-tax returns.",category:"Portfolio"},
  {q:"What is a risk budget?",a:"Allocating tracking error or active risk across positions/sectors. Ensures risk is taken intentionally.",category:"Portfolio"},
  {q:"What is correlation risk?",a:"Risk that correlations spike during stress, reducing diversification benefit exactly when you need it most.",category:"Portfolio"},
  {q:"What is crowding risk?",a:"Many investors in the same positions. If they exit simultaneously, forced selling amplifies losses.",category:"Portfolio"},
  {q:"What is a stop-loss?",a:"Pre-set level to sell a losing position. Limits downside but can trigger in temporary volatility.",category:"Portfolio"},
  {q:"What is position-level vs portfolio-level risk?",a:"Individual stock risk vs aggregate portfolio behavior. Diversification means portfolio risk < sum of position risks.",category:"Portfolio"},
  {q:"What is a barbell strategy?",a:"Concentrating in extremes (very safe + very risky) and avoiding the middle. Used in bonds and equities.",category:"Portfolio"},
  {q:"What is tactical asset allocation?",a:"Short-term deviations from strategic allocation based on market views. Must add value net of costs and timing risk.",category:"Portfolio"},
  {q:"What is strategic asset allocation?",a:"Long-term target mix of asset classes based on risk tolerance, return objectives, and time horizon.",category:"Portfolio"},
  // ═══ ADDITIONAL MACRO (15) ═══
  {q:"What is the yield curve telling you?",a:"Shape reflects growth and rate expectations. Steep = growth optimism. Flat/inverted = slowing expectations or tight policy.",category:"Macro"},
  {q:"What is quantitative tightening?",a:"Central bank reducing balance sheet by not reinvesting maturing bonds. Tightens financial conditions.",category:"Macro"},
  {q:"What is the output gap?",a:"Difference between actual and potential GDP. Positive = overheating (inflation). Negative = slack (disinflation).",category:"Macro"},
  {q:"What is the Phillips curve?",a:"Inverse relationship between unemployment and inflation. Has weakened in recent decades but still relevant framework.",category:"Macro"},
  {q:"What is the neutral rate (r*)?",a:"Interest rate neither stimulating nor restraining economy. Unobservable — estimated. Guides central bank policy.",category:"Macro"},
  {q:"What is a risk-off trade?",a:"Selling risky assets (equities, HY credit) and buying safe havens (Treasuries, gold, yen). Flight to quality.",category:"Macro"},
  {q:"What are leading vs lagging indicators?",a:"Leading: predict future activity (PMI, yield curve, building permits). Lagging: confirm trends (unemployment, CPI).",category:"Macro"},
  {q:"What is PMI?",a:"Purchasing Managers' Index. Above 50 = expansion, below 50 = contraction. Leading indicator of economic activity.",category:"Macro"},
  {q:"How does a strong dollar affect US multinationals?",a:"Reduces foreign revenue when translated back. Hurts competitiveness. Benefits importers. Headwind for EM.",category:"Macro"},
  {q:"What is stagflation?",a:"High inflation + low growth + high unemployment. Worst combination for policymakers. Limits both fiscal and monetary tools.",category:"Macro"},
  {q:"What is fiscal policy vs monetary policy?",a:"Fiscal: government spending and taxation. Monetary: central bank rates and balance sheet. Both affect growth and inflation.",category:"Macro"},
  // ═══ ADDITIONAL STOCK PITCH (15) ═══
  {q:"How do you identify what consensus expects?",a:"Sell-side estimates, implied multiples, management guidance, earnings call sentiment, buy-side positioning surveys.",category:"Stock Pitch"},
  {q:"What is an asymmetric risk/reward?",a:"Upside potential significantly exceeds downside risk. Example: 50% upside, 15% downside. The best investment setups.",category:"Stock Pitch"},
  {q:"How do you build a bear case?",a:"Identify what goes wrong: margin compression, competitive threats, macro headwinds, balance sheet stress, multiple contraction.",category:"Stock Pitch"},
  {q:"How do you build a bull case?",a:"Identify upside drivers: accelerating growth, margin expansion, capital return, positive revisions, re-rating.",category:"Stock Pitch"},
  {q:"What is a base/bull/bear probability weighting?",a:"Assign probabilities to scenarios. Expected value = Σ(probability × return). Shows discipline vs single-point forecasting.",category:"Stock Pitch"},
  {q:"How do you defend against 'why not the competitor instead?'",a:"Compare business quality, valuation, balance sheet, catalyst path, and risk-reward. Show you considered alternatives.",category:"Stock Pitch"},
  {q:"What is a short pitch?",a:"Thesis that stock is overvalued. Must identify: what expectations are too high, catalyst for disappointment, timing, squeeze risk.",category:"Stock Pitch"},
  {q:"What is a pair trade pitch?",a:"Long one stock, short a related one. Express a relative view. Market-neutral if balanced.",category:"Stock Pitch"},
  // ═══ ADDITIONAL PERFORMANCE (10) ═══
  {q:"What is the Sortino ratio?",a:"Return / downside deviation. Better than Sharpe because it only penalizes harmful volatility (below target).",category:"Performance"},
  {q:"What is max drawdown?",a:"Largest peak-to-trough decline. Shows worst-case experienced loss. Critical for risk-averse clients.",category:"Performance"},
  {q:"What is the Calmar ratio?",a:"Annualized return / max drawdown. Measures return relative to worst experienced loss.",category:"Performance"},
  {q:"What is batting average?",a:"% of periods beating the benchmark. Measures consistency of outperformance.",category:"Performance"},
  {q:"What is up-capture vs down-capture?",a:"Up-capture: % of benchmark gains captured. Down-capture: % of benchmark losses experienced. Want high up, low down.",category:"Performance"},
  {q:"What is style analysis?",a:"Decomposing returns into factor exposures (value, growth, size) to determine what's driving performance.",category:"Performance"},
  {q:"What is net exposure?",a:"Long % - Short %. 100% net long = fully invested long-only. 0% = market neutral.",category:"Performance"},
  {q:"What is gross exposure?",a:"Long % + Short %. 150% gross = leveraged. Shows total capital deployed.",category:"Performance"},
  // ═══ ADDITIONAL BEHAVIORAL (15) ═══
  {q:"Describe your investment research process.",a:"Idea generation → business analysis → valuation → thesis development → risk assessment → portfolio fit → monitoring.",category:"Behavioral"},
  {q:"What book about investing has influenced you most?",a:"Pick one you actually read. Explain the key takeaway and how it shaped your thinking. Show intellectual curiosity.",category:"Behavioral"},
  {q:"How do you handle being wrong on an investment?",a:"Acknowledge it, analyze what went wrong (thesis error, timing, external shock), learn from it, adjust process.",category:"Behavioral"},
  {q:"What is behavioral finance?",a:"Study of psychological biases affecting investment decisions: anchoring, loss aversion, herding, overconfidence, recency.",category:"Behavioral"},
  {q:"What is confirmation bias?",a:"Seeking information that confirms existing beliefs while ignoring contradictory evidence. Dangerous for investors.",category:"Behavioral"},
  {q:"What is anchoring bias?",a:"Over-relying on first piece of information (initial price, analyst target). Can prevent updating views with new data.",category:"Behavioral"},
  {q:"What is loss aversion?",a:"Pain of losses exceeds pleasure of equal gains (~2x). Causes investors to hold losers too long and sell winners too early.",category:"Behavioral"},
  {q:"What is herding?",a:"Following the crowd. Feels safe but creates crowded trades and amplifies booms/busts.",category:"Behavioral"},
  {q:"What is the disposition effect?",a:"Tendency to sell winners too early (lock in gains) and hold losers too long (avoid realizing losses).",category:"Behavioral"},
  {q:"What is recency bias?",a:"Overweighting recent events. After a crash, investors are too cautious. After a boom, too aggressive.",category:"Behavioral"},
  {q:"How do you manage your own biases?",a:"Written process, pre-mortems, devil's advocate, checklist discipline, journaling decisions and reasoning.",category:"Behavioral"},
];

