import { Flashcard } from './ib-flashcard-data';
export const AM_FLASHCARDS: Flashcard[] = [
  { q: "What is asset management?", a: "Professional management of capital on behalf of clients/institutions to achieve specific return and risk outcomes over a defined time horizon.", category: "Foundations" },
  { q: "What is the difference between a good business and a good investment?", a: "A great business can be a poor investment if overpriced. A mediocre business can be a good investment if expectations are too low. Price vs value is what matters.", category: "Foundations" },
  { q: "What is variant perception?", a: "Having a view that is both different from market consensus and correct often enough to matter. The source of alpha for active managers.", category: "Foundations" },
  { q: "What drives equity returns over time?", a: "Earnings growth, multiple expansion/contraction, dividends and buybacks, balance sheet changes, and shifts in discount rates.", category: "Markets" },
  { q: "What drives bond prices?", a: "Interest rates, inflation expectations, credit spreads, duration, convexity, default risk, and liquidity.", category: "Markets" },
  { q: "Why do discount rates matter across asset classes?", a: "Every asset's price depends on discounting future cash flows. Rising rates hurt long-duration assets most, compress equity multiples, and lower bond prices.", category: "Markets" },
  { q: "What is a benchmark?", a: "A reference portfolio (S&P 500, MSCI World, etc.) against which active manager performance is measured. Shapes sector weights, tracking error, and risk budget.", category: "Markets" },
  { q: "What is market efficiency?", a: "Idea that prices reflect available information quickly. Active management exploits imperfections from behavioral biases, complexity, forced flows, and time horizon mismatches.", category: "Markets" },
  { q: "How do you analyze a business model?", a: "Ask: What does it sell? Who pays? Why do customers buy? What drives volume/price/mix? What are major costs? What makes it defensible or vulnerable?", category: "Analysis" },
  { q: "Why do returns on capital matter?", a: "Growth only creates value if ROIC exceeds cost of capital. High-ROIC businesses compound value faster when reinvesting.", category: "Analysis" },
  { q: "What is free cash flow conversion?", a: "How much of earnings actually turns into cash. Weak conversion (rising AR, heavy CapEx, inventory builds) is a red flag.", category: "Analysis" },
  { q: "What is margin of safety?", a: "Buying with enough valuation cushion that even if assumptions are wrong, downside is limited relative to upside.", category: "Valuation" },
  { q: "What is intrinsic vs relative value?", a: "Intrinsic = DCF-based worth from cash flows. Relative = comparison to peer multiples. Best to triangulate both.", category: "Valuation" },
  { q: "Why can a cheap stock still be dangerous?", a: "Value traps: deteriorating industry, leverage, governance issues, no catalyst, or earnings collapse. Valuation is necessary but not sufficient.", category: "Valuation" },
  { q: "How do you reverse-engineer expectations?", a: "Ask: What growth is implied by the current multiple? What margins? What ROIC? Then assess if reality is likely better or worse than implied.", category: "Valuation" },
  { q: "What is portfolio construction?", a: "Translating ideas into a portfolio: sizing positions by conviction and risk, diversifying across factors, managing benchmark and liquidity constraints.", category: "Portfolio" },
  { q: "How would you size a position?", a: "Based on conviction, downside risk, balance sheet strength, correlation with existing holdings, liquidity, and contribution to portfolio-level risk.", category: "Portfolio" },
  { q: "What is true diversification?", a: "Not just many names — it's exposure diversity across sectors, factors, business models, geographies, and durations.", category: "Portfolio" },
  { q: "What is tracking error?", a: "Volatility of excess return vs benchmark. Measures how much active risk the manager is taking.", category: "Portfolio" },
  { q: "What is alpha?", a: "Return beyond what's explained by benchmark/factor exposure. True security selection skill, net of factor bets and luck.", category: "Performance" },
  { q: "What is information ratio?", a: "Excess return / tracking error. Measures efficiency of active risk-taking relative to benchmark.", category: "Performance" },
  { q: "What is attribution analysis?", a: "Decomposing returns into sector allocation, security selection, factor exposure, and other sources. Explains where performance came from.", category: "Performance" },
  { q: "Walk me through a stock pitch.", a: "1) Recommendation, 2) Business overview, 3) Why market is wrong, 4) Valuation, 5) Catalysts, 6) Risks. Always discuss downside.", category: "Stock Pitch" },
  { q: "What makes a stock pitch weak?", a: "Good business with no valuation. Valuation with no thesis. Thesis with no catalyst. Upside only, no downside. No understanding of consensus.", category: "Stock Pitch" },
  { q: "Why asset management?", a: "Combines business analysis, valuation, psychology, and decision-making under uncertainty. Accountable for outcomes. Requires independent thinking and discipline.", category: "Behavioral" },
  { q: "How do you think about risk?", a: "Probability and severity of permanent capital impairment, not just volatility. Includes leverage, liquidity, factor concentration, and thesis risk.", category: "Behavioral" },
  { q: "Tell me about a time you changed your mind on an investment.", a: "Show humility, evidence-based adaptation, and no ego attachment to ideas. Good investors revise views when facts change.", category: "Behavioral" },
];
