import { Flashcard } from './ib-flashcard-data';
export const CONSULTING_FLASHCARDS: Flashcard[] = [
  // FRAMEWORKS (30)
  { q: "What is the MECE principle?", a: "Mutually Exclusive, Collectively Exhaustive — categories should not overlap and should cover all possibilities.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "What is a profitability framework?", a: "Revenue - Costs = Profit. Break revenue into price × volume. Break costs into fixed vs variable. Identify which lever is driving the issue.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you structure a market entry case?", a: "Market attractiveness (size, growth, competition), company capability (resources, brand), entry mode (organic, JV, M&A), financial viability.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you structure a pricing case?", a: "Cost-based (cost + margin), value-based (willingness to pay), competition-based (relative positioning). Consider elasticity and segmentation.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a growth strategy framework?", a: "Organic (new products, new markets, penetration) vs inorganic (M&A, partnerships). Evaluate feasibility, investment, risk, timeline.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "What is Porter's Five Forces?", a: "Industry rivalry, new entrants, substitutes, buyer power, supplier power. Determines industry attractiveness.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "What is a 3C framework?", a: "Company, Customers, Competitors. Useful for strategy and competitive positioning cases.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "What is an issue tree?", a: "Hierarchical breakdown of a problem into sub-issues. Each level should be MECE. Helps identify root causes.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you structure a cost reduction case?", a: "Fixed vs variable costs. Identify largest buckets, benchmark against peers, prioritize by impact vs feasibility.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a value chain analysis?", a: "R&D → procurement → production → distribution → marketing → sales → service. Identify where value is created or lost.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you structure an M&A case?", a: "Strategic rationale, target evaluation, synergies (cost + revenue), valuation, financing, integration risks, alternatives.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you structure a new product launch?", a: "Market need, target customer, product features, pricing, distribution, marketing, competitive response, financial projections.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is the BCG matrix?", a: "Classifies businesses by market growth (high/low) and market share (high/low): Stars, Cash Cows, Question Marks, Dogs.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "What is the Ansoff matrix?", a: "Growth strategies: market penetration (existing/existing), product development (new/existing), market development (existing/new), diversification (new/new).", category: "Frameworks",difficulty:"Intermediate"},
  { q: "When should you NOT use a framework?", a: "When it doesn't fit. Frameworks are starting points — best candidates customize structure to the specific case.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you structure a operations/efficiency case?", a: "Process mapping, bottleneck identification, capacity utilization, automation potential, quality metrics, benchmarking.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a hypothesis-driven approach?", a: "Start with a hypothesis about the answer, then test it with data. Faster and more focused than exhaustive exploration.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you structure a turnaround case?", a: "Stabilize (cash, costs), restructure (operations, org), grow (revenue initiatives, strategic options). Prioritize by urgency.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a segmentation framework?", a: "Divide customers/markets into distinct groups by demographics, behavior, needs, value, or geography to target differently.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you analyze a supply chain issue?", a: "Sourcing → manufacturing → logistics → distribution → last mile. Identify bottlenecks, costs, lead times, risks at each stage.", category: "Frameworks",difficulty:"Advanced"},
  // MARKET SIZING (25)
  { q: "How would you estimate gas stations in the US?", a: "~330M people, ~250M cars, each fills weekly. Station serves ~1,750/week. 250M ÷ 1,750 ≈ ~143K. Actual ~150K.", category: "Market Sizing",difficulty:"Advanced"},
  { q: "Top-down vs bottom-up market sizing?", a: "Top-down: total market → narrow. Bottom-up: unit economics × customers. Best to triangulate both.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate annual Starbucks store revenue.", a: "~300 customers/day × $5 avg = $1,500/day × 365 ≈ $550K. Actual avg ~$1.5M (higher traffic in many locations).", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the US wedding industry size.", a: "~330M people, ~2M weddings/year × ~$30K avg cost = ~$60B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate tennis balls sold annually in the US.", a: "~20M players × ~20 balls/year = ~400M. Add tournaments/clubs for ~450-500M.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the US pet food market.", a: "~90M dog households × ~$100/year + ~60M cat households × ~$70/year ≈ ~$13B basic. Premium/treats push actual to $50B+.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate number of Uber rides per day in NYC.", a: "~8M people, ~40% use rideshare, ~20% on given day, ~1.5 rides = ~960K. Actual ~750K-1M.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate revenue of a movie theater.", a: "~8 screens × 3 showings × 200 seats × 40% occupancy × $12 ticket = ~$23K/day. Plus $8K concessions. ~$31K/day × 365 ≈ $11M.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate number of dentists in the US.", a: "~330M people, see dentist ~2x/year = 660M visits. Dentist sees ~8 patients/day × 250 days = 2,000/year. 660M ÷ 2,000 = ~330K. Actual ~200K.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the global smartphone market size.", a: "~4.5B smartphone users, ~30% replace annually, ~$400 avg price = ~$540B. Actual ~$450B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate weight of a Boeing 747.", a: "~400 passengers × 180 lbs = 72K lbs people + luggage ~30K + fuel ~400K + structure ~400K ≈ ~900K lbs. Actual MTOW ~970K.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "What makes a good market sizing answer?", a: "Clear structure, stated assumptions, clean math, sanity check. Process > precision. Show your thinking.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate number of flights per day in the US.", a: "~330 commercial airports, avg ~50 flights/day = ~16,500. Major hubs have 500+. Actual ~45,000 (many small airports).", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the US coffee market.", a: "~200M adults, ~60% drink coffee, ~1.5 cups/day, ~$2 avg = ~$130B. Actual ~$100B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate gym memberships in the US.", a: "~330M people, ~20% have gym membership = ~66M. Actual ~65M. At ~$40/month = ~$32B revenue.", category: "Market Sizing",difficulty:"Intermediate"},
  // CASE CONCEPTS (40)
  { q: "What is breakeven analysis?", a: "Fixed Costs / (Price - Variable Cost) = Breakeven Volume. The point where total revenue equals total costs.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is CLV?", a: "Customer Lifetime Value = avg revenue × margin × lifespan. Determines how much to spend on acquisition.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is price elasticity?", a: "% change in quantity / % change in price. Elastic (>1) = price-sensitive. Inelastic (<1) = price-insensitive.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is economies of scale?", a: "Cost advantages from increased volume — fixed costs spread, purchasing power increases, operational efficiency improves.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is economies of scope?", a: "Cost savings from producing multiple products together vs separately. Shared R&D, distribution, or brand.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a switching cost?", a: "Cost (financial, time, effort) to switch to a competitor. High switching costs create stickiness and pricing power.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is cannibalization?", a: "New product takes sales from existing product in same portfolio. Consider net impact, not just new revenue.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "Organic vs inorganic growth?", a: "Organic = internal (new products, expansion). Inorganic = M&A, JVs, partnerships. Different risk/speed/cost profiles.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a moat?", a: "Durable competitive advantage: brand, network effects, switching costs, scale, regulation, IP, or cost leadership.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is NPV?", a: "Net Present Value = sum of discounted future cash flows minus initial investment. Positive NPV = creates value.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is payback period?", a: "Time to recover initial investment. Simple but ignores time value and post-payback cash flows.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is capacity utilization?", a: "Actual output / max output. Low utilization = fixed costs spread over fewer units, hurting margins.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is market share?", a: "Company revenue / total market revenue. Indicates competitive position and scale advantages.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a loss leader?", a: "Selling a product below cost to attract customers who buy profitable items. Common in retail and subscriptions.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is bundling?", a: "Selling multiple products together at a discount. Increases perceived value and average transaction size.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is the 80/20 rule (Pareto)?", a: "~80% of effects come from ~20% of causes. 80% of revenue from 20% of customers. Focus analysis on the vital few.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is working capital?", a: "Current assets - current liabilities. Measures cash tied up in operations. Less working capital = more cash available.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a razor/razorblade model?", a: "Sell the base product cheaply, profit from consumables/refills. Printers/ink, game consoles/games.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is network effects?", a: "Product becomes more valuable as more people use it (social media, marketplaces, payment networks). Powerful moat.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is first-mover advantage?", a: "Benefits from entering a market first: brand recognition, customer lock-in, learning curve. But not always decisive.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is vertical integration?", a: "Owning upstream (suppliers) or downstream (distribution/retail) in the value chain. Can reduce costs but increases complexity.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is horizontal integration?", a: "Acquiring competitors at the same stage of the value chain to gain scale, market share, and pricing power.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is outsourcing vs insourcing?", a: "Outsource: lower cost, flexibility, focus on core. Insource: control, quality, IP protection. Evaluate strategically.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a platform business model?", a: "Connects two or more user groups (buyers/sellers, riders/drivers). Value grows with network size. Marketplaces, app stores.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is SaaS?", a: "Software-as-a-Service: subscription-based software delivery. High margins, recurring revenue, scalable. Key metrics: ARR, churn, NRR.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is churn rate?", a: "% of customers who stop using a product/service per period. Critical for subscription businesses. Low churn = healthy retention.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is contribution margin?", a: "Revenue - Variable Costs. Contribution per unit to covering fixed costs and generating profit.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is operating leverage?", a: "High fixed costs = small revenue changes create large profit swings. Great when growing, dangerous when declining.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a two-sided market?", a: "Platform serving two interdependent groups. Must solve chicken-and-egg problem. Uber needs drivers AND riders.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is disintermediation?", a: "Removing middlemen from a value chain. E-commerce disintermediates traditional retail. Can create or destroy value.", category: "Case Concepts",difficulty:"Intermediate"},
  // MENTAL MATH (15)
  { q: "What is 17% of 400?", a: "10% = 40, 7% = 28. Total = 68.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Revenue grows 8%/year for 3 years from $100M?", a: "$100M × 1.08³ ≈ $126M. Quick: 8% × 3 = 24% + ~2% compounding.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 15% of $3.2B?", a: "10% = $320M, 5% = $160M. Total = $480M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "$50 product, 40% gross margin. COGS?", a: "$50 × 0.60 = $30.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "$200M revenue, 25% EBITDA margin. EBITDA?", a: "$200M × 0.25 = $50M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is the Rule of 72?", a: "72 / growth rate = years to double. At 8% growth: ~9 years.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 7/8 as a percentage?", a: "87.5%. Quick: 1/8 = 12.5%, so 7/8 = 100% - 12.5%.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "23 × 17?", a: "23 × 17 = 23 × 20 - 23 × 3 = 460 - 69 = 391.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "$450M revenue, 12% growth. Revenue next year?", a: "$450M × 1.12 = $450M + $54M = $504M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 3/7 approximately?", a: "~43%. 3 ÷ 7 ≈ 0.4286.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Breakeven: $2M fixed costs, $50 price, $30 variable cost?", a: "$2M / ($50 - $30) = $2M / $20 = 100,000 units.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Compound 5% growth over 10 years?", a: "1.05^10 ≈ 1.63. So $100 becomes ~$163. Rule of 72: doubles in ~14 years.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 250 / 8?", a: "31.25. 8 × 30 = 240, remainder 10. 10/8 = 1.25.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "$1.2B market, 15% share. Our revenue?", a: "$1.2B × 0.15 = $180M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "If margin improves from 20% to 25% on $400M revenue, how much incremental profit?", a: "5% × $400M = $20M incremental.", category: "Mental Math",difficulty:"Intermediate"},
  // BEHAVIORAL (20)
  { q: "Why consulting?", a: "Steep learning curve, diverse industries, structured problem-solving, team-based, direct client impact. Be specific.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Why this firm?", a: "Reference specific practice areas, culture, people you've met, training, or case studies. Specificity wins.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Tell me about a time you led a team.", a: "STAR. Show alignment, delegation, conflict handling, and results. Leadership through influence.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Tell me about a complex problem you solved.", a: "Show structured thinking: broke it down, analyzed, found insight, took action. Process matters.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "What is your biggest accomplishment?", a: "Real stakes, clear action, measurable impact. Tie to consulting-relevant skills.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "How do you handle ambiguity?", a: "Structure the unknown, make assumptions, iterate, communicate clearly despite incomplete info.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Tell me about a time you failed.", a: "Real failure, ownership, what you learned, how you improved. Show resilience.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Tell me about a time you convinced someone.", a: "Show empathy, data-driven argumentation, adapting approach, reaching alignment.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "How do you handle disagreement?", a: "Listen first, understand their perspective, present evidence calmly, find common ground. No ego.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "What is your greatest weakness?", a: "Real but manageable. Show self-awareness and concrete improvement steps.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Where do you see yourself in 5 years?", a: "Show ambition but flexibility. Industry expertise, client leadership, or exploring exit options.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "Tell me about yourself.", a: "Present → key experiences → why consulting → why now. Concise, directed, compelling narrative.", category: "Behavioral",difficulty:"Intermediate"},
  // ── ADDITIONAL FRAMEWORKS (20) ──
  { q: "How would you structure a digital transformation case?", a: "Current state assessment, customer/market needs, technology options, implementation plan, costs, timeline, risks, ROI.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you evaluate a potential acquisition?", a: "Strategic fit, financial impact (accretion/synergies), cultural fit, integration complexity, alternatives, risks.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you structure a customer retention case?", a: "Segment customers by value, analyze churn drivers by segment, identify retention levers, prioritize by ROI, measure.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you structure a go-to-market strategy?", a: "Target customer, value proposition, pricing, distribution channels, sales strategy, marketing, competitive positioning.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a root cause analysis?", a: "Systematic identification of the fundamental reason for a problem. Ask 'why' repeatedly until you reach the core issue.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you assess a company's competitive position?", a: "Market share, growth vs market, margins vs peers, customer loyalty, brand strength, innovation pipeline, cost position.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a waterfall chart used for?", a: "Showing how components build up or break down a total. Revenue bridge, profit bridge, cost drivers.", category: "Frameworks",difficulty:"Advanced"},
  { q: "How would you structure a channel strategy case?", a: "Current channels, customer preferences, economics per channel, capacity, competitive channel strategies, optimization.", category: "Frameworks",difficulty:"Advanced"},
  { q: "What is a zero-based budgeting approach?", a: "Build budget from scratch each period rather than adjusting previous year. Forces justification of every expense.", category: "Frameworks",difficulty:"Intermediate"},
  { q: "How would you evaluate make vs buy decision?", a: "Cost comparison, quality control, core competency, speed, flexibility, IP risk, supplier reliability, scalability.", category: "Frameworks",difficulty:"Advanced"},
  // ── ADDITIONAL CASE CONCEPTS (30) ──
  { q: "What is willingness to pay?", a: "Maximum price a customer will pay for a product/service. Varies by segment. Key for value-based pricing.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a marginal cost?", a: "Cost of producing one additional unit. Important for pricing decisions and capacity utilization analysis.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is working capital management?", a: "Optimizing receivables, payables, and inventory to minimize cash tied up in operations while maintaining operations.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is total addressable market (TAM)?", a: "Total revenue opportunity if you captured 100% of the market. Top of the market sizing funnel.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a customer journey?", a: "Path from awareness to purchase to retention. Identifying friction points and optimization opportunities.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a flywheel effect?", a: "Self-reinforcing cycle where momentum builds: more users → more data → better product → more users (Amazon).", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is benchmarking?", a: "Comparing performance against peers or best-in-class. Identifies gaps and improvement opportunities.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a razor-thin margin business?", a: "Business with very low margins (groceries, airlines). Scale and volume critical. Small efficiency gains are huge.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a land-and-expand strategy?", a: "Win small initial deal, then grow within the account through upsells and cross-sells. Common in SaaS.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is unit economics?", a: "Revenue and costs at the individual unit level (per customer, per transaction). Must be positive for scalable business.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a loss ratio?", a: "In insurance: claims paid / premiums earned. Key profitability metric. Below 100% = underwriting profit.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is market concentration?", a: "How consolidated a market is. Measured by HHI or CR4. Concentrated = few large players, pricing power.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a freemium model?", a: "Free basic product, paid premium features. Drives adoption. Conversion rate and ARPU matter.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a marketplace model?", a: "Platform connecting buyers and sellers, taking a cut. Value = liquidity. Chicken-and-egg challenge.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a fixed vs variable cost?", a: "Fixed: doesn't change with volume (rent, salaries). Variable: scales with volume (materials, commissions).", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a sunk cost?", a: "Cost already incurred that cannot be recovered. Should not affect future decisions (but psychologically does).", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is opportunity cost?", a: "Value of the best alternative foregone. Important for investment and resource allocation decisions.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is cross-subsidization?", a: "One product/segment subsidizes another. Can be strategic (loss leader) or hidden (unprofitable segments).", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a value proposition?", a: "Why customers choose you over alternatives. Must be clear, differentiated, and aligned with target segment needs.", category: "Case Concepts",difficulty:"Intermediate"},
  { q: "What is a price war?", a: "Competitors cutting prices to gain share. Destroys industry profitability. Usually ends when one player exits or stops.", category: "Case Concepts",difficulty:"Intermediate"},
  // ── ADDITIONAL MARKET SIZING (15) ──
  { q: "Estimate the global bottled water market.", a: "~5B people with access × ~30% buy bottled water × $1/day avg = ~$550B. Actual ~$300B. Cross-check with per-capita data.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate revenue of a McDonald's restaurant.", a: "~15 hrs × 100 customers/hr × $8 avg ticket = $12K/day × 365 = ~$4.4M. Actual avg ~$3.5M.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate number of elevators in NYC.", a: "~1M buildings, ~10% have elevators = 100K buildings × ~3 elevators = ~300K. Actual ~70K (many small buildings).", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate US tutoring market.", a: "~55M K-12 students × ~15% use tutoring × $200/month × 9 months = ~$15B. Actual ~$12B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate number of pizzas consumed in US daily.", a: "~330M people × ~40% eat pizza weekly ÷ 7 = ~19M slices/day. ~8 slices/pizza = ~2.4M pizzas. Actual ~3M.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the US car wash market.", a: "~280M cars × 50% get washed × 6 washes/year × $15 = ~$12.6B. Actual ~$15B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate US dry cleaning market.", a: "~130M households × ~20% use dry cleaning × $50/month × 12 = ~$15.6B. Actual ~$10B.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate Uber's daily revenue.", a: "~130M monthly users, ~25% active daily = ~33M rides/day × $15 avg = ~$500M/day gross, ~$100M net (take rate). Approximate.", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate the US dental industry size.", a: "~330M people × ~60% visit dentist × ~1.5 visits × $300/visit = ~$89B. Actual ~$160B (procedures drive higher avg).", category: "Market Sizing",difficulty:"Intermediate"},
  { q: "Estimate weight of all people in the US.", a: "~330M × ~170 lbs avg = ~56B lbs = ~28M tons.", category: "Market Sizing",difficulty:"Intermediate"},
  // ── ADDITIONAL MENTAL MATH (15) ──
  { q: "What is 8.5% of $2.4B?", a: "10% = $240M, 1.5% = $36M. 8.5% = $240M - $36M = $204M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "A company grows revenue 12% annually from $500M. Revenue in 5 years?", a: "$500M × 1.12⁵ ≈ $500M × 1.76 = ~$880M. Rule of 72: doubles in ~6 years.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Market is $10B, you have 3% share. What's your revenue?", a: "$10B × 0.03 = $300M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Operating margin improves from 15% to 18% on $800M revenue. Incremental profit?", a: "3% × $800M = $24M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 45 × 22?", a: "45 × 20 = 900, 45 × 2 = 90. Total = 990.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Revenue $2.1B, EBITDA margin 22%. What's EBITDA?", a: "$2.1B × 0.22 = $462M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "What is 5/12 as a percentage?", a: "~41.7%. 5 ÷ 12 ≈ 0.417.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Customer pays $50/month, costs $15/month to serve, stays 3 years. What's CLV?", a: "($50 - $15) × 12 × 3 = $35 × 36 = $1,260.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "If you need 100K units to break even at $20 margin, what are fixed costs?", a: "100K × $20 = $2M.", category: "Mental Math",difficulty:"Intermediate"},
  { q: "Population grows 2% annually from 10M. Population in 10 years?", a: "10M × 1.02¹⁰ ≈ 10M × 1.22 = ~12.2M.", category: "Mental Math",difficulty:"Intermediate"},
  // ── ADDITIONAL BEHAVIORAL (10) ──
  { q: "Tell me about a time you showed creativity.", a: "Problem where standard approach didn't work. Show how you thought differently, tried something new, and it worked.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "How would you manage a difficult client?", a: "Listen actively, understand their concern, manage expectations clearly, deliver on commitments, escalate if needed.", category: "Behavioral",difficulty:"Advanced"},
  { q: "What is the most interesting business you've analyzed?", a: "Pick one genuinely. Explain the business model, what makes it interesting, and what insight you gained.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "How do you structure your thinking under pressure?", a: "Pause briefly, define the problem, identify key issues, prioritize, work through systematically. Don't rush.", category: "Behavioral",difficulty:"Intermediate"},
  { q: "What would you improve about your last project?", a: "Show self-awareness. Identify specific improvement, explain why, and what you'd do differently.", category: "Behavioral",difficulty:"Intermediate"},
];

