import { Flashcard } from './ib-flashcard-data';
export const CONSULTING_FLASHCARDS: Flashcard[] = [
{q:"Our client is a US airline whose profits have declined 20% YoY. What do you look at?",a:"I\'d break this into revenue and costs. On revenue: Passenger volume, Ticket pricing, Route mix. On costs: Fuel, Labor, Maintenance. Then I\'d identify whether this is industry-wide or company-specific. That tells me whether it\'s structural (industry problem) or execution (company issue).",category:"Profitability",difficulty:"Intermediate"},
{q:"Our client is a coffee chain - should they enter China?",a:"I\'d structure this into: Market attractiveness (Demand for coffee, Growth rate, Competition), Client capabilities (Brand strength, Supply chain, Local adaptation), Economics (Expected revenue, Costs of entry). Then I\'d conclude based on whether returns justify risk.",category:"Market Entry",difficulty:"Intermediate"},
{q:"A retail company\'s profits are declining but revenue is stable - what\'s happening?",a:"If revenue is flat but profits are down, costs must be increasing. I\'d look at: COGS (supplier prices, input costs), SG&A (marketing, labor), Store inefficiencies. Then identify which cost driver is growing fastest.",category:"Profitability",difficulty:"Intermediate"},
{q:"How many tennis balls are sold in the US annually?",a:"I\'d structure: Population (~330M), % who play tennis (~5-10%), Frequency (e.g., 1-2x/week for active players), Balls used per session. Then multiply: Players x frequency x usage. The key is clear assumptions + logical math.",category:"Market Sizing",difficulty:"Intermediate"},
{q:"Our client wants to increase profits by 30% - how would you approach this?",a:"I\'d break into: Profit = Revenue - Costs. So options: Increase revenue (price, volume, new products), Reduce costs (efficiency, sourcing). Then prioritize based on feasibility and impact.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company is losing market share - what are possible reasons?",a:"I\'d break into: Market factors (Industry decline, New entrants), Customer factors (Changing preferences, Brand perception), Company factors (Pricing, Product quality, Distribution). Then test which explains the shift.",category:"Strategy",difficulty:"Intermediate"},
{q:"A company wants to launch a new product - what would you evaluate?",a:"I\'d look at: Market demand (Size, Growth), Competitive landscape, Economics (Price vs cost), Capabilities (Can the company execute?). Then assess expected profitability.",category:"Frameworks",difficulty:"Intermediate"},
{q:"Should a company cut prices to gain market share?",a:"I\'d evaluate: Price elasticity (Will volume increase enough?), Cost structure (Can margins sustain it?), Competitive response (Will competitors follow?). Then determine net impact on profit.",category:"Pricing",difficulty:"Intermediate"},
{q:"Our client\'s costs are higher than competitors - what do we do?",a:"I\'d benchmark: Cost structure vs competitors, Identify largest gaps. Then evaluate whether costs are justified (e.g., premium product). If not, focus on efficiency improvements.",category:"Profitability",difficulty:"Intermediate"},
{q:"A PE firm is considering acquiring a company - what do you analyze?",a:"I\'d focus on: Business fundamentals (Revenue growth, Profitability), Valuation, Upside potential, Operational improvements, Exit opportunities.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a manufacturer - should they build a new factory?",a:"I\'d evaluate: Demand outlook, Current capacity utilization, Cost of building vs benefits, Alternatives (outsourcing, optimization). Then compare ROI vs risk.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Sales are declining - what\'s your first step?",a:"First confirm the problem. Then break into: Volume vs price, Customer segments, Geography. Then identify where decline is happening.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A company wants to expand internationally - what factors matter?",a:"Market size and growth, Competitive landscape, Regulatory environment, Entry costs. Then assess risk vs return.",category:"Market Entry",difficulty:"Intermediate"},
{q:"Our client is a luxury brand - how should they grow?",a:"Growth options: Expand geographically, New product lines, Increase pricing. But must maintain brand exclusivity.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company has excess capacity - what should they do?",a:"Options: Increase demand (marketing, pricing), Enter new markets, Reduce capacity. Then evaluate which is most profitable.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Should a company vertically integrate?",a:"I\'d evaluate: Cost savings, Control over supply, Risks. Then compare make vs buy decision.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A competitor enters the market - what do you do?",a:"I\'d assess: Competitor strength, Customer impact. Then consider pricing, differentiation, or cost strategy.",category:"Market Entry",difficulty:"Intermediate"},
{q:"Our client\'s revenue is growing but profits are not - why?",a:"Likely margins are shrinking. I\'d check: Pricing pressure, Rising costs, Mix shift.",category:"Profitability",difficulty:"Intermediate"},
{q:"A startup is growing fast but losing money - is this okay?",a:"Depends on unit economics. If positive unit economics, acceptable. If not, problematic.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company wants to improve margins - what do you do?",a:"Two levers: Increase price, Reduce costs. Then evaluate which is more feasible.",category:"Profitability",difficulty:"Intermediate"},
{q:"Should a company outsource production?",a:"I\'d evaluate: Cost savings, Quality risks, Strategic control.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client wants to double revenue - how?",a:"Options: Increase volume, Increase price, New markets, New products. Then prioritize based on feasibility.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company has declining customer satisfaction - what do you do?",a:"I\'d identify root causes, Segment customers, Link satisfaction to revenue.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A company is entering a saturated market - is it a good idea?",a:"Depends on differentiation. If no clear advantage, likely not attractive.",category:"Market Entry",difficulty:"Intermediate"},
{q:"What\'s the most important thing in a case interview?",a:"Clear structure + logical thinking. Not getting the exact answer, but showing how you think.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Our client is a European airline. Profits are down 25%, but revenue is flat. What do you do?",a:"Since revenue is flat, I\'d focus on cost drivers. For airlines, I\'d prioritize: Fuel costs, Labor, Route profitability. Then I\'d segment which routes or geographies are driving the cost increase. If it\'s industry-wide (e.g., fuel), the solution differs vs a company-specific issue like inefficient routes.",category:"Profitability",difficulty:"Intermediate"},
{q:"Fuel prices increased 30%. Now what?",a:"If it\'s fuel-driven, I\'d evaluate: Can we pass costs to customers (price elasticity)? Can we hedge fuel? Can we optimize routes / reduce capacity? Then decide short-term vs long-term fixes.",category:"Pricing",difficulty:"Intermediate"},
{q:"Our client\'s profits declined only in one region - how do you approach?",a:"I\'d isolate the issue: Revenue vs cost in that region, Compare to other regions. Then ask what\'s unique about this geography. Possible drivers: Competition, Regulation, Customer behavior.",category:"Profitability",difficulty:"Intermediate"},
{q:"A retailer\'s revenue is growing but profits are falling - what\'s your hypothesis?",a:"My initial hypothesis: Margin compression. I\'d test: Discounting / pricing pressure, Rising COGS, Product mix shift. Then quantify which driver explains most of the decline.",category:"Profitability",difficulty:"Intermediate"},
{q:"It\'s due to heavy discounting - what do you recommend?",a:"I\'d evaluate: Is discounting driving volume? Are we targeting the right segments? Then options: Reduce discounting, Improve targeting, Differentiate product. Goal: Maintain volume while improving margins.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client wants to enter a new market - but margins are lower than their current business. Should they enter?",a:"Lower margins don\'t automatically mean no. I\'d evaluate: Market size, Growth potential, Strategic value (e.g., long-term positioning). If total profit pool is large, it\'s still attractive.",category:"Market Entry",difficulty:"Intermediate"},
{q:"A company\'s costs are 20% higher than competitors - how do you diagnose?",a:"I\'d break costs into: Fixed vs variable, Major categories (labor, materials, overhead). Then benchmark where the gap is largest. That tells me where to focus.",category:"Profitability",difficulty:"Intermediate"},
{q:"Labor costs are the issue - now what?",a:"I\'d evaluate: Productivity per worker, Wage levels, Automation opportunities. Then decide reduce headcount vs improve efficiency.",category:"Profitability",difficulty:"Intermediate"},
{q:"A client wants to grow revenue by 50% in 3 years - is this realistic?",a:"I\'d break growth into: Organic growth, Price increases, New markets/products. Then calculate required annual growth rate. If unrealistic, recommend alternative targets.",category:"Profitability",difficulty:"Intermediate"},
{q:"How many Uber rides happen daily in NYC?",a:"I\'d structure: Population of NYC, % using Uber, Frequency per user. Then multiply. Focus: Clear assumptions + logical flow.",category:"Market Sizing",difficulty:"Intermediate"},
{q:"A company is losing customers - how do you approach?",a:"I\'d segment: Customer types, Usage patterns. Then identify where churn is highest. Then diagnose root cause.",category:"Frameworks",difficulty:"Intermediate"},
{q:"Churn is highest among new customers - what does that imply?",a:"Likely poor onboarding or unmet expectations. I\'d focus on: First experience, Product fit, Pricing perception.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company wants to increase prices - what do you consider?",a:"Key factor: Price elasticity. Also: Competitive response, Customer segments. Goal: Maximize profit, not just price.",category:"Pricing",difficulty:"Intermediate"},
{q:"Demand is highly elastic - now what?",a:"If demand is elastic, price increases may reduce revenue. So instead: Focus on cost reduction, Improve value proposition.",category:"Pricing",difficulty:"Intermediate"},
{q:"A company is considering launching a premium product - what do you evaluate?",a:"I\'d assess: Target segment, Willingness to pay, Brand positioning. Risk: Cannibalization of existing products.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A client wants to reduce costs by 15% - how do you approach?",a:"I\'d identify largest cost buckets, Prioritize high-impact areas, Evaluate feasibility. Then avoid cutting core capabilities.",category:"Profitability",difficulty:"Intermediate"},
{q:"You can\'t cut labor - now what?",a:"Then I\'d look at: Procurement / supplier costs, Process efficiency, Automation.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company is deciding between two projects - how do you choose?",a:"I\'d compare: ROI, Risk, Strategic alignment. Then recommend highest risk-adjusted return.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A company\'s profits are volatile - what does that suggest?",a:"Likely high fixed costs or cyclical demand. So earnings sensitivity to external factors.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company has strong growth but low profitability - what do you think?",a:"I\'d evaluate unit economics. If positive, growth may justify losses. If negative, business model issue.",category:"Profitability",difficulty:"Intermediate"},
{q:"Unit economics are negative - what now?",a:"Fix the model before scaling. Options: Increase price, Reduce costs, Change target segment.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company wants to expand into a declining industry - should they?",a:"I\'d evaluate: Market decline rate, Competitive positioning, Ability to gain share. If strong differentiation, could still be viable.",category:"Market Entry",difficulty:"Intermediate"},
{q:"A competitor launches a better product - what do you do?",a:"Options: Improve product, Adjust pricing, Focus on differentiation.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A company is profitable but growth is slowing - what do you do?",a:"I\'d explore: New markets, New products, Pricing strategy.",category:"Profitability",difficulty:"Intermediate"},
{q:"What\'s the biggest mistake candidates make in cases?",a:"They jump to answers and use generic frameworks. Instead, tailor structure to the problem.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Our client is a grocery chain. Profits are declining, but only in urban stores. What do you do?",a:"I\'d isolate what\'s unique about urban locations. I\'d break into: Revenue (pricing, traffic, basket size), Costs (rent, labor, logistics). Then compare urban vs suburban stores. My hypothesis would be higher fixed costs (like rent) or different customer behavior.",category:"Profitability",difficulty:"Intermediate"},
{q:"Urban customers are buying fewer items per visit - now what?",a:"That suggests lower basket size. I\'d explore: Are customers switching to competitors? Are they making more frequent trips? Is pricing perception worse? Then consider promotions, product mix, or store layout.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A SaaS company is growing revenue but losing money - what do you focus on?",a:"I\'d focus on unit economics, specifically: Customer acquisition cost (CAC), Lifetime value (LTV), Retention. If LTV > CAC, growth may be justified. If not, business model issue.",category:"Profitability",difficulty:"Intermediate"},
{q:"CAC is increasing - why might that happen?",a:"Possible reasons: Market saturation, Increased competition, Less effective marketing channels. Implication: Growth is becoming more expensive.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company\'s revenue is flat, but market demand is growing - what does this mean?",a:"It means they are losing market share. I\'d investigate: Competitor actions, Pricing, Product quality.",category:"Profitability",difficulty:"Intermediate"},
{q:"A client wants to expand into a new country where margins are lower - should they?",a:"I\'d evaluate: Market size vs margin, Strategic importance, Long-term potential. Even with lower margins, high volume markets can still be attractive.",category:"Market Entry",difficulty:"Intermediate"},
{q:"Margins are half of current business - now what?",a:"Then I\'d compare total profit potential. If large market + scale opportunity, still viable. If not, likely not attractive.",category:"Profitability",difficulty:"Intermediate"},
{q:"A manufacturing company has declining margins - what\'s your hypothesis?",a:"I\'d test: Rising input costs, Pricing pressure, Inefficiencies. Then quantify which driver explains most of the decline.",category:"Profitability",difficulty:"Intermediate"},
{q:"A client wants to reduce costs but maintain growth - how do you balance?",a:"I\'d prioritize cutting non-core or inefficient costs. Avoid cutting growth drivers like marketing or innovation.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company is considering raising prices, but competitors are cheaper - what do you do?",a:"I\'d evaluate: Price elasticity, Brand strength, Differentiation. If strong differentiation, price increase may still work.",category:"Pricing",difficulty:"Intermediate"},
{q:"Customers are very price sensitive - now what?",a:"Then raising price is risky. Instead, focus on cost reduction or value improvement.",category:"Pricing",difficulty:"Intermediate"},
{q:"A company has excess inventory - what does that imply?",a:"Possible issues: Overproduction, Weak demand, Poor forecasting. Implication: Inefficiency + potential margin pressure.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A retailer is opening more stores but profits are declining - why?",a:"Likely new stores are less profitable. I\'d check: Store-level economics, Cannibalization, Location quality.",category:"Profitability",difficulty:"Intermediate"},
{q:"A client wants to double market share - is this realistic?",a:"I\'d evaluate: Market size, Competitive intensity, Required investment. Then calculate what doubling implies.",category:"Strategy",difficulty:"Intermediate"},
{q:"It requires taking share from a dominant competitor - now what?",a:"That\'s difficult. I\'d explore: Differentiation strategy, Niche segments, Pricing or innovation.",category:"Strategy",difficulty:"Intermediate"},
{q:"A company\'s profits increased, but stock price fell - why?",a:"Possible reasons: Expectations were higher, Future outlook is weaker, Market sentiment.",category:"Pricing",difficulty:"Intermediate"},
{q:"A client wants to enter a highly competitive market - what matters most?",a:"Differentiation. Without it, entry is difficult.",category:"Market Entry",difficulty:"Intermediate"},
{q:"A company has strong brand but weak margins - what does that suggest?",a:"They may underprice or have high costs. Opportunity: Improve pricing.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company has declining revenue but stable profits - how is that possible?",a:"Likely costs are decreasing. Could be cost-cutting or efficiency gains.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company\'s customer base is shrinking but revenue is stable - why?",a:"Possible: Higher pricing or higher spending per customer.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company wants to grow but has limited capital - what do you do?",a:"I\'d prioritize highest ROI opportunities. Possibly focus on core markets and avoid capital-intensive expansion.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A company is considering two markets: one large with low margins, one small with high margins - which do you pick?",a:"Depends on total profit potential. Not just margins.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company is losing employees - what do you look at?",a:"Compensation, Culture, Career growth. Then link talent loss to performance impact.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company is profitable but losing relevance - what does that imply?",a:"Long-term risk. They may need innovation or repositioning.",category:"Profitability",difficulty:"Intermediate"},
{q:"What separates a top consulting candidate?",a:"They stay structured under pressure, adapt when new info comes, and drive the case forward. Most importantly, they think, not memorize.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Our client is a US fast-casual restaurant chain. Profits are down 15% YoY. What do you do?",a:"I\'d start by structuring the problem: Profit = Revenue - Costs. So I\'d break into Revenue (Number of customers, Average ticket size) and Costs (Food costs, Labor, Rent). Then I\'d identify where the decline is coming from.",category:"Profitability",difficulty:"Intermediate"},
{q:"Revenue is flat, but profits declined - now what?",a:"That suggests costs have increased. I\'d prioritize: Food costs (ingredients), Labor costs (wages), Rent. Then quantify which cost driver increased most.",category:"Profitability",difficulty:"Intermediate"},
{q:"Customers are price sensitive - raising prices reduces traffic.",a:"Then raising prices is limited. I\'d explore cost-side solutions: Supplier renegotiation, Menu optimization, Reducing waste.",category:"Pricing",difficulty:"Intermediate"},
{q:"We can\'t reduce food costs much - what else?",a:"Then I\'d shift to improving revenue efficiency: Increase ticket size (upselling), Improve throughput, Focus on high-margin items.",category:"Profitability",difficulty:"Intermediate"},
{q:"Final recommendation?",a:"I\'d recommend a mix of: Menu optimization (shift to higher-margin items), Operational efficiency improvements, Selective price increases where elasticity is low.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a US gym chain considering entering India. Should they?",a:"I\'d structure into: Market attractiveness, Competitive landscape, Client capabilities, Financial viability.",category:"Market Entry",difficulty:"Intermediate"},
{q:"Competitors are mostly low-cost gyms.",a:"Then I see two options: Compete on cost, Enter as premium. I\'d evaluate which aligns with client strengths.",category:"Profitability",difficulty:"Intermediate"},
{q:"Our brand is premium.",a:"Then competing on cost is difficult. I\'d explore premium niche strategy: Target higher-income customers, Offer differentiated experience.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What risks do you see?",a:"Market may not support premium pricing, Brand may not translate, High upfront investment.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Recommendation?",a:"I\'d recommend entering selectively in urban, higher-income areas. Test demand before scaling.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a software company considering increasing prices by 10%. Should they?",a:"I\'d evaluate: Price elasticity, Customer segments, Competitive positioning.",category:"Pricing",difficulty:"Intermediate"},
{q:"Enterprise customers are not price sensitive, but small businesses are.",a:"Then I\'d recommend segment pricing: Increase prices for enterprise, Maintain or adjust for SMB.",category:"Market Entry",difficulty:"Intermediate"},
{q:"Competitors are not increasing prices.",a:"Then risk increases. I\'d evaluate differentiation. If strong, price increase viable. If weak, risk of churn.",category:"Pricing",difficulty:"Intermediate"},
{q:"Recommendation?",a:"I\'d suggest targeted price increases + monitor churn.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client wants to grow revenue by 30% in 2 years. How do you approach?",a:"I\'d break into: Organic growth, Price increases, New products, New markets. Then estimate contribution from each.",category:"Profitability",difficulty:"Intermediate"},
{q:"Current growth is only 5% annually.",a:"Then achieving 30% requires new initiatives. Organic alone won\'t be enough.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"New product launch is possible but risky.",a:"Then I\'d weigh risk vs return and time to market.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Recommendation?",a:"I\'d recommend a balanced strategy: Moderate organic growth, Selective new initiatives.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a logistics company with rising costs. What do you do?",a:"I\'d break costs into: Fuel, Labor, Infrastructure. Then identify largest cost drivers.",category:"Profitability",difficulty:"Intermediate"},
{q:"Fuel costs are the biggest issue.",a:"Then I\'d evaluate: Route optimization, Fuel efficiency, Hedging.",category:"Profitability",difficulty:"Intermediate"},
{q:"Routes are inefficient.",a:"Then optimize network: Reduce empty miles, Improve routing.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Recommendation?",a:"Focus on operational efficiency improvements.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What is the most important thing across all cases?",a:"Driving the case forward with structure. Not waiting for the interviewer, but leading the thinking.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a large newspaper company. Revenue is declining. What do you do?",a:"I\'d start by clarifying: Is decline coming from Print, Digital, or Advertising? Then I\'d segment revenue streams: Subscription, Advertising, Other. My hypothesis: Print is declining structurally. So I\'d focus on transition to digital and monetization strategy.",category:"Profitability",difficulty:"Intermediate"},
{q:"Print is declining fast, digital is growing but not enough.",a:"That confirms structural industry shift. I\'d focus on: Accelerating digital growth, Improving digital monetization, Reducing print costs.",category:"Profitability",difficulty:"Intermediate"},
{q:"Digital users don\'t want to pay.",a:"Then I\'d explore alternative monetization: Ads, Freemium model, Bundling.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Final recommendation?",a:"Transition aggressively to digital: Invest in content + platform, Optimize pricing model, Gradually phase out print.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a luxury fashion brand. Should they lower prices to increase volume?",a:"I\'d be cautious. Luxury brands rely on exclusivity. Lowering prices could increase volume but damage brand.",category:"Pricing",difficulty:"Intermediate"},
{q:"Sales are declining.",a:"Then I\'d explore alternative solutions: Expand product lines, Enter new markets, Improve marketing.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Competitors are lowering prices.",a:"Still risky. I\'d evaluate whether brand differentiation is strong. If yes, maintain pricing. If no, consider limited adjustments.",category:"Pricing",difficulty:"Intermediate"},
{q:"Recommendation?",a:"Avoid broad price cuts. Instead, protect brand + find growth elsewhere.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client sells a product for $100 with $60 cost. Volume = 1M units. Should they cut price by 10% if volume increases 20%?",a:"Current profit: (100 - 60) x 1M = $40M. New: Price = 90, Profit per unit = 30, Volume = 1.2M. 30 x 1.2M = $36M. So profit declines.",category:"Pricing",difficulty:"Intermediate"},
{q:"Conclusion?",a:"Price cut is not profitable unless long-term benefits justify it.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client is a taxi company losing business to ride-sharing apps. What do you do?",a:"I\'d recognize this as structural disruption. Options: Compete directly, Differentiate, Partner / pivot.",category:"Frameworks",difficulty:"Intermediate"},
{q:"We can\'t compete on price.",a:"Then I\'d focus on differentiation: Premium service, Corporate contracts, Reliability.",category:"Pricing",difficulty:"Intermediate"},
{q:"Recommendation?",a:"Don\'t compete head-on. Focus on niche positioning.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client asks: \"How can we grow?\" with no other context.",a:"Very open-ended. I\'d structure: Existing business growth, New products, New markets. Then prioritize based on feasibility + impact.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Be more specific.",a:"I\'d ask clarifying questions: Industry? Current growth? Constraints? Then refine structure.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Revenue is growing, profits are growing, but CEO is unhappy - why?",a:"Possible reasons: Growth below expectations, Market share loss, Future risks.",category:"Profitability",difficulty:"Intermediate"},
{q:"Market share is declining.",a:"That\'s key. Even if growing, competitors growing faster.",category:"Strategy",difficulty:"Intermediate"},
{q:"Recommendation?",a:"Focus on competitive positioning.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Client has 5 possible initiatives - how do you prioritize?",a:"I\'d evaluate: Impact, Feasibility, Risk. Then rank highest ROI first.",category:"Frameworks",difficulty:"Intermediate"},
{q:"Two options have same ROI.",a:"Then consider strategic alignment and execution risk.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company is profitable - should it still cut costs?",a:"Yes, if costs are inefficient. But avoid harming growth.",category:"Profitability",difficulty:"Intermediate"},
{q:"A company is growing fast - should it cut costs?",a:"Depends. If growth is inefficient, yes.",category:"Profitability",difficulty:"Intermediate"},
{q:"Your recommendation is wrong - defend it.",a:"I\'d stay calm, reiterate logic, adjust if needed. Key: Don\'t panic.",category:"Strategy",difficulty:"Intermediate"},
{q:"If you had to summarize your approach to cases in one sentence?",a:"Break the problem into clear components, prioritize the biggest drivers, and adapt based on new information.",category:"Frameworks",difficulty:"Intermediate"},
{q:"What separates top 1% consulting candidates?",a:"They stay structured under ambiguity, quantify when needed, adapt quickly. Most importantly, they lead the case, not follow it.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Our client is a city government. Traffic congestion is worsening - what do you do?",a:"I\'d structure around: Demand for roads (Population growth, Car usage), Supply of roads (Infrastructure capacity), Behavioral factors (Public transport usage). Then solutions: Reduce demand OR increase capacity.",category:"Frameworks",difficulty:"Intermediate"},
{q:"You cannot build more roads.",a:"Then I\'d focus on reducing demand. Options: Congestion pricing, Public transport incentives, Remote work.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Public hates congestion pricing.",a:"Then I\'d look for softer incentives: Subsidize alternatives, Improve convenience.",category:"Pricing",difficulty:"Intermediate"},
{q:"A non-profit wants to maximize impact with limited budget - how do you approach?",a:"I\'d define Impact = Benefit per dollar. Then identify programs, Estimate impact, Prioritize highest ROI.",category:"Profitability",difficulty:"Intermediate"},
{q:"Impact is hard to measure.",a:"Then I\'d use proxies: Reach, Outcomes, Cost efficiency.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client asks: \"Should we grow?\" with no data provided.",a:"I\'d start by clarifying the objective. Then structure: Growth options, Risks, Constraints. And make reasonable assumptions.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"You don\'t get more data.",a:"Then proceed with assumptions clearly stated. This tests comfort with ambiguity.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company is highly profitable - but all competitors are growing faster. What do you do?",a:"This suggests risk of long-term decline. I\'d analyze competitive positioning and identify growth opportunities.",category:"Profitability",difficulty:"Intermediate"},
{q:"Recommendation?",a:"Balance: Protect current profit + invest in growth.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"A company is growing users but losing money on every transaction - what do you do?",a:"This is critical. If unit economics are negative, growth worsens the problem. I\'d fix pricing, reduce costs, or rethink model.",category:"Profitability",difficulty:"Intermediate"},
{q:"They want to keep growing anyway.",a:"Then I\'d challenge sustainability. Growth without profitability is risky long-term.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"The CEO wants growth, CFO wants cost cuts - what do you do?",a:"I\'d quantify tradeoffs: Growth potential, Cost savings. Then recommend balanced approach.",category:"Profitability",difficulty:"Intermediate"},
{q:"Client wants to double profit in 1 year - realistic?",a:"I\'d break down drivers: Revenue growth required, Cost reduction required. Then assess feasibility.",category:"Profitability",difficulty:"Intermediate"},
{q:"It\'s unrealistic - what do you say?",a:"I\'d be honest but constructive. Explain constraints, Propose alternative targets.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Customers say they love the product but don\'t buy - why?",a:"Possible reasons: Price too high, Not urgent need, Better alternatives.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Data shows demand is rising, but sales are falling - explain.",a:"Possible: Supply constraints, Competitors capturing demand, Distribution issues.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Your structure is wrong - restart.",a:"I\'d stay calm and reframe clearly. Shows composure.",category:"Frameworks",difficulty:"Intermediate"},
{q:"A profitable strategy harms customers - what do you do?",a:"I\'d consider long-term reputation, Legal risk, Ethics. Then recommend sustainable solution.",category:"Profitability",difficulty:"Intermediate"},
{q:"You have 30 seconds - what\'s your answer?",a:"Focus on key driver + recommendation. Not full analysis.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Why are manhole covers round?",a:"Because round covers can\'t fall through. Tests logical thinking.",category:"Market Sizing",difficulty:"Intermediate"},
{q:"Convince me your recommendation is correct.",a:"I\'d state recommendation clearly, support with 2-3 key points, address risks.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What would you do if your analysis is wrong?",a:"I\'d reassess quickly. Consulting is iterative.",category:"Frameworks",difficulty:"Intermediate"},
{q:"What if the client disagrees?",a:"I\'d understand their perspective and adjust or defend.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What\'s more important: being right or being persuasive?",a:"Both matter. But persuasion is critical in consulting.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Final question - what is consulting really testing?",a:"How you think under uncertainty. Not memorization, but structured reasoning.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client asks: \"Should we enter this market?\" You have 30 seconds.",a:"I\'d say: \"Based on what we know, I\'d recommend a cautious entry, focused on high-value segments. The market appears attractive, but margins and competitive intensity suggest we should test before scaling.\" Clear, direct, no rambling.",category:"Market Entry",difficulty:"Intermediate"},
{q:"What makes a good 30-second answer?",a:"Clear recommendation first, 2-3 supporting points, Acknowledgment of risk.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Our client must choose between two equally good options - what do you do?",a:"I\'d look beyond financials: Strategic fit, Execution risk, Long-term positioning. Then recommend the more robust option.",category:"Frameworks",difficulty:"Intermediate"},
{q:"Client says: \"I don\'t agree with your recommendation.\"",a:"I\'d respond: \"I understand your concern - can you share which part you disagree with? That will help us refine the analysis or explore alternatives.\" Collaborative, not defensive.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Client says: \"Fix my business.\"",a:"I\'d structure: Identify core problem, Prioritize biggest drivers, Focus on high-impact solutions. Then move quickly into analysis.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Is it better to be roughly right or exactly wrong?",a:"Roughly right. Because speed + direction matter more than precision early.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Would you prioritize growth or profitability?",a:"Depends on context. Early-stage: growth. Mature: profitability. The key is align with company goals.",category:"Profitability",difficulty:"Intermediate"},
{q:"What is the biggest risk in most strategies?",a:"Execution risk. Even good ideas fail if poorly implemented.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"How would you explain a complex idea to a CEO?",a:"I\'d start with the conclusion, use simple language, focus on impact.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"You have 10 issues - what do you tackle first?",a:"The highest impact driver. Not the easiest or the most interesting.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"You realize your analysis is wrong mid-case - what do you do?",a:"I\'d say: \"Let me revisit that assumption - I think there\'s a better way to approach it.\" Acknowledge + correct quickly.",category:"Frameworks",difficulty:"Intermediate"},
{q:"What do clients actually pay consultants for?",a:"Clarity and decision-making. Not just analysis.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Client is emotional and not listening - what do you do?",a:"I\'d stay calm, acknowledge concerns, refocus on facts.",category:"Frameworks",difficulty:"Intermediate"},
{q:"Is more analysis always better?",a:"No. At some point, diminishing returns.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Would you deliver a fast imperfect answer or slow perfect one?",a:"Usually fast, directional answer first. Then refine.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What do partners care about most?",a:"Can you think clearly and communicate simply.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you build trust with a client?",a:"Be clear, Be honest, Be reliable.",category:"Frameworks",difficulty:"Intermediate"},
{q:"What makes a good business decision?",a:"Based on data, Aligned with strategy, Practical to execute.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What if your recommendation fails?",a:"I\'d analyze why and adjust quickly.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"What is the hardest part of consulting?",a:"Dealing with ambiguity and uncertainty.",category:"Case Concepts",difficulty:"Intermediate"},
{q:"Convince me you\'d be a good consultant.",a:"I approach problems in a structured way, stay adaptable as new information comes in, and communicate clearly. I focus on identifying the key drivers rather than getting lost in details, which allows me to move quickly toward actionable recommendations.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is the biggest mistake candidates make at this level?",a:"Overcomplicating answers.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What\'s the simplest way to improve in case interviews?",a:"Practice structured thinking.",category:"Behavioral",difficulty:"Intermediate"},
{q:"If you had one piece of advice for consulting interviews?",a:"Be clear, not clever.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Final question - what actually gets you the offer?",a:"Confidence + clarity under pressure. Not perfect answers, but strong thinking.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Our client\'s revenue, profit, and market share are all increasing - but the CEO is worried. Why might that be?",a:"I\'d think about forward-looking risks, not current performance. Possibilities: Growth is slowing relative to competitors, Margins are declining, Market is peaking. So I\'d investigate whether current success is sustainable.",category:"Profitability",difficulty:"Advanced"},
{q:"Margins are declining slightly - does that matter?",a:"Yes, because small margin compression can signal future problems. I\'d check cost trends and pricing pressure.",category:"Profitability",difficulty:"Advanced"},
{q:"Our client has too much demand and can\'t keep up - what should they do?",a:"This is a capacity issue. Options: Expand capacity, Raise prices, Prioritize high-value customers. I\'d evaluate which maximizes profit.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Capacity expansion takes 2 years.",a:"Then short-term solution: Price increases or prioritization.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company\'s profits dropped suddenly - everything looks normal. What could be happening?",a:"I\'d consider hidden drivers: One-time events, Accounting changes, Mix shift.",category:"Profitability",difficulty:"Advanced"},
{q:"Our client is in a declining industry - how can they grow?",a:"Options: Gain market share, Diversify, Innovate. But key: Growth must come from outside the core decline.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Customers say your product is \"fine\" - what does that imply?",a:"That\'s weak positioning. No strong differentiation. Risk: Easy to switch.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company increased prices and profits went up - is this always good?",a:"Not necessarily. I\'d check long-term demand impact. Short-term gains may hurt future growth.",category:"Pricing",difficulty:"Advanced"},
{q:"A company is growing fast but customer satisfaction is declining - what do you do?",a:"I\'d prioritize fixing core experience. Because growth without quality is unsustainable.",category:"Frameworks",difficulty:"Advanced"},
{q:"Your client cuts prices, competitors match immediately - what now?",a:"Then price isn\'t a differentiator. I\'d shift to differentiation or cost leadership.",category:"Pricing",difficulty:"Advanced"},
{q:"Sales are declining - how do you know if it\'s demand or supply?",a:"I\'d check: Customer demand indicators, Inventory levels, Stockouts. Then determine if it\'s demand-side or supply-side.",category:"Frameworks",difficulty:"Advanced"},
{q:"A company is profitable today but losing relevance - what do you do?",a:"This is a long-term risk. I\'d invest in future positioning even if short-term profits decline.",category:"Profitability",difficulty:"Advanced"},
{q:"Should a luxury brand enter a low-income country?",a:"Not obvious. I\'d evaluate: Size of wealthy segment, Brand perception, Long-term growth.",category:"Market Entry",difficulty:"Advanced"},
{q:"Profits declined due to both lower revenue and higher costs - where do you focus first?",a:"I\'d prioritize the largest impact driver. Then the easiest to fix.",category:"Profitability",difficulty:"Advanced"},
{q:"You identify 3 major issues - how do you choose where to act?",a:"I\'d evaluate impact and feasibility. Then focus on highest ROI.",category:"Frameworks",difficulty:"Advanced"},
{q:"Client insists on a strategy you think is wrong - what do you do?",a:"I\'d acknowledge their view, present data clearly, suggest alternatives.",category:"Frameworks",difficulty:"Advanced"},
{q:"Should a company sacrifice profit to gain market share?",a:"Depends. If long-term value justifies it, yes. If not, no.",category:"Profitability",difficulty:"Advanced"},
{q:"If demand is perfectly inelastic, what should pricing be?",a:"In theory, increase price. But in reality, consider brand and regulation.",category:"Pricing",difficulty:"Advanced"},
{q:"Why do companies with high fixed costs struggle more in downturns?",a:"Because costs don\'t adjust with revenue. So profits drop faster.",category:"Profitability",difficulty:"Advanced"},
{q:"When does scale actually help a business?",a:"When it reduces unit costs. But not always if complexity increases.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How do you know when you\'re ready to give a recommendation?",a:"When you\'ve identified the main driver. Not when you\'ve analyzed everything.",category:"Frameworks",difficulty:"Advanced"},
{q:"What\'s more important: creativity or structure?",a:"Both, but structure comes first.",category:"Frameworks",difficulty:"Advanced"},
{q:"What\'s the biggest signal of a weak candidate?",a:"Disorganized thinking.",category:"Behavioral",difficulty:"Advanced"},
{q:"What\'s the biggest signal of a strong candidate?",a:"Clear, confident, structured answers.",category:"Behavioral",difficulty:"Advanced"},
{q:"Our client runs a social media platform. Growth is slowing - what do you do?",a:"I\'d think in terms of network effects. Growth slowing could mean: Market saturation, Reduced engagement, Stronger competition. I\'d evaluate user acquisition vs engagement because retention drives long-term value.",category:"Frameworks",difficulty:"Advanced"},
{q:"User growth is flat but engagement is dropping.",a:"That\'s more concerning. It suggests weakening product value. I\'d focus on: Product improvements, Content quality, User experience.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A marketplace has many buyers but few sellers - what do you do?",a:"This is a supply imbalance. I\'d incentivize sellers: Lower fees, Subsidies, Better tools. Because platform value depends on balance.",category:"Frameworks",difficulty:"Advanced"},
{q:"Should you prioritize buyers or sellers in a marketplace?",a:"Depends on constraint. Focus on the bottleneck side. If too few sellers, fix supply. If too few buyers, fix demand.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A product has zero substitutes - how should you price it?",a:"In theory, price can be high. But in practice, consider long-term demand, fairness, and regulation.",category:"Pricing",difficulty:"Advanced"},
{q:"A company serves 3 customer segments - one is highly profitable, one is not. What do you do?",a:"I\'d focus on high-profit segment. Then decide: Improve low-profit segment or exit.",category:"Profitability",difficulty:"Advanced"},
{q:"A premium brand has higher costs than competitors - is that a problem?",a:"Not necessarily. If customers value the brand, higher costs may be justified.",category:"Profitability",difficulty:"Advanced"},
{q:"A key supplier shuts down - what do you do?",a:"Immediate: Find alternatives. Long-term: Diversify supply.",category:"Frameworks",difficulty:"Advanced"},
{q:"A new product reduces sales of an existing one - is that bad?",a:"Not always. If total profit increases, acceptable.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has positive margins but negative unit economics - how is that possible?",a:"Could be fixed costs masking losses. So scaling may worsen profitability.",category:"Profitability",difficulty:"Advanced"},
{q:"Demand suddenly doubles - what risks do you see?",a:"Operational strain, Quality decline, Supply shortages.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Would you rather sell high margin low volume or low margin high volume?",a:"Depends on total profit. Not margin alone.",category:"Profitability",difficulty:"Advanced"},
{q:"CAC is rising - what does that signal?",a:"Market saturation or competition increasing.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Which is more important: acquiring new customers or retaining existing ones?",a:"Usually retention. Because lower cost, higher lifetime value.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Should a company enter a market where they are clearly worse than competitors?",a:"Only if they have a path to differentiate. Otherwise, likely not viable.",category:"Market Entry",difficulty:"Advanced"},
{q:"A company is at 90% capacity - expand or not?",a:"Depends on demand certainty. If stable, expand. If uncertain, wait.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Should a company sacrifice short-term profit for long-term growth?",a:"Often yes, if long-term value is higher.",category:"Profitability",difficulty:"Advanced"},
{q:"Data shows correlation but not causation - what do you do?",a:"Validate before acting.",category:"Frameworks",difficulty:"Advanced"},
{q:"When should a company exit a market?",a:"When there\'s no path to profitability.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What makes a business defensible?",a:"Brand, Cost advantage, Network effects.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How do you make decisions with incomplete information?",a:"Use assumptions + test sensitivity.",category:"Frameworks",difficulty:"Advanced"},
{q:"Why do some businesses fail when scaling?",a:"Because unit economics break down.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What is the hardest part of consulting cases?",a:"Prioritization.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What is the key mindset shift from beginner to advanced?",a:"Stop using frameworks - start thinking.",category:"Behavioral",difficulty:"Advanced"},
{q:"Why do people buy bottled water when tap water is cheaper?",a:"I\'d break into: Perception of quality (purity, taste), Convenience, Branding / marketing. So even if objectively similar, perceived value drives behavior.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How would you estimate the number of gas stations in the US without data?",a:"I\'d structure: Number of cars, Average fueling frequency, Capacity per station. Then back into total stations. Key: Logical assumptions > exact number.",category:"Market Sizing",difficulty:"Advanced"},
{q:"Should Netflix buy a chain of movie theaters?",a:"I\'d evaluate: Strategic fit, Synergies (content + distribution), Risks (declining theaters). Likely not attractive unless strong synergy.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why might lowering price reduce revenue?",a:"If demand is inelastic or brand perception declines.",category:"Pricing",difficulty:"Advanced"},
{q:"A company increased profit - what could have caused it?",a:"Possible drivers: Higher prices, Lower costs, Better product mix. Key: Think backward.",category:"Profitability",difficulty:"Advanced"},
{q:"Why do customers not choose the cheapest option?",a:"Because decisions involve: Trust, Brand, Perceived quality. Not just price.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why doesn\'t doubling marketing spend always double sales?",a:"Because of diminishing returns. Early spend is more effective.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has strong metrics but is failing - what could be missing?",a:"Possibilities: External risks, Market shift, Competitive pressure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"You can only fix one thing in a business - what do you choose?",a:"The biggest value driver. Usually revenue driver or largest cost.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do companies make bad long-term decisions?",a:"Because short-term incentives dominate.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why might a successful small business fail when expanding?",a:"Loss of control, Higher complexity, Cost increases.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do some industries naturally have low margins?",a:"Because of high competition or low differentiation.",category:"Profitability",difficulty:"Advanced"},
{q:"If you were CEO for a day, what would you look at first?",a:"The biggest driver of value. Usually revenue or profit drivers.",category:"Frameworks",difficulty:"Advanced"},
{q:"Why do most startups fail?",a:"Poor product-market fit, Weak unit economics, Competition.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Would you rather have 100% of a small company or 1% of a huge one?",a:"Depends on total value.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Revenue doubled - is that good?",a:"Not necessarily. Need to check profitability.",category:"Profitability",difficulty:"Advanced"},
{q:"Client says profits are down - what\'s the first question?",a:"Is it revenue or cost?",category:"Profitability",difficulty:"Advanced"},
{q:"Explain a business in one sentence.",a:"It creates value for customers and captures some of that value as profit.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why is consulting harder than it looks?",a:"Ambiguity + pressure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do companies exist?",a:"To create value more efficiently than individuals.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What would you do if you had no structure at all?",a:"Create one.",category:"Frameworks",difficulty:"Advanced"},
{q:"Why don\'t clients always follow recommendations?",a:"Risk, Politics, Culture.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What is consulting really about?",a:"Helping clients make better decisions.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What is the best way to approach any problem?",a:"Break it down.",category:"Frameworks",difficulty:"Advanced"},
{q:"What separates elite candidates from everyone else?",a:"They stay clear under pressure.",category:"Behavioral",difficulty:"Advanced"},
{q:"A SaaS company has strong revenue growth but declining retention - what do you do?",a:"I\'d focus on retention first because it drives lifetime value and long-term growth. I\'d analyze: Cohort retention, Customer segments, Reasons for churn. Then address product or value gaps.",category:"Profitability",difficulty:"Advanced"},
{q:"Churn is highest among small customers.",a:"That suggests weak product-market fit for that segment. Options: Improve product for SMB or refocus on enterprise.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A hospital is losing money - what do you look at?",a:"I\'d break into: Revenue (patient volume, pricing, payer mix), Costs (labor, equipment, admin). Then identify largest driver.",category:"Profitability",difficulty:"Advanced"},
{q:"Costs are rising due to staffing shortages.",a:"Then I\'d evaluate: Hiring vs outsourcing, Efficiency improvements.",category:"Profitability",difficulty:"Advanced"},
{q:"Should a PE firm invest in a declining industry?",a:"Potentially yes if they can improve operations or consolidate. Key: Value creation opportunities.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A retailer\'s online sales are growing but store sales are declining - what do you do?",a:"I\'d evaluate: Cannibalization, Profitability of each channel. Then optimize channel mix.",category:"Profitability",difficulty:"Advanced"},
{q:"Oil prices drop 40% - what happens to energy companies?",a:"Revenue declines, Margins compress. Response: Cost cuts + efficiency.",category:"Pricing",difficulty:"Advanced"},
{q:"Airline demand increases - why might profits still fall?",a:"Because costs (fuel, labor) may rise faster.",category:"Profitability",difficulty:"Advanced"},
{q:"A payments startup is growing users but not revenue - why?",a:"Possible: Low monetization. I\'d evaluate pricing model and transaction fees.",category:"Profitability",difficulty:"Advanced"},
{q:"A factory has low utilization - what do you do?",a:"Options: Increase demand, Reduce capacity.",category:"Frameworks",difficulty:"Advanced"},
{q:"A telecom company has declining ARPU - why?",a:"Possible: Price competition, Changing usage.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A streaming platform is losing subscribers - what do you check?",a:"Content quality, Pricing, Competition.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Delivery costs are rising - what do you do?",a:"Optimize logistics, Adjust pricing, Improve efficiency.",category:"Profitability",difficulty:"Advanced"},
{q:"A university has declining enrollment - why?",a:"Demographics, Competition, Cost.",category:"Case Concepts",difficulty:"Advanced"},
{q:"EV adoption is rising - what should a traditional automaker do?",a:"Invest in EV + adapt strategy.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A bank\'s profits decline due to lower interest rates - why?",a:"Net interest margin shrinks.",category:"Profitability",difficulty:"Advanced"},
{q:"Office demand declines - what happens?",a:"Lower rents + vacancy.",category:"Profitability",difficulty:"Advanced"},
{q:"Shipping delays increase - what do you do?",a:"Improve routing, Increase capacity.",category:"Frameworks",difficulty:"Advanced"},
{q:"A drug loses patent protection - what happens?",a:"Revenue declines due to generics.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A restaurant chain\'s traffic declines - why?",a:"Competition, Pricing, Experience.",category:"Profitability",difficulty:"Advanced"},
{q:"Luxury demand declines - what do you do?",a:"Focus on core customers.",category:"Profitability",difficulty:"Advanced"},
{q:"Startup burns cash quickly - what do you do?",a:"Improve unit economics.",category:"Frameworks",difficulty:"Advanced"},
{q:"Subscription growth slows - what do you check?",a:"Acquisition, Retention.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Market is saturated - how do you grow?",a:"New markets, New products.",category:"Frameworks",difficulty:"Advanced"},
{q:"What is the key insight across all industries?",a:"Same core logic applies: Revenue, Costs, Strategy.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Our client is a free mobile app with millions of users but no revenue. What should they do?",a:"I\'d first clarify the goal - monetize or grow? Then evaluate monetization options: Ads, Subscription, In-app purchases. Then assess which aligns best with user behavior.",category:"Profitability",difficulty:"Advanced"},
{q:"Users hate ads.",a:"Then ads may hurt engagement. I\'d explore freemium or premium features.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has great financials but is losing customers - what\'s going on?",a:"Possibly a lagging indicator problem. Financials reflect past performance, not future.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company is the cheapest in the market but still losing customers - why?",a:"Price isn\'t everything. Likely quality, brand, or experience issues.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do companies offer free trials?",a:"To reduce customer risk and increase conversion.",category:"Behavioral",difficulty:"Advanced"},
{q:"Sales increased after price increase - why?",a:"Possible reasons: Perceived higher quality, Inelastic demand.",category:"Pricing",difficulty:"Advanced"},
{q:"A company is optimizing revenue but profits are declining - what\'s wrong?",a:"Wrong KPI focus. Should optimize profit, not revenue.",category:"Profitability",difficulty:"Advanced"},
{q:"A strategy improves profits today but hurts them later - should you do it?",a:"Depends on long-term value.",category:"Profitability",difficulty:"Advanced"},
{q:"Why do some companies become less efficient as they grow?",a:"Because complexity increases.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What\'s something companies often overlook?",a:"Customer perspective.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why might a good strategy fail?",a:"Competitors react.",category:"Case Concepts",difficulty:"Advanced"},
{q:"You have 10 growth ideas - how do you choose?",a:"Prioritize by impact and feasibility.",category:"Frameworks",difficulty:"Advanced"},
{q:"Should a company enter a market where demand is unclear?",a:"Only if risk is manageable.",category:"Market Entry",difficulty:"Advanced"},
{q:"How do you create demand where none exists?",a:"Education + awareness.",category:"Frameworks",difficulty:"Advanced"},
{q:"Why do companies stay in bad businesses too long?",a:"Sunk cost fallacy.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do some products fail despite good marketing?",a:"Weak product-market fit.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Can growth ever be bad?",a:"Yes, if unit economics are negative.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do executives make bad decisions?",a:"Bias, Incomplete info, Pressure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do customers sometimes choose more expensive options?",a:"Perceived value.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do some industries consolidate over time?",a:"Scale advantages.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why are gas stations often located near each other?",a:"Competition + demand clustering.",category:"Market Sizing",difficulty:"Advanced"},
{q:"Why do companies bundle products?",a:"Increase perceived value + revenue.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters more: price or convenience?",a:"Depends on customer segment.",category:"Pricing",difficulty:"Advanced"},
{q:"What\'s the simplest way to solve complex problems?",a:"Break them into parts.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Our client says: \"We need to grow.\" What\'s your first move?",a:"I wouldn\'t jump into solutions. I\'d first clarify why they need growth. Is it revenue pressure? Investor expectations? Competitive threat? Because the solution depends on the underlying problem.",category:"Frameworks",difficulty:"Advanced"},
{q:"Explain a complex business problem in one sentence.",a:"I\'d distill it to: \"We\'re losing profitability due to rising costs outpacing revenue growth.\"",category:"Case Concepts",difficulty:"Advanced"},
{q:"You have 100 data points - how do you decide what matters?",a:"I\'d focus on variables that impact the objective. Ignore noise.",category:"Frameworks",difficulty:"Advanced"},
{q:"How do you know when to stop analyzing?",a:"When additional analysis won\'t change the decision.",category:"Frameworks",difficulty:"Advanced"},
{q:"If you were CEO, what\'s the one metric you\'d track daily?",a:"The key value driver. Usually revenue, profit, or customer metric.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How do you make decisions when you\'re not confident?",a:"Use best available info + test assumptions.",category:"Frameworks",difficulty:"Advanced"},
{q:"Client asks: \"What would YOU do?\"",a:"I\'d give a clear answer: \"Based on what we\'ve discussed, I\'d prioritize X because it has the highest impact and is most feasible.\"",category:"Frameworks",difficulty:"Advanced"},
{q:"When should you change your recommendation?",a:"When new data materially changes the conclusion.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why is structure so important?",a:"It prevents missing key drivers.",category:"Frameworks",difficulty:"Advanced"},
{q:"What is the biggest risk in any recommendation?",a:"Execution.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why is simplicity powerful?",a:"Easier to understand and execute.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What makes a recommendation actionable?",a:"Clear, Practical, Implementable.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do strategies fail in real life?",a:"Poor execution or unrealistic assumptions.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What makes consulting different from other jobs?",a:"Constant ambiguity + pressure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"You can only solve one issue - how do you choose?",a:"Highest impact on objective.",category:"Frameworks",difficulty:"Advanced"},
{q:"Summarize a case in 15 seconds.",a:"Problem + key insight + recommendation.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How do you build credibility quickly?",a:"Be clear, Be logical, Be confident.",category:"Frameworks",difficulty:"Advanced"},
{q:"A strategy looks perfect on paper - what could go wrong?",a:"Execution or external factors.",category:"Case Concepts",difficulty:"Advanced"},
{q:"How do you explain tradeoffs to a client?",a:"Compare pros vs cons clearly.",category:"Frameworks",difficulty:"Advanced"},
{q:"What is the hardest part of decision-making?",a:"Choosing under uncertainty.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What would a partner do differently from a junior consultant?",a:"Focus on big picture, not details.",category:"Behavioral",difficulty:"Advanced"},
{q:"What is the most important skill in consulting?",a:"Structured thinking.",category:"Behavioral",difficulty:"Advanced"},
{q:"If everything is important, what do you do?",a:"Prioritize.",category:"Frameworks",difficulty:"Advanced"},
{q:"What\'s the difference between analysis and insight?",a:"Insight = actionable conclusion.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Final question - what actually gets someone hired?",a:"Clear thinking, confidence, and communication.",category:"Behavioral",difficulty:"Advanced"},
{q:"Our client\'s profits are down, but only on weekdays - what do you look at?",a:"I\'d isolate what\'s different about weekdays: Customer mix, Pricing/promotions, Operating hours. My hypothesis: Different demand patterns or cost structure.",category:"Profitability",difficulty:"Advanced"},
{q:"A company\'s best-selling product is also its least profitable - what do you do?",a:"I\'d evaluate: Raise price, Reduce cost, Shift demand to higher-margin products. Goal: Improve overall profit, not just volume.",category:"Profitability",difficulty:"Advanced"},
{q:"A client\'s growth is entirely driven by one customer - is this a problem?",a:"Yes. High concentration risk. I\'d recommend diversification and strengthening other segments.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company increased marketing spend, but sales didn\'t change - why?",a:"Possible: Wrong channel, Saturation, Poor messaging.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A product is profitable but declining - should you invest in it?",a:"Depends on long-term potential vs opportunity cost.",category:"Profitability",difficulty:"Advanced"},
{q:"A company has strong demand but poor customer reviews - what do you prioritize?",a:"Fix customer experience. Because negative reviews will eventually hurt demand.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has high revenue but low cash flow - why?",a:"Possible: High working capital, Delayed payments.",category:"Profitability",difficulty:"Advanced"},
{q:"A company wants to expand, but operations are already struggling - what do you do?",a:"Fix operations first.",category:"Frameworks",difficulty:"Advanced"},
{q:"A competitor is copying your strategy - what do you do?",a:"Differentiate.",category:"Frameworks",difficulty:"Advanced"},
{q:"A company has declining costs but profits aren\'t improving - why?",a:"Revenue may also be declining.",category:"Profitability",difficulty:"Advanced"},
{q:"A company is profitable but investors are unhappy - why?",a:"Growth expectations not met.",category:"Profitability",difficulty:"Advanced"},
{q:"A client wants to enter a market quickly - what risks do you highlight?",a:"Execution risk, Lack of understanding, Operational strain.",category:"Market Entry",difficulty:"Advanced"},
{q:"A company\'s best employees are leaving - what do you check?",a:"Compensation, Culture, Growth opportunities.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A product has strong demand but low margins - what do you do?",a:"Improve cost structure or pricing.",category:"Profitability",difficulty:"Advanced"},
{q:"A company has multiple small problems - how do you approach?",a:"Identify biggest driver.",category:"Frameworks",difficulty:"Advanced"},
{q:"A company\'s revenue is seasonal - what do you do?",a:"Smooth demand or manage costs.",category:"Profitability",difficulty:"Advanced"},
{q:"A company is growing but losing brand value - what do you do?",a:"Protect brand.",category:"Profitability",difficulty:"Advanced"},
{q:"A company has too many products - what\'s the issue?",a:"Complexity and inefficiency.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company\'s profits are stable but cash is declining - why?",a:"Cash flow issues (working capital, CapEx, or debt payments consuming cash despite stable profits).",category:"Profitability",difficulty:"Advanced"},
{q:"A company is losing customers slowly over time - what does that suggest?",a:"Gradual competitive pressure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company\'s pricing is lower than competitors but still losing share - why?",a:"Price isn\'t the main factor. Likely product, brand, or distribution issues.",category:"Pricing",difficulty:"Advanced"},
{q:"A company has strong sales but weak repeat customers - what do you do?",a:"Improve retention.",category:"Frameworks",difficulty:"Advanced"},
{q:"A company wants to expand globally but has no experience - what do you recommend?",a:"Start small. Test in one market before scaling.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has declining margins but strong growth - is this okay?",a:"Depends on whether long-term value justifies it.",category:"Profitability",difficulty:"Advanced"},
{q:"What\'s the key skill in messy cases?",a:"Prioritization.",category:"Behavioral",difficulty:"Advanced"},
{q:"What if all your assumptions are wrong?",a:"Adjust quickly.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if there is no clear answer?",a:"Provide best judgment.",category:"Case Concepts",difficulty:"Advanced"},
{q:"Why do smart candidates fail cases?",a:"Poor structure.",category:"Behavioral",difficulty:"Advanced"},
{q:"What\'s worse: wrong answer or bad thinking?",a:"Bad thinking.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if the interviewer gives conflicting data?",a:"Clarify or reconcile.",category:"Behavioral",difficulty:"Advanced"},
{q:"What if the case feels impossible?",a:"Break it down.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if you get stuck?",a:"Reframe.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if your math is wrong?",a:"Correct quickly.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if you don\'t understand the question?",a:"Ask clarifying questions.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if you run out of time?",a:"Give best answer.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if interviewer interrupts you?",a:"Adapt.",category:"Behavioral",difficulty:"Advanced"},
{q:"What if your structure doesn\'t fit?",a:"Adjust.",category:"Frameworks",difficulty:"Advanced"},
{q:"What if client changes objective mid-case?",a:"Reframe.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if two answers are both valid?",a:"Choose and justify.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if data contradicts your hypothesis?",a:"Update.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if the problem is unclear?",a:"Clarify.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if the client is wrong?",a:"Guide carefully.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if you disagree with interviewer?",a:"Stay respectful.",category:"Behavioral",difficulty:"Advanced"},
{q:"What if you panic?",a:"Slow down.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if you overcomplicate?",a:"Simplify.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if nothing stands out?",a:"Prioritize.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if everything matters?",a:"Focus.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if the case is easy?",a:"Don\'t overthink.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What if it\'s too hard?",a:"Stay structured.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What\'s the biggest trap overall?",a:"Losing structure.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What would you do differently from competitors?",a:"Differentiate on the dimension that matters most to customers.",category:"Frameworks",difficulty:"Advanced"},
{q:"What\'s the biggest lever in any business?",a:"Revenue - it\'s the top line that everything else flows from.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What\'s the fastest way to improve profit?",a:"Fix the biggest driver - whether that\'s revenue or the largest cost bucket.",category:"Profitability",difficulty:"Advanced"},
{q:"What\'s the biggest risk in growth?",a:"Overexpansion beyond what operations or unit economics can support.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters more: speed or accuracy?",a:"Balance - but in consulting, speed with directional accuracy usually wins over slow perfection.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What drives value?",a:"Profit + growth, specifically sustainable profit growth over time.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What\'s the simplest strategy?",a:"Focus - do fewer things better rather than many things poorly.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What makes a strategy good?",a:"It\'s actionable, differentiated, and aligned with capabilities.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What makes a strategy bad?",a:"It\'s unrealistic, undifferentiated, or ignores execution constraints.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What is insight?",a:"An actionable idea that changes the decision - not just a data point.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most to clients?",a:"Results - tangible impact on their business.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in communication?",a:"Clarity - say what you mean in the fewest words possible.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in thinking?",a:"Structure - it ensures you don\'t miss key drivers.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in cases?",a:"Prioritization - knowing what to focus on and what to ignore.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in consulting?",a:"Impact - everything else is a means to this end.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in interviews?",a:"How you think - not what you know.",category:"Behavioral",difficulty:"Advanced"},
{q:"What matters most in decisions?",a:"Understanding the tradeoffs clearly.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in growth?",a:"Sustainability - growth that destroys value is worse than no growth.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in profit?",a:"Margins - revenue without margin is just activity, not profit.",category:"Profitability",difficulty:"Advanced"},
{q:"What matters most in strategy?",a:"Focus - a strategy that tries to do everything does nothing well.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in leadership?",a:"Judgment - the ability to make good decisions under uncertainty.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most in execution?",a:"Discipline - consistently doing what was planned, not what\'s easiest.",category:"Case Concepts",difficulty:"Advanced"},
{q:"What matters most overall?",a:"Clear thinking - it\'s the foundation of everything else in consulting.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company has a 40% market share but is still not profitable - what could explain this?",a:"High market share doesn\'t guarantee profit. Possible causes: aggressive pricing to gain share, high fixed cost base not yet covered, or spending heavily on growth (marketing, R&D). I\'d check whether the cost structure is sustainable at this scale or if the business model is fundamentally broken.",category:"Profitability",difficulty:"Advanced"},
{q:"Two identical products are sold at different prices in the same market - why might this work?",a:"Different customer segments value different things. One may be sold through premium channels with better service, branding, or convenience. The other may be a no-frills option. This is price discrimination - capturing more total value by segmenting willingness to pay.",category:"Pricing",difficulty:"Advanced"},
{q:"A company\'s employees are highly productive but the company is still losing money - how?",a:"Productivity measures output per worker, not profitability. The company could have: wrong pricing, excessive overhead, high debt service, or be in a market where even maximum efficiency can\'t cover costs. I\'d separate operational efficiency from business model viability.",category:"Profitability",difficulty:"Advanced"},
{q:"Our client acquired a competitor but profits got worse, not better - what happened?",a:"Common post-merger issues: integration costs exceeded plan, customer attrition during transition, culture clash reducing productivity, synergies were overestimated, or the acquirer overpaid. I\'d diagnose which factor is the largest drag and whether the issues are temporary or structural.",category:"Case Concepts",difficulty:"Advanced"},
{q:"A company dominates its home market - should it go international or launch new products?",a:"I\'d compare: international expansion leverages existing product with new customers (lower product risk, higher market risk), while new products serve existing customers differently (higher product risk, lower market risk). The right choice depends on which risk the company is better equipped to manage and where the larger profit pool sits.",category:"Strategy",difficulty:"Advanced"},
{q:"How would you estimate the total revenue of all coffee shops in Manhattan?",a:"I\'d structure: number of blocks in Manhattan (~200 N-S x ~12 E-W), coffee shops per block (~2-3 in commercial areas, fewer residential), average daily revenue per shop (transactions x average ticket). Roughly 1,500 shops x $2,000/day x 365 = ~$1.1B annually. The key is showing logical building blocks, not the exact number.",category:"Market Sizing",difficulty:"Intermediate"},
{q:"Your client\'s NPS score is high but revenue is flat - what\'s the disconnect?",a:"Customer satisfaction doesn\'t automatically translate to spending. Possible explanations: customers love the product but buy infrequently, the market is saturated so there are no new customers to convert, pricing hasn\'t kept up with value delivered, or competitors offer similar satisfaction at lower cost. I\'d investigate the gap between satisfaction and purchase behavior.",category:"Case Concepts",difficulty:"Advanced"},
];