import { Flashcard } from './ib-flashcard-data';
export const CONSULTING_FLASHCARDS: Flashcard[] = [
  // Frameworks
  { q: "What is the MECE principle?", a: "Mutually Exclusive, Collectively Exhaustive — categories should not overlap and should cover all possibilities. The foundation of structured thinking.", category: "Frameworks" },
  { q: "What is a profitability framework?", a: "Revenue - Costs = Profit. Break revenue into price × volume. Break costs into fixed vs variable. Identify which lever is driving the issue.", category: "Frameworks" },
  { q: "How would you structure a market entry case?", a: "Market attractiveness (size, growth, competition), company capability (resources, brand, distribution), entry mode (organic, JV, acquisition), financial viability (investment, timeline, returns).", category: "Frameworks" },
  { q: "How would you structure a pricing case?", a: "Cost-based (cost + margin), value-based (willingness to pay), competition-based (relative positioning). Consider elasticity, segmentation, and channel.", category: "Frameworks" },
  { q: "What is a growth strategy framework?", a: "Organic (new products, new markets, penetration) vs inorganic (M&A, partnerships). Evaluate feasibility, investment, risk, and time horizon.", category: "Frameworks" },
  { q: "What is Porter's Five Forces?", a: "Industry rivalry, threat of new entrants, threat of substitutes, buyer power, supplier power. Determines industry attractiveness and profitability.", category: "Frameworks" },
  { q: "What is a 3C/4C framework?", a: "Company, Customers, Competitors (+ Channel in 4C). Useful for strategy and competitive positioning cases.", category: "Frameworks" },
  { q: "When should you NOT use a framework?", a: "When it doesn't fit the problem. Frameworks are starting points — the best candidates customize their structure to the specific case.", category: "Frameworks" },
  { q: "What is an issue tree?", a: "A hierarchical breakdown of a problem into sub-issues. Each level should be MECE. Helps identify root causes systematically.", category: "Frameworks" },
  { q: "How do you structure a cost reduction case?", a: "Fixed costs (rent, salaries, depreciation) vs variable costs (materials, labor, distribution). Identify largest buckets, benchmark against peers, prioritize impact vs feasibility.", category: "Frameworks" },
  // Market Sizing
  { q: "How would you estimate the number of gas stations in the US?", a: "~330M people, ~250M cars, each fills up ~once/week. A station serves ~250 cars/day × 7 = 1,750/week. 250M fills/week ÷ 1,750 ≈ ~143K stations. Actual is ~150K.", category: "Market Sizing" },
  { q: "How would you estimate annual revenue of a Starbucks store?", a: "~16 hrs/day, ~300 customers/day at avg $5 ticket = $1,500/day × 365 = ~$550K/year. Actual avg is ~$1.5M due to higher traffic in many locations.", category: "Market Sizing" },
  { q: "What is a top-down vs bottom-up market sizing?", a: "Top-down starts with total market and narrows (TAM → SAM → SOM). Bottom-up builds from unit economics (customers × usage × price). Best to triangulate both.", category: "Market Sizing" },
  { q: "How would you estimate the US wedding industry size?", a: "~330M people, ~2M weddings/year, avg cost ~$30K = ~$60B. Cross-check with known data points.", category: "Market Sizing" },
  { q: "What makes a good market sizing answer?", a: "Clear structure, reasonable assumptions stated explicitly, clean math, sanity check at the end. Process matters more than precision.", category: "Market Sizing" },
  { q: "How would you estimate number of tennis balls sold in the US annually?", a: "~20M tennis players, average player uses ~20 balls/year = ~400M balls. Add tournament/club usage for ~450-500M total.", category: "Market Sizing" },
  { q: "How would you size the US pet food market?", a: "~90M dog-owning households, ~50 lbs food/dog/year at ~$2/lb = ~$9B dogs. Add ~$4B cats. Total ~$13B. (Actual ~$50B+ including premium/treats.)", category: "Market Sizing" },
  // Case Concepts
  { q: "What is breakeven analysis?", a: "Fixed Costs / (Price - Variable Cost per Unit) = Breakeven Volume. The point where total revenue equals total costs.", category: "Case Concepts" },
  { q: "What is customer lifetime value (CLV)?", a: "Average revenue per customer × gross margin × average customer lifespan. Used to evaluate acquisition spending and retention investments.", category: "Case Concepts" },
  { q: "What is price elasticity of demand?", a: "% change in quantity demanded / % change in price. Elastic (>1) means price-sensitive; inelastic (<1) means price-insensitive.", category: "Case Concepts" },
  { q: "What is a value chain?", a: "The sequence of activities a company performs to deliver a product/service: R&D → procurement → production → distribution → marketing → sales → service.", category: "Case Concepts" },
  { q: "What is economies of scale?", a: "Cost advantages from increased volume — fixed costs spread over more units, purchasing power increases, operational efficiency improves.", category: "Case Concepts" },
  { q: "What is a switching cost?", a: "The cost (financial, time, effort) a customer incurs to switch to a competitor. High switching costs create customer stickiness and pricing power.", category: "Case Concepts" },
  { q: "What is cannibalization?", a: "When a new product takes sales from an existing product in the same company's portfolio. Must consider net impact, not just new product revenue.", category: "Case Concepts" },
  { q: "What is the difference between organic and inorganic growth?", a: "Organic = internal growth (new products, expansion). Inorganic = growth through M&A, JVs, or partnerships. Each has different risk/speed profiles.", category: "Case Concepts" },
  { q: "What is a synergy in M&A?", a: "Value created by combining two companies that wouldn't exist separately. Cost synergies (headcount, procurement) are more reliable than revenue synergies.", category: "Case Concepts" },
  { q: "What is market share and why does it matter?", a: "Company revenue / total market revenue. Indicates competitive position, pricing power, and scale advantages. Trends matter more than absolute level.", category: "Case Concepts" },
  { q: "What is a moat?", a: "A durable competitive advantage: brand, network effects, switching costs, scale, regulatory barriers, IP, or cost advantages that protect against competition.", category: "Case Concepts" },
  { q: "What is NPV?", a: "Net Present Value — sum of discounted future cash flows minus initial investment. Positive NPV = project creates value above required return.", category: "Case Concepts" },
  { q: "What is payback period?", a: "Time to recover the initial investment from cash flows. Simple but ignores time value of money and cash flows beyond payback.", category: "Case Concepts" },
  { q: "What is capacity utilization?", a: "Actual output / maximum possible output. Low utilization means fixed costs are spread over fewer units, hurting margins.", category: "Case Concepts" },
  // Mental Math
  { q: "What is 17% of 400?", a: "10% = 40, 7% = 28. Total = 68.", category: "Mental Math" },
  { q: "If revenue grows 8% annually for 3 years from $100M, what's the end value?", a: "$100M × 1.08³ ≈ $100M × 1.26 = ~$126M. Quick trick: 8% × 3 = 24% simple, add ~2% for compounding.", category: "Mental Math" },
  { q: "What is 15% of $3.2B?", a: "10% = $320M, 5% = $160M. Total = $480M.", category: "Mental Math" },
  { q: "A $50 product has 40% gross margin. What's COGS per unit?", a: "$50 × (1 - 0.40) = $50 × 0.60 = $30 COGS per unit.", category: "Mental Math" },
  { q: "If a company has $200M revenue and 25% EBITDA margin, what's EBITDA?", a: "$200M × 0.25 = $50M.", category: "Mental Math" },
  { q: "What is the Rule of 72?", a: "72 / growth rate = years to double. At 8% growth, it takes ~9 years to double. Quick compounding estimation.", category: "Mental Math" },
  // Behavioral
  { q: "Why consulting?", a: "Steep learning curve, exposure to diverse industries and problems, structured problem-solving, team-based work, and direct client impact. Be specific about what attracts you.", category: "Behavioral" },
  { q: "Why this firm specifically?", a: "Reference specific practice areas, culture, people you've met, training model, or case studies. Generic answers fail — specificity wins.", category: "Behavioral" },
  { q: "Tell me about a time you led a team.", a: "Use STAR. Emphasize how you aligned the team, delegated, handled disagreements, and delivered results. Show leadership through influence, not authority.", category: "Behavioral" },
  { q: "Tell me about a time you solved a complex problem.", a: "Structure the problem, show how you broke it down, what analysis you did, what insight emerged, and what action resulted. Show structured thinking.", category: "Behavioral" },
  { q: "What is your biggest accomplishment?", a: "Choose something with real stakes, clear action, and measurable impact. Tie it to skills relevant for consulting.", category: "Behavioral" },
  { q: "How do you handle ambiguity?", a: "Show comfort with uncertainty. Describe structuring the unknown, making reasonable assumptions, iterating, and communicating clearly despite incomplete info.", category: "Behavioral" },
];
