// Technical Practice Flashcards — Investment Banking (300+ cards)
export type Flashcard = { q: string; a: string; category: string };

export const IB_FLASHCARDS: Flashcard[] = [
  // ── ACCOUNTING (1-60) ──
  { q: "Walk me through the three financial statements.", a: "The income statement shows revenue, expenses, and net income over a period. The balance sheet shows assets, liabilities, and equity at a point in time. The cash flow statement shows how cash changed via operating, investing, and financing activities. Net income links to retained earnings and is the starting point for CFO.", category: "Accounting" },
  { q: "How do the three statements link together?", a: "Net income flows from the IS to the top of the CFS and into retained earnings on the BS. The CFS adjusts NI for non-cash items and working capital to get CFO, then adds CFI and CFF to get ending cash, which ties to the BS.", category: "Accounting" },
  { q: "If depreciation increases by $10, walk through the impact (25% tax rate).", a: "IS: EBIT down $10, taxes down $2.5, NI down $7.5. CFS: NI down $7.5, add back $10 D&A, cash up $2.5. BS: Cash +$2.5, PP&E -$10, RE -$7.5. Balances.", category: "Accounting" },
  { q: "Why does depreciation increase cash flow?", a: "Depreciation is a non-cash expense. It reduces pre-tax income and thus taxes, creating a tax shield. The depreciation is then added back on the CFS, so net cash increases by the tax savings.", category: "Accounting" },
  { q: "If CapEx increases by $20, walk through the statements.", a: "IS: No immediate impact (CapEx is capitalized). CFS: Cash decreases $20 in CFI. BS: Cash -$20, PP&E +$20. No change to NI or equity. Assets unchanged net.", category: "Accounting" },
  { q: "What is the difference between CapEx and depreciation?", a: "CapEx is a real cash outflow to acquire or improve long-lived assets. Depreciation is the later non-cash accounting allocation of that asset's cost over its useful life.", category: "Accounting" },
  { q: "If accounts receivable increases by $10, what happens?", a: "Revenue was recognized but cash not collected. IS: Revenue up (assume $10, 25% tax → NI +$7.5). CFS: NI +$7.5 but AR increase subtracts $10 → cash -$2.5. BS: Cash -$2.5, AR +$10, RE +$7.5.", category: "Accounting" },
  { q: "Why does an increase in AR reduce cash flow?", a: "Because the company recognized revenue but hasn't collected the cash yet. The revenue boosts NI, but the AR increase in working capital offsets that on the CFS.", category: "Accounting" },
  { q: "If accounts payable increases by $10, what happens?", a: "Expense recognized but not paid. IS: Expense +$10, NI -$7.5. CFS: NI -$7.5, AP increase adds $10 → cash +$2.5. BS: Cash +$2.5, AP +$10, RE -$7.5.", category: "Accounting" },
  { q: "If inventory increases by $10 (purchased, not sold), walk through.", a: "IS: No impact (inventory not yet expensed as COGS). CFS: Working capital use of $10 in CFO. BS: Cash -$10, inventory +$10. Assets unchanged net.", category: "Accounting" },
  { q: "What is working capital?", a: "Current operating assets minus current operating liabilities (typically AR + inventory - AP - accrued expenses), excluding cash and debt. It measures cash tied up in day-to-day operations.", category: "Accounting" },
  { q: "Why does an increase in working capital reduce cash flow?", a: "More cash is tied up in operations — either collected later (AR), spent on unsold goods (inventory), or obligations are being paid faster (AP down).", category: "Accounting" },
  { q: "What is deferred revenue and why is it a liability?", a: "Cash collected before revenue is earned. It's a liability because the company owes goods or services. As performance occurs, it's recognized as revenue.", category: "Accounting" },
  { q: "If deferred revenue increases by $30, what happens?", a: "Cash received, no revenue yet. IS: No impact. CFS: Deferred revenue increase is a source of cash in CFO (+$30). BS: Cash +$30, deferred revenue liability +$30.", category: "Accounting" },
  { q: "What are accrued expenses?", a: "Expenses recognized on the IS before cash is paid. Example: wages incurred but not yet paid. The accrued liability increases on the BS.", category: "Accounting" },
  { q: "Walk through a debt issuance of $100.", a: "IS: No immediate impact. CFS: Financing inflow +$100. BS: Cash +$100, debt +$100. Future periods will see interest expense.", category: "Accounting" },
  { q: "Walk through a dividend payment of $20.", a: "IS: No impact (dividends are not expenses). CFS: Financing outflow -$20. BS: Cash -$20, retained earnings -$20.", category: "Accounting" },
  { q: "What is the difference between accrual and cash accounting?", a: "Cash accounting records when cash moves. Accrual accounting records revenue when earned and expenses when incurred, regardless of cash timing. Accrual better reflects economic performance.", category: "Accounting" },
  { q: "Why is EBITDA not cash flow?", a: "EBITDA ignores CapEx, working capital changes, cash taxes, and interest. A company can have strong EBITDA but poor cash generation if it's capital-intensive or has deteriorating working capital.", category: "Accounting" },
  { q: "What is the difference between EBIT and EBITDA?", a: "EBITDA adds back D&A to EBIT. EBIT is more meaningful for capital-intensive businesses because D&A partially reflects the cost of maintaining assets.", category: "Accounting" },
  { q: "What is goodwill?", a: "The excess of purchase price over the fair value of identifiable net assets in an acquisition. It reflects synergies, brand value, and control premium paid.", category: "Accounting" },
  { q: "How is goodwill created?", a: "Goodwill = Purchase Price - Fair Value of Identifiable Net Assets Acquired. It arises only in business combinations.", category: "Accounting" },
  { q: "What is goodwill impairment?", a: "A non-cash write-down when the carrying value of a reporting unit exceeds its fair value. It reduces assets and net income but is added back on the CFS.", category: "Accounting" },
  { q: "What is stock-based compensation?", a: "A non-cash expense reflecting equity granted to employees. It reduces NI but is added back in CFO. However, it's economically real because it dilutes shareholders.", category: "Accounting" },
  { q: "What are deferred taxes?", a: "Arise from timing differences between book and tax treatment. Deferred tax liabilities mean taxes owed later; deferred tax assets mean future tax benefits.", category: "Accounting" },
  { q: "What is the bad debt allowance?", a: "An estimate of receivables that won't be collected. Dr Bad Debt Expense / Cr Allowance for Doubtful Accounts. Separates estimation from actual write-offs.", category: "Accounting" },
  { q: "What is operating leverage?", a: "A business with high fixed costs sees profits rise disproportionately when revenue grows, but also collapse faster when revenue falls.", category: "Accounting" },
  { q: "What is gross margin?", a: "Gross Profit / Revenue. It reveals pricing power, input cost pressure, product mix, and business model quality.", category: "Accounting" },
  { q: "What does Return on Equity (ROE) measure?", a: "Net Income / Shareholders' Equity. It measures how efficiently equity capital generates profit. Can be inflated by leverage.", category: "Accounting" },
  { q: "What does Return on Assets (ROA) measure?", a: "Net Income / Total Assets. Measures how efficiently total assets generate earnings, independent of capital structure.", category: "Accounting" },
  { q: "What is the current ratio?", a: "Current Assets / Current Liabilities. Measures short-term liquidity — whether the company can cover near-term obligations.", category: "Accounting" },
  { q: "What is Days Sales Outstanding (DSO)?", a: "AR / Revenue × 365. Measures how quickly the company collects cash from customers. Rising DSO can signal collection issues.", category: "Accounting" },
  { q: "What is the cash conversion cycle?", a: "DSO + DIO - DPO. Measures how long cash is tied up from purchasing inventory to collecting from customers.", category: "Accounting" },
  { q: "Why might net income be negative while cash flow is positive?", a: "Non-cash charges like D&A or impairments reduce NI without using cash. Favorable working capital movements or deferred revenue inflows can also boost cash above NI.", category: "Accounting" },
  { q: "What is a prepaid expense?", a: "Cash paid for a future benefit (e.g., insurance paid upfront). It's an asset that becomes an expense over the benefit period through adjusting entries.", category: "Accounting" },
  { q: "What is revenue recognition?", a: "Revenue is recognized when control of goods/services transfers and the entity is entitled to consideration — not necessarily when cash is received.", category: "Accounting" },
  { q: "What is the matching principle?", a: "Expenses should be recognized in the same period as the revenues they help generate. Example: COGS is recognized when inventory is sold.", category: "Accounting" },
  { q: "What is an adjusting entry?", a: "Period-end entries to correct timing — accruals, deferrals, depreciation, allowances. Without them, statements may be materially misstated.", category: "Accounting" },
  { q: "What is retained earnings?", a: "Cumulative net income minus cumulative dividends paid. It links the income statement to the balance sheet through equity.", category: "Accounting" },
  { q: "What is treasury stock?", a: "Shares repurchased by the company. It reduces equity. It is a contra-equity account.", category: "Accounting" },

  // ── VALUATION (61-130) ──
  { q: "What are the three main valuation methodologies?", a: "1) DCF (intrinsic value from projected cash flows), 2) Comparable Companies / Trading Comps (market-based peer multiples), 3) Precedent Transactions (acquisition multiples from past deals).", category: "Valuation" },
  { q: "What is Enterprise Value?", a: "Value of the company's core operations to all capital providers. EV = Equity Value + Debt + Preferred + Minority Interest - Cash.", category: "Valuation" },
  { q: "What is Equity Value?", a: "Value attributable to common shareholders. Often = Share Price × Diluted Shares Outstanding.", category: "Valuation" },
  { q: "Why do you subtract cash from Enterprise Value?", a: "Cash is a non-operating asset. If you acquired the company, the cash on hand would reduce the effective net cost of acquiring the operations.", category: "Valuation" },
  { q: "Why do you add debt to Enterprise Value?", a: "Debt represents a claim on the company's value that must be repaid. An acquirer takes on this obligation, so it's part of the total cost of the enterprise.", category: "Valuation" },
  { q: "What metrics pair with Enterprise Value?", a: "Pre-interest, capital-structure-neutral metrics: Revenue, EBITDA, EBIT, Unlevered FCF.", category: "Valuation" },
  { q: "What metrics pair with Equity Value?", a: "Post-interest, equity-specific metrics: Net Income, EPS, Levered FCF, Book Value.", category: "Valuation" },
  { q: "Why is EV/Net Income wrong?", a: "It's a mismatch — EV includes both debt and equity holders' claims, while NI is only available to equity holders after interest.", category: "Valuation" },
  { q: "Walk me through a DCF.", a: "1) Project cash flows 5-10 years, 2) Calculate UFCF, 3) Determine WACC, 4) Estimate terminal value, 5) Discount all back to present, 6) Sum for Enterprise Value, 7) Bridge to Equity Value, 8) Divide by diluted shares for implied price.", category: "Valuation" },
  { q: "What is Unlevered Free Cash Flow?", a: "UFCF = EBIT × (1 - Tax Rate) + D&A - CapEx - Change in NWC. Cash generated by operations after tax and reinvestment, before financing.", category: "Valuation" },
  { q: "Why use UFCF instead of levered cash flow in a DCF?", a: "UFCF is capital-structure neutral, making it appropriate for valuing the entire firm. Using levered cash flow would bake in financing decisions.", category: "Valuation" },
  { q: "What is WACC?", a: "Weighted Average Cost of Capital = (E/V) × Cost of Equity + (D/V) × Cost of Debt × (1-T). The blended required return of all capital providers.", category: "Valuation" },
  { q: "Why is WACC the appropriate discount rate for UFCF?", a: "Because UFCF belongs to all capital providers (debt + equity), and WACC reflects the blended required return of those providers.", category: "Valuation" },
  { q: "What is the Cost of Equity formula (CAPM)?", a: "Cost of Equity = Risk-Free Rate + Beta × Equity Risk Premium. It reflects the return equity investors require for bearing risk.", category: "Valuation" },
  { q: "What is Beta?", a: "A measure of a stock's sensitivity to market movements. Higher beta = more volatile relative to the market.", category: "Valuation" },
  { q: "Why do you unlever and relever Beta?", a: "Observed beta reflects both business risk and leverage. You unlever comps' betas to isolate business risk, then relever for the target's capital structure.", category: "Valuation" },
  { q: "Why is cost of debt tax-affected in WACC?", a: "Interest expense is tax-deductible, creating a tax shield that reduces the effective cost of debt financing.", category: "Valuation" },
  { q: "Why use market values in WACC, not book values?", a: "WACC reflects current investor opportunity costs and market expectations, which are better captured by market values.", category: "Valuation" },
  { q: "What are the two methods for Terminal Value?", a: "1) Gordon Growth: TV = Final UFCF × (1+g) / (WACC-g). 2) Exit Multiple: TV = Final Year EBITDA × Exit Multiple.", category: "Valuation" },
  { q: "What is a reasonable perpetual growth rate?", a: "Usually 2-3%, tied to long-term GDP or inflation. A rate above nominal GDP growth is hard to justify indefinitely.", category: "Valuation" },
  { q: "Why does terminal value often dominate a DCF?", a: "The explicit forecast is usually only 5-10 years, while the business operates indefinitely beyond that. Terminal value captures all that residual value.", category: "Valuation" },
  { q: "What increases DCF valuation?", a: "Higher revenue growth, higher margins, lower WACC, higher terminal growth rate, lower CapEx, favorable working capital.", category: "Valuation" },
  { q: "Why does increasing WACC lower valuation?", a: "Future cash flows are discounted more heavily, reducing their present value.", category: "Valuation" },
  { q: "What is the mid-year convention?", a: "Discounting cash flows as if they arrive mid-year rather than year-end. It slightly increases valuation by reducing the discount period.", category: "Valuation" },
  { q: "What are the key sensitivities in a DCF?", a: "WACC, terminal growth rate / exit multiple, margin assumptions, revenue growth, CapEx intensity, working capital.", category: "Valuation" },
  { q: "When is a DCF less useful?", a: "For companies with highly unpredictable cash flows, early-stage companies with no steady-state economics, or financial institutions where debt is operational.", category: "Valuation" },
  { q: "Why is EV/EBITDA commonly used?", a: "EBITDA is capital-structure neutral and widely available, making it useful for comparing companies with different leverage levels.", category: "Valuation" },
  { q: "Why can P/E be misleading?", a: "Net income is affected by capital structure, non-operating items, tax differences, and accounting quirks, distorting comparability.", category: "Valuation" },
  { q: "What is LTM vs NTM?", a: "LTM = Last Twelve Months (historical). NTM = Next Twelve Months (forward). Forward multiples are often more relevant because markets price expectations.", category: "Valuation" },
  { q: "How do you select comparable companies?", a: "Match on business model, end markets, growth profile, margin profile, capital intensity, and size. No comp set is perfect.", category: "Valuation" },
  { q: "Why do precedent transactions often show higher values than trading comps?", a: "Because acquisitions include a control premium, expected synergies, scarcity value, and competitive auction dynamics.", category: "Valuation" },
  { q: "What is a control premium?", a: "The extra amount buyers pay above the unaffected share price to acquire control of a company.", category: "Valuation" },
  { q: "What is a valuation football field?", a: "A visual showing ranges from different valuation methods (DCF, comps, precedents) side by side to identify overlap and central tendency.", category: "Valuation" },
  { q: "How do higher interest rates affect valuation?", a: "They increase discount rates, lowering PV of future cash flows. They also compress market multiples. The effect is greater for long-duration, high-growth assets.", category: "Valuation" },
  { q: "Why can two companies with the same EBITDA trade at different multiples?", a: "Differences in growth, margins, ROIC, capital intensity, risk, cash conversion, and business quality all justify different multiples.", category: "Valuation" },
  { q: "What is maintenance CapEx vs growth CapEx?", a: "Maintenance CapEx sustains current operations. Growth CapEx expands capacity. EBITDA may overstate free cash flow if maintenance CapEx is high.", category: "Valuation" },
  { q: "How do you value banks differently?", a: "Traditional DCF and EV/EBITDA are less useful because debt is operational. Use P/Book, P/E, and ROE-based metrics instead.", category: "Valuation" },
  { q: "What is a circular reference in modeling?", a: "When interest expense depends on debt, debt depends on cash flow, and cash flow depends on interest. Solved with iteration or average debt balances.", category: "Valuation" },

  // ── M&A (131-200) ──
  { q: "What is accretion/dilution?", a: "Measures whether a deal increases (accretive) or decreases (dilutive) the acquirer's EPS. Accretive if pro forma EPS > standalone EPS.", category: "M&A" },
  { q: "Is accretive always good?", a: "No. A deal can be accretive but strategically terrible. True value creation depends on paying less than the target is worth including synergies.", category: "M&A" },
  { q: "What makes a deal accretive?", a: "Target has lower P/E than buyer (stock deal), cheap debt financing, high synergies, limited purchase accounting charges, reasonable premium.", category: "M&A" },
  { q: "What makes a deal dilutive?", a: "High premium, expensive equity issuance, low target earnings vs price, high financing costs, significant incremental D&A from write-ups.", category: "M&A" },
  { q: "Walk through a simplified accretion/dilution analysis.", a: "Start with buyer standalone EPS. Add target NI + after-tax synergies - after-tax financing costs - foregone interest - incremental D&A. Divide by new share count. Compare to standalone EPS.", category: "M&A" },
  { q: "Why does relative P/E matter in stock deals?", a: "If the buyer has a higher P/E, it's using 'expensive' shares to buy 'cheaper' earnings, which tends to be accretive. But synergies, premium, and accounting also matter.", category: "M&A" },
  { q: "Cash deal vs stock deal — key differences?", a: "Cash: no dilution to ownership, but potential interest expense. Stock: no cash burden, but share count increases and EPS impact depends on relative P/E.", category: "M&A" },
  { q: "What are cost synergies?", a: "Savings from combining operations: headcount reduction, facility consolidation, procurement savings, eliminating duplicate overhead.", category: "M&A" },
  { q: "What are revenue synergies?", a: "Revenue gains from cross-selling, bundling, geographic expansion, or customer access. Harder to quantify and execute than cost synergies.", category: "M&A" },
  { q: "Why are cost synergies more credible?", a: "They're more tangible, faster to model, and more controllable than revenue synergies which depend on customer behavior and execution.", category: "M&A" },
  { q: "What is Purchase Price Allocation (PPA)?", a: "Allocating the purchase price to acquired assets at fair value, assumed liabilities, newly identified intangibles, and residual goodwill.", category: "M&A" },
  { q: "How does PPA affect earnings?", a: "Asset step-ups create higher D&A and intangible amortization, which reduce post-deal earnings and can make deals more dilutive.", category: "M&A" },
  { q: "Why might a company pursue an acquisition?", a: "Growth, new markets, technology, cost synergies, market share, eliminate competition, capital reallocation, or defensive positioning.", category: "M&A" },
  { q: "Strategic buyer vs financial buyer?", a: "Strategic = operating company, can pay more due to synergies. Financial = PE firm, focused on returns via leverage and cash flow, less likely to pay for speculative synergies.", category: "M&A" },
  { q: "Why can a strategic buyer pay more?", a: "Because they can generate synergies (cost savings, revenue enhancement) that increase the target's value to them specifically.", category: "M&A" },
  { q: "What is a fairness opinion?", a: "A formal opinion from a bank or advisor that the financial terms of a transaction are fair to shareholders from a financial point of view.", category: "M&A" },
  { q: "What is a hostile takeover?", a: "An acquisition where the buyer bypasses management resistance, often going directly to shareholders via tender offer or proxy fight.", category: "M&A" },
  { q: "What is a tender offer?", a: "A direct offer to shareholders to buy their shares at a premium, bypassing board approval.", category: "M&A" },
  { q: "What are sources and uses in M&A?", a: "Sources = how the deal is funded (debt, equity, cash). Uses = what the money pays for (equity purchase, refinancing, fees). Sources must equal uses.", category: "M&A" },
  { q: "What is a merger vs an acquisition?", a: "Economically similar, but legally a merger combines two entities into one, while an acquisition is one entity purchasing another. Often used interchangeably.", category: "M&A" },
  { q: "What is a sell-side process?", a: "When an investment bank advises a company looking to sell itself, running an auction or negotiated sale to maximize value.", category: "M&A" },
  { q: "What is a buy-side mandate?", a: "When an investment bank advises a buyer on identifying targets, valuation, negotiation, due diligence, and deal execution.", category: "M&A" },
  { q: "What is an earnout?", a: "Contingent consideration where part of the purchase price depends on the target meeting future performance milestones.", category: "M&A" },
  { q: "What is a reverse merger?", a: "A private company acquires a public company's shell to become publicly traded without a traditional IPO.", category: "M&A" },
  { q: "What is a breakup fee?", a: "A penalty the target pays to the buyer if the deal falls through for certain reasons. It protects the buyer's investment in the process.", category: "M&A" },
  { q: "What is due diligence?", a: "The investigation of a target's financials, operations, legal matters, and risks before completing a transaction.", category: "M&A" },
  { q: "What is a definitive agreement?", a: "The binding contract between buyer and seller that outlines all material terms of the transaction.", category: "M&A" },
  { q: "What is a material adverse change (MAC) clause?", a: "A provision that allows the buyer to walk away if the target's business materially deteriorates between signing and closing.", category: "M&A" },

  // ── LBO (201-260) ──
  { q: "What is an LBO?", a: "A Leveraged Buyout is an acquisition where a PE sponsor buys a company using significant debt, contributes equity, uses the company's cash flow to repay debt, and aims to exit at a higher equity value.", category: "LBO" },
  { q: "Why do PE firms use leverage?", a: "Debt is cheaper than equity and reduces the equity check required. If the company can service and repay debt, equity returns are magnified. But leverage also increases risk.", category: "LBO" },
  { q: "What drives LBO returns?", a: "Entry multiple, leverage amount, EBITDA growth, cash flow for debt paydown, exit multiple, and holding period.", category: "LBO" },
  { q: "What makes a good LBO candidate?", a: "Stable/predictable cash flow, defensible market position, moderate CapEx, manageable working capital, operational improvement opportunities, and assets supporting debt.", category: "LBO" },
  { q: "What makes a bad LBO candidate?", a: "Highly volatile earnings, heavy cyclicality, massive CapEx needs, negative cash flow, customer concentration, or severe regulatory risk.", category: "LBO" },
  { q: "Walk through a simplified LBO.", a: "Entry: 8.0x EBITDA ($100) = $800 EV. Debt $500, equity $300. EBITDA grows to $130, debt paid to $250. Exit at 8.0x = $1,040 EV. Exit equity = $790. Strong return on $300 invested.", category: "LBO" },
  { q: "What are the sources of value creation in an LBO?", a: "1) EBITDA/revenue growth, 2) Debt paydown (deleveraging), 3) Multiple expansion. Strong candidates decompose returns into these three.", category: "LBO" },
  { q: "What is IRR?", a: "Internal Rate of Return — the annualized return that equates the initial equity investment with future equity proceeds. Higher IRR = better equity return.", category: "LBO" },
  { q: "What increases IRR?", a: "Lower entry multiple, higher exit multiple, stronger EBITDA growth, more debt paydown, lower equity check, shorter holding period (all else equal).", category: "LBO" },
  { q: "Why might a strategic buyer outbid a sponsor?", a: "Strategics can pay more because of synergies. Sponsors are constrained by required return thresholds and debt capacity.", category: "LBO" },
  { q: "What happens to returns if the exit multiple declines?", a: "IRR and MOIC decrease because exit equity value falls. This is why entry price discipline and EBITDA growth matter — they buffer against multiple compression.", category: "LBO" },
  { q: "What is a MOIC?", a: "Multiple of Invested Capital = Exit Equity / Initial Equity. A 2.5x MOIC means the sponsor got $2.50 back for every $1 invested.", category: "LBO" },
  { q: "What are typical LBO debt instruments?", a: "Revolver, term loans (senior secured), senior notes, subordinated debt, mezzanine. Each has different priority, cost, and covenant structures.", category: "LBO" },
  { q: "What is a sources and uses table?", a: "Shows where money comes from (sponsor equity, debt tranches, seller rollover) and where it goes (equity purchase, refinancing, fees). Must balance.", category: "LBO" },
  { q: "Why do sponsors care about free cash flow?", a: "FCF is used to pay down debt. More FCF = faster deleveraging = more equity value at exit = higher IRR.", category: "LBO" },
  { q: "What is a dividend recapitalization?", a: "When a PE-owned company issues new debt to pay a special dividend to the sponsor. It returns capital to the sponsor before exit.", category: "LBO" },
  { q: "What is a management rollover in an LBO?", a: "When existing management reinvests some of their equity into the new deal, aligning incentives with the sponsor.", category: "LBO" },
  { q: "What is a debt covenant?", a: "A contractual restriction in a loan agreement. Maintenance covenants require ongoing compliance; incurrence covenants restrict certain actions.", category: "LBO" },
  { q: "How does a shorter holding period affect IRR?", a: "All else equal, shorter hold = higher IRR because you achieve the same MOIC faster. But you may sacrifice total value creation.", category: "LBO" },
  { q: "What is an add-on acquisition?", a: "When a PE portfolio company acquires a smaller company to consolidate the industry, gain scale, or enter new markets.", category: "LBO" },
  { q: "LBO vs DCF — how do they differ?", a: "DCF = intrinsic value from discounted cash flows. LBO = constrained by sponsor return requirements and debt capacity. LBO often acts as a valuation floor.", category: "LBO" },
  { q: "What leverage ratio do LBOs typically use?", a: "Depends on market conditions, but 4-6x Debt/EBITDA is common. Higher for stable businesses, lower for cyclical ones.", category: "LBO" },

  // ── MODELING (261-300) ──
  { q: "What is a financial model?", a: "A structured quantitative representation of a business used to analyze performance, forecast outcomes, and evaluate strategic decisions. Inputs drive outputs through linked logic.", category: "Modeling" },
  { q: "How would you forecast revenue for a retailer?", a: "Stores × sales per store, or same-store sales growth + new store openings. Break into volume and price components if possible.", category: "Modeling" },
  { q: "How would you forecast revenue for a SaaS company?", a: "Subscribers × ARPU, adjusted for churn and new customer adds. Track expansion revenue from upsells.", category: "Modeling" },
  { q: "Why keep assumptions separate from calculations?", a: "For transparency, flexibility, and audit trail. Allows easy scenario analysis and reduces formula errors.", category: "Modeling" },
  { q: "What is sensitivity analysis?", a: "Testing how one or two assumptions affect the output across a range. Common: WACC vs terminal growth, entry vs exit multiple.", category: "Modeling" },
  { q: "What is scenario analysis?", a: "Testing complete coherent cases (bull/base/bear) where multiple assumptions change together to reflect different business outcomes.", category: "Modeling" },
  { q: "What is a debt schedule?", a: "Tracks beginning debt, mandatory amortization, optional paydown, new issuance, ending debt, and interest expense for each period.", category: "Modeling" },
  { q: "Why do circular references arise in models?", a: "Interest depends on debt, debt depends on cash flow, cash flow depends on interest. Solved with iteration or average debt balances.", category: "Modeling" },
  { q: "What are the biggest modeling mistakes?", a: "Not matching EV/Equity properly, forgetting taxes, treating CapEx as an expense, not sanity-checking outputs, hardcoding instead of linking.", category: "Modeling" },
  { q: "What makes a good financial model?", a: "Clear assumptions, logical flow, linked statements, no hardcodes in formulas, transparent structure, and outputs that make business sense.", category: "Modeling" },

  // ── BEHAVIORAL (301-330) ──
  { q: "Why investment banking?", a: "Strong answers mention: attraction to transactions/strategic finance, steep learning curve, rigorous analytical training, team-driven high-stakes work, and exposure to companies/industries/executives.", category: "Behavioral" },
  { q: "Tell me about yourself.", a: "Structure: Present → relevant past experiences → why they led to banking → why now/this role. Be concise, chronological, and directed toward the opportunity.", category: "Behavioral" },
  { q: "Why our firm?", a: "Mention specific platform strengths, culture, people you've spoken with, group-specific reasons, and evidence of genuine research. Avoid generic praise.", category: "Behavioral" },
  { q: "What is your greatest strength?", a: "Pick something relevant: analytical rigor, attention to detail, ability to work under pressure, communication skills. Back it with a specific example.", category: "Behavioral" },
  { q: "What is your greatest weakness?", a: "Give a real but manageable weakness with concrete steps you're taking to improve. Never disguise a strength as a weakness.", category: "Behavioral" },
  { q: "Tell me about a time you worked under pressure.", a: "Use STAR: Situation, Task, Action, Result. Show composure, prioritization, and quality output under deadline.", category: "Behavioral" },
  { q: "Tell me about a failure.", a: "Show real setback, ownership, what changed, evidence of improvement. Demonstrate learning and resilience, not just the failure itself.", category: "Behavioral" },
  { q: "Tell me about a leadership experience.", a: "Show ownership, initiative, influence, reliability under pressure. Banking values leadership through execution, not just titles.", category: "Behavioral" },
  { q: "Tell me about a conflict.", a: "Describe the disagreement, how you listened, how you found resolution professionally. Show maturity and collaboration.", category: "Behavioral" },
  { q: "Where do you see yourself in 5 years?", a: "Show trajectory and commitment. Could mention PE, staying in banking, or other paths — but express genuine interest in learning and growing in IB first.", category: "Behavioral" },
  { q: "Why not consulting / PE / S&T?", a: "Differentiate positively. Banking: transaction focus, analytical depth, client advisory, steep learning curve. Don't badmouth other paths.", category: "Behavioral" },
  { q: "What deal have you been following?", a: "Pick a real recent deal. Know the buyer, seller, rationale, valuation, strategic logic. Show you read beyond headlines.", category: "Behavioral" },
  { q: "Walk me through your resume.", a: "Tell a narrative, not a list. What each experience taught you, how they connect, why they point naturally toward banking.", category: "Behavioral" },
  { q: "How do you handle repetitive work?", a: "Show maturity. Acknowledge that building skills requires repetition. Emphasize learning in the details and earning trust through quality.", category: "Behavioral" },
  { q: "How would your teammates describe you?", a: "Be honest and specific: reliable, detail-oriented, collaborative, calm under pressure, willing to take feedback.", category: "Behavioral" },
  { q: "What is one thing not on your resume?", a: "Share something genuine that reveals your character: a hobby, personal challenge, or perspective that makes you more interesting.", category: "Behavioral" },
  { q: "What questions do you have for me?", a: "Ask about their experience, deal flow, team culture, what makes someone succeed. Never say 'no questions.' Show genuine curiosity.", category: "Behavioral" },
  { q: "How do you stay informed about markets?", a: "Mention specific sources: WSJ, Bloomberg, FT, earnings calls, deal announcements. Show you actively follow, not passively skim.", category: "Behavioral" },
  { q: "Tell me about a time you paid attention to detail.", a: "Give a specific example where catching a small error had meaningful impact. Bankers live and die by accuracy.", category: "Behavioral" },
  { q: "What would you do if you disagreed with a VP's approach?", a: "Respectfully share your reasoning with evidence, but ultimately defer to seniority. Show you can push back thoughtfully without ego.", category: "Behavioral" },
];
