import { Flashcard } from './ib-flashcard-data';

// ═══ EQUITY RESEARCH (150+) ═══
export const ER_FLASHCARDS: Flashcard[] = [
// ROLE (20)
{q:"What does a sell-side ER analyst do?",a:"Covers public companies: writes research, builds models, makes recommendations, advises institutional clients.",category:"Role"},
{q:"Buy-side vs sell-side research?",a:"Sell-side: publishes for external clients. Buy-side: internal research driving actual investment decisions.",category:"Role"},
{q:"What is an initiation report?",a:"First coverage: thesis, business overview, industry analysis, model, valuation, risks, catalysts, recommendation.",category:"Role"},
{q:"What is a flash note?",a:"Quick reaction to earnings/news. Brief analysis of impact and revised views.",category:"Role"},
{q:"What is consensus estimate?",a:"Average of analyst estimates (usually EPS). Surprises vs consensus drive stock reactions.",category:"Role"},
{q:"What is a price target?",a:"Analyst's estimate of stock value, typically 12-month forward, based on model and valuation.",category:"Role"},
{q:"What is estimate revision?",a:"Analyst changes forecast. Positive revisions often bullish, negative bearish. Drives stock movement.",category:"Role"},
{q:"What is channel checking?",a:"Gathering data from industry contacts, suppliers, customers to validate thesis before earnings.",category:"Role"},
{q:"What is an earnings preview?",a:"Pre-earnings expectations, key metrics to watch, scenarios.",category:"Role"},
{q:"What is an earnings call?",a:"Management's quarterly call: prepared remarks + analyst Q&A. Critical information source.",category:"Role"},
{q:"How do you stay on top of coverage?",a:"Earnings calls, SEC filings, industry data, competitor commentary, management meetings, daily news.",category:"Role"},
{q:"What is a rating system?",a:"Buy/Overweight, Hold/Neutral, Sell/Underweight. Reflects expected return vs benchmark.",category:"Role"},
{q:"What does Investor Day/Analyst Day mean?",a:"Company event for deep dives on strategy, financials, outlook. Often moves stocks on new info.",category:"Role"},
{q:"What is a quiet period?",a:"Period before/after IPO where company limits communications. Analysts restricted from publishing.",category:"Role"},
{q:"What is MiFID II's impact on research?",a:"Unbundled research payments from trading commissions. Reduced research budgets, fewer analysts.",category:"Role"},
// MODELING (35)
{q:"What is an earnings model?",a:"Detailed financial projections (often quarterly) to estimate EPS and compare to consensus.",category:"Modeling"},
{q:"Revenue build for SaaS?",a:"Subscribers × ARPU, adjusted for churn and expansion. Track NRR, new logos, pricing.",category:"Modeling"},
{q:"Revenue build for retailer?",a:"Stores × sales/store, or SSS growth + new openings. Decompose into traffic and ticket.",category:"Modeling"},
{q:"Revenue build for consumer staples?",a:"Volume × price/mix. Organic vs M&A contribution. Geographic decomposition.",category:"Modeling"},
{q:"Revenue build for ad-tech?",a:"Impressions × CPM, or clients × ARPU. Track fill rates, pricing trends.",category:"Modeling"},
{q:"Revenue build for a bank?",a:"Net interest income (NIM × earning assets) + non-interest income (fees, trading). Separate clearly.",category:"Modeling"},
{q:"Revenue build for insurance?",a:"Premiums written × retention + investment income. Track loss ratio and combined ratio.",category:"Modeling"},
{q:"Revenue build for pharma?",a:"Product-by-product: volume × price, adjusted for patent cliffs, new launches, geographic mix.",category:"Modeling"},
{q:"How do you forecast COGS?",a:"As % of revenue (gross margin), or build from input costs, labor, manufacturing. Check trends.",category:"Modeling"},
{q:"How do you forecast SG&A?",a:"Fixed vs variable. Headcount × avg comp for labor. Marketing as % of revenue.",category:"Modeling"},
{q:"How do you forecast CapEx?",a:"% of revenue, or maintenance + growth separately. Check management guidance.",category:"Modeling"},
{q:"How do you forecast working capital?",a:"DSO × revenue, DIO × COGS, DPO × COGS. Or as % of revenue with trends.",category:"Modeling"},
{q:"What is EPS?",a:"Net Income / Diluted Shares. Most-watched metric. Beats/misses drive stocks.",category:"Modeling"},
{q:"What is diluted share count?",a:"Basic + dilutive securities (options, RSUs, convertibles) via treasury stock method.",category:"Modeling"},
{q:"What is a DCF in ER context?",a:"Intrinsic valuation: project UFCF, discount at WACC, terminal value, bridge to per-share equity.",category:"Modeling"},
{q:"What is SOTP valuation?",a:"Value each segment separately with appropriate multiples, then sum.",category:"Modeling"},
{q:"Key modeling checks?",a:"BS balances, CF reconciles, margins reasonable, growth realistic, no broken links.",category:"Modeling"},
{q:"How do you handle seasonality?",a:"Quarterly models. Compare Q vs prior-year Q, not sequential. Adjust for calendar.",category:"Modeling"},
{q:"What is sensitivity analysis in ER?",a:"Test key assumptions (growth, margin, multiple) on price target. Show range.",category:"Modeling"},
{q:"How do you bridge EBITDA to FCF?",a:"EBITDA - cash taxes - CapEx - WC changes = UFCF.",category:"Modeling"},
{q:"What is operating leverage in a model?",a:"Fixed costs mean revenue growth > expense growth = margin expansion. Model fixed vs variable separately.",category:"Modeling"},
{q:"How do you model share buybacks?",a:"Estimate buyback spend, divide by avg share price = shares retired. Reduces share count, boosts EPS.",category:"Modeling"},
{q:"How do you model an acquisition in an ER model?",a:"Add target revenue/costs from close date. Include synergies, financing costs, goodwill/amortization.",category:"Modeling"},
{q:"What is consensus vs your estimate?",a:"Your variant view vs market expectation. The gap drives your recommendation.",category:"Modeling"},
{q:"How do you set a price target?",a:"Apply target multiple to forward earnings/EBITDA, or DCF-derived per-share value. State methodology clearly.",category:"Modeling"},
// VALUATION (25)
{q:"Common multiples in ER?",a:"P/E (most watched), EV/EBITDA, EV/Revenue for growth, P/FCF, sector-specific (P/B for banks).",category:"Valuation"},
{q:"Forward vs trailing multiples?",a:"Forward (NTM) more relevant — markets price expectations. Trailing shows history.",category:"Valuation"},
{q:"How do you select a target multiple?",a:"Peer comparison, historical range, growth/margin premium or discount, market conditions.",category:"Valuation"},
{q:"What is PEG ratio?",a:"P/E / EPS growth rate. <1 may suggest undervalued for growth. Simplistic but useful.",category:"Valuation"},
{q:"Value high-growth unprofitable company?",a:"EV/Revenue, DCF with long-term margins, unit economics, comparable transactions.",category:"Valuation"},
{q:"What is bull/base/bear?",a:"Three scenarios with different assumptions. Shows upside/downside range around target.",category:"Valuation"},
{q:"Why can two similar companies trade at different multiples?",a:"Growth, margins, ROIC, balance sheet, management, market position, earnings quality.",category:"Valuation"},
{q:"What is a re-rating?",a:"Market assigns higher/lower multiple. From improved outlook, sector rotation, or risk change.",category:"Valuation"},
{q:"What is normalized earnings?",a:"Adjusted for cyclical/one-time effects to show sustainable earning power.",category:"Valuation"},
{q:"What is a football field chart?",a:"Valuation ranges from different methods side by side.",category:"Valuation"},
{q:"When is P/E most useful?",a:"Profitable companies with stable capital structure and tax rates. Less useful for cyclicals or levered cos.",category:"Valuation"},
{q:"When is EV/EBITDA preferred?",a:"Comparing companies with different capital structures. More capital-structure neutral than P/E.",category:"Valuation"},
{q:"What is a justified multiple?",a:"Multiple derived from fundamentals (growth, ROIC, risk). Not arbitrary. P/E = payout/(r-g).",category:"Valuation"},
// STOCK PITCH (25)
{q:"Tell me about a stock you follow.",a:"Business model, revenue drivers, margins, competitive position, recent results vs consensus, your view, valuation, risks.",category:"Stock Pitch"},
{q:"How do you build a stock pitch?",a:"1) Pick company you know. 2) Why mispriced. 3) Valuation. 4) Catalysts. 5) Risks. 6) Practice.",category:"Stock Pitch"},
{q:"What is the market missing?",a:"Core of a good pitch. What does consensus get wrong about growth, margins, capital allocation, or risk?",category:"Stock Pitch"},
{q:"Compare two investment ideas.",a:"Risk-adjusted return, conviction, catalyst visibility, downside protection, liquidity, portfolio fit.",category:"Stock Pitch"},
{q:"What would make you change your rating?",a:"Thesis invalidation, valuation fully reflected, fundamental deterioration, better opportunity, risk-reward shift.",category:"Stock Pitch"},
{q:"Handle pushback on a pitch?",a:"Acknowledge concern, explain why your view differs, cite evidence. Don't get defensive.",category:"Stock Pitch"},
{q:"What is a contrarian call?",a:"Going against consensus with differentiated thesis. Requires strong evidence and conviction.",category:"Stock Pitch"},
{q:"Why is downside analysis important?",a:"Shows you've considered what goes wrong. Investors care about risk-reward, not just upside.",category:"Stock Pitch"},
{q:"What is a catalyst?",a:"Event closing gap between price and value: earnings, product launch, regulatory change, management action.",category:"Stock Pitch"},
{q:"What is a variant view?",a:"Your differentiated perspective vs market consensus. The basis for any actionable recommendation.",category:"Stock Pitch"},
{q:"How do you frame upside/downside?",a:"Bull/base/bear with probabilities. Calculate expected value. Show asymmetry if it exists.",category:"Stock Pitch"},
{q:"What is a show-me story?",a:"Stock that needs to prove something (turnaround, margin improvement). Market skeptical, needs evidence.",category:"Stock Pitch"},
// BEHAVIORAL (25)
{q:"Why equity research?",a:"Deep company/industry expertise, fundamental analysis, writing/communication, influencing institutional investors.",category:"Behavioral"},
{q:"Why sell-side vs buy-side?",a:"Sell-side: broader coverage, more communication, client-facing. Buy-side: deeper analysis, capital allocation.",category:"Behavioral"},
{q:"What sectors interest you?",a:"Pick one genuinely. Know key players, dynamics, trends, regulatory backdrop.",category:"Behavioral"},
{q:"How do you prioritize during earnings season?",a:"Coverage first, then adjacent. Pre-write templates. Flag surprises quickly. Manage time ruthlessly.",category:"Behavioral"},
{q:"Tell me about being wrong on a stock.",a:"Thesis, what went wrong, what you learned, process changes.",category:"Behavioral"},
{q:"Tell me about yourself.",a:"Markets interest → analytical/writing skills → why ER combines both → sector interest.",category:"Behavioral"},
{q:"What do you read every morning?",a:"WSJ, Bloomberg, FT, sector sources, transcripts, research. Show daily habit.",category:"Behavioral"},
{q:"Evaluate management quality?",a:"Track record on guidance, capital allocation, candor, strategic consistency, insider activity.",category:"Behavioral"},
{q:"What is the hardest part of ER?",a:"Being wrong publicly, maintaining conviction under pressure, producing quality under tight deadlines.",category:"Behavioral"},
{q:"How do you handle disagreement with senior analyst?",a:"Present your reasoning with data, listen to their experience, find common ground, learn.",category:"Behavioral"},
{q:"What stock are you following right now?",a:"Have 2-3 ready. Know recent quarter, consensus, your view, key drivers, valuation.",category:"Behavioral"},
{q:"How do you add value as a junior analyst?",a:"Thorough modeling, industry contacts, creative analysis, detailed notes, reliable work product.",category:"Behavioral"},
{q:"What is your writing style?",a:"Clear, concise, data-driven. Lead with conclusion, support with analysis, flag risks.",category:"Behavioral"},
];

// ═══ REAL ESTATE (150+) ═══
export const RE_FLASHCARDS: Flashcard[] = [
// FUNDAMENTALS (35)
{q:"What is NOI?",a:"Net Operating Income = Revenue - Operating Expenses. Excludes debt service, CapEx, taxes.",category:"Fundamentals"},
{q:"What is a cap rate?",a:"NOI / Property Value. Yield on property. Lower cap = higher price.",category:"Fundamentals"},
{q:"Cap rate and value relationship?",a:"Inverse. Cap rates rise → values fall. Value = NOI / Cap Rate.",category:"Fundamentals"},
{q:"Going-in vs exit cap rate?",a:"Going-in: at acquisition. Exit: at sale. Exit usually higher (older/riskier).",category:"Fundamentals"},
{q:"What drives cap rates?",a:"Rates, risk perception, supply/demand, property quality, location, lease profile, growth.",category:"Fundamentals"},
{q:"What is occupancy rate?",a:"% of rentable space leased. Higher = more stable income.",category:"Fundamentals"},
{q:"What is effective gross income?",a:"Potential gross income - vacancy + other income. Revenue expected to be collected.",category:"Fundamentals"},
{q:"What is a triple-net (NNN) lease?",a:"Tenant pays rent + taxes + insurance + maintenance. Minimal landlord risk.",category:"Fundamentals"},
{q:"What is a gross lease?",a:"Landlord pays operating expenses. Tenant pays flat rent.",category:"Fundamentals"},
{q:"What is a modified gross lease?",a:"Some expenses shared between landlord and tenant. Hybrid approach.",category:"Fundamentals"},
{q:"What is tenant improvement (TI)?",a:"Landlord-funded space buildout. Higher TI = lower effective rent.",category:"Fundamentals"},
{q:"What is lease-up risk?",a:"Risk of not filling vacant space. New developments and value-add face this.",category:"Fundamentals"},
{q:"Main property types?",a:"Multifamily, office, retail, industrial, hospitality, self-storage, data centers, life science.",category:"Fundamentals"},
{q:"What is absorption?",a:"Net change in occupied space. Positive = more occupied. Key demand indicator.",category:"Fundamentals"},
{q:"What is WALT?",a:"Weighted Average Lease Term. Longer = more income certainty.",category:"Fundamentals"},
{q:"What is replacement cost?",a:"Cost to build equivalent property today. Floor for existing values.",category:"Fundamentals"},
{q:"What is a rent roll?",a:"Schedule of all tenants, lease terms, rents, expirations. Foundation of property analysis.",category:"Fundamentals"},
{q:"What is mark-to-market rent?",a:"Difference between in-place rents and current market rents. Upside if below market.",category:"Fundamentals"},
{q:"What is a tenant credit analysis?",a:"Evaluating tenant's ability to pay rent. Investment-grade vs local business matters.",category:"Fundamentals"},
{q:"What is a lease escalation?",a:"Annual rent increase. Fixed (3%/year), CPI-linked, or step-up schedule.",category:"Fundamentals"},
{q:"What is concessions?",a:"Incentives to attract tenants: free rent, TI, moving allowance. Reduce effective rent.",category:"Fundamentals"},
{q:"What is net effective rent?",a:"Actual rent after accounting for concessions, TI, and free rent over lease term.",category:"Fundamentals"},
{q:"What is a ground lease?",a:"Lease of land only. Tenant builds/owns improvements. Long-term (50-99 years).",category:"Fundamentals"},
{q:"What is highest and best use?",a:"Most productive legally permissible, physically possible, financially feasible use of land.",category:"Fundamentals"},
{q:"What is zoning?",a:"Government regulation of land use: residential, commercial, industrial, mixed-use. Limits what you can build.",category:"Fundamentals"},
// MODELING & RETURNS (30)
{q:"What is a pro forma?",a:"Projected financials: revenue, expenses, NOI, debt service, returns, exit.",category:"Modeling"},
{q:"What is cash-on-cash return?",a:"Annual pre-tax cash flow / total cash invested. Simple yield.",category:"Modeling"},
{q:"What is IRR in real estate?",a:"Annualized return on all cash flows: acquisition, operations, capital events, sale.",category:"Modeling"},
{q:"What is an equity multiple?",a:"Total distributions / total equity. 2.0x = doubled money.",category:"Modeling"},
{q:"What is LTV?",a:"Loan / Property Value. Measures leverage. Higher = more risk.",category:"Modeling"},
{q:"What is DSCR?",a:"NOI / Debt Service. Lenders want >1.2x.",category:"Modeling"},
{q:"What is a waterfall structure?",a:"Distributes cash in tiers: preferred return → GP catch-up → profit split.",category:"Modeling"},
{q:"What is a preferred return?",a:"Minimum LP return before GP earns promote. Typically 8%.",category:"Modeling"},
{q:"What is promote?",a:"GP's profit share above preferred return. Similar to carried interest.",category:"Modeling"},
{q:"What is a lookback provision?",a:"Ensures LPs receive pref over entire hold, not just annually.",category:"Modeling"},
{q:"How project rent growth?",a:"Market trends, escalations, mark-to-market on expiry.",category:"Modeling"},
{q:"What is CapEx reserve?",a:"Annual budget for capital improvements. Reduces distributable cash.",category:"Modeling"},
{q:"Amortizing vs IO loan?",a:"Amortizing: principal + interest. IO: interest only. IO = higher cash flow, slower equity build.",category:"Modeling"},
{q:"What is unlevered yield?",a:"NOI / total cost (acquisition + closing + CapEx). Return before financing.",category:"Modeling"},
{q:"What is yield-on-cost?",a:"Stabilized NOI / total development cost. Key development feasibility metric.",category:"Modeling"},
{q:"How do you model a development?",a:"Land cost + hard/soft costs + financing → lease-up period → stabilized NOI → exit value → returns.",category:"Modeling"},
{q:"What is a sensitivity table for RE?",a:"Vary exit cap rate and rent growth to show IRR range. Standard for investment memos.",category:"Modeling"},
{q:"What is a hold period?",a:"Planned ownership duration. Typically 3-7 years for value-add, 7-10+ for core.",category:"Modeling"},
{q:"What is a reversion value?",a:"Estimated sale price at exit. Usually NOI at exit / exit cap rate.",category:"Modeling"},
{q:"What is a closing cost estimate?",a:"Transfer taxes, legal, title, lender fees, inspection. Typically 1-3% of purchase price.",category:"Modeling"},
// STRATEGY & REITS (25)
{q:"Core vs Value-Add vs Opportunistic?",a:"Core: 6-8%, stabilized. Value-Add: 12-18%, improvement. Opportunistic: 18%+, development/distressed.",category:"Strategy"},
{q:"What is value-add RE?",a:"Properties needing improvement (renovation, re-leasing) to increase NOI and value.",category:"Strategy"},
{q:"What is ground-up development?",a:"Building from scratch. Highest risk (entitlement, construction, lease-up) but highest potential returns.",category:"Strategy"},
{q:"What is a 1031 exchange?",a:"Tax-deferred exchange: sell property, buy equal/greater value. Defers capital gains.",category:"Strategy"},
{q:"What is FFO?",a:"NI + D&A - gains on sales. Standard REIT earnings metric.",category:"REITs"},
{q:"What is AFFO?",a:"FFO - maintenance CapEx - straight-line rent adjustments. Better cash flow proxy.",category:"REITs"},
{q:"Why FFO over NI for REITs?",a:"RE depreciation overstates expense. Properties often appreciate. FFO removes distortion.",category:"REITs"},
{q:"What is NAV for a REIT?",a:"Property values (NOI/cap rate) minus debt plus other assets. Compare to stock price.",category:"REITs"},
{q:"Premium vs discount to NAV?",a:"Premium: market values growth/management. Discount: market skeptical.",category:"REITs"},
{q:"What is a REIT?",a:"Must distribute 90%+ taxable income. Provides liquidity and diversification in RE.",category:"REITs"},
{q:"What is same-store NOI growth?",a:"NOI growth from properties owned in both periods. Shows organic performance.",category:"REITs"},
{q:"What is a UPREIT?",a:"Umbrella Partnership REIT. Allows property owners to contribute assets tax-deferred in exchange for OP units.",category:"REITs"},
{q:"What is a triple-net REIT?",a:"REIT owning NNN-leased properties. Very stable, low management intensity, lower growth.",category:"REITs"},
// DEBT & MARKET (25)
{q:"RE debt types?",a:"Senior mortgage, mezz, CMBS, construction, bridge, preferred equity.",category:"Debt"},
{q:"What is CMBS?",a:"Commercial Mortgage-Backed Securities. Pooled commercial loans sold as bonds.",category:"Debt"},
{q:"What is mezzanine debt in RE?",a:"Subordinate to senior mortgage. Higher rate. Secured by ownership interest, not property.",category:"Debt"},
{q:"What is a bridge loan?",a:"Short-term (1-3yr) for transitional properties. Higher rate. Used during value-add.",category:"Debt"},
{q:"Rising rates affect RE how?",a:"Cap rates expand (values fall), financing expensive, volume drops. But rents may offset in inflation.",category:"Debt"},
{q:"Recourse vs non-recourse?",a:"Recourse: lender pursues other assets. Non-recourse: limited to property.",category:"Debt"},
{q:"What is debt yield?",a:"NOI / Loan Amount. Lender-focused return metric regardless of rates.",category:"Debt"},
{q:"What is a rate lock?",a:"Fixes interest rate before closing. Protects against rate increases.",category:"Debt"},
{q:"What is loan amortization in RE?",a:"Gradual principal repayment. 25-30 year schedule common even on 5-10 year terms (balloon).",category:"Debt"},
{q:"What is a balloon payment?",a:"Remaining principal due at loan maturity. Creates refinancing risk.",category:"Debt"},
{q:"What is an interest rate cap?",a:"Derivative limiting maximum floating rate. Required by many floating-rate lenders.",category:"Debt"},
{q:"What is a defeasance?",a:"Substituting collateral (usually Treasuries) to release property from loan. Expensive but enables sale.",category:"Debt"},
{q:"What is loan-to-cost (LTC)?",a:"Loan / total project cost. Used for development and value-add. Typically 60-75%.",category:"Debt"},
// BEHAVIORAL (15)
{q:"Why real estate?",a:"Tangible assets, inflation protection, income, leverage, intersection of finance and operations.",category:"Behavioral"},
{q:"What property type interests you?",a:"Pick one. Know supply/demand, cap rates, key players, recent transactions.",category:"Behavioral"},
{q:"Tell me about a deal you analyzed.",a:"Property type, location, strategy, returns, risks. Show analytical depth.",category:"Behavioral"},
{q:"What market are you bullish/bearish on?",a:"Specific city or property type. Support with supply, demand, demographics, employment.",category:"Behavioral"},
{q:"How would you evaluate a property?",a:"Location, condition, tenant quality, lease terms, NOI stability, comps, basis vs replacement.",category:"Behavioral"},
{q:"Tell me about yourself.",a:"Interest in real assets → analytical skills → relevant experience → why RE.",category:"Behavioral"},
{q:"What is the biggest risk in RE right now?",a:"Pick a current issue: rates, remote work (office), oversupply, cap rate expansion. Show market awareness.",category:"Behavioral"},
{q:"How do you source deals?",a:"Broker relationships, off-market outreach, proprietary research, industry events, owner relationships.",category:"Behavioral"},
];

// ═══ VENTURE CAPITAL (150+) ═══
export const VC_FLASHCARDS: Flashcard[] = [
// FUNDAMENTALS (25)
{q:"What is venture capital?",a:"Investing in early-stage, high-growth companies for equity. High failure offset by outsized winners.",category:"Fundamentals"},
{q:"What is the power law?",a:"Most returns from tiny number of investments. One company may return the entire fund.",category:"Fundamentals"},
{q:"Seed vs Series A vs B?",a:"Seed: idea/early product, $1-5M. A: PMF, $5-25M. B: scaling, $20-100M+.",category:"Fundamentals"},
{q:"What is a cap table?",a:"Ownership %, share classes, option pools, dilution from each round.",category:"Fundamentals"},
{q:"What is an option pool?",a:"Shares reserved for employees. Usually 10-20%. Created/expanded at rounds.",category:"Fundamentals"},
{q:"What is dilution?",a:"Ownership % reduction when new shares issued. Each round dilutes existing holders.",category:"Fundamentals"},
{q:"What is a down round?",a:"Funding at lower valuation. Triggers anti-dilution. Signals distress.",category:"Fundamentals"},
{q:"What is product-market fit?",a:"Product satisfies strong demand. Signs: organic growth, retention, word-of-mouth.",category:"Fundamentals"},
{q:"What makes a great VC investment?",a:"Massive market, exceptional founders, PMF, unit economics, defensibility, reasonable valuation.",category:"Fundamentals"},
{q:"How do VCs make money?",a:"2% management fee + 20% carry on profits above hurdle.",category:"Fundamentals"},
{q:"VC fund lifecycle?",a:"10 years: 3-4yr investment + harvesting through exits.",category:"Fundamentals"},
{q:"VC exit strategies?",a:"IPO, M&A, secondary sale, or shutdown/write-off.",category:"Fundamentals"},
{q:"What is a unicorn?",a:"Private company valued at $1B+. Term coined 2013. Much more common now.",category:"Fundamentals"},
{q:"What is a decacorn?",a:"Private company valued at $10B+. Rare, represents the biggest winners.",category:"Fundamentals"},
{q:"What is bridge financing?",a:"Short-term funding between rounds. Usually converts. Can signal either momentum or distress.",category:"Fundamentals"},
// DEAL TERMS (35)
{q:"What is a term sheet?",a:"Non-binding key terms: valuation, amount, liquidation pref, board seats, anti-dilution.",category:"Deal Terms"},
{q:"Pre-money vs post-money?",a:"Pre = value before investment. Post = pre + investment. Ownership = investment / post.",category:"Deal Terms"},
{q:"What is liquidation preference?",a:"Investor gets money back (1x) before common in a sale. 1x non-participating standard.",category:"Deal Terms"},
{q:"Participating vs non-participating?",a:"Non-participating: choose pref or common share. Participating: get pref back PLUS share remaining.",category:"Deal Terms"},
{q:"What is anti-dilution?",a:"Protects in down rounds. Weighted average (common) vs full ratchet (harsh).",category:"Deal Terms"},
{q:"What is a SAFE?",a:"Simple Agreement for Future Equity. Not debt, converts at next round with discount/cap.",category:"Deal Terms"},
{q:"What is a convertible note?",a:"Debt converting to equity at next round with discount and/or cap.",category:"Deal Terms"},
{q:"Discount vs cap?",a:"Discount: buy at X% less than round price. Cap: max valuation for conversion.",category:"Deal Terms"},
{q:"What is pro rata?",a:"Right to invest in future rounds to maintain ownership %. Valuable for winners.",category:"Deal Terms"},
{q:"What is a board seat?",a:"Lead investor gets board seat for governance and investment protection.",category:"Deal Terms"},
{q:"What is drag-along?",a:"Majority can force minority to join sale. Prevents blocking exits.",category:"Deal Terms"},
{q:"What is tag-along?",a:"Minority can join if majority sells. Protects from being left behind.",category:"Deal Terms"},
{q:"What is information rights?",a:"Right to receive financial reports and updates.",category:"Deal Terms"},
{q:"What is a vesting schedule?",a:"4-year vest, 1-year cliff. Earn equity over time.",category:"Deal Terms"},
{q:"What is an 83(b) election?",a:"Pay taxes on stock at grant (low value) vs vesting (high value).",category:"Deal Terms"},
{q:"What is a protective provision?",a:"Investor veto rights on major decisions: fundraising, sale, debt, bylaws changes.",category:"Deal Terms"},
{q:"What is a pay-to-play provision?",a:"Investors who don't participate in future rounds lose certain rights. Encourages follow-on support.",category:"Deal Terms"},
{q:"What is a right of first refusal (ROFR)?",a:"Company or investors can match any secondary sale offer before allowing transfer.",category:"Deal Terms"},
{q:"What is a redemption right?",a:"Investor can force company to buy back shares after set period. Rarely exercised, provides leverage.",category:"Deal Terms"},
{q:"What is a founder lockup?",a:"Restriction on founders selling shares for a period post-IPO. Typically 180 days.",category:"Deal Terms"},
{q:"What is weighted average anti-dilution?",a:"Adjusts conversion price based on new shares issued and price. Less severe than full ratchet.",category:"Deal Terms"},
{q:"What is a valuation cap on a SAFE?",a:"Maximum valuation at which SAFE converts. Protects early investor if next round is much higher.",category:"Deal Terms"},
{q:"What is a most favored nation (MFN) clause?",a:"If company issues SAFEs with better terms later, earlier SAFE holder can adopt those terms.",category:"Deal Terms"},
// SAAS METRICS (25)
{q:"What is ARR/MRR?",a:"Annual/Monthly Recurring Revenue. Core subscription metric.",category:"SaaS Metrics"},
{q:"What is NDR?",a:"Net Dollar Retention. Existing customer revenue Y2/Y1. >120% excellent.",category:"SaaS Metrics"},
{q:"What is CAC?",a:"Customer Acquisition Cost. Sales + marketing / new customers.",category:"SaaS Metrics"},
{q:"What is LTV?",a:"Lifetime Value = avg revenue × margin × lifespan. LTV/CAC > 3x healthy.",category:"SaaS Metrics"},
{q:"What is CAC payback?",a:"Months to recover acquisition cost. <12 good. >18 concerning.",category:"SaaS Metrics"},
{q:"Gross vs net churn?",a:"Gross: total revenue lost. Net: gross offset by expansion from remaining.",category:"SaaS Metrics"},
{q:"Logo vs revenue churn?",a:"Logo: % customers lost. Revenue: % revenue lost. Can differ by customer size.",category:"SaaS Metrics"},
{q:"What is expansion revenue?",a:"Additional revenue from existing customers: upsells, cross-sells, usage growth.",category:"SaaS Metrics"},
{q:"What is Rule of 40?",a:"Revenue growth % + profit margin % > 40% for healthy SaaS.",category:"SaaS Metrics"},
{q:"Gross margin for SaaS?",a:"Typically 70-85%. Includes hosting, support, CS costs.",category:"SaaS Metrics"},
{q:"What is ACV?",a:"Annual Contract Value. Higher ACV = more enterprise-focused.",category:"SaaS Metrics"},
{q:"What is magic number?",a:"Net new ARR / prior quarter S&M spend. >1x is good.",category:"SaaS Metrics"},
{q:"What is burn rate?",a:"Monthly cash consumed. Revenue minus all expenses.",category:"SaaS Metrics"},
{q:"What is runway?",a:"Cash / monthly burn = months until cash out. 12-18 comfortable.",category:"SaaS Metrics"},
{q:"What is NPS?",a:"Net Promoter Score. Customer satisfaction metric. Promoters minus detractors.",category:"SaaS Metrics"},
{q:"What is DAU/MAU ratio?",a:"Daily/Monthly active users. Measures engagement stickiness. >50% excellent.",category:"SaaS Metrics"},
{q:"What is virality coefficient (K-factor)?",a:"Users × invites × conversion rate. K > 1 = viral growth.",category:"SaaS Metrics"},
{q:"What is cohort analysis?",a:"Tracking behavior of user groups over time. Reveals retention and monetization trends.",category:"SaaS Metrics"},
{q:"What is gross merchandise value (GMV)?",a:"Total value of transactions on a marketplace. Revenue = GMV × take rate.",category:"SaaS Metrics"},
// EVALUATION (25)
{q:"What is TAM/SAM/SOM?",a:"Total/Serviceable/Obtainable Market. Theoretical to realistic capture.",category:"Evaluation"},
{q:"Top-down vs bottom-up TAM?",a:"Top-down: industry data. Bottom-up: customers × price. Bottom-up more credible.",category:"Evaluation"},
{q:"Evaluate a founding team?",a:"Domain expertise, complementary skills, execution track record, resilience, coachability, vision.",category:"Evaluation"},
{q:"What is a moat for a startup?",a:"Network effects, data advantages, switching costs, brand, regulatory, technical IP.",category:"Evaluation"},
{q:"Evaluate unit economics?",a:"LTV/CAC, margins, payback. Must be positive and scalable.",category:"Evaluation"},
{q:"Attractive market for VC?",a:"Large, growing, fragmented, tech-disruption possible, venture-scale outcomes.",category:"Evaluation"},
{q:"What is venture-scale return?",a:"10-100x+ potential. VC math requires winners compensate for many losses.",category:"Evaluation"},
{q:"Assess competitive landscape?",a:"Direct competitors, adjacent players, incumbent response, differentiation, barriers.",category:"Evaluation"},
{q:"Common startup failure reasons?",a:"No market need (#1), ran out of cash, wrong team, outcompeted, pricing issues, bad product, timing.",category:"Evaluation"},
{q:"What is a pivot?",a:"Fundamental change in product/market/model based on learnings. Adaptability if done well.",category:"Evaluation"},
{q:"What is a business model canvas?",a:"One-page framework: value prop, segments, channels, revenue, costs, partners, activities, resources.",category:"Evaluation"},
{q:"What is a minimum viable product (MVP)?",a:"Simplest version of product to test hypothesis with real users. Core lean startup concept.",category:"Evaluation"},
{q:"What is the lean startup methodology?",a:"Build → Measure → Learn loop. Rapid iteration based on customer feedback.",category:"Evaluation"},
{q:"What is traction?",a:"Evidence of product-market fit: revenue, users, engagement, partnerships. What investors look for.",category:"Evaluation"},
{q:"How do you assess timing risk?",a:"Too early: market not ready. Too late: competition established. Best: inflection point.",category:"Evaluation"},
{q:"What is a winner-take-most market?",a:"Market where one player captures dominant share due to network effects or scale. Huge outcome if you win.",category:"Evaluation"},
// BEHAVIORAL (15)
{q:"Why venture capital?",a:"Innovation passion, founder evaluation, long horizon, conviction on trends, helping companies scale.",category:"Behavioral"},
{q:"What sector thesis excites you?",a:"Pick one genuinely. Know landscape, startups, trends, risks.",category:"Behavioral"},
{q:"Tell me about a startup you'd invest in.",a:"Team, market, product, traction, unit economics, competitive position, valuation, risks.",category:"Behavioral"},
{q:"How do you source deals?",a:"Network, events, accelerators, referrals, cold outreach, thesis-driven research.",category:"Behavioral"},
{q:"What makes a great VC?",a:"Pattern recognition, founder empathy, conviction, network, willingness to be wrong, value-add.",category:"Behavioral"},
{q:"How do you add value?",a:"Introductions, hiring help, strategic advice, follow-on capital, governance, customer connections.",category:"Behavioral"},
{q:"Tell me about yourself.",a:"Interest in tech/startups → analytical skills → experience → why VC combines all.",category:"Behavioral"},
{q:"What is your investment thesis?",a:"Have a sector or trend view. Explain why now, what you look for, what excites you.",category:"Behavioral"},
{q:"Tell me about a company you wish you'd invested in.",a:"Show market awareness. Explain why it was compelling and what you'd look for next time.",category:"Behavioral"},
{q:"How do you evaluate a pitch deck?",a:"Team, problem, solution, market, traction, business model, financials, ask. Look for clarity and honesty.",category:"Behavioral"},
];

// ═══ RESTRUCTURING (150+) ═══
export const RX_FLASHCARDS: Flashcard[] = [
// FUNDAMENTALS (25)
{q:"What is restructuring?",a:"Reorganizing financial structure, operations, or capital in distress or for transformation.",category:"Fundamentals"},
{q:"What causes financial distress?",a:"Over-leverage, revenue decline, liquidity crunch, covenant breach, industry disruption, litigation.",category:"Fundamentals"},
{q:"What is a covenant breach?",a:"Violating debt restrictions. Can trigger default, accelerate debt, force restructuring.",category:"Fundamentals"},
{q:"In-court vs out-of-court?",a:"Out-of-court: negotiated, faster, cheaper. In-court (Ch.11): court-supervised, binding, more tools.",category:"Fundamentals"},
{q:"What is forbearance?",a:"Creditor agrees not to exercise default rights while debtor negotiates.",category:"Fundamentals"},
{q:"What is amend and extend?",a:"Modify terms to push maturity, adjust covenants. Avoids default without full restructuring.",category:"Fundamentals"},
{q:"What is a distressed exchange?",a:"Swap existing debt for new securities (often at discount or with equity).",category:"Fundamentals"},
{q:"What is a liability management exercise?",a:"Transactions addressing maturities, leverage, liquidity outside formal restructuring.",category:"Fundamentals"},
{q:"Going concern vs liquidation?",a:"Going concern: business continues. Liquidation: assets sold, wound down. GC usually more value.",category:"Fundamentals"},
{q:"Three sides in restructuring?",a:"Debtor, creditors, equity. Each has different interests. Banks advise all three.",category:"Fundamentals"},
{q:"What is a zone of insolvency?",a:"When company is near or at insolvency. Board duties shift from shareholders toward all stakeholders.",category:"Fundamentals"},
{q:"What is a credit bid?",a:"Secured creditor bids claim value in asset sale, converting debt to ownership.",category:"Fundamentals"},
{q:"What is a stalking horse bid?",a:"Initial bid that sets floor price in bankruptcy auction. Gets breakup fee protection.",category:"Fundamentals"},
{q:"What is a cramdown?",a:"Court confirms plan over dissenting class objection if fair and equitable.",category:"Fundamentals"},
// BANKRUPTCY (35)
{q:"What is Chapter 11?",a:"US reorganization: debtor continues operating, proposes plan, creditors vote.",category:"Bankruptcy"},
{q:"What is Chapter 7?",a:"Liquidation: operations cease, assets sold to repay creditors in priority.",category:"Bankruptcy"},
{q:"What is automatic stay?",a:"Upon filing, all creditor actions paused. Gives debtor breathing room.",category:"Bankruptcy"},
{q:"What is DIP?",a:"Debtor-in-Possession: existing management runs company during Ch.11.",category:"Bankruptcy"},
{q:"What is a DIP loan?",a:"New financing during Ch.11 with super-priority. Allows continued operations.",category:"Bankruptcy"},
{q:"What is absolute priority rule?",a:"Claims paid in order: secured → admin → unsecured → sub → preferred → equity.",category:"Bankruptcy"},
{q:"What is a 363 sale?",a:"Asset sale under Section 363. Often through auction. Free of liens.",category:"Bankruptcy"},
{q:"What is a pre-pack?",a:"Pre-negotiated plan agreed with key creditors before filing. Fast emergence.",category:"Bankruptcy"},
{q:"What is a pre-arranged bankruptcy?",a:"Key terms negotiated pre-filing but voted on after. Between pre-pack and free-fall.",category:"Bankruptcy"},
{q:"What is a plan of reorganization?",a:"Blueprint for restructured company: new cap structure, claim treatment, governance.",category:"Bankruptcy"},
{q:"What is a disclosure statement?",a:"Document providing adequate info for creditors to vote on plan.",category:"Bankruptcy"},
{q:"Voting on a plan?",a:"Each class votes. Accept: 2/3 in amount AND 1/2 in number within class.",category:"Bankruptcy"},
{q:"What are executory contracts?",a:"Both parties have remaining obligations. Debtor can assume or reject.",category:"Bankruptcy"},
{q:"What is avoidance actions?",a:"Claw back preferential (90 days) or fraudulent transfers.",category:"Bankruptcy"},
{q:"What is adequate protection?",a:"Secured creditors' right to protection against collateral decline.",category:"Bankruptcy"},
{q:"What is a UCC?",a:"Unsecured Creditors' Committee. Represents unsecured interests.",category:"Bankruptcy"},
{q:"What is first-day motions?",a:"Immediate court requests: pay employees, honor customers, pay critical vendors.",category:"Bankruptcy"},
{q:"What is cash collateral?",a:"Cash subject to a lien. Debtor needs court permission to use.",category:"Bankruptcy"},
{q:"What is emergence?",a:"Restructured company exits bankruptcy with new cap structure.",category:"Bankruptcy"},
{q:"What is a rights offering?",a:"Post-emergence equity offering to raise capital.",category:"Bankruptcy"},
{q:"What is equitable subordination?",a:"Court subordinates claim for inequitable conduct (fraud, fiduciary breach).",category:"Bankruptcy"},
{q:"What is Section 1111(b) election?",a:"Undersecured creditor treats full claim as secured. Strategic choice.",category:"Bankruptcy"},
{q:"What is a plan currency?",a:"What creditors receive: new debt, equity, cash, warrants, or combo.",category:"Bankruptcy"},
{q:"What is exclusivity period?",a:"First 120 days only debtor can propose a plan. Can be extended.",category:"Bankruptcy"},
{q:"What is a proof of claim?",a:"Creditor files to establish their claim amount and priority.",category:"Bankruptcy"},
{q:"What is a bar date?",a:"Deadline for filing proofs of claim. Late claims may be disallowed.",category:"Bankruptcy"},
{q:"What is assumption vs rejection of a lease?",a:"Assume: keep lease, cure defaults. Reject: terminate, landlord gets unsecured claim.",category:"Bankruptcy"},
{q:"What is critical vendor motion?",a:"Court approval to pay pre-petition claims of essential suppliers.",category:"Bankruptcy"},
// VALUATION & ANALYSIS (35)
{q:"What is the fulcrum security?",a:"Class where value breaks — partially impaired. Senior: full recovery. Junior: nothing.",category:"Valuation"},
{q:"How find the fulcrum?",a:"Estimate EV, work down cap structure: secured → unsecured → sub → equity. Where EV runs out.",category:"Valuation"},
{q:"What is recovery analysis?",a:"Estimates recovery per class under different scenarios. Drives negotiation.",category:"Valuation"},
{q:"What is a liquidity analysis?",a:"Projects cash flows (13-week) to determine when cash runs out.",category:"Valuation"},
{q:"EV in distressed context?",a:"Total value for claimants. Via distressed comps, asset values, or going-concern DCF.",category:"Valuation"},
{q:"What is liquidation analysis?",a:"Recovery from selling all assets. Usually lower than going-concern. Floor value.",category:"Valuation"},
{q:"Value a distressed company?",a:"Going-concern DCF (if viable), distressed comps, asset-based, SOTP, liquidation.",category:"Valuation"},
{q:"What is recovery rate?",a:"Cents on dollar. Secured: typically 60-80%+. Unsecured: varies widely.",category:"Valuation"},
{q:"What is a 13-week cash flow model?",a:"Weekly cash projections showing receipts, disbursements, ending balance. Critical for distress.",category:"Valuation"},
{q:"What drives restructuring negotiation?",a:"Who controls fulcrum, liquidity position, value estimates, alternatives, litigation threats.",category:"Valuation"},
{q:"What is new money?",a:"Fresh capital during/after restructuring. Favorable terms (DIP, rights offering).",category:"Valuation"},
{q:"What is a make-whole premium?",a:"Prepayment penalty. Often disputed in bankruptcy.",category:"Valuation"},
{q:"What is enterprise value coverage?",a:"EV / Total Debt. Shows how much cushion above total claims. <1x = underwater.",category:"Valuation"},
{q:"What is a plan value?",a:"Estimated value of reorganized company used to allocate distributions.",category:"Valuation"},
{q:"How do you estimate plan value?",a:"DCF of reorganized entity, comparable companies, precedent transactions for emerged companies.",category:"Valuation"},
{q:"What is a TIA (total indebtedness analysis)?",a:"Mapping all debt by priority, maturity, rate, covenants, and collateral.",category:"Valuation"},
{q:"What is a debt capacity analysis?",a:"How much debt the reorganized entity can support based on projected cash flows.",category:"Valuation"},
{q:"What is a claims analysis?",a:"Cataloging all claims by class, amount, and priority. Foundation for recovery analysis.",category:"Valuation"},
{q:"What are section 503(b)(9) claims?",a:"Goods received by debtor within 20 days pre-filing get administrative priority.",category:"Valuation"},
{q:"What is a professional fee claim?",a:"Advisors' fees during bankruptcy. Administrative priority. Can be substantial.",category:"Valuation"},
// CAPITAL STRUCTURE (20)
{q:"Priority of claims?",a:"Super-priority (DIP) → secured → admin → priority unsecured → general unsecured → sub → equity.",category:"Capital Structure"},
{q:"First lien vs second lien?",a:"First: priority on collateral. Second: subordinate, higher risk/yield.",category:"Capital Structure"},
{q:"What is an intercreditor agreement?",a:"Defines rights and priorities between first and second lien lenders.",category:"Capital Structure"},
{q:"What is subordination?",a:"Contractual or structural arrangement ranking one class below another.",category:"Capital Structure"},
{q:"Structural vs contractual subordination?",a:"Structural: claims at subsidiary (parent below). Contractual: explicit agreement to rank below.",category:"Capital Structure"},
{q:"Revolver in distress?",a:"Usually drawn fully pre-filing. Super-senior. Repaid early.",category:"Capital Structure"},
{q:"Senior unsecured notes?",a:"Bonds without collateral. Below secured. Recovery often 20-50%.",category:"Capital Structure"},
{q:"What is trade debt in bankruptcy?",a:"Vendor amounts owed. Can be critical (essential ops) or general unsecured.",category:"Capital Structure"},
{q:"What is an ad hoc group?",a:"Informal creditor group negotiating collectively. Often holds significant claims.",category:"Capital Structure"},
{q:"What is a crossover creditor?",a:"Holds both debt and equity in same company. Complex interests in restructuring.",category:"Capital Structure"},
{q:"What is a credit facility agent?",a:"Administrative agent managing syndicated loan. Coordinates lender actions.",category:"Capital Structure"},
{q:"What is a trustee vs agent?",a:"Agent: for loans (less fiduciary duty). Trustee: for bonds (fiduciary obligations to holders).",category:"Capital Structure"},
{q:"What is priming?",a:"New debt (DIP) with priority above existing secured debt. Requires adequate protection.",category:"Capital Structure"},
{q:"What is roll-up DIP?",a:"Pre-petition debt 'rolled up' into DIP financing, gaining super-priority. Controversial.",category:"Capital Structure"},
// BEHAVIORAL (20)
{q:"Why restructuring?",a:"Most intellectually demanding. Complex cap structures, high stakes, legal/financial/operational intersection.",category:"Behavioral"},
{q:"Debtor-side vs creditor-side?",a:"Debtor: help company reorganize. Creditor: protect recovery. Both need deep analysis.",category:"Behavioral"},
{q:"What RX deal have you followed?",a:"Know company, cap structure, what went wrong, negotiation dynamics, outcome.",category:"Behavioral"},
{q:"What makes someone good at RX?",a:"Comfort with ambiguity, detail in complex cap structures, negotiation, pressure tolerance.",category:"Behavioral"},
{q:"How is RX different from M&A?",a:"RX: adversarial multi-party, legal complexity, time pressure, declining business. M&A: cooperative, growth.",category:"Behavioral"},
{q:"Tell me about yourself.",a:"Analytical rigor → complex problems → why finance/RX → relevant experience.",category:"Behavioral"},
{q:"How do you handle pressure?",a:"RX is high-stakes with tight deadlines. Show composure, prioritization, detail under pressure.",category:"Behavioral"},
{q:"What is the most interesting aspect of RX?",a:"Pick something specific: negotiation dynamics, capital structure analysis, multi-stakeholder complexity.",category:"Behavioral"},
{q:"What would you do if a client was being unreasonable?",a:"Understand their perspective, present facts/alternatives, maintain professionalism, escalate if needed.",category:"Behavioral"},
{q:"Why this firm for RX?",a:"Reference specific deal experience, team reputation, training, client base. Be specific.",category:"Behavioral"},
{q:"Tell me about a time you had to analyze complex information quickly.",a:"Show structured approach to breaking down complexity under time pressure. Common in RX.",category:"Behavioral"},
{q:"What current distressed situation interests you?",a:"Know a real situation: industry, what went wrong, cap structure, likely outcome.",category:"Behavioral"},
];
