import { Flashcard } from './ib-flashcard-data';

// ═══ EQUITY RESEARCH (150+) ═══
export const ER_FLASHCARDS: Flashcard[] = [
// ROLE (20)
{q:"What does a sell-side ER analyst do?",a:"Covers public companies: writes research, builds models, makes recommendations, advises institutional clients.",category:"Role",difficulty:"Intermediate"},
{q:"Buy-side vs sell-side research?",a:"Sell-side: publishes for external clients. Buy-side: internal research driving actual investment decisions.",category:"Role",difficulty:"Intermediate"},
{q:"What is an initiation report?",a:"First coverage: thesis, business overview, industry analysis, model, valuation, risks, catalysts, recommendation.",category:"Role",difficulty:"Intermediate"},
{q:"What is a flash note?",a:"Quick reaction to earnings/news. Brief analysis of impact and revised views.",category:"Role",difficulty:"Intermediate"},
{q:"What is consensus estimate?",a:"Average of analyst estimates (usually EPS). Surprises vs consensus drive stock reactions.",category:"Role",difficulty:"Intermediate"},
{q:"What is a price target?",a:"Analyst's estimate of stock value, typically 12-month forward, based on model and valuation.",category:"Role",difficulty:"Intermediate"},
{q:"What is estimate revision?",a:"Analyst changes forecast. Positive revisions often bullish, negative bearish. Drives stock movement.",category:"Role",difficulty:"Intermediate"},
{q:"What is channel checking?",a:"Gathering data from industry contacts, suppliers, customers to validate thesis before earnings.",category:"Role",difficulty:"Intermediate"},
{q:"What is an earnings preview?",a:"Pre-earnings expectations, key metrics to watch, scenarios.",category:"Role",difficulty:"Intermediate"},
{q:"What is an earnings call?",a:"Management's quarterly call: prepared remarks + analyst Q&A. Critical information source.",category:"Role",difficulty:"Intermediate"},
{q:"How do you stay on top of coverage?",a:"Earnings calls, SEC filings, industry data, competitor commentary, management meetings, daily news.",category:"Role",difficulty:"Intermediate"},
{q:"What is a rating system?",a:"Buy/Overweight, Hold/Neutral, Sell/Underweight. Reflects expected return vs benchmark.",category:"Role",difficulty:"Intermediate"},
{q:"What does Investor Day/Analyst Day mean?",a:"Company event for deep dives on strategy, financials, outlook. Often moves stocks on new info.",category:"Role",difficulty:"Intermediate"},
{q:"What is a quiet period?",a:"Period before/after IPO where company limits communications. Analysts restricted from publishing.",category:"Role",difficulty:"Intermediate"},
{q:"What is MiFID II's impact on research?",a:"Unbundled research payments from trading commissions. Reduced research budgets, fewer analysts.",category:"Role",difficulty:"Intermediate"},
// MODELING (35)
{q:"What is an earnings model?",a:"Detailed financial projections (often quarterly) to estimate EPS and compare to consensus.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for SaaS?",a:"Subscribers × ARPU, adjusted for churn and expansion. Track NRR, new logos, pricing.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for retailer?",a:"Stores × sales/store, or SSS growth + new openings. Decompose into traffic and ticket.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for consumer staples?",a:"Volume × price/mix. Organic vs M&A contribution. Geographic decomposition.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for ad-tech?",a:"Impressions × CPM, or clients × ARPU. Track fill rates, pricing trends.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for a bank?",a:"Net interest income (NIM × earning assets) + non-interest income (fees, trading). Separate clearly.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for insurance?",a:"Premiums written × retention + investment income. Track loss ratio and combined ratio.",category:"Modeling",difficulty:"Intermediate"},
{q:"Revenue build for pharma?",a:"Product-by-product: volume × price, adjusted for patent cliffs, new launches, geographic mix.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you forecast COGS?",a:"As % of revenue (gross margin), or build from input costs, labor, manufacturing. Check trends.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you forecast SG&A?",a:"Fixed vs variable. Headcount × avg comp for labor. Marketing as % of revenue.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you forecast CapEx?",a:"% of revenue, or maintenance + growth separately. Check management guidance.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you forecast working capital?",a:"DSO × revenue, DIO × COGS, DPO × COGS. Or as % of revenue with trends.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is EPS?",a:"Net Income / Diluted Shares. Most-watched metric. Beats/misses drive stocks.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is diluted share count?",a:"Basic + dilutive securities (options, RSUs, convertibles) via treasury stock method.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a DCF in ER context?",a:"Intrinsic valuation: project UFCF, discount at WACC, terminal value, bridge to per-share equity.",category:"Modeling",difficulty:"Advanced"},
{q:"What is SOTP valuation?",a:"Value each segment separately with appropriate multiples, then sum.",category:"Modeling",difficulty:"Intermediate"},
{q:"Key modeling checks?",a:"BS balances, CF reconciles, margins reasonable, growth realistic, no broken links.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you handle seasonality?",a:"Quarterly models. Compare Q vs prior-year Q, not sequential. Adjust for calendar.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is sensitivity analysis in ER?",a:"Test key assumptions (growth, margin, multiple) on price target. Show range.",category:"Modeling",difficulty:"Advanced"},
{q:"How do you bridge EBITDA to FCF?",a:"EBITDA - cash taxes - CapEx - WC changes = UFCF.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is operating leverage in a model?",a:"Fixed costs mean revenue growth > expense growth = margin expansion. Model fixed vs variable separately.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you model share buybacks?",a:"Estimate buyback spend, divide by avg share price = shares retired. Reduces share count, boosts EPS.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you model an acquisition in an ER model?",a:"Add target revenue/costs from close date. Include synergies, financing costs, goodwill/amortization.",category:"Modeling",difficulty:"Advanced"},
{q:"What is consensus vs your estimate?",a:"Your variant view vs market expectation. The gap drives your recommendation.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you set a price target?",a:"Apply target multiple to forward earnings/EBITDA, or DCF-derived per-share value. State methodology clearly.",category:"Modeling",difficulty:"Intermediate"},
// VALUATION (25)
{q:"Common multiples in ER?",a:"P/E (most watched), EV/EBITDA, EV/Revenue for growth, P/FCF, sector-specific (P/B for banks).",category:"Valuation",difficulty:"Intermediate"},
{q:"Forward vs trailing multiples?",a:"Forward (NTM) more relevant — markets price expectations. Trailing shows history.",category:"Valuation",difficulty:"Intermediate"},
{q:"How do you select a target multiple?",a:"Peer comparison, historical range, growth/margin premium or discount, market conditions.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is PEG ratio?",a:"P/E / EPS growth rate. <1 may suggest undervalued for growth. Simplistic but useful.",category:"Valuation",difficulty:"Intermediate"},
{q:"Value high-growth unprofitable company?",a:"EV/Revenue, DCF with long-term margins, unit economics, comparable transactions.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is bull/base/bear?",a:"Three scenarios with different assumptions. Shows upside/downside range around target.",category:"Valuation",difficulty:"Intermediate"},
{q:"Why can two similar companies trade at different multiples?",a:"Growth, margins, ROIC, balance sheet, management, market position, earnings quality.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is a re-rating?",a:"Market assigns higher/lower multiple. From improved outlook, sector rotation, or risk change.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is normalized earnings?",a:"Adjusted for cyclical/one-time effects to show sustainable earning power.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is a football field chart?",a:"Valuation ranges from different methods side by side.",category:"Valuation",difficulty:"Advanced"},
{q:"When is P/E most useful?",a:"Profitable companies with stable capital structure and tax rates. Less useful for cyclicals or levered cos.",category:"Valuation",difficulty:"Intermediate"},
{q:"When is EV/EBITDA preferred?",a:"Comparing companies with different capital structures. More capital-structure neutral than P/E.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is a justified multiple?",a:"Multiple derived from fundamentals (growth, ROIC, risk). Not arbitrary. P/E = payout/(r-g).",category:"Valuation",difficulty:"Intermediate"},
// STOCK PITCH (25)
{q:"Tell me about a stock you follow.",a:"Business model, revenue drivers, margins, competitive position, recent results vs consensus, your view, valuation, risks.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"How do you build a stock pitch?",a:"1) Pick company you know. 2) Why mispriced. 3) Valuation. 4) Catalysts. 5) Risks. 6) Practice.",category:"Stock Pitch",difficulty:"Advanced"},
{q:"What is the market missing?",a:"Core of a good pitch. What does consensus get wrong about growth, margins, capital allocation, or risk?",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"Compare two investment ideas.",a:"Risk-adjusted return, conviction, catalyst visibility, downside protection, liquidity, portfolio fit.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"What would make you change your rating?",a:"Thesis invalidation, valuation fully reflected, fundamental deterioration, better opportunity, risk-reward shift.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"Handle pushback on a pitch?",a:"Acknowledge concern, explain why your view differs, cite evidence. Don't get defensive.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"What is a contrarian call?",a:"Going against consensus with differentiated thesis. Requires strong evidence and conviction.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"Why is downside analysis important?",a:"Shows you've considered what goes wrong. Investors care about risk-reward, not just upside.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"What is a catalyst?",a:"Event closing gap between price and value: earnings, product launch, regulatory change, management action.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"What is a variant view?",a:"Your differentiated perspective vs market consensus. The basis for any actionable recommendation.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"How do you frame upside/downside?",a:"Bull/base/bear with probabilities. Calculate expected value. Show asymmetry if it exists.",category:"Stock Pitch",difficulty:"Intermediate"},
{q:"What is a show-me story?",a:"Stock that needs to prove something (turnaround, margin improvement). Market skeptical, needs evidence.",category:"Stock Pitch",difficulty:"Intermediate"},
// BEHAVIORAL (25)
{q:"Why equity research?",a:"Deep company/industry expertise, fundamental analysis, writing/communication, influencing institutional investors.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Why sell-side vs buy-side?",a:"Sell-side: broader coverage, more communication, client-facing. Buy-side: deeper analysis, capital allocation.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What sectors interest you?",a:"Pick one genuinely. Know key players, dynamics, trends, regulatory backdrop.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you prioritize during earnings season?",a:"Coverage first, then adjacent. Pre-write templates. Flag surprises quickly. Manage time ruthlessly.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about being wrong on a stock.",a:"Thesis, what went wrong, what you learned, process changes.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about yourself.",a:"Markets interest → analytical/writing skills → why ER combines both → sector interest.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What do you read every morning?",a:"WSJ, Bloomberg, FT, sector sources, transcripts, research. Show daily habit.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Evaluate management quality?",a:"Track record on guidance, capital allocation, candor, strategic consistency, insider activity.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is the hardest part of ER?",a:"Being wrong publicly, maintaining conviction under pressure, producing quality under tight deadlines.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you handle disagreement with senior analyst?",a:"Present your reasoning with data, listen to their experience, find common ground, learn.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What stock are you following right now?",a:"Have 2-3 ready. Know recent quarter, consensus, your view, key drivers, valuation.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you add value as a junior analyst?",a:"Thorough modeling, industry contacts, creative analysis, detailed notes, reliable work product.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is your writing style?",a:"Clear, concise, data-driven. Lead with conclusion, support with analysis, flag risks.",category:"Behavioral",difficulty:"Intermediate"},
];

// ═══ REAL ESTATE (150+) ═══
export const RE_FLASHCARDS: Flashcard[] = [
// FUNDAMENTALS (35)
{q:"What is NOI?",a:"Net Operating Income = Revenue - Operating Expenses. Excludes debt service, CapEx, taxes.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a cap rate?",a:"NOI / Property Value. Yield on property. Lower cap = higher price.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Cap rate and value relationship?",a:"Inverse. Cap rates rise → values fall. Value = NOI / Cap Rate.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Going-in vs exit cap rate?",a:"Going-in: at acquisition. Exit: at sale. Exit usually higher (older/riskier).",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What drives cap rates?",a:"Rates, risk perception, supply/demand, property quality, location, lease profile, growth.",category:"Fundamentals",difficulty:"Advanced"},
{q:"What is occupancy rate?",a:"% of rentable space leased. Higher = more stable income.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is effective gross income?",a:"Potential gross income - vacancy + other income. Revenue expected to be collected.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a triple-net (NNN) lease?",a:"Tenant pays rent + taxes + insurance + maintenance. Minimal landlord risk.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a gross lease?",a:"Landlord pays operating expenses. Tenant pays flat rent.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a modified gross lease?",a:"Some expenses shared between landlord and tenant. Hybrid approach.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is tenant improvement (TI)?",a:"Landlord-funded space buildout. Higher TI = lower effective rent.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is lease-up risk?",a:"Risk of not filling vacant space. New developments and value-add face this.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Main property types?",a:"Multifamily, office, retail, industrial, hospitality, self-storage, data centers, life science.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is absorption?",a:"Net change in occupied space. Positive = more occupied. Key demand indicator.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is WALT?",a:"Weighted Average Lease Term. Longer = more income certainty.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is replacement cost?",a:"Cost to build equivalent property today. Floor for existing values.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a rent roll?",a:"Schedule of all tenants, lease terms, rents, expirations. Foundation of property analysis.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is mark-to-market rent?",a:"Difference between in-place rents and current market rents. Upside if below market.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a tenant credit analysis?",a:"Evaluating tenant's ability to pay rent. Investment-grade vs local business matters.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a lease escalation?",a:"Annual rent increase. Fixed (3%/year), CPI-linked, or step-up schedule.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is concessions?",a:"Incentives to attract tenants: free rent, TI, moving allowance. Reduce effective rent.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is net effective rent?",a:"Actual rent after accounting for concessions, TI, and free rent over lease term.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a ground lease?",a:"Lease of land only. Tenant builds/owns improvements. Long-term (50-99 years).",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is highest and best use?",a:"Most productive legally permissible, physically possible, financially feasible use of land.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is zoning?",a:"Government regulation of land use: residential, commercial, industrial, mixed-use. Limits what you can build.",category:"Fundamentals",difficulty:"Intermediate"},
// MODELING & RETURNS (30)
{q:"What is a pro forma?",a:"Projected financials: revenue, expenses, NOI, debt service, returns, exit.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is cash-on-cash return?",a:"Annual pre-tax cash flow / total cash invested. Simple yield.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is IRR in real estate?",a:"Annualized return on all cash flows: acquisition, operations, capital events, sale.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is an equity multiple?",a:"Total distributions / total equity. 2.0x = doubled money.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is LTV?",a:"Loan / Property Value. Measures leverage. Higher = more risk.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is DSCR?",a:"NOI / Debt Service. Lenders want >1.2x.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a waterfall structure?",a:"Distributes cash in tiers: preferred return → GP catch-up → profit split.",category:"Modeling",difficulty:"Advanced"},
{q:"What is a preferred return?",a:"Minimum LP return before GP earns promote. Typically 8%.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is promote?",a:"GP's profit share above preferred return. Similar to carried interest.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a lookback provision?",a:"Ensures LPs receive pref over entire hold, not just annually.",category:"Modeling",difficulty:"Intermediate"},
{q:"How project rent growth?",a:"Market trends, escalations, mark-to-market on expiry.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is CapEx reserve?",a:"Annual budget for capital improvements. Reduces distributable cash.",category:"Modeling",difficulty:"Intermediate"},
{q:"Amortizing vs IO loan?",a:"Amortizing: principal + interest. IO: interest only. IO = higher cash flow, slower equity build.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is unlevered yield?",a:"NOI / total cost (acquisition + closing + CapEx). Return before financing.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is yield-on-cost?",a:"Stabilized NOI / total development cost. Key development feasibility metric.",category:"Modeling",difficulty:"Intermediate"},
{q:"How do you model a development?",a:"Land cost + hard/soft costs + financing → lease-up period → stabilized NOI → exit value → returns.",category:"Modeling",difficulty:"Advanced"},
{q:"What is a sensitivity table for RE?",a:"Vary exit cap rate and rent growth to show IRR range. Standard for investment memos.",category:"Modeling",difficulty:"Advanced"},
{q:"What is a hold period?",a:"Planned ownership duration. Typically 3-7 years for value-add, 7-10+ for core.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a reversion value?",a:"Estimated sale price at exit. Usually NOI at exit / exit cap rate.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a closing cost estimate?",a:"Transfer taxes, legal, title, lender fees, inspection. Typically 1-3% of purchase price.",category:"Modeling",difficulty:"Intermediate"},
// STRATEGY & REITS (25)
{q:"Core vs Value-Add vs Opportunistic?",a:"Core: 6-8%, stabilized. Value-Add: 12-18%, improvement. Opportunistic: 18%+, development/distressed.",category:"Strategy",difficulty:"Intermediate"},
{q:"What is value-add RE?",a:"Properties needing improvement (renovation, re-leasing) to increase NOI and value.",category:"Strategy",difficulty:"Intermediate"},
{q:"What is ground-up development?",a:"Building from scratch. Highest risk (entitlement, construction, lease-up) but highest potential returns.",category:"Strategy",difficulty:"Intermediate"},
{q:"What is a 1031 exchange?",a:"Tax-deferred exchange: sell property, buy equal/greater value. Defers capital gains.",category:"Strategy",difficulty:"Intermediate"},
{q:"What is FFO?",a:"NI + D&A - gains on sales. Standard REIT earnings metric.",category:"REITs",difficulty:"Intermediate"},
{q:"What is AFFO?",a:"FFO - maintenance CapEx - straight-line rent adjustments. Better cash flow proxy.",category:"REITs",difficulty:"Intermediate"},
{q:"Why FFO over NI for REITs?",a:"RE depreciation overstates expense. Properties often appreciate. FFO removes distortion.",category:"REITs",difficulty:"Intermediate"},
{q:"What is NAV for a REIT?",a:"Property values (NOI/cap rate) minus debt plus other assets. Compare to stock price.",category:"REITs",difficulty:"Intermediate"},
{q:"Premium vs discount to NAV?",a:"Premium: market values growth/management. Discount: market skeptical.",category:"REITs",difficulty:"Intermediate"},
{q:"What is a REIT?",a:"Must distribute 90%+ taxable income. Provides liquidity and diversification in RE.",category:"REITs",difficulty:"Intermediate"},
{q:"What is same-store NOI growth?",a:"NOI growth from properties owned in both periods. Shows organic performance.",category:"REITs",difficulty:"Intermediate"},
{q:"What is a UPREIT?",a:"Umbrella Partnership REIT. Allows property owners to contribute assets tax-deferred in exchange for OP units.",category:"REITs",difficulty:"Intermediate"},
{q:"What is a triple-net REIT?",a:"REIT owning NNN-leased properties. Very stable, low management intensity, lower growth.",category:"REITs",difficulty:"Intermediate"},
// DEBT & MARKET (25)
{q:"RE debt types?",a:"Senior mortgage, mezz, CMBS, construction, bridge, preferred equity.",category:"Debt",difficulty:"Intermediate"},
{q:"What is CMBS?",a:"Commercial Mortgage-Backed Securities. Pooled commercial loans sold as bonds.",category:"Debt",difficulty:"Intermediate"},
{q:"What is mezzanine debt in RE?",a:"Subordinate to senior mortgage. Higher rate. Secured by ownership interest, not property.",category:"Debt",difficulty:"Intermediate"},
{q:"What is a bridge loan?",a:"Short-term (1-3yr) for transitional properties. Higher rate. Used during value-add.",category:"Debt",difficulty:"Intermediate"},
{q:"Rising rates affect RE how?",a:"Cap rates expand (values fall), financing expensive, volume drops. But rents may offset in inflation.",category:"Debt",difficulty:"Intermediate"},
{q:"Recourse vs non-recourse?",a:"Recourse: lender pursues other assets. Non-recourse: limited to property.",category:"Debt",difficulty:"Intermediate"},
{q:"What is debt yield?",a:"NOI / Loan Amount. Lender-focused return metric regardless of rates.",category:"Debt",difficulty:"Intermediate"},
{q:"What is a rate lock?",a:"Fixes interest rate before closing. Protects against rate increases.",category:"Debt",difficulty:"Intermediate"},
{q:"What is loan amortization in RE?",a:"Gradual principal repayment. 25-30 year schedule common even on 5-10 year terms (balloon).",category:"Debt",difficulty:"Intermediate"},
{q:"What is a balloon payment?",a:"Remaining principal due at loan maturity. Creates refinancing risk.",category:"Debt",difficulty:"Intermediate"},
{q:"What is an interest rate cap?",a:"Derivative limiting maximum floating rate. Required by many floating-rate lenders.",category:"Debt",difficulty:"Intermediate"},
{q:"What is a defeasance?",a:"Substituting collateral (usually Treasuries) to release property from loan. Expensive but enables sale.",category:"Debt",difficulty:"Intermediate"},
{q:"What is loan-to-cost (LTC)?",a:"Loan / total project cost. Used for development and value-add. Typically 60-75%.",category:"Debt",difficulty:"Intermediate"},
// BEHAVIORAL (15)
{q:"Why real estate?",a:"Tangible assets, inflation protection, income, leverage, intersection of finance and operations.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What property type interests you?",a:"Pick one. Know supply/demand, cap rates, key players, recent transactions.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about a deal you analyzed.",a:"Property type, location, strategy, returns, risks. Show analytical depth.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What market are you bullish/bearish on?",a:"Specific city or property type. Support with supply, demand, demographics, employment.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How would you evaluate a property?",a:"Location, condition, tenant quality, lease terms, NOI stability, comps, basis vs replacement.",category:"Behavioral",difficulty:"Advanced"},
{q:"Tell me about yourself.",a:"Interest in real assets → analytical skills → relevant experience → why RE.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is the biggest risk in RE right now?",a:"Pick a current issue: rates, remote work (office), oversupply, cap rate expansion. Show market awareness.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you source deals?",a:"Broker relationships, off-market outreach, proprietary research, industry events, owner relationships.",category:"Behavioral",difficulty:"Intermediate"},
];

// ═══ VENTURE CAPITAL (150+) ═══
export const VC_FLASHCARDS: Flashcard[] = [
// FUNDAMENTALS (25)
{q:"What is venture capital?",a:"Investing in early-stage, high-growth companies for equity. High failure offset by outsized winners.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the power law?",a:"Most returns from tiny number of investments. One company may return the entire fund.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Seed vs Series A vs B?",a:"Seed: idea/early product, $1-5M. A: PMF, $5-25M. B: scaling, $20-100M+.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a cap table?",a:"Ownership %, share classes, option pools, dilution from each round.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is an option pool?",a:"Shares reserved for employees. Usually 10-20%. Created/expanded at rounds.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is dilution?",a:"Ownership % reduction when new shares issued. Each round dilutes existing holders.",category:"Fundamentals",difficulty:"Advanced"},
{q:"What is a down round?",a:"Funding at lower valuation. Triggers anti-dilution. Signals distress.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is product-market fit?",a:"Product satisfies strong demand. Signs: organic growth, retention, word-of-mouth.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What makes a great VC investment?",a:"Massive market, exceptional founders, PMF, unit economics, defensibility, reasonable valuation.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"How do VCs make money?",a:"2% management fee + 20% carry on profits above hurdle.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"VC fund lifecycle?",a:"10 years: 3-4yr investment + harvesting through exits.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"VC exit strategies?",a:"IPO, M&A, secondary sale, or shutdown/write-off.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a unicorn?",a:"Private company valued at $1B+. Term coined 2013. Much more common now.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a decacorn?",a:"Private company valued at $10B+. Rare, represents the biggest winners.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is bridge financing?",a:"Short-term funding between rounds. Usually converts. Can signal either momentum or distress.",category:"Fundamentals",difficulty:"Intermediate"},
// DEAL TERMS (35)
{q:"What is a term sheet?",a:"Non-binding key terms: valuation, amount, liquidation pref, board seats, anti-dilution.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"Pre-money vs post-money?",a:"Pre = value before investment. Post = pre + investment. Ownership = investment / post.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is liquidation preference?",a:"Investor gets money back (1x) before common in a sale. 1x non-participating standard.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"Participating vs non-participating?",a:"Non-participating: choose pref or common share. Participating: get pref back PLUS share remaining.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is anti-dilution?",a:"Protects in down rounds. Weighted average (common) vs full ratchet (harsh).",category:"Deal Terms",difficulty:"Advanced"},
{q:"What is a SAFE?",a:"Simple Agreement for Future Equity. Not debt, converts at next round with discount/cap.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a convertible note?",a:"Debt converting to equity at next round with discount and/or cap.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"Discount vs cap?",a:"Discount: buy at X% less than round price. Cap: max valuation for conversion.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is pro rata?",a:"Right to invest in future rounds to maintain ownership %. Valuable for winners.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a board seat?",a:"Lead investor gets board seat for governance and investment protection.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is drag-along?",a:"Majority can force minority to join sale. Prevents blocking exits.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is tag-along?",a:"Minority can join if majority sells. Protects from being left behind.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is information rights?",a:"Right to receive financial reports and updates.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a vesting schedule?",a:"4-year vest, 1-year cliff. Earn equity over time.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is an 83(b) election?",a:"Pay taxes on stock at grant (low value) vs vesting (high value).",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a protective provision?",a:"Investor veto rights on major decisions: fundraising, sale, debt, bylaws changes.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a pay-to-play provision?",a:"Investors who don't participate in future rounds lose certain rights. Encourages follow-on support.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a right of first refusal (ROFR)?",a:"Company or investors can match any secondary sale offer before allowing transfer.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a redemption right?",a:"Investor can force company to buy back shares after set period. Rarely exercised, provides leverage.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a founder lockup?",a:"Restriction on founders selling shares for a period post-IPO. Typically 180 days.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is weighted average anti-dilution?",a:"Adjusts conversion price based on new shares issued and price. Less severe than full ratchet.",category:"Deal Terms",difficulty:"Advanced"},
{q:"What is a valuation cap on a SAFE?",a:"Maximum valuation at which SAFE converts. Protects early investor if next round is much higher.",category:"Deal Terms",difficulty:"Intermediate"},
{q:"What is a most favored nation (MFN) clause?",a:"If company issues SAFEs with better terms later, earlier SAFE holder can adopt those terms.",category:"Deal Terms",difficulty:"Intermediate"},
// SAAS METRICS (25)
{q:"What is ARR/MRR?",a:"Annual/Monthly Recurring Revenue. Core subscription metric.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is NDR?",a:"Net Dollar Retention. Existing customer revenue Y2/Y1. >120% excellent.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is CAC?",a:"Customer Acquisition Cost. Sales + marketing / new customers.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is LTV?",a:"Lifetime Value = avg revenue × margin × lifespan. LTV/CAC > 3x healthy.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is CAC payback?",a:"Months to recover acquisition cost. <12 good. >18 concerning.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"Gross vs net churn?",a:"Gross: total revenue lost. Net: gross offset by expansion from remaining.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"Logo vs revenue churn?",a:"Logo: % customers lost. Revenue: % revenue lost. Can differ by customer size.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is expansion revenue?",a:"Additional revenue from existing customers: upsells, cross-sells, usage growth.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is Rule of 40?",a:"Revenue growth % + profit margin % > 40% for healthy SaaS.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"Gross margin for SaaS?",a:"Typically 70-85%. Includes hosting, support, CS costs.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is ACV?",a:"Annual Contract Value. Higher ACV = more enterprise-focused.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is magic number?",a:"Net new ARR / prior quarter S&M spend. >1x is good.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is burn rate?",a:"Monthly cash consumed. Revenue minus all expenses.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is runway?",a:"Cash / monthly burn = months until cash out. 12-18 comfortable.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is NPS?",a:"Net Promoter Score. Customer satisfaction metric. Promoters minus detractors.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is DAU/MAU ratio?",a:"Daily/Monthly active users. Measures engagement stickiness. >50% excellent.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is virality coefficient (K-factor)?",a:"Users × invites × conversion rate. K > 1 = viral growth.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is cohort analysis?",a:"Tracking behavior of user groups over time. Reveals retention and monetization trends.",category:"SaaS Metrics",difficulty:"Intermediate"},
{q:"What is gross merchandise value (GMV)?",a:"Total value of transactions on a marketplace. Revenue = GMV × take rate.",category:"SaaS Metrics",difficulty:"Intermediate"},
// EVALUATION (25)
{q:"What is TAM/SAM/SOM?",a:"Total/Serviceable/Obtainable Market. Theoretical to realistic capture.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Top-down vs bottom-up TAM?",a:"Top-down: industry data. Bottom-up: customers × price. Bottom-up more credible.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Evaluate a founding team?",a:"Domain expertise, complementary skills, execution track record, resilience, coachability, vision.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is a moat for a startup?",a:"Network effects, data advantages, switching costs, brand, regulatory, technical IP.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Evaluate unit economics?",a:"LTV/CAC, margins, payback. Must be positive and scalable.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Attractive market for VC?",a:"Large, growing, fragmented, tech-disruption possible, venture-scale outcomes.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is venture-scale return?",a:"10-100x+ potential. VC math requires winners compensate for many losses.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Assess competitive landscape?",a:"Direct competitors, adjacent players, incumbent response, differentiation, barriers.",category:"Evaluation",difficulty:"Intermediate"},
{q:"Common startup failure reasons?",a:"No market need (#1), ran out of cash, wrong team, outcompeted, pricing issues, bad product, timing.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is a pivot?",a:"Fundamental change in product/market/model based on learnings. Adaptability if done well.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is a business model canvas?",a:"One-page framework: value prop, segments, channels, revenue, costs, partners, activities, resources.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is a minimum viable product (MVP)?",a:"Simplest version of product to test hypothesis with real users. Core lean startup concept.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is the lean startup methodology?",a:"Build → Measure → Learn loop. Rapid iteration based on customer feedback.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is traction?",a:"Evidence of product-market fit: revenue, users, engagement, partnerships. What investors look for.",category:"Evaluation",difficulty:"Intermediate"},
{q:"How do you assess timing risk?",a:"Too early: market not ready. Too late: competition established. Best: inflection point.",category:"Evaluation",difficulty:"Intermediate"},
{q:"What is a winner-take-most market?",a:"Market where one player captures dominant share due to network effects or scale. Huge outcome if you win.",category:"Evaluation",difficulty:"Intermediate"},
// BEHAVIORAL (15)
{q:"Why venture capital?",a:"Innovation passion, founder evaluation, long horizon, conviction on trends, helping companies scale.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What sector thesis excites you?",a:"Pick one genuinely. Know landscape, startups, trends, risks.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about a startup you'd invest in.",a:"Team, market, product, traction, unit economics, competitive position, valuation, risks.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you source deals?",a:"Network, events, accelerators, referrals, cold outreach, thesis-driven research.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What makes a great VC?",a:"Pattern recognition, founder empathy, conviction, network, willingness to be wrong, value-add.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you add value?",a:"Introductions, hiring help, strategic advice, follow-on capital, governance, customer connections.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about yourself.",a:"Interest in tech/startups → analytical skills → experience → why VC combines all.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is your investment thesis?",a:"Have a sector or trend view. Explain why now, what you look for, what excites you.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about a company you wish you'd invested in.",a:"Show market awareness. Explain why it was compelling and what you'd look for next time.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you evaluate a pitch deck?",a:"Team, problem, solution, market, traction, business model, financials, ask. Look for clarity and honesty.",category:"Behavioral",difficulty:"Intermediate"},
];

// ═══ RESTRUCTURING (150+) ═══
export const RX_FLASHCARDS: Flashcard[] = [
// ═══ FUNDAMENTALS (1-25) ═══
{q:"What is restructuring?",a:"The process of fixing a company's capital structure when it becomes unsustainable — reducing leverage, improving liquidity, extending runway so the company can survive and return to stability.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What are the two main types of restructuring?",a:"Out-of-court (negotiated privately, faster, cheaper, requires consent) and in-court/Chapter 11 (formal legal process, used when agreement can't be reached, allows forcing a plan).",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the main goal of restructuring?",a:"Right-size the capital structure so it's sustainable — reduce debt burden, improve liquidity, align obligations with actual cash flow. Not just buy time but create a viable long-term business.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is financial distress?",a:"When a company cannot meet its debt obligations or is likely to default soon. Can stem from declining revenue, excess leverage, or poor liquidity. Doesn't always mean bankruptcy.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the difference between liquidity and solvency?",a:"Liquidity = short-term ability to pay obligations (do we have cash now?). Solvency = long-term viability (are assets worth more than liabilities?). A company can be solvent but illiquid, or insolvent but temporarily liquid.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a default vs a technical default?",a:"Default = failing to make required payments (interest or principal). Technical default = violating a covenant even if payments are current. Both can trigger restructuring discussions.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is Chapter 11?",a:"Legal bankruptcy process allowing a company to continue operating, restructure obligations, and negotiate with creditors under court supervision. Key advantage: can force a plan even if not all creditors agree.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why would a company choose out-of-court vs in-court?",a:"Out-of-court: faster, cheaper, less reputational damage. In-court when: creditors disagree, need legal tools like cramdown, capital structure too complex. Tradeoff between efficiency and control.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a capital structure?",a:"How a company finances itself — debt (loans, bonds) and equity. Critical in restructuring because it determines who gets paid first, drives recoveries, and defines negotiation dynamics.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is capital structure so important in restructuring?",a:"Because restructuring is fundamentally about reallocating value across the capital structure. If the company is worth less than its debt, not everyone gets paid — the key question is: who gets what?",category:"Fundamentals",difficulty:"Advanced"},
{q:"What is recovery?",a:"The percentage of a creditor's claim they receive after restructuring. Example: owed $100, receive $60 = 60% recovery. One of the most important outputs in restructuring analysis.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What determines recovery rates?",a:"Enterprise value of the company, position in the capital structure, and legal protections (collateral, covenants). Senior secured lenders typically recover more than junior creditors.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a haircut?",a:"A reduction in a creditor's claim. Example: $100 claim reduced to $70 = 30% haircut. Common when the company's value is insufficient to cover all obligations.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is restructuring considered more art than science?",a:"Because multiple valid solutions can exist. Two experienced bankers might propose different approaches (extend maturities, exchange debt, file Ch.11) — all could work. Highly contextual.",category:"Fundamentals",difficulty:"Advanced"},
{q:"Why is psychology important in restructuring?",a:"Because you must convince creditors to accept less than they're owed. Even financially sound solutions can fail if creditors reject them. Success depends on incentives, negotiation strategy, and stakeholder alignment.",category:"Fundamentals",difficulty:"Advanced"},
{q:"Why don't bulge bracket banks dominate restructuring?",a:"Conflicts of interest — they lend money, hold debt, provide research. Restructuring requires independent advice, which is why elite boutiques (PJT, Houlihan, Evercore) dominate.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What makes restructuring different from M&A?",a:"M&A focuses on valuation and transactions. RX solves a financial crisis. RX outcomes vary more widely, involve more creativity and uncertainty, and require legal + financial + negotiation skills.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a restructuring mandate?",a:"When a company or creditor group hires a bank to advise. Winning mandates depends on quality of ideas and thoughtfulness of solutions, not just brand name.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is RX considered more meritocratic?",a:"Companies in distress don't have prior relationships and don't care about balance sheet strength — they care about who has the best solution. Analyst work can actually influence outcomes.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is leverage?",a:"Amount of debt a company uses. Higher leverage increases returns in good times but increases risk in bad times. Most restructuring situations are driven by excess leverage.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a maturity wall?",a:"When large amounts of debt come due in the near term. If the company can't refinance, it may be forced into restructuring.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is free cash flow and why does it matter in RX?",a:"Cash generated after expenses and investments. Debt is repaid with cash, not accounting earnings — if FCF is insufficient, distress follows.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is interest coverage?",a:"EBITDA / Interest expense. Measures how easily a company can service debt. Low coverage = high risk of default.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a distressed company?",a:"One where debt is trading at a discount and default risk is high. Often reflects market expectations of restructuring.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the core mindset of a restructuring banker?",a:"'Given this company's constraints, what is the best achievable solution?' Not just what is the company worth, but how do we fix the capital structure so it survives.",category:"Fundamentals",difficulty:"Advanced"},
// ═══ DAY-TO-DAY & MODELING (26-50) ═══
{q:"Walk me through what a restructuring banker does day-to-day.",a:"Analyzing distressed companies and proposing solutions: building operating models, creating recap models, analyzing capital structures and creditor recoveries, preparing pitch decks with solutions.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a recap model?",a:"Shows how a company's capital structure changes under different restructuring scenarios — debt exchanges, new financing, maturity extensions. Shows how leverage, liquidity, and sustainability change.",category:"Modeling",difficulty:"Intermediate"},
{q:"How is modeling in RX different from M&A?",a:"M&A focuses on valuation (DCF, comps). RX focuses on scenario analysis — what happens if we restructure this way vs that way? Does the company survive? Less 'what is it worth' and more 'what path works.'",category:"Modeling",difficulty:"Intermediate"},
{q:"What is the difference between out-of-court and in-court modeling?",a:"Out-of-court: scenario-driven, uses recap models, tests liquidity/leverage/runway. In-court: valuation-driven, needed for Plan of Reorganization, uses DCF + comps to determine EV.",category:"Modeling",difficulty:"Advanced"},
{q:"Why is valuation harder in restructuring?",a:"Company is unstable — uncertain future cash flows, binary outcomes (survive vs fail), dependent on restructuring outcome itself. Valuation becomes highly subjective and debated.",category:"Modeling",difficulty:"Advanced"},
{q:"What is a Plan of Reorganization (POR)?",a:"Formal plan in Ch.11 outlining how the company restructures, how much each creditor class recovers, and what the post-reorg company looks like. The blueprint for the company's future.",category:"Bankruptcy",difficulty:"Advanced"},
{q:"What does 'impaired' mean in restructuring?",a:"A class is impaired if their rights are changed or they receive less than originally promised. Paid in full = unimpaired. Less than full = impaired. Only impaired classes vote on the plan.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What is a fulcrum security?",a:"The class of debt at the point where value runs out — typically gets converted into equity. This group often becomes the new owners of the company post-restructuring.",category:"Valuation",difficulty:"Advanced"},
{q:"Why is enterprise value so important in restructuring?",a:"It determines who gets paid and who doesn't. Higher EV = more creditors recover. Lower EV = junior creditors get wiped out. Even small valuation changes can shift billions in recovery.",category:"Valuation",difficulty:"Advanced"},
{q:"What is a waterfall analysis?",a:"Shows how value flows down the capital structure: start with EV, pay most senior first, continue down until value runs out. Determines recoveries for each class.",category:"Valuation",difficulty:"Intermediate"},
{q:"Why are waterfalls heavily tested in interviews?",a:"They test capital structure understanding, logical thinking, and attention to detail. They reflect real RX work — figuring out who gets what.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is senior vs junior debt?",a:"Senior = paid first. Junior = paid after senior. Priority determines recovery — higher priority = higher recovery.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is secured vs unsecured debt?",a:"Secured = backed by collateral. Unsecured = no collateral. Secured lenders have stronger claims and typically recover more.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is pari passu?",a:"Equal ranking in the capital structure. If two debts are pari passu, they share recoveries proportionally (pro rata).",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is structural subordination?",a:"Debt at a parent company is effectively junior to debt at a subsidiary because subsidiary creditors get paid first from subsidiary assets.",category:"Capital Structure",difficulty:"Advanced"},
{q:"What is a distressed exchange?",a:"Creditors agree to modify debt terms to avoid bankruptcy — extend maturity, reduce principal, change interest terms.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a debt-for-equity swap?",a:"Creditors exchange debt for ownership in the company. Reduces debt burden and aligns incentives. Common in Ch.11.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a maturity extension?",a:"Pushing back when debt is due. Improves liquidity and buys time but doesn't reduce total debt.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a liquidity crisis vs solvency crisis?",a:"Liquidity crisis = short-term cash issue (can sometimes be fixed quickly). Solvency crisis = long-term value problem (requires deeper restructuring).",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is 'runway' in restructuring?",a:"How long a company can survive before running out of cash. Driven by cash balance and burn rate.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is liquidity often more important than valuation short-term?",a:"Companies fail due to lack of cash, not lack of value. Even valuable companies can go bankrupt if they can't pay bills.",category:"Fundamentals",difficulty:"Advanced"},
{q:"What is DIP financing?",a:"New financing provided during bankruptcy. Has priority over existing debt and provides liquidity to operate. Super-senior status.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"Why would lenders provide DIP financing?",a:"Because it's senior and protected with super-priority status. Often earns high returns with strong collateral protections.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What is a restructuring pitch?",a:"Presents the company's situation, potential solutions, and why your solution is best. In RX, pitches are solution-driven, not just informational.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What differentiates top candidates in RX interviews?",a:"Contextual understanding of restructuring — not just memorizing answers but understanding how deals work, explaining tradeoffs, thinking through problems logically.",category:"Behavioral",difficulty:"Advanced"},
// ═══ DEBT INSTRUMENTS & CREDIT (51-75) ═══
{q:"What is a corporate bond?",a:"A loan to a company packaged as a tradable security. Investors receive periodic interest (coupon) and return of principal at maturity. Publicly traded, held by institutional investors.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a bank loan vs a bond?",a:"Loan: direct from lenders, private, relationship-driven, tighter covenants, easier to renegotiate. Bond: security issued to investors, public, market-driven, harder to coordinate.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What are the two main types of loans?",a:"Revolver (can be drawn, repaid, redrawn — for liquidity) and Term Loan (fixed amount, repaid over time — longer-term financing).",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a covenant?",a:"A rule or restriction on a borrower in debt agreements to protect lenders from excessive risk.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What are the three types of covenants?",a:"Affirmative (things company must do), Negative (things company cannot do), Financial/maintenance (ratio-based tests like leverage ratios).",category:"Capital Structure",difficulty:"Intermediate"},
{q:"Why are covenants important in restructuring?",a:"Covenant breaches can trigger defaults and force negotiations. Often the first signal of distress.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is an indenture?",a:"The legal document governing a bond — outlines terms, covenants, and rights of bondholders.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a spread?",a:"Yield on a bond or loan above a benchmark rate (SOFR for loans, Treasuries for bonds). Reflects credit risk — higher spread = higher perceived risk.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is yield to maturity (YTM)?",a:"Total annualized return if you hold the bond until maturity. Incorporates coupon payments, purchase price, and time to maturity.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"Why does yield matter in restructuring?",a:"Yield reflects market-implied risk of default. Very high yields signal distress and potential restructuring.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What does it mean if a bond trades at a discount?",a:"Market expects losses — high probability of restructuring. Trading at 70 cents on the dollar means the market thinks you won't get full recovery.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a tranche?",a:"A specific layer of debt within the capital structure. Each tranche can differ by priority, interest rate, and maturity.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is leverage in credit analysis?",a:"Amount of debt relative to earnings or assets. Common metrics: Debt/EBITDA, Debt/Equity.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What are the two key pillars of credit analysis?",a:"Cash flow (liquidity — can the company survive?) and asset protection (collateral value — if it fails, what can be sold to repay creditors?).",category:"Valuation",difficulty:"Intermediate"},
{q:"What is amortization in debt context?",a:"Gradual repayment of debt over time. More common in loans, less common in bonds.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a cash flow sweep?",a:"Requirement that excess cash flow is used to pay down debt. Reduces leverage and protects lenders.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a revolver and why important in distress?",a:"Flexible credit line that can be drawn when needed. In distress, companies often draw it fully as a 'war chest' before restructuring.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"Why are loans easier to renegotiate than bonds?",a:"Loans have fewer lenders and amendments require fewer approvals. Bonds are widely distributed and harder to coordinate.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is PIK (Payment-in-Kind) interest?",a:"Company pays interest with additional debt instead of cash — debt balance grows. Used when liquidity is weak. Delays distress but worsens eventual outcome.",category:"Capital Structure",difficulty:"Advanced"},
{q:"What are toggle bonds?",a:"Give the company the option to pay interest in cash or PIK. Flexibility helps manage liquidity in distress.",category:"Capital Structure",difficulty:"Advanced"},
{q:"What is 'trading flat'?",a:"Bond trading without accrued interest due to distress or default. Signals high risk of non-payment.",category:"Capital Structure",difficulty:"Advanced"},
{q:"Why do distressed investors buy debt at a discount?",a:"They expect higher recovery than purchase price. Buy at 40, recover 70 = strong return. This is the basis of distressed debt investing.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a fulcrum investor?",a:"An investor who buys the fulcrum security (class likely to convert to equity). Goal: take control of the company post-restructuring.",category:"Capital Structure",difficulty:"Advanced"},
{q:"What is a tender offer?",a:"Company offers to buy back its debt, often at a discount. Used to reduce debt and improve capital structure.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a consent fee?",a:"Fee paid to creditors to approve changes to loan terms. Incentivizes participation in restructuring negotiations.",category:"Capital Structure",difficulty:"Intermediate"},
// ═══ WATERFALL ANALYSIS (76-100) ═══
{q:"Walk through a basic waterfall analysis.",a:"Start with EV → subtract admin/priority claims → pay most senior debt first → continue down capital structure sequentially → calculate Recovery = Value received / Claim amount at each level.",category:"Valuation",difficulty:"Intermediate"},
{q:"EV $500, Senior $300, Junior $200. Recoveries?",a:"Senior: $300 → 100%. Remaining $200. Junior: $200 → 100%. Everyone is made whole.",category:"Valuation",difficulty:"Intermediate"},
{q:"Same scenario, EV = $400?",a:"Senior: $300 → 100%. Remaining $100. Junior: $100 on $200 claim → 50%. Junior takes the loss.",category:"Valuation",difficulty:"Intermediate"},
{q:"Same scenario, EV = $250?",a:"Senior: $250 out of $300 → ~83%. Junior: $0 → 0%. Once value runs out, lower classes are wiped out completely.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is the key insight from waterfall analysis?",a:"Small changes in EV can dramatically shift recoveries between classes, especially around the fulcrum point.",category:"Valuation",difficulty:"Advanced"},
{q:"How do you identify the fulcrum security?",a:"The class where EV 'breaks' — above it gets full recovery, below it gets nothing. This class typically receives equity in restructuring.",category:"Valuation",difficulty:"Advanced"},
{q:"If EV is uncertain, how handle in a waterfall?",a:"Run multiple scenarios (downside, base, upside) and analyze how recoveries shift. Reflects the high uncertainty in restructuring valuation.",category:"Valuation",difficulty:"Advanced"},
{q:"What happens if EV is below secured debt?",a:"Secured lenders are impaired, all junior creditors wiped out. Deep distress scenario.",category:"Valuation",difficulty:"Intermediate"},
{q:"What happens if EV is above total debt?",a:"All creditors made whole, equity retains value. No restructuring needed in most cases.",category:"Valuation",difficulty:"Intermediate"},
{q:"How do legal priorities affect waterfalls?",a:"Legal structure determines who gets paid first — secured vs unsecured, senior vs subordinated, structural subordination. Waterfalls are legal AND mathematical.",category:"Valuation",difficulty:"Advanced"},
{q:"How does collateral affect recoveries?",a:"Secured creditors have claims on specific assets and recover more in downside. Unsecured rely on residual value.",category:"Valuation",difficulty:"Intermediate"},
{q:"What happens to equity in most restructurings?",a:"Usually wiped out because debt exceeds EV and equity is last in priority.",category:"Valuation",difficulty:"Intermediate"},
{q:"Can equity ever retain value in restructuring?",a:"Only if EV exceeds total debt, or creditors agree to give equity something (rare, usually to speed up the process).",category:"Valuation",difficulty:"Advanced"},
{q:"Why do valuation fights happen in restructuring?",a:"Recovery depends on valuation. Higher valuation benefits junior creditors, lower benefits senior. Both sides have incentives to argue their case.",category:"Valuation",difficulty:"Advanced"},
{q:"What is a recovery range?",a:"Because valuation is uncertain, recoveries are often expressed as ranges (e.g., 40-60% recovery).",category:"Valuation",difficulty:"Intermediate"},
{q:"What is cramdown?",a:"Legal mechanism forcing a restructuring plan on dissenting creditors. Used in Ch.11. Powerful because it allows restructuring without full agreement.",category:"Bankruptcy",difficulty:"Advanced"},
{q:"What is an impaired vs unimpaired class?",a:"Impaired = rights changed. Unimpaired = paid in full. Only impaired classes vote on the plan.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What are you solving for in a restructuring model?",a:"A capital structure the company can sustain — reasonable leverage, manageable interest, sufficient liquidity.",category:"Modeling",difficulty:"Intermediate"},
// Complex waterfall (126-150)
{q:"Walk through a complex capital structure waterfall.",a:"$200 Revolver + $300 TL (secured) + $250 Sr Notes (unsecured) + $150 Sub Notes. If EV=$600: Revolver $200 (100%), TL $300 (100%), remaining $100 → Sr Notes get 40%, Sub gets 0%. Fulcrum = Sr Notes.",category:"Valuation",difficulty:"Advanced"},
{q:"How quickly identify the fulcrum in an interview?",a:"Stack capital structure top-down and subtract EV step-by-step. Whichever class is not fully covered but still receives some value = fulcrum.",category:"Valuation",difficulty:"Advanced"},
{q:"What if multiple tranches are pari passu?",a:"They share recoveries pro rata (proportionally based on claim size). Example: $200 + $200 pari passu, $200 value → each gets 50%.",category:"Valuation",difficulty:"Intermediate"},
{q:"What happens if a tranche is partially secured?",a:"Secured portion paid first, unsecured portion falls lower in priority. One instrument can have multiple recovery layers.",category:"Valuation",difficulty:"Advanced"},
{q:"What happens if the company has DIP financing?",a:"DIP gets paid first (super senior), then existing secured debt, then others. DIP is given priority because no one would lend during bankruptcy otherwise.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What happens with administrative expenses?",a:"Legal fees, advisory fees paid before creditors — they reduce the recovery pool.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What is an 'out-of-the-money' creditor?",a:"No value left for them in the waterfall — recovery = 0%. But they may still negotiate aggressively because they can delay or block restructuring.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is a 'gifting' scenario?",a:"Senior creditors voluntarily give value to junior creditors to speed up negotiations and avoid costly litigation.",category:"Valuation",difficulty:"Advanced"},
{q:"What is the absolute priority rule?",a:"Senior creditors must be paid in full before juniors receive anything. Governs in-court restructurings. Can be violated through negotiated outcomes.",category:"Bankruptcy",difficulty:"Advanced"},
{q:"Why do small EV changes matter so much?",a:"The 'cliff effect' in waterfalls — once value crosses a threshold, entire classes gain or lose recovery. This is why valuation is so contested.",category:"Valuation",difficulty:"Advanced"},
{q:"What is the biggest mistake in waterfall questions?",a:"Not following strict priority, missing pro rata sharing, or rushing calculations. Key: be structured and methodical, walk through step-by-step.",category:"Valuation",difficulty:"Intermediate"},
{q:"What is 'pro forma' in restructuring?",a:"What the company looks like after restructuring adjustments — pro forma cap table, pro forma leverage, pro forma liquidity.",category:"Modeling",difficulty:"Intermediate"},
{q:"What is a pro forma cap table?",a:"Capital structure after restructuring showing new debt, equity ownership, and converted securities. Essential for waterfalls, recoveries, and negotiations.",category:"Modeling",difficulty:"Intermediate"},
// ═══ SCENARIO ANALYSIS & DECISION-MAKING (151-175) ═══
{q:"Company has liquidity issue but is solvent — what do you recommend?",a:"Extend maturities, raise short-term financing (revolver, bridge loan), negotiate covenant relief. Goal: buy time without full restructuring since the business is fundamentally healthy.",category:"Scenario",difficulty:"Advanced"},
{q:"Company is insolvent but has good operations — what would you do?",a:"Capital structure needs fixing. Debt-for-equity swap, reduce total debt, possibly Ch.11 if agreement isn't feasible. Align debt with sustainable cash flow — structural fix, not just buying time.",category:"Scenario",difficulty:"Advanced"},
{q:"How decide between out-of-court and in-court?",a:"Three factors: creditor alignment (cooperative → out-of-court, fragmented → in-court), complexity of capital structure, urgency of liquidity needs.",category:"Scenario",difficulty:"Advanced"},
{q:"What are advantages of out-of-court restructuring?",a:"Faster execution, lower cost, less reputational damage, less operational disruption. But requires creditor cooperation.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What are advantages of in-court restructuring?",a:"Ability to cram down creditors, structured legal process, access to DIP financing, ability to reject contracts. More control but higher cost.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Company has many bondholders — what challenge?",a:"Coordination problems. Bondholders are fragmented, hard to get unanimous consent. Makes out-of-court restructuring more difficult.",category:"Scenario",difficulty:"Intermediate"},
{q:"What if creditors refuse to cooperate?",a:"Move toward in-court restructuring. Ch.11 allows enforcement and cramdown. The threat of filing itself can bring creditors to the table.",category:"Scenario",difficulty:"Advanced"},
{q:"Large maturity wall in 6 months — options?",a:"Short-term: extend maturities, raise new financing, amend covenants. If not viable: begin restructuring process early. Timing is critical — don't run out of cash.",category:"Scenario",difficulty:"Advanced"},
{q:"Why is timing so important in restructuring?",a:"Liquidity determines survival. Even a good business can fail if it runs out of cash. Acting early gives more options and more negotiating power.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the biggest mistake management teams make?",a:"Waiting too long. They hope things improve and delay restructuring, which reduces options and worsens outcomes.",category:"Scenario",difficulty:"Intermediate"},
{q:"When is Chapter 11 actually a good option?",a:"When capital structure is too complex, creditors are misaligned, or a clean reset is needed. Ch.11 can create a fresh start.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What makes a strong restructuring pitch?",a:"Clear understanding of the problem, thoughtful solutions, realistic assumptions, awareness of stakeholder incentives. Solution-driven, not just diagnostic.",category:"Fundamentals",difficulty:"Advanced"},
{q:"How do creditors evaluate restructuring proposals?",a:"They ask: 'Is this better than my alternatives?' — which includes liquidation, bankruptcy, or other proposals.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the role of negotiation in restructuring?",a:"Critical. Even financially optimal solutions must be acceptable to stakeholders. Restructuring = finance + law + negotiation.",category:"Fundamentals",difficulty:"Advanced"},
{q:"What would you do if senior and junior creditors disagree?",a:"Analyze recovery scenarios, show outcomes under different options, try to align incentives. If no agreement → move toward court.",category:"Scenario",difficulty:"Advanced"},
{q:"What does 'right-sizing the balance sheet' mean?",a:"Adjusting debt to match the company's true earning capacity so it can sustainably service obligations.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the biggest driver of restructuring outcomes?",a:"Enterprise value — it determines total value available. Everything else (recoveries, negotiations, plan structure) flows from that.",category:"Valuation",difficulty:"Advanced"},
{q:"Why is restructuring considered more interesting than M&A by some?",a:"More creative, less formulaic, higher stakes. Solving a crisis, not just executing a transaction. Multiple valid solutions exist.",category:"Behavioral",difficulty:"Intermediate"},
{q:"If you had to answer 'Why restructuring?' in an interview?",a:"'I'm drawn to RX because it sits at the intersection of finance, law, and strategy. Unlike formulaic areas, RX requires creative problem-solving where multiple solutions exist and small changes materially impact outcomes.'",category:"Behavioral",difficulty:"Intermediate"},
// ═══ ADVANCED CONCEPTS & CASH FLOW (176-200) ═══
{q:"If a company is cash flow positive, can it still need restructuring?",a:"Yes. Even if it generates cash, it may have too much debt, face near-term maturities, or be unable to refinance. Cash flow alone doesn't guarantee sustainability.",category:"Scenario",difficulty:"Advanced"},
{q:"Company is EBITDA positive but still distressed — why?",a:"EBITDA ≠ cash. Issues could include high interest expense, large capex needs, working capital drains. Always focus on actual cash flow, not just EBITDA.",category:"Scenario",difficulty:"Advanced"},
{q:"What's more important in distress: EBITDA or liquidity?",a:"Liquidity. Companies fail when they run out of cash, not when EBITDA is low.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Strong assets but weak cash flow — what does that imply?",a:"May be solvent (asset value high) but illiquid (cash flow weak). Could still need restructuring despite strong asset base.",category:"Scenario",difficulty:"Advanced"},
{q:"Strong cash flow but too much debt — solution?",a:"Reduce debt burden through debt-for-equity swap, buybacks, or restructuring. Cash flow may not be enough to support current leverage.",category:"Scenario",difficulty:"Intermediate"},
{q:"Why might creditors prefer equity over debt in restructuring?",a:"Debt may not be recoverable. Equity gives upside potential and participation in recovery.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"Tradeoff between debt reduction and maturity extension?",a:"Debt reduction improves solvency. Extension improves liquidity. Best solution depends on whether problem is short-term or structural.",category:"Scenario",difficulty:"Advanced"},
{q:"Sign that a company needs full restructuring vs quick fix?",a:"If debt >> EV and cash flow can't support interest → requires structural change. If it's just a timing issue → quick fix may work.",category:"Scenario",difficulty:"Advanced"},
{q:"Why might management resist restructuring?",a:"Equity gets diluted or wiped out, loss of control, reputational concerns. Management incentives may not align with optimal restructuring.",category:"Scenario",difficulty:"Intermediate"},
{q:"What is the biggest misconception about restructuring?",a:"That it's just about bankruptcy. In reality, most restructuring work is about avoiding bankruptcy through negotiated solutions.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is RX harder than M&A technically?",a:"More moving parts, legal + financial complexity, no standard framework. Every situation is unique with multiple valid approaches.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"If advising creditors, what matters most?",a:"Recovery value, timing of recovery, and certainty of outcome. 'What do I get, when, and how certain is it?'",category:"Scenario",difficulty:"Advanced"},
{q:"If advising the company, what matters most?",a:"Survival, liquidity, maintaining operations. Focus on preserving the business as a going concern.",category:"Scenario",difficulty:"Advanced"},
{q:"What is a scenario where doing nothing is the best option?",a:"If business is improving, liquidity is sufficient, and debt is manageable. Avoid unnecessary restructuring that could be worse than the status quo.",category:"Scenario",difficulty:"Advanced"},
{q:"What is the role of valuation in negotiations?",a:"Determines who gets value — the most contested input. Higher valuation benefits juniors, lower benefits seniors. Often the core dispute.",category:"Valuation",difficulty:"Advanced"},
{q:"How handle a question where you don't know the exact answer?",a:"Stay structured, walk through logic, make reasonable assumptions. In RX, thought process matters more than exact answers.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is the best way to stand out in RX interviews?",a:"Not memorization. Show contextual understanding of how restructuring works — understand tradeoffs, explain clearly under pressure, think in solutions not just answers.",category:"Behavioral",difficulty:"Advanced"},
{q:"What does 'thinking like a restructuring banker' mean?",a:"Asking 'what solution actually works given constraints?' Not just calculating numbers but understanding tradeoffs between stakeholders.",category:"Behavioral",difficulty:"Advanced"},
{q:"If given a completely unfamiliar scenario, what should you do?",a:"Break it down: What is the problem? Is it liquidity or solvency? What are the options? What are the tradeoffs? Structure beats memorization.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What separates a top 1% RX candidate?",a:"Understands capital structures deeply, explains clearly under pressure, thinks in terms of solutions not just answers, and shows they understand what restructuring is in practice.",category:"Behavioral",difficulty:"Advanced"},
// ═══ MISSING QUESTIONS — BATCH 2 ═══
// Credit & Debt Instruments
{q:"What is principal?",a:"The amount of money originally borrowed, to be repaid at maturity.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What does a higher spread indicate?",a:"Higher perceived risk. In distressed situations, spreads widen significantly and prices fall.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is yield to worst (YTW)?",a:"Lowest possible yield assuming worst-case scenario such as early repayment. Especially relevant when bonds trade above par.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a call option on a bond?",a:"Allows the issuer to repay the bond early at a set price. Benefits the issuer if interest rates fall.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a put option on a bond?",a:"Allows investors to sell the bond back at a set price. Protects investors against downside.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What does 'trading rich' or 'trading cheap' mean?",a:"Trading rich = lower yield, higher price. Trading cheap = higher yield, lower price. In distress, bonds usually trade cheap.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is asset protection in credit analysis?",a:"The idea that if the company fails, assets can be sold to repay creditors. Determines downside risk and recovery rates.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is financial liquidity in credit analysis?",a:"Cash on hand and cash generation ability. Answers: can the company survive short-term obligations?",category:"Capital Structure",difficulty:"Intermediate"},
// Waterfall — Advanced
{q:"What happens if EV is exactly equal to a tranche boundary?",a:"That class is fully paid, the next class gets 0%. The fulcrum is technically at the next class down.",category:"Valuation",difficulty:"Advanced"},
{q:"How would you handle a scenario with cash on the balance sheet?",a:"Cash increases available value for creditors. Equity value = EV - Net Debt, but in waterfalls cash adds to the recovery pool.",category:"Valuation",difficulty:"Advanced"},
{q:"What happens if enterprise value increases during negotiations?",a:"Value may 'move down' the capital structure — previously wiped-out creditors may now recover something.",category:"Valuation",difficulty:"Advanced"},
{q:"What happens if EV decreases?",a:"Losses move upward. Even senior creditors may become impaired.",category:"Valuation",difficulty:"Intermediate"},
{q:"How would you explain recoveries to a non-finance person?",a:"'Imagine a company is worth $500 but owes $700. We pay the most senior lenders first, and by the time we get to the bottom, there may be nothing left.'",category:"Valuation",difficulty:"Intermediate"},
{q:"How should you approach a waterfall under pressure?",a:"'Let me walk through step-by-step from the top of the capital structure.' Move slowly and clearly. Interviewers care more about logic than speed.",category:"Valuation",difficulty:"Intermediate"},
{q:"What tricks do interviewers use in waterfalls?",a:"Add pari passu tranches, include partial recoveries, mix secured/unsecured — to test whether you truly understand structure, not just math.",category:"Valuation",difficulty:"Advanced"},
{q:"What is the deeper purpose of waterfall questions?",a:"They test capital structure understanding, logical thinking, and attention to detail — but more importantly, whether you understand how value is allocated in distress.",category:"Valuation",difficulty:"Intermediate"},
{q:"Summarize waterfall intuition in one line.",a:"'Value flows from the top of the capital structure downward until it runs out.'",category:"Valuation",difficulty:"Intermediate"},
{q:"What is structural subordination in a waterfall?",a:"Even if two debts look equal, one may be effectively junior due to structure. Parent debt vs subsidiary debt — subsidiary creditors get paid first from subsidiary assets.",category:"Valuation",difficulty:"Advanced"},
{q:"Why would senior creditors agree to gifting?",a:"Time and legal costs can be expensive. Giving up small value can accelerate the process and avoid costly litigation.",category:"Valuation",difficulty:"Advanced"},
// Scenario & Strategy
{q:"What is a 'kick the can' strategy?",a:"Delaying restructuring through temporary fixes (extending maturities, adding PIK). Can buy time but may not solve core issues — just pushes the problem forward.",category:"Scenario",difficulty:"Advanced"},
{q:"What is the tradeoff between debt reduction and maturity extension?",a:"Debt reduction improves solvency (long-term fix). Extension improves liquidity (short-term fix). Best solution depends on whether the problem is structural or temporary.",category:"Scenario",difficulty:"Advanced"},
{q:"Why might extending maturities not be enough?",a:"It doesn't reduce total debt. If the business is fundamentally weak, the problem just gets pushed forward without being solved.",category:"Scenario",difficulty:"Advanced"},
{q:"A company wants to avoid bankruptcy at all costs — what would you suggest?",a:"Explore debt exchanges, maturity extensions, new capital injections. But be realistic: if the structure is unsustainable, avoiding bankruptcy may not be optimal.",category:"Scenario",difficulty:"Advanced"},
{q:"How does having a concentrated lender base help?",a:"Fewer parties = faster agreement = more likely out-of-court solution. Concentrated lenders are easier to negotiate with.",category:"Scenario",difficulty:"Intermediate"},
{q:"Why do different restructuring advisors propose different solutions?",a:"Because there is no single correct answer. Restructuring is not formulaic — different approaches can all be valid depending on context and priorities.",category:"Scenario",difficulty:"Intermediate"},
{q:"Why might a company choose a risky out-of-court solution?",a:"To avoid bankruptcy stigma, even if the fix isn't perfect. Reputational damage from Ch.11 can hurt customer relationships and operations.",category:"Scenario",difficulty:"Advanced"},
{q:"Why might creditors push for aggressive restructuring?",a:"They want to maximize recovery, especially if they're senior with control. Aggressive restructuring can accelerate their payouts.",category:"Scenario",difficulty:"Intermediate"},
{q:"Why is 'doing nothing' often not an option in distress?",a:"Problems compound over time — liquidity worsens, options shrink, leverage increases. Delay usually makes outcomes worse.",category:"Scenario",difficulty:"Intermediate"},
{q:"What is the banker's role in negotiations?",a:"Provide analysis, propose solutions, facilitate agreement between parties. Not to decide, but to guide stakeholders toward a workable outcome.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why do companies draw revolvers before bankruptcy?",a:"To build a 'war chest' of cash ensuring operational continuity during restructuring. The revolver provides immediate liquidity.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What is the difference between loans and bonds in distress?",a:"Loans: fewer holders, easier to renegotiate, tighter covenants. Bonds: fragmented holders, harder to coordinate, more complex amendments.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What is a creditor group?",a:"A group of lenders/bondholders who act together in negotiations. Increases bargaining power and coordination.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"What drives negotiation dynamics in restructuring?",a:"Three things: position in capital structure, recovery expectations, and legal leverage. Each creditor class has different incentives.",category:"Fundamentals",difficulty:"Advanced"},
{q:"Why do different creditors disagree?",a:"Their incentives are different. Senior lenders want preservation and certainty. Junior creditors may want riskier paths with more upside potential.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is the key question in any restructuring?",a:"How much is the company worth, and how is that value distributed? Everything flows from enterprise value and priority of claims.",category:"Fundamentals",difficulty:"Advanced"},
{q:"Summarize restructuring in one sentence.",a:"Restructuring is about reallocating value across a company's capital structure to keep it alive when it can no longer meet its obligations.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why might creditors NOT want equity?",a:"Higher risk, illiquid, no guaranteed return. Some creditors prefer fixed recovery (cash or new debt) over uncertain equity upside.",category:"Capital Structure",difficulty:"Intermediate"},
{q:"Why do interviewers push back on correct answers?",a:"To test depth of understanding. Common in RX — they want to see if you can defend your logic and think deeper, not just recite answers.",category:"Behavioral",difficulty:"Intermediate"},
// Behavioral — Missing
{q:"Tell me about yourself (RX version).",a:"Analytical rigor → complex problems → why finance/RX → relevant experience. Show a logical path that leads to restructuring specifically.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Debtor-side vs creditor-side advisory?",a:"Debtor: help company reorganize, preserve value, negotiate with creditors. Creditor: protect recovery, maximize distributions. Both need deep analytical work.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What RX deal have you followed?",a:"Know the company, capital structure, what went wrong, negotiation dynamics, and outcome. Show you follow distressed situations with genuine interest.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What makes someone good at RX?",a:"Comfort with ambiguity, attention to detail in complex cap structures, negotiation awareness, pressure tolerance, and creative problem-solving.",category:"Behavioral",difficulty:"Intermediate"},
{q:"How do you handle pressure in RX?",a:"RX is high-stakes with tight deadlines. Show composure, ability to prioritize, and maintain attention to detail under pressure.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is the most interesting aspect of RX?",a:"Pick something specific: negotiation dynamics between competing creditor classes, capital structure analysis, multi-stakeholder complexity, or the creativity required.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What would you do if a client was being unreasonable?",a:"Understand their perspective, present facts and alternatives clearly, maintain professionalism, escalate if needed. In RX, emotions run high because real money is at stake.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Why this firm for RX?",a:"Reference specific deal experience, team reputation, training program, client base. Be specific about what differentiates them in restructuring.",category:"Behavioral",difficulty:"Intermediate"},
{q:"Tell me about a time you analyzed complex information quickly.",a:"Show a structured approach to breaking down complexity under time pressure. This is the daily reality of RX work.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What current distressed situation interests you?",a:"Know a real situation: industry, what went wrong, capital structure, key creditor dynamics, and likely outcome. Shows genuine interest in the space.",category:"Behavioral",difficulty:"Intermediate"},
{q:"What is a distressed exchange vs bankruptcy?",a:"Distressed exchange: voluntary agreement, faster, less costly, but requires creditor cooperation. Bankruptcy: legal process, can force outcomes but expensive and disruptive.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is a maturity extension vs a debt reduction?",a:"Extension delays payment (helps liquidity). Reduction lowers total obligation (fixes solvency). Extension buys time; reduction fixes the root problem.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"Why is PIK debt risky?",a:"Debt keeps growing with no cash being paid down. Can delay distress temporarily but worsen the eventual outcome by increasing total obligations.",category:"Capital Structure",difficulty:"Advanced"},
{q:"What does 'impaired' mean in restructuring?",a:"A class of creditors is impaired if their rights are changed or they receive less than originally promised. Only impaired classes vote on the plan.",category:"Bankruptcy",difficulty:"Intermediate"},
{q:"What is a roll-up DIP?",a:"Pre-petition debt 'rolled up' into DIP financing, gaining super-priority status. Controversial because it elevates existing claims above other creditors.",category:"Bankruptcy",difficulty:"Advanced"},
{q:"What is a liquidity runway?",a:"The amount of time before the company runs out of cash. Critical for timing restructuring decisions and negotiations.",category:"Fundamentals",difficulty:"Intermediate"},
{q:"What is 'pro forma' in restructuring?",a:"What the company looks like after restructuring adjustments — pro forma cap table, pro forma leverage, pro forma liquidity position.",category:"Modeling",difficulty:"Intermediate"},
];
