import { Flashcard } from './ib-flashcard-data';
export const PE_FLASHCARDS: Flashcard[] = [
  // LBO Mechanics
  { q: "What is a leveraged buyout (LBO)?", a: "An acquisition where a PE sponsor uses significant debt financing to buy a company, contributes equity, uses the target's cash flows to repay debt, and exits at a higher equity value.", category: "LBO Mechanics" },
  { q: "What are the main drivers of LBO returns?", a: "Entry multiple, leverage amount, EBITDA growth, free cash flow for debt paydown, exit multiple, and holding period length.", category: "LBO Mechanics" },
  { q: "What is a sources and uses table?", a: "Shows where money comes from (sponsor equity, debt tranches, rollover) and where it goes (equity purchase, refinancing, fees). Sources must equal uses.", category: "LBO Mechanics" },
  { q: "What makes a good LBO candidate?", a: "Stable/predictable cash flows, defensible market position, low CapEx needs, manageable working capital, operational improvement potential, and assets to support debt.", category: "LBO Mechanics" },
  { q: "What makes a bad LBO candidate?", a: "Volatile earnings, heavy cyclicality, massive CapEx, negative cash flow, customer concentration, or severe regulatory risk.", category: "LBO Mechanics" },
  { q: "What is IRR?", a: "Internal Rate of Return — the annualized return that equates initial equity invested with future equity proceeds. The key return metric for PE sponsors.", category: "LBO Mechanics" },
  { q: "What is MOIC?", a: "Multiple of Invested Capital = Exit Equity / Initial Equity. A 3.0x MOIC means $3 back for every $1 invested.", category: "LBO Mechanics" },
  { q: "How does a shorter holding period affect IRR?", a: "Same MOIC over shorter time = higher IRR. But you may sacrifice total value creation if you exit too early.", category: "LBO Mechanics" },
  { q: "What are the three sources of value creation in an LBO?", a: "1) EBITDA/revenue growth, 2) Debt paydown (deleveraging), 3) Multiple expansion. Elite candidates decompose returns into all three.", category: "LBO Mechanics" },
  { q: "Walk through a simplified LBO.", a: "Entry: 8x EBITDA ($100) = $800 EV. Debt $500, equity $300. EBITDA grows to $130, debt paid to $250. Exit at 8x = $1,040. Exit equity = $790 on $300 invested.", category: "LBO Mechanics" },
  { q: "Why do PE firms use leverage?", a: "Debt is cheaper than equity and reduces the equity check. If the company services debt, equity returns are magnified. But leverage also increases risk.", category: "LBO Mechanics" },
  { q: "What is a dividend recapitalization?", a: "A PE-owned company issues new debt to pay a special dividend to the sponsor, returning capital before exit.", category: "LBO Mechanics" },
  { q: "What is a management rollover?", a: "Existing management reinvests some equity into the new deal structure, aligning their incentives with the sponsor.", category: "LBO Mechanics" },
  { q: "What is an add-on acquisition?", a: "When a PE portfolio company acquires a smaller company to consolidate the industry, gain scale, or enter adjacent markets.", category: "LBO Mechanics" },
  { q: "What typical leverage ratio do LBOs use?", a: "Usually 4-6x Debt/EBITDA depending on market conditions. Higher for stable businesses, lower for cyclical ones.", category: "LBO Mechanics" },
  { q: "What is a debt covenant?", a: "A contractual restriction in a loan agreement. Maintenance covenants require ongoing compliance; incurrence covenants restrict certain actions.", category: "LBO Mechanics" },
  { q: "What are common LBO debt instruments?", a: "Revolver, term loans (senior secured), senior notes, subordinated debt, mezzanine. Each has different priority, cost, and covenant structures.", category: "LBO Mechanics" },
  { q: "Why might a strategic buyer outbid a PE sponsor?", a: "Strategics can generate synergies that increase the target's value. Sponsors are constrained by required return thresholds and debt capacity.", category: "LBO Mechanics" },
  { q: "What happens to LBO returns if the exit multiple drops 1x?", a: "IRR and MOIC decrease materially. This is why entry discipline and EBITDA growth matter — they buffer against multiple compression.", category: "LBO Mechanics" },
  { q: "What is a paper LBO?", a: "A simplified LBO analysis done by hand (no Excel) during interviews to test your understanding of mechanics, sources/uses, and returns.", category: "LBO Mechanics" },
  // Fund Economics
  { q: "What is a typical PE fund structure?", a: "Limited partners (LPs) provide ~99% of capital; general partner (GP) provides ~1% and manages the fund. Usually a 10-year fund life.", category: "Fund Economics" },
  { q: "What is 2 and 20?", a: "2% management fee on committed/invested capital plus 20% carried interest (carry) on profits above a hurdle rate.", category: "Fund Economics" },
  { q: "What is carried interest?", a: "The GP's share of fund profits (typically 20%) above the preferred return/hurdle rate. It's the primary incentive for fund performance.", category: "Fund Economics" },
  { q: "What is a preferred return / hurdle rate?", a: "The minimum return (often 8%) LPs must receive before the GP earns carry. Ensures GP is rewarded only for meaningful outperformance.", category: "Fund Economics" },
  { q: "What is a GP commit?", a: "The general partner's own capital invested alongside LPs, typically 1-5% of fund size. Aligns GP interests with LPs.", category: "Fund Economics" },
  { q: "What is DPI vs TVPI?", a: "DPI = Distributions to Paid-In (realized returns). TVPI = Total Value to Paid-In (realized + unrealized). DPI is 'cash on cash'; TVPI includes paper gains.", category: "Fund Economics" },
  { q: "What is a J-curve?", a: "Early in a fund's life, returns appear negative because fees and investments create cash outflows before value is realized. Returns typically improve as exits occur.", category: "Fund Economics" },
  { q: "What is a clawback provision?", a: "Allows LPs to reclaim excess carry paid to the GP if later fund performance deteriorates. Protects LPs from overpayment on early exits.", category: "Fund Economics" },
  { q: "What is dry powder?", a: "Uncommitted capital that PE firms have available to invest. High dry powder can mean competition for deals and higher prices.", category: "Fund Economics" },
  { q: "What is a capital call?", a: "When the GP requests LPs to fund a portion of their committed capital, typically when making an investment.", category: "Fund Economics" },
  // Deal Process & Operations
  { q: "What is the typical PE deal process?", a: "Sourcing → screening → preliminary diligence → LOI/IOI → confirmatory diligence → definitive agreement → closing → value creation → exit.", category: "Deal Process" },
  { q: "What are common PE exit strategies?", a: "Strategic sale (to corporate buyer), secondary sale (to another PE firm), IPO, dividend recap, or management buyout.", category: "Deal Process" },
  { q: "What is a platform vs bolt-on acquisition?", a: "Platform = initial large acquisition in a sector. Bolt-on/add-on = smaller acquisitions that are integrated into the platform to build scale.", category: "Deal Process" },
  { q: "What is operational value creation?", a: "Improving the portfolio company through margin expansion, revenue growth initiatives, management upgrades, procurement optimization, or technology investment.", category: "Deal Process" },
  { q: "What is a 100-day plan?", a: "The GP's roadmap for the first 100 days post-acquisition, covering quick wins, management changes, operational initiatives, and strategic priorities.", category: "Deal Process" },
  { q: "What is a quality of earnings (QoE) report?", a: "Third-party analysis of the target's earnings to identify non-recurring items, accounting adjustments, and sustainable run-rate EBITDA.", category: "Deal Process" },
  { q: "What is an IOI vs LOI?", a: "IOI (Indication of Interest) = preliminary non-binding offer. LOI (Letter of Intent) = more detailed proposal, often with exclusivity, before final diligence.", category: "Deal Process" },
  { q: "What is a management presentation?", a: "A meeting where the target's management team presents to potential buyers during the sale process. Key for assessing team quality.", category: "Deal Process" },
  { q: "What is vendor due diligence?", a: "Due diligence commissioned by the seller before the sale process to identify and address issues proactively, speeding up buyer diligence.", category: "Deal Process" },
  { q: "What is a stapled financing?", a: "Pre-arranged debt financing offered by the seller's advisor to potential buyers. Demonstrates the deal is financeable and sets a baseline.", category: "Deal Process" },
  // PE Behavioral
  { q: "Why private equity?", a: "Strong answers mention: ownership mindset, operational value creation, long-term horizon, analytical depth of deal evaluation, and accountability for returns.", category: "Behavioral" },
  { q: "Why not stay in banking?", a: "PE offers ownership, operational involvement, longer-term thinking, and seeing how value creation plays out — versus advisory execution in banking.", category: "Behavioral" },
  { q: "What PE deal have you followed recently?", a: "Pick a real deal. Know the sponsor, target, rationale, entry multiple, leverage, value creation thesis, and potential risks.", category: "Behavioral" },
  { q: "Tell me about a time you had to make a decision with incomplete data.", a: "Use STAR. Show how you identified what mattered most, made reasonable assumptions, and delivered a sound recommendation despite uncertainty.", category: "Behavioral" },
  { q: "What makes a great PE investor?", a: "Pattern recognition, operational intuition, discipline on entry price, ability to attract and evaluate management, and comfort with ambiguity.", category: "Behavioral" },
];
