import { Flashcard } from './ib-flashcard-data';
export const PE_FLASHCARDS: Flashcard[] = [
  // LBO MECHANICS (50)
  { q: "What is a leveraged buyout?", a: "An acquisition where a PE sponsor uses significant debt to buy a company, contributes equity, uses the target's cash flows to repay debt, and exits at a higher equity value.", category: "LBO" },
  { q: "What are the main drivers of LBO returns?", a: "Entry multiple, leverage amount, EBITDA growth, free cash flow for debt paydown, exit multiple, and holding period.", category: "LBO" },
  { q: "Walk through a simplified LBO.", a: "Entry: 8x EBITDA ($100) = $800 EV. Debt $500, equity $300. EBITDA grows to $130, debt paid to $250. Exit 8x = $1,040. Exit equity = $790 on $300.", category: "LBO" },
  { q: "What are the three sources of value creation?", a: "1) EBITDA/revenue growth, 2) Debt paydown (deleveraging), 3) Multiple expansion.", category: "LBO" },
  { q: "What is IRR?", a: "Internal Rate of Return — annualized return equating initial equity investment with future equity proceeds.", category: "LBO" },
  { q: "What is MOIC?", a: "Multiple of Invested Capital = Exit Equity / Initial Equity. A 3x MOIC = $3 back per $1 invested.", category: "LBO" },
  { q: "What increases IRR?", a: "Lower entry multiple, higher exit multiple, stronger EBITDA growth, more debt paydown, lower equity check, shorter hold.", category: "LBO" },
  { q: "How does holding period affect IRR vs MOIC?", a: "Shorter hold = higher IRR for same MOIC. But longer hold may generate higher absolute MOIC through more growth and deleveraging.", category: "LBO" },
  { q: "What makes a good LBO candidate?", a: "Stable cash flows, defensible position, low CapEx, manageable working capital, operational improvement potential, assets supporting debt.", category: "LBO" },
  { q: "What makes a bad LBO candidate?", a: "Volatile earnings, heavy cyclicality, massive CapEx, negative FCF, customer concentration, regulatory risk.", category: "LBO" },
  { q: "Why do PE firms use leverage?", a: "Debt is cheaper than equity, reduces equity check, and magnifies returns. But it also increases risk of distress.", category: "LBO" },
  { q: "What is a sources and uses table?", a: "Shows funding sources (equity, debt tranches, rollover) and uses (equity purchase, refinancing, fees). Must balance.", category: "LBO" },
  { q: "What are common LBO debt instruments?", a: "Revolver, term loan A/B, senior secured notes, unsecured notes, subordinated debt, mezzanine.", category: "LBO" },
  { q: "What is the difference between Term Loan A and Term Loan B?", a: "TLA: amortizing, lower spread, held by banks. TLB: minimal amortization (1%/year), higher spread, held by institutional investors.", category: "LBO" },
  { q: "What is a revolver?", a: "A committed credit facility the company can draw on and repay as needed. Like a corporate credit card. Usually undrawn at close.", category: "LBO" },
  { q: "What is mezzanine debt?", a: "Subordinated debt with higher interest (often 12-20%), sometimes with equity warrants. Sits between senior debt and equity in the capital structure.", category: "LBO" },
  { q: "What typical leverage ratio do LBOs use?", a: "4-6x Debt/EBITDA is common. Higher for stable businesses, lower for cyclical. Market conditions affect availability.", category: "LBO" },
  { q: "What is a debt covenant?", a: "Contractual restriction in loan agreements. Maintenance covenants require ongoing compliance; incurrence covenants restrict certain actions.", category: "LBO" },
  { q: "What happens if covenants are breached?", a: "Technical default. Lender can accelerate the loan, demand immediate repayment, or negotiate a waiver/amendment (often with fees).", category: "LBO" },
  { q: "What is a covenant-lite loan?", a: "A loan with incurrence-only covenants (no maintenance tests). Gives borrowers more flexibility but less lender protection.", category: "LBO" },
  { q: "What is interest coverage ratio?", a: "EBITDA / Interest Expense. Measures ability to service debt. Lenders typically want >2.0x.", category: "LBO" },
  { q: "What is a cash sweep?", a: "Mandatory debt repayment from excess cash flow after required payments. Accelerates deleveraging when FCF is strong.", category: "LBO" },
  { q: "What is a dividend recapitalization?", a: "PE-owned company issues new debt to pay a special dividend to the sponsor, returning capital before exit.", category: "LBO" },
  { q: "What is PIK interest?", a: "Payment-in-Kind — interest that accrues and compounds rather than being paid in cash. Preserves cash but increases total debt.", category: "LBO" },
  { q: "What is a management rollover?", a: "Existing management reinvests equity into the new deal, aligning incentives with the sponsor.", category: "LBO" },
  { q: "What is an equity co-invest?", a: "When LPs invest directly alongside the fund in a specific deal, typically with lower/no fees and carry.", category: "LBO" },
  { q: "What happens to returns if exit multiple drops 1x?", a: "IRR and MOIC decrease materially. Entry discipline and EBITDA growth buffer against multiple compression.", category: "LBO" },
  { q: "What is a paper LBO?", a: "Simplified LBO analysis done by hand during interviews. Tests understanding of sources/uses, cash flow, debt paydown, and returns.", category: "LBO" },
  { q: "How do you calculate exit equity value?", a: "Exit Enterprise Value (Exit EBITDA × Exit Multiple) minus net debt at exit.", category: "LBO" },
  { q: "What is the difference between LBO and DCF valuation?", a: "DCF = intrinsic value from discounted cash flows. LBO = what a sponsor can pay given return requirements and debt capacity. Often a valuation floor.", category: "LBO" },
  { q: "Why might a strategic buyer outbid a sponsor?", a: "Strategics generate synergies that increase target value. Sponsors are constrained by return thresholds and debt capacity.", category: "LBO" },
  { q: "What is purchase price as a multiple of EBITDA?", a: "Entry EV / EBITDA. Typically 7-12x depending on quality, growth, industry, and market conditions.", category: "LBO" },
  { q: "How does working capital affect LBO returns?", a: "Favorable WC releases cash for debt paydown. Unfavorable WC consumes cash and slows deleveraging, hurting IRR.", category: "LBO" },
  { q: "What is a credit agreement?", a: "The legal document governing the terms of the loan: interest rate, maturity, covenants, events of default, prepayment terms.", category: "LBO" },
  { q: "What is a first lien vs second lien?", a: "First lien has priority claim on collateral. Second lien is subordinate — higher risk, higher yield, lower recovery in distress.", category: "LBO" },
  // FUND ECONOMICS (30)
  { q: "What is a typical PE fund structure?", a: "LPs provide ~99% of capital; GP provides ~1% and manages the fund. Usually 10-year life with extensions.", category: "Fund Economics" },
  { q: "What is 2 and 20?", a: "2% management fee on committed/invested capital plus 20% carried interest on profits above the hurdle rate.", category: "Fund Economics" },
  { q: "What is carried interest?", a: "GP's share of fund profits (typically 20%) above the preferred return. The primary GP incentive for performance.", category: "Fund Economics" },
  { q: "What is the preferred return / hurdle rate?", a: "Minimum return (often 8%) LPs must receive before GP earns carry. Ensures GP is rewarded only for outperformance.", category: "Fund Economics" },
  { q: "What is a GP commit?", a: "GP's own capital invested alongside LPs (1-5% of fund). Aligns interests and shows skin in the game.", category: "Fund Economics" },
  { q: "What is DPI?", a: "Distributions to Paid-In — realized, cash-on-cash returns. Tells you what LPs actually got back.", category: "Fund Economics" },
  { q: "What is TVPI?", a: "Total Value to Paid-In = (Distributions + Remaining NAV) / Paid-In Capital. Includes unrealized gains (paper returns).", category: "Fund Economics" },
  { q: "What is RVPI?", a: "Residual Value to Paid-In — unrealized portion of TVPI. TVPI = DPI + RVPI.", category: "Fund Economics" },
  { q: "What is the J-curve?", a: "Early fund years show negative returns (fees + investments before exits). Returns improve as portfolio matures and exits occur.", category: "Fund Economics" },
  { q: "What is a clawback provision?", a: "Allows LPs to reclaim excess carry if later performance deteriorates. Protects against overpayment on early exits.", category: "Fund Economics" },
  { q: "What is a capital call?", a: "GP requests LPs to fund a portion of their commitment, typically when making an investment or paying fees.", category: "Fund Economics" },
  { q: "What is dry powder?", a: "Uncommitted capital available to invest. High dry powder can mean competition for deals and higher entry prices.", category: "Fund Economics" },
  { q: "What is a vintage year?", a: "The year a fund makes its first investment. Performance is often compared across vintage years.", category: "Fund Economics" },
  { q: "What is a fund-of-funds?", a: "A vehicle that invests in multiple PE funds rather than directly in companies. Provides diversification but adds a layer of fees.", category: "Fund Economics" },
  { q: "What is a secondary transaction?", a: "Buying/selling existing LP interests in PE funds. Provides liquidity to sellers and potential discounts to buyers.", category: "Fund Economics" },
  { q: "What is a continuation vehicle?", a: "A GP rolls a portfolio company from an existing fund into a new vehicle, giving LPs the option to cash out or re-invest.", category: "Fund Economics" },
  { q: "What is the management fee offset?", a: "Transaction/monitoring fees the GP charges portfolio companies reduce the management fee owed by LPs. Alignment mechanism.", category: "Fund Economics" },
  { q: "How is a PE fund's life structured?", a: "Typically 5-year investment period + 5-year harvesting period, with 1-2 year extensions possible.", category: "Fund Economics" },
  { q: "What is an LP advisory committee (LPAC)?", a: "A committee of major LPs that advises the GP on conflicts of interest, valuations, and certain fund matters.", category: "Fund Economics" },
  { q: "What is a European vs American waterfall?", a: "European: carry calculated on whole-fund returns (LP-friendly). American: carry calculated deal-by-deal (GP-friendly, with clawback).", category: "Fund Economics" },
  // DEAL PROCESS & OPERATIONS (40)
  { q: "What is the typical PE deal process?", a: "Sourcing → screening → preliminary diligence → LOI/IOI → confirmatory diligence → SPA → closing → value creation → exit.", category: "Deal Process" },
  { q: "What are common PE exit strategies?", a: "Strategic sale, secondary sale (to another PE firm), IPO, dividend recap, or management buyout.", category: "Deal Process" },
  { q: "What is a platform vs bolt-on acquisition?", a: "Platform = initial large acquisition in a sector. Bolt-on = smaller acquisitions integrated into the platform for scale.", category: "Deal Process" },
  { q: "What is a buy-and-build strategy?", a: "Acquire a platform company then make multiple bolt-on acquisitions to consolidate the industry, achieve scale, and drive multiple arbitrage.", category: "Deal Process" },
  { q: "What is multiple arbitrage?", a: "Buying at a lower multiple and selling at a higher one. Often achieved through scale (small companies trade lower than large ones).", category: "Deal Process" },
  { q: "What is operational value creation?", a: "Improving the portfolio company through margin expansion, revenue growth, management upgrades, procurement optimization, or technology investment.", category: "Deal Process" },
  { q: "What is a 100-day plan?", a: "GP's roadmap for first 100 days post-acquisition: quick wins, management changes, operational initiatives, strategic priorities.", category: "Deal Process" },
  { q: "What is a quality of earnings (QoE) report?", a: "Third-party analysis identifying non-recurring items, accounting adjustments, and sustainable run-rate EBITDA.", category: "Deal Process" },
  { q: "What is an IOI vs LOI?", a: "IOI = preliminary non-binding offer. LOI = more detailed proposal with exclusivity before final diligence.", category: "Deal Process" },
  { q: "What is a management presentation?", a: "Target management presents to potential buyers. Key for assessing team quality, strategy, and chemistry.", category: "Deal Process" },
  { q: "What is vendor due diligence?", a: "Seller-commissioned diligence to identify issues proactively, speeding up the buyer's process.", category: "Deal Process" },
  { q: "What is stapled financing?", a: "Pre-arranged debt package offered by seller's advisor. Shows deal is financeable and sets a baseline.", category: "Deal Process" },
  { q: "What is a confidential information memorandum (CIM)?", a: "Detailed document prepared by the sell-side advisor describing the target's business, financials, and investment highlights.", category: "Deal Process" },
  { q: "What is a teaser?", a: "One-page anonymous summary of the target sent to potential buyers to gauge interest before signing NDAs.", category: "Deal Process" },
  { q: "What is a data room?", a: "Virtual repository of documents (financials, contracts, legal, HR) shared with buyers during diligence.", category: "Deal Process" },
  { q: "What is a representation & warranty (R&W)?", a: "Seller's assertions about the target's condition (financials, legal, etc.) in the purchase agreement. Breach can trigger indemnification.", category: "Deal Process" },
  { q: "What is R&W insurance?", a: "Insurance policy that covers breaches of reps and warranties, allowing cleaner exits for sellers.", category: "Deal Process" },
  { q: "What is an escrow in M&A?", a: "Portion of purchase price held by a third party to cover potential post-closing adjustments or indemnification claims.", category: "Deal Process" },
  { q: "What is a purchase price adjustment?", a: "Post-closing true-up based on actual working capital, cash, or debt at close vs estimated amounts at signing.", category: "Deal Process" },
  { q: "What is an earnout?", a: "Contingent consideration where part of the price depends on future performance milestones.", category: "Deal Process" },
  { q: "What is a carve-out?", a: "Acquiring a division or subsidiary from a larger company. Requires separating financials, systems, and operations.", category: "Deal Process" },
  { q: "What is a take-private?", a: "A PE firm acquires a public company, delisting it from the stock exchange. Requires board approval and shareholder vote.", category: "Deal Process" },
  { q: "What is a club deal?", a: "Multiple PE firms co-investing in a single deal, sharing risk and capital requirements.", category: "Deal Process" },
  { q: "What are operating partners?", a: "Former executives or operators hired by PE firms to work with portfolio companies on operational improvements.", category: "Deal Process" },
  { q: "What is EBITDA add-backs?", a: "Non-recurring items added back to reported EBITDA to estimate run-rate profitability: one-time costs, litigation, owner compensation, etc.", category: "Deal Process" },
  { q: "Why are EBITDA add-backs controversial?", a: "Aggressive add-backs inflate EBITDA, justifying higher leverage and valuation. Buyers must diligence each add-back carefully.", category: "Deal Process" },
  { q: "What is a management equity plan (MEP)?", a: "Equity incentive program for portfolio company management, typically 10-20% of equity, vesting over time or on exit.", category: "Deal Process" },
  { q: "What KPIs do PE firms track?", a: "Revenue growth, EBITDA margin, FCF conversion, leverage ratio, customer metrics, employee retention, CapEx efficiency, working capital days.", category: "Deal Process" },
  { q: "What is a recapitalization?", a: "Restructuring a company's debt and equity mix without changing ownership. Can involve dividend recaps or refinancing.", category: "Deal Process" },
  { q: "What is proprietary deal flow?", a: "Deals sourced directly by the GP without an intermediary. Reduces competition and can lead to better pricing.", category: "Deal Process" },
  // BEHAVIORAL (30)
  { q: "Why private equity?", a: "Ownership mindset, operational value creation, long-term horizon, analytical depth of deal evaluation, accountability for returns.", category: "Behavioral" },
  { q: "Why not stay in banking?", a: "PE offers ownership, operational involvement, longer-term thinking, seeing value creation through vs advisory execution.", category: "Behavioral" },
  { q: "Why our firm specifically?", a: "Reference sector focus, fund size, investment style, portfolio companies, reputation, people you've spoken with. Be specific.", category: "Behavioral" },
  { q: "What PE deal have you followed recently?", a: "Know the sponsor, target, rationale, entry multiple, leverage, value creation thesis, and risks. Show genuine interest.", category: "Behavioral" },
  { q: "Tell me about a time you made a decision with incomplete data.", a: "Use STAR. Show how you identified key variables, made assumptions, delivered a recommendation, and acknowledged uncertainty.", category: "Behavioral" },
  { q: "What makes a great PE investor?", a: "Pattern recognition, operational intuition, entry price discipline, management evaluation skills, and comfort with ambiguity.", category: "Behavioral" },
  { q: "Walk me through your resume.", a: "Tell a narrative: what each role taught you, how skills built on each other, why your path leads naturally to PE.", category: "Behavioral" },
  { q: "Tell me about a time you worked on a team.", a: "Show collaboration, delegation, handling disagreements, and delivering results. PE is team-intensive.", category: "Behavioral" },
  { q: "What industry would you want to focus on?", a: "Pick one you genuinely find interesting. Know the dynamics, key players, deal activity, and why PE is active in it.", category: "Behavioral" },
  { q: "Tell me about your modeling experience.", a: "Describe the most complex model you built: what it modeled, key assumptions, outputs, and what you learned.", category: "Behavioral" },
  { q: "What is your investment style?", a: "Show thoughtfulness: quality vs value, sector focus, growth vs mature, operational vs financial engineering emphasis.", category: "Behavioral" },
  { q: "Tell me about a time you had to persuade someone.", a: "Show logical argumentation, listening, adapting your approach, and ultimately reaching alignment through evidence.", category: "Behavioral" },
  { q: "How do you prioritize when overwhelmed?", a: "Identify highest-impact items, communicate proactively, delegate where possible, and maintain quality on critical tasks.", category: "Behavioral" },
  { q: "What would you do in your first 30 days?", a: "Learn the portfolio, understand team dynamics, study active deals, build relationships, and identify how to add value quickly.", category: "Behavioral" },
  { q: "Tell me about a mistake and what you learned.", a: "Be honest and specific. Show self-awareness, what you changed, and how the lesson improved your work.", category: "Behavioral" },
];
