import { Flashcard } from './ib-flashcard-data';
export const PE_FLASHCARDS: Flashcard[] = [
// ═══ LBO MECHANICS (100) ═══
{q:"What is a leveraged buyout?",a:"PE sponsor acquires a company using significant debt, contributes equity, uses target's cash flows to repay debt, and exits at higher equity value.",category:"LBO"},
{q:"What are the main drivers of LBO returns?",a:"Entry multiple, leverage amount, EBITDA growth, FCF for debt paydown, exit multiple, holding period.",category:"LBO"},
{q:"Walk through a paper LBO.",a:"Entry: 8x $100M EBITDA = $800M EV. 5x debt ($500M), $300M equity. EBITDA grows to $130M, debt to $250M. Exit 8x = $1,040M. Equity = $790M. ~2.6x MOIC.",category:"LBO"},
{q:"What are the three sources of LBO value creation?",a:"1) EBITDA growth (revenue + margin), 2) Debt paydown (deleveraging), 3) Multiple expansion.",category:"LBO"},
{q:"What is IRR?",a:"Annualized return equating initial equity to future proceeds. The primary PE return metric.",category:"LBO"},
{q:"What is MOIC?",a:"Multiple of Invested Capital = Exit Equity / Entry Equity. 3x = tripled your money.",category:"LBO"},
{q:"How does holding period affect IRR vs MOIC?",a:"Same MOIC over shorter time = higher IRR. Longer hold may achieve higher MOIC but lower IRR.",category:"LBO"},
{q:"What makes a good LBO candidate?",a:"Stable/predictable cash flows, defensible position, low CapEx, manageable WC, operational improvement potential, assets for debt support.",category:"LBO"},
{q:"What makes a bad LBO candidate?",a:"Volatile earnings, heavy cyclicality, massive CapEx, negative FCF, customer concentration, regulatory risk, no improvement levers.",category:"LBO"},
{q:"Why do PE firms use leverage?",a:"Debt is cheaper than equity, reduces equity check, magnifies returns. But increases risk and distress probability.",category:"LBO"},
{q:"What is a sources and uses table?",a:"Sources: equity, debt tranches, rollover. Uses: equity purchase, refinancing, fees. Must balance.",category:"LBO"},
{q:"What are common LBO debt instruments?",a:"Revolver, TLA, TLB, senior secured notes, unsecured notes, subordinated debt, mezzanine.",category:"LBO"},
{q:"Difference between Term Loan A and B?",a:"TLA: amortizing, lower spread, bank-held. TLB: minimal amortization (1%/yr), higher spread, institutional investors.",category:"LBO"},
{q:"What is a revolver?",a:"Committed credit facility drawn/repaid as needed. Like a corporate credit card. Usually undrawn at close.",category:"LBO"},
{q:"What is mezzanine debt?",a:"Subordinated, 12-20% interest, sometimes with equity warrants. Between senior debt and equity in priority.",category:"LBO"},
{q:"What typical leverage do LBOs use?",a:"4-6x Debt/EBITDA. Higher for stable businesses, lower for cyclical. Market-dependent.",category:"LBO"},
{q:"What is a debt covenant?",a:"Contractual restriction. Maintenance: ongoing compliance tests. Incurrence: restrict certain actions.",category:"LBO"},
{q:"What happens if covenants are breached?",a:"Technical default. Lender can accelerate, demand repayment, or negotiate waiver (usually with fees).",category:"LBO"},
{q:"What is covenant-lite?",a:"Incurrence-only covenants. More borrower flexibility, less lender protection. Common in strong credit markets.",category:"LBO"},
{q:"What is interest coverage ratio?",a:"EBITDA / Interest. Measures ability to service debt. Lenders want >2.0x.",category:"LBO"},
{q:"What is a cash sweep?",a:"Mandatory debt repayment from excess FCF. Accelerates deleveraging when cash flow is strong.",category:"LBO"},
{q:"What is a dividend recapitalization?",a:"Portfolio company issues new debt to pay sponsor a special dividend. Returns capital before exit.",category:"LBO"},
{q:"What is PIK interest?",a:"Payment-in-Kind: interest accrues/compounds instead of cash payment. Preserves cash but grows total debt.",category:"LBO"},
{q:"What is a management rollover?",a:"Management reinvests equity in the new deal. Aligns incentives with sponsor.",category:"LBO"},
{q:"What is an equity co-invest?",a:"LPs invest directly alongside the fund in a deal, often with lower fees/carry.",category:"LBO"},
{q:"What happens if exit multiple drops 1x?",a:"IRR/MOIC decrease materially. Entry discipline and EBITDA growth buffer against multiple compression.",category:"LBO"},
{q:"How do you calculate exit equity value?",a:"Exit EV (Exit EBITDA × Exit Multiple) minus net debt at exit.",category:"LBO"},
{q:"LBO vs DCF valuation?",a:"DCF = intrinsic value from cash flows. LBO = what a sponsor can pay given return requirements. Often a valuation floor.",category:"LBO"},
{q:"Why might strategics outbid sponsors?",a:"Synergies increase target value for strategics. Sponsors are constrained by return thresholds and debt capacity.",category:"LBO"},
{q:"What is purchase price as multiple of EBITDA?",a:"Entry EV / EBITDA. Typically 7-12x depending on quality, growth, industry.",category:"LBO"},
{q:"How does working capital affect LBO returns?",a:"Favorable WC releases cash for debt paydown. Unfavorable WC consumes cash, slows deleveraging, hurts IRR.",category:"LBO"},
{q:"What is a credit agreement?",a:"Legal document governing loan terms: rate, maturity, covenants, events of default, prepayment.",category:"LBO"},
{q:"First lien vs second lien?",a:"First lien: priority on collateral, lower yield. Second lien: subordinate, higher risk/yield, lower recovery.",category:"LBO"},
{q:"What is a paper LBO?",a:"Simplified LBO done by hand. Tests understanding of sources/uses, cash flow, debt paydown, returns.",category:"LBO"},
{q:"What is EBITDA in an LBO context?",a:"The key cash flow proxy for debt capacity and valuation. But must be adjusted for non-recurring items.",category:"LBO"},
{q:"What is adjusted EBITDA?",a:"EBITDA plus add-backs for non-recurring items. Must be scrutinized — aggressive add-backs inflate leverage capacity.",category:"LBO"},
{q:"What is minimum cash balance?",a:"Cash the company must maintain for operations. Excess above minimum is available for debt repayment.",category:"LBO"},
{q:"How do you project debt paydown?",a:"Start with mandatory amortization. Add optional paydown from excess FCF (after CapEx, WC, taxes, interest, minimums).",category:"LBO"},
{q:"What is a refinancing in LBO context?",a:"Replacing existing debt with new debt at better terms (lower rate, extended maturity). Can free up cash flow.",category:"LBO"},
{q:"What is a recap and why do sponsors do it?",a:"Recapitalization: issue new debt to return capital to sponsors. Reduces equity at risk, boosts IRR if done wisely.",category:"LBO"},
{q:"What is the equity contribution ratio?",a:"Sponsor equity / total sources. Typically 30-50%. Lower = more leverage = higher returns but more risk.",category:"LBO"},
{q:"How does CapEx intensity affect LBO attractiveness?",a:"High CapEx reduces FCF for debt paydown. Low CapEx businesses convert more EBITDA to cash, improving returns.",category:"LBO"},
{q:"What is a management incentive plan?",a:"Equity pool (10-20%) for management, vesting over time or on exit. Aligns management with sponsor.",category:"LBO"},
{q:"What is a strip in LBO financing?",a:"Each lender takes a proportional piece of multiple debt tranches. Aligns interests across the capital structure.",category:"LBO"},
{q:"What is a flex provision?",a:"Allows arranging banks to adjust pricing/structure of debt if market conditions change before syndication.",category:"LBO"},
{q:"What is original issue discount (OID)?",a:"Debt issued below par (e.g., 98 cents on dollar). Effectively increases yield to the lender.",category:"LBO"},
{q:"What is call protection?",a:"Period during which borrower cannot prepay debt without penalty. Protects lender yield. Common in HY bonds.",category:"LBO"},
{q:"What is a make-whole provision?",a:"Prepayment penalty ensuring lender receives full economic benefit of the loan. Discourages early repayment.",category:"LBO"},
{q:"How do interest rates affect LBO returns?",a:"Higher rates increase interest expense, reduce FCF for paydown, and can compress valuation multiples. Major headwind.",category:"LBO"},
{q:"What is a unitranche loan?",a:"Single facility combining senior and subordinated debt from one lender. Simpler structure, often used in middle market.",category:"LBO"},
{q:"What is a delayed draw term loan?",a:"Committed but unfunded term loan drawn later for acquisitions or CapEx. Borrower pays commitment fee.",category:"LBO"},
{q:"What is a leverage ratio test?",a:"Debt/EBITDA covenant. If exceeded, technical default. Key ongoing compliance metric.",category:"LBO"},
{q:"What is fixed charge coverage ratio?",a:"(EBITDA - CapEx) / (Interest + Mandatory Amortization + Taxes). Measures ability to cover all fixed obligations.",category:"LBO"},
{q:"What is a springing covenant?",a:"Only tested if a condition is met (e.g., revolver drawn above a threshold). More borrower-friendly.",category:"LBO"},
{q:"What is excess cash flow sweep percentage?",a:"Typically 50-75% of excess FCF. Steps down as leverage decreases. Accelerates deleveraging.",category:"LBO"},
{q:"How do you sensitize an LBO?",a:"Vary entry multiple, exit multiple, revenue growth, margins, and leverage. Show IRR/MOIC under each scenario.",category:"LBO"},
{q:"What is a holding company vs operating company structure?",a:"HoldCo owns OpCo. Debt can be at either level. Structural subordination: HoldCo debt is below OpCo debt.",category:"LBO"},
{q:"What is a carve-out LBO?",a:"Acquiring a division from a larger company. Must separate financials, systems, TSAs. Additional complexity.",category:"LBO"},
{q:"What is a take-private LBO?",a:"PE firm acquires a public company, delists it. Requires shareholder vote, premium to market price.",category:"LBO"},
{q:"What is a secondary buyout?",a:"One PE firm sells to another PE firm. Increasingly common. Questions about remaining value creation.",category:"LBO"},
{q:"What is a club deal?",a:"Multiple PE firms co-invest in one deal. Shares capital requirements and risk.",category:"LBO"},
{q:"What is a continuation vehicle?",a:"GP rolls portfolio company from old fund into new vehicle. LPs can cash out or re-invest.",category:"LBO"},
{q:"What is rollover equity from management?",a:"Management keeps equity in the new structure. Demonstrates confidence and aligns interests. Tax-efficient.",category:"LBO"},
{q:"What is a stub period in an LBO?",a:"Partial year between close and first full fiscal year end. Must model separately for accurate cash flows.",category:"LBO"},
{q:"How do you handle transaction fees in an LBO?",a:"Fees are a use of funds in sources/uses. Typically capitalized and may be amortized or expensed.",category:"LBO"},
{q:"What is the difference between gross and net IRR?",a:"Gross: return before management fees/carry. Net: return after fees. LPs care about net IRR.",category:"LBO"},
// ═══ FUND ECONOMICS (60) ═══
{q:"What is a typical PE fund structure?",a:"LPs (~99% capital) + GP (~1%). 10-year life. 5yr investment period + 5yr harvesting. Extensions possible.",category:"Fund Economics"},
{q:"What is 2 and 20?",a:"2% management fee on committed/invested capital + 20% carried interest on profits above hurdle.",category:"Fund Economics"},
{q:"What is carried interest?",a:"GP's share of profits (typically 20%) above preferred return. Primary GP incentive.",category:"Fund Economics"},
{q:"What is preferred return / hurdle rate?",a:"Minimum return (often 8%) LPs receive before GP earns carry. Protects LP returns.",category:"Fund Economics"},
{q:"What is GP commit?",a:"GP's own capital (1-5% of fund). Skin in the game. Aligns interests with LPs.",category:"Fund Economics"},
{q:"What is DPI?",a:"Distributions to Paid-In. Realized cash returns. What LPs actually got back.",category:"Fund Economics"},
{q:"What is TVPI?",a:"Total Value to Paid-In = (Distributions + NAV) / Paid-In. Includes unrealized paper gains.",category:"Fund Economics"},
{q:"What is RVPI?",a:"Residual Value to Paid-In. Unrealized portion. TVPI = DPI + RVPI.",category:"Fund Economics"},
{q:"What is the J-curve?",a:"Early years show negative returns (fees + investments before exits). Improves as exits occur.",category:"Fund Economics"},
{q:"What is a clawback?",a:"LPs can reclaim excess carry if later performance drops. Protects against overpayment on early exits.",category:"Fund Economics"},
{q:"What is a capital call?",a:"GP requests LPs fund their commitment. Typically when making an investment.",category:"Fund Economics"},
{q:"What is dry powder?",a:"Uncommitted capital available to invest. High dry powder = competition for deals.",category:"Fund Economics"},
{q:"What is a vintage year?",a:"Year fund makes first investment. Performance compared across vintages.",category:"Fund Economics"},
{q:"What is a fund-of-funds?",a:"Invests in multiple PE funds. Diversification but adds fee layer.",category:"Fund Economics"},
{q:"What is a secondary transaction?",a:"Buying/selling existing LP interests. Provides liquidity and potential discounts.",category:"Fund Economics"},
{q:"What is a continuation vehicle?",a:"GP rolls asset from old fund to new vehicle. LPs choose cash out or re-invest.",category:"Fund Economics"},
{q:"What is management fee offset?",a:"Transaction/monitoring fees reduce management fee. Alignment mechanism.",category:"Fund Economics"},
{q:"How is fund life structured?",a:"5yr investment + 5yr harvest + 1-2yr extensions. ~10-12 years total.",category:"Fund Economics"},
{q:"What is an LPAC?",a:"LP Advisory Committee. Advises GP on conflicts, valuations, fund matters.",category:"Fund Economics"},
{q:"European vs American waterfall?",a:"European: whole-fund basis (LP-friendly). American: deal-by-deal (GP-friendly, with clawback).",category:"Fund Economics"},
{q:"What is a catch-up?",a:"After LPs receive preferred return, GP gets 100% of next profits until they 'catch up' to their carry percentage.",category:"Fund Economics"},
{q:"What is a distribution waterfall?",a:"Order of cash distribution: return of capital → preferred return → GP catch-up → carried interest split.",category:"Fund Economics"},
{q:"What is committed vs invested capital?",a:"Committed: total pledged. Invested: actually deployed. Fee basis may shift from committed to invested over time.",category:"Fund Economics"},
{q:"What is a subscription line?",a:"Short-term borrowing against LP commitments. Bridges capital calls. Can inflate IRR by delaying equity deployment.",category:"Fund Economics"},
{q:"How do subscription lines affect IRR?",a:"Delay equity deployment → shorter measured hold → higher IRR. Criticized for artificial IRR inflation.",category:"Fund Economics"},
{q:"What is NAV?",a:"Net Asset Value = fair value of portfolio investments minus liabilities. Updated quarterly.",category:"Fund Economics"},
{q:"How are PE portfolio companies valued?",a:"Fair value using comps, DCF, or recent transactions. Governed by ASC 820. Involves significant judgment.",category:"Fund Economics"},
{q:"What is a GP-led secondary?",a:"GP initiates sale of portfolio assets to a new vehicle. Provides LP liquidity and GP continuation.",category:"Fund Economics"},
{q:"What is co-investment?",a:"LP invests directly alongside fund in specific deal. Lower/no fees. Larger check for LP.",category:"Fund Economics"},
{q:"What is a side car?",a:"Separate vehicle for a specific co-investment opportunity outside the main fund.",category:"Fund Economics"},
{q:"What is recycling?",a:"Reinvesting capital from early exits back into new deals within the investment period.",category:"Fund Economics"},
{q:"What is the investment period?",a:"First 3-5 years when GP actively deploys capital. After this, only follow-ons allowed.",category:"Fund Economics"},
{q:"What is a key person clause?",a:"If named key people leave, fund may suspend investing until resolved. Protects LPs.",category:"Fund Economics"},
{q:"What is a no-fault divorce?",a:"Supermajority of LPs can remove GP without cause. Extreme LP protection mechanism.",category:"Fund Economics"},
{q:"What is a GP removal provision?",a:"Allows LP supermajority (typically 75-80%) to remove GP for cause (fraud, felony).",category:"Fund Economics"},
{q:"What is an investment committee?",a:"GP committee that approves investments. Typically includes founding partners and sector heads.",category:"Fund Economics"},
{q:"How do PE firms fundraise?",a:"Roadshows to LPs (pensions, endowments, SWFs, HNW). Present track record, strategy, team. Can take 12-18 months.",category:"Fund Economics"},
{q:"What types of LPs invest in PE?",a:"Pensions, endowments, foundations, sovereign wealth funds, insurance companies, family offices, fund-of-funds.",category:"Fund Economics"},
{q:"Why do LPs invest in PE?",a:"Higher returns than public markets (illiquidity premium), diversification, access to operational value creation.",category:"Fund Economics"},
{q:"What is the PME (Public Market Equivalent)?",a:"Compares PE returns to what LPs would have earned investing in public markets. Measures true alpha.",category:"Fund Economics"},
// ═══ DEAL PROCESS & OPERATIONS (100) ═══
{q:"What is the PE deal process?",a:"Sourcing → screening → preliminary DD → LOI → confirmatory DD → SPA → closing → value creation → exit.",category:"Deal Process"},
{q:"What are common PE exit strategies?",a:"Strategic sale, secondary sale, IPO, dividend recap, management buyout.",category:"Deal Process"},
{q:"What is a platform vs bolt-on?",a:"Platform: initial large acquisition. Bolt-on: smaller acquisitions integrated into platform for scale.",category:"Deal Process"},
{q:"What is buy-and-build?",a:"Acquire platform then make multiple bolt-ons to consolidate industry. Drives scale and multiple arbitrage.",category:"Deal Process"},
{q:"What is multiple arbitrage?",a:"Buy at lower multiple, sell at higher one. Often from scale (small cos trade lower than large).",category:"Deal Process"},
{q:"What is operational value creation?",a:"Margin expansion, revenue growth, management upgrades, procurement optimization, technology, process improvement.",category:"Deal Process"},
{q:"What is a 100-day plan?",a:"GP roadmap for first 100 days: quick wins, management changes, operational priorities, KPI tracking.",category:"Deal Process"},
{q:"What is a QoE report?",a:"Quality of Earnings: third-party analysis of non-recurring items, adjustments, and sustainable run-rate EBITDA.",category:"Deal Process"},
{q:"IOI vs LOI?",a:"IOI: preliminary non-binding. LOI: more detailed, often with exclusivity.",category:"Deal Process"},
{q:"What is a management presentation?",a:"Target management presents to buyers. Key for team assessment, strategy evaluation, chemistry.",category:"Deal Process"},
{q:"What is vendor due diligence?",a:"Seller-commissioned DD to address issues proactively and speed buyer process.",category:"Deal Process"},
{q:"What is stapled financing?",a:"Pre-arranged debt package from seller's advisor. Shows deal is financeable.",category:"Deal Process"},
{q:"What is a CIM?",a:"Confidential Information Memorandum: detailed document describing target's business, financials, highlights.",category:"Deal Process"},
{q:"What is a teaser?",a:"One-page anonymous summary sent before NDAs to gauge buyer interest.",category:"Deal Process"},
{q:"What is a data room?",a:"Virtual repository of documents (financials, contracts, legal, HR) for buyer diligence.",category:"Deal Process"},
{q:"What are reps and warranties?",a:"Seller's assertions about target condition. Breach can trigger indemnification claims.",category:"Deal Process"},
{q:"What is R&W insurance?",a:"Covers rep breaches. Allows cleaner exits for sellers. Increasingly standard.",category:"Deal Process"},
{q:"What is an escrow?",a:"Portion of purchase price held by third party for post-closing adjustments or claims.",category:"Deal Process"},
{q:"What is purchase price adjustment?",a:"Post-closing true-up based on actual WC, cash, debt vs estimated at signing.",category:"Deal Process"},
{q:"What is an earnout?",a:"Contingent consideration tied to future milestones. Bridges valuation gaps.",category:"Deal Process"},
{q:"What is a carve-out?",a:"Acquiring a division. Must separate financials, systems, personnel. Requires TSAs.",category:"Deal Process"},
{q:"What is a TSA?",a:"Transition Services Agreement: seller provides services (IT, HR, accounting) to carved-out business temporarily.",category:"Deal Process"},
{q:"What is a take-private?",a:"PE acquires public company, delists it. Premium required. Shareholder vote needed.",category:"Deal Process"},
{q:"What is a club deal?",a:"Multiple PE firms co-invest. Shares capital and risk.",category:"Deal Process"},
{q:"What are operating partners?",a:"Former executives hired by PE to work with portfolio companies on operational improvements.",category:"Deal Process"},
{q:"What is EBITDA add-backs?",a:"Non-recurring items added to reported EBITDA: one-time costs, litigation, owner comp, etc.",category:"Deal Process"},
{q:"Why are add-backs controversial?",a:"Aggressive add-backs inflate EBITDA, justify higher leverage/valuation. Must diligence each one.",category:"Deal Process"},
{q:"What KPIs do PE firms track?",a:"Revenue growth, EBITDA margin, FCF conversion, leverage, customer metrics, retention, CapEx efficiency, WC days.",category:"Deal Process"},
{q:"What is proprietary deal flow?",a:"Deals sourced directly without intermediary. Less competition, potentially better pricing.",category:"Deal Process"},
{q:"What is an exclusive negotiation?",a:"Buyer has sole negotiating rights for a period. Typically granted via LOI with exclusivity.",category:"Deal Process"},
{q:"What is a process letter?",a:"Sell-side advisor's letter outlining timeline, bid requirements, and process rules for buyers.",category:"Deal Process"},
{q:"What is a broad vs targeted auction?",a:"Broad: many potential buyers contacted. Targeted: select group of logical buyers. Trade-off: competition vs confidentiality.",category:"Deal Process"},
{q:"What is a go-shop provision?",a:"Post-signing period where seller can solicit competing bids. Protects board from duty of care claims.",category:"Deal Process"},
{q:"What is a breakup fee?",a:"Penalty if deal falls through for certain reasons. Typically 1-3% of deal value.",category:"Deal Process"},
{q:"What is a reverse breakup fee?",a:"Buyer pays if they can't close (e.g., financing failure). Protects seller.",category:"Deal Process"},
{q:"What is material adverse change (MAC)?",a:"Clause allowing buyer to walk away if target's business materially deteriorates between signing and closing.",category:"Deal Process"},
{q:"What is a non-compete?",a:"Seller agrees not to compete with the business for a specified period/geography after sale.",category:"Deal Process"},
{q:"What is a working capital peg?",a:"Agreed-upon normalized WC level. Actual WC at close is compared and purchase price adjusted.",category:"Deal Process"},
{q:"What is net debt at closing?",a:"Total debt minus cash at close. Usually deducted from enterprise value to get equity purchase price.",category:"Deal Process"},
{q:"What is a locked box mechanism?",a:"Purchase price fixed at a historical date. No post-closing adjustment. Seller bears WC risk after lock date.",category:"Deal Process"},
{q:"What is a completion accounts mechanism?",a:"Purchase price adjusted based on actual balance sheet at closing. Standard in US/UK.",category:"Deal Process"},
{q:"What is financial due diligence?",a:"Analysis of historical financials, quality of earnings, WC trends, CapEx needs, tax exposures.",category:"Deal Process"},
{q:"What is commercial due diligence?",a:"Market analysis, competitive positioning, customer validation, growth opportunity assessment.",category:"Deal Process"},
{q:"What is legal due diligence?",a:"Review of contracts, litigation, IP, compliance, regulatory matters, corporate structure.",category:"Deal Process"},
{q:"What is operational due diligence?",a:"Assessment of operations, supply chain, technology, workforce, management capabilities.",category:"Deal Process"},
{q:"What is tax due diligence?",a:"Review of tax compliance, exposures, NOLs, transfer pricing, structuring opportunities.",category:"Deal Process"},
{q:"What is environmental due diligence?",a:"Assessment of environmental liabilities, contamination, regulatory compliance. Critical for industrial assets.",category:"Deal Process"},
{q:"What is IT due diligence?",a:"Systems assessment, cybersecurity, tech debt, integration complexity, scalability.",category:"Deal Process"},
{q:"What is an add-on acquisition strategy?",a:"Systematic bolt-on program to consolidate fragmented markets. Drives scale, capability, geographic expansion.",category:"Deal Process"},
{q:"What is a strategic plan in PE context?",a:"Portfolio company roadmap: revenue initiatives, margin improvement, M&A pipeline, org changes, exit preparation.",category:"Deal Process"},
{q:"What is board governance in PE?",a:"PE firms typically take board seats, influence strategy, approve major decisions, monitor KPIs, hire/fire management.",category:"Deal Process"},
{q:"What is a management assessment?",a:"Evaluating existing leadership during DD. Determine who stays, who goes, what gaps need filling.",category:"Deal Process"},
{q:"How do PE firms create value operationally?",a:"Pricing optimization, procurement savings, org redesign, system upgrades, geographic expansion, product development, talent upgrade.",category:"Deal Process"},
{q:"What is an exit readiness process?",a:"Preparing portfolio company for sale: clean up financials, resolve issues, build equity story, engage advisors.",category:"Deal Process"},
{q:"What is a sell-side QoE?",a:"Vendor-initiated quality of earnings to pre-empt buyer concerns and accelerate diligence.",category:"Deal Process"},
{q:"What is a red flag report?",a:"Preliminary DD identifying major issues before full diligence. Helps decide whether to proceed.",category:"Deal Process"},
// ═══ ACCOUNTING & VALUATION (60) ═══
{q:"How do you value a company for an LBO?",a:"EV/EBITDA primary. Also DCF, comps, precedents. LBO valuation = max price sponsor can pay for target IRR.",category:"Valuation"},
{q:"What is the difference between EV and equity value?",a:"EV = value of operations to all capital providers. Equity = residual to common shareholders after debt.",category:"Valuation"},
{q:"Enterprise Value formula?",a:"EV = Equity Value + Debt + Preferred + Minority Interest - Cash.",category:"Valuation"},
{q:"Why subtract cash from EV?",a:"Cash is non-operating. An acquirer gets the cash, reducing the effective purchase price of operations.",category:"Valuation"},
{q:"Walk through a DCF.",a:"Project UFCF 5-10 years → discount at WACC → terminal value → sum PV → EV → bridge to equity value.",category:"Valuation"},
{q:"What is UFCF?",a:"EBIT(1-T) + D&A - CapEx - ΔWC. Cash from operations after tax and reinvestment, before financing.",category:"Valuation"},
{q:"What is WACC?",a:"Weighted cost of equity + after-tax cost of debt, weighted by market cap structure. Discount rate for UFCF.",category:"Valuation"},
{q:"What is terminal value?",a:"Value beyond forecast period. Gordon Growth: FCF(1+g)/(WACC-g). Or Exit Multiple: EBITDA × multiple.",category:"Valuation"},
{q:"Why does terminal value dominate most DCFs?",a:"Explicit forecast is only 5-10 years. Business assumed to operate indefinitely. Terminal captures remaining value.",category:"Valuation"},
{q:"What is EV/EBITDA?",a:"Enterprise Value / EBITDA. Capital-structure neutral multiple. Most common for comparing companies.",category:"Valuation"},
{q:"Why is P/E less useful than EV/EBITDA?",a:"P/E is affected by leverage, taxes, non-operating items. EV/EBITDA is cleaner for comparison.",category:"Valuation"},
{q:"What is a precedent transaction analysis?",a:"Valuation based on multiples paid in past M&A deals for similar companies. Reflects control premium.",category:"Valuation"},
{q:"Walk through the three statements.",a:"IS: revenue → expenses → NI. CFS: NI → adjustments → cash change. BS: A = L + E. NI links to RE and CFO.",category:"Valuation"},
{q:"If depreciation increases by $10 (25% tax), walk through statements.",a:"IS: EBIT -10, tax -2.5, NI -7.5. CFS: NI -7.5, add back 10 D&A, cash +2.5. BS: cash +2.5, PP&E -10, RE -7.5.",category:"Valuation"},
{q:"Why does depreciation increase cash flow?",a:"Non-cash expense creates tax shield. Reduces taxes while being added back on CFS. Net effect = tax savings.",category:"Valuation"},
{q:"What is working capital?",a:"Current operating assets - current operating liabilities. Cash tied up in day-to-day operations.",category:"Valuation"},
{q:"What is goodwill in an acquisition?",a:"Purchase price minus fair value of identifiable net assets. Reflects synergies, brand, premium paid.",category:"Valuation"},
{q:"What is purchase price allocation?",a:"Allocating purchase price to acquired assets/liabilities at fair value, creating intangibles and goodwill.",category:"Valuation"},
{q:"How does PPA affect post-deal earnings?",a:"Asset step-ups create higher D&A and amortization, reducing reported earnings. Can impact accretion/dilution.",category:"Valuation"},
{q:"What is accretion/dilution?",a:"Whether a deal increases (accretive) or decreases (dilutive) acquirer's EPS.",category:"Valuation"},
{q:"What makes a deal accretive?",a:"Target's lower P/E than buyer (stock deal), cheap financing, high synergies, limited purchase accounting charges.",category:"Valuation"},
{q:"What is a sum-of-the-parts valuation?",a:"Value each business segment separately with appropriate multiples, then sum. Useful for diversified companies.",category:"Valuation"},
{q:"What is comparable company analysis?",a:"Value target by comparing to publicly traded peers using EV/EBITDA, P/E, and other multiples.",category:"Valuation"},
{q:"How do you select comparable companies?",a:"Match on business model, end markets, growth, margins, size, capital intensity. No comp set is perfect.",category:"Valuation"},
{q:"Forward vs trailing multiples?",a:"Forward (NTM) more relevant — markets price expectations. Trailing (LTM) shows historical.",category:"Valuation"},
// ═══ BEHAVIORAL (80) ═══
{q:"Why private equity?",a:"Ownership, operational value creation, long-term horizon, analytical depth, accountability for returns.",category:"Behavioral"},
{q:"Why not stay in banking?",a:"PE offers ownership, operational involvement, longer-term thinking, seeing value creation through.",category:"Behavioral"},
{q:"Why our firm specifically?",a:"Reference sector focus, fund size, style, portfolio companies, people you've met. Be specific.",category:"Behavioral"},
{q:"What PE deal have you followed?",a:"Know sponsor, target, rationale, entry multiple, leverage, value creation thesis, risks.",category:"Behavioral"},
{q:"Tell me about yourself.",a:"Narrative: roles → skills built → why PE is natural next step. Not a bullet-point resume recitation.",category:"Behavioral"},
{q:"Walk me through your resume.",a:"Chronological story: what you learned, how experiences connect, why they point to PE.",category:"Behavioral"},
{q:"Tell me about a time with incomplete data.",a:"STAR. Identify key variables, make assumptions, deliver recommendation, acknowledge uncertainty.",category:"Behavioral"},
{q:"What makes a great PE investor?",a:"Pattern recognition, operational intuition, price discipline, management evaluation, comfort with ambiguity.",category:"Behavioral"},
{q:"What industry would you focus on?",a:"Pick one genuinely. Know dynamics, key players, deal activity, why PE is active there.",category:"Behavioral"},
{q:"Tell me about your modeling experience.",a:"Most complex model: what it modeled, key assumptions, outputs, challenges, what you learned.",category:"Behavioral"},
{q:"What is your investment style?",a:"Quality vs value, sector focus, growth vs mature, operational vs financial engineering. Show thoughtfulness.",category:"Behavioral"},
{q:"Tell me about a time you persuaded someone.",a:"Logical argument, listening, adapting approach, reaching alignment through evidence.",category:"Behavioral"},
{q:"How do you prioritize when overwhelmed?",a:"Highest-impact items first, communicate proactively, delegate, maintain quality on critical tasks.",category:"Behavioral"},
{q:"What would you do in first 30 days?",a:"Learn portfolio, understand team, study active deals, build relationships, identify how to add value.",category:"Behavioral"},
{q:"Tell me about a mistake and lesson.",a:"Honest, specific. Show self-awareness, what changed, how lesson improved your work.",category:"Behavioral"},
{q:"How do you evaluate a management team?",a:"Track record, strategic clarity, execution ability, culture, incentive alignment, succession depth.",category:"Behavioral"},
{q:"What makes a good board member?",a:"Strategic guidance, accountability, network, governance, challenging management constructively.",category:"Behavioral"},
{q:"Tell me about a time you showed leadership.",a:"Initiative, ownership, influence without authority, results. Banking to PE leadership is often 'leading up.'",category:"Behavioral"},
{q:"How do you handle disagreement with a senior?",a:"Present reasoning with evidence, listen to their perspective, defer appropriately, but don't be a pushover.",category:"Behavioral"},
{q:"What is your biggest accomplishment?",a:"Real stakes, clear action, measurable impact. Tie to skills relevant for PE.",category:"Behavioral"},
{q:"Why should we hire you over other candidates?",a:"Specific skills, relevant experience, cultural fit, genuine passion. Not generic 'I work hard.'",category:"Behavioral"},
{q:"What do you read to stay informed?",a:"WSJ, Bloomberg, PE Hub, Pitchbook, industry publications, earnings calls. Show genuine daily habit.",category:"Behavioral"},
{q:"Tell me about a time you worked in a team.",a:"Role clarity, collaboration, handling disagreements, delivering results together.",category:"Behavioral"},
{q:"Where do you see yourself in 5-10 years?",a:"Show ambition: principal/partner track, or building on PE skills. Express commitment to learning first.",category:"Behavioral"},
{q:"Tell me about a deal you worked on in banking.",a:"Know it cold: client, situation, your role, analysis, outcome. Show what you contributed specifically.",category:"Behavioral"},
{q:"What is the hardest part of PE?",a:"Honest answers: uncertainty of outcomes, responsibility for capital, managing underperforming companies, time pressure.",category:"Behavioral"},
{q:"How do you handle a portfolio company that's struggling?",a:"Diagnose root cause, assess management, consider operational changes, evaluate strategic alternatives, maintain transparency with LPs.",category:"Behavioral"},
{q:"What questions do you have for us?",a:"Ask about deal flow, team structure, portfolio company involvement, culture, what success looks like. Show curiosity.",category:"Behavioral"},
{q:"Tell me about a time you went above and beyond.",a:"Specific example showing initiative, not just working late. Added value beyond what was asked.",category:"Behavioral"},
{q:"How do you build relationships with management teams?",a:"Trust through competence, transparency, follow-through. Be helpful, not just demanding. Earn respect.",category:"Behavioral"},
];
