import { Flashcard } from './ib-flashcard-data';
export const QUANT_FLASHCARDS: Flashcard[] = [
  // PROBABILITY (40)
  { q: "Expected coin flips to get heads?", a: "E[X] = 1/p = 2 for fair coin. Recursive: E = ½·1 + ½·(1+E) → E = 2.", category: "Probability",firm:"Two Sigma",difficulty:"Easy"},
  { q: "What is Bayes' Rule?", a: "P(A|B) = P(B|A)P(A)/P(B). Updates probability of a hypothesis with new evidence.", category: "Probability",firm:"Jump Trading",difficulty:"Easy"},
  { q: "What is a martingale?", a: "Process whose expected future value, given current info, equals current value. Fair game concept.", category: "Probability",firm:"DE Shaw, Jump Trading",difficulty:"Hard"},
  { q: "E[max] of two U[0,1] draws?", a: "2/3. For n draws: E[max] = n/(n+1).", category: "Probability",firm:"DE Shaw",difficulty:"Easy"},
  { q: "Birthday problem: how many for >50% match?", a: "23 people. With 70 people, >99.9%. Counterintuitive combinatorics.", category: "Probability",firm:"Jane Street",difficulty:"Medium"},
  { q: "What is CLT?", a: "Sums/averages of many independent RVs → normal distribution. Justifies normal approximations.", category: "Probability",firm:"Renaissance Technologies",difficulty:"Easy"},
  { q: "When does CLT fail?", a: "Independence violated, small sample, or infinite variance (heavy tails).", category: "Probability",firm:"Hudson River Trading",difficulty:"Easy"},
  { q: "What is Law of Large Numbers?", a: "Sample averages converge to true expectation as n grows. Foundation for Monte Carlo.", category: "Probability",firm:"Renaissance Technologies",difficulty:"Easy"},
  { q: "PDF vs CDF?", a: "PDF = density at a point. CDF = P(X ≤ x), cumulative probability.", category: "Probability",firm:"Jane Street",difficulty:"Easy"},
  { q: "Variance of Bernoulli(p)?", a: "Var(X) = p(1-p). Maximum at p = 0.5.", category: "Probability",firm:"Renaissance Technologies, Jane Street",difficulty:"Easy"},
  { q: "What is conditional expectation?", a: "E[X|Y] = expected X given Y. Key in pricing, filtering, Bayesian updating.", category: "Probability",firm:"DE Shaw, Renaissance Technologies, Citadel",difficulty:"Easy"},
  { q: "What is the Poisson distribution?", a: "Counts events in a time interval. Parameter λ = mean = variance. Used for trade arrivals, jumps.", category: "Probability",firm:"Jane Street",difficulty:"Easy"},
  { q: "What is independence?", a: "P(A∩B) = P(A)P(B). Strong assumption — often violated in finance during crises.", category: "Probability",firm:"Citadel, DE Shaw, Two Sigma",difficulty:"Easy"},
  { q: "Gambler's ruin probability?", a: "Starting at k, absorbing at 0 and N. Fair coin: P(ruin) = 1 - k/N.", category: "Probability",firm:"Two Sigma, Citadel, Hudson River Trading",difficulty:"Easy"},
  { q: "E[geometric distribution]?", a: "E[X] = 1/p where X = trials until first success.", category: "Probability",firm:"Citadel, Hudson River Trading, Renaissance Technologies",difficulty:"Easy"},
  { q: "What is the memoryless property?", a: "Exponential (continuous) and geometric (discrete) distributions: P(X > s+t | X > s) = P(X > t). Past doesn't inform future.", category: "Probability",firm:"Jump Trading",difficulty:"Easy"},
  { q: "What is Jensen's inequality?", a: "For convex f: E[f(X)] ≥ f(E[X]). For concave f: opposite. Relevant in option pricing (options are convex payoffs).", category: "Probability",firm:"Hudson River Trading",difficulty:"Easy"},
  { q: "Expected value of |X| where X ~ N(0,1)?", a: "E[|X|] = √(2/π) ≈ 0.798.", category: "Probability",firm:"Jane Street, Renaissance Technologies",difficulty:"Easy"},
  { q: "What is covariance?", a: "Cov(X,Y) = E[(X-μx)(Y-μy)]. Measures linear co-movement. Zero covariance ≠ independence.", category: "Probability",firm:"Citadel",difficulty:"Easy"},
  { q: "Coupon collector: expected rolls to see all 6 die faces?", a: "6/6 + 6/5 + 6/4 + 6/3 + 6/2 + 6/1 = 14.7.", category: "Probability",firm:"Jane Street, Hudson River Trading",difficulty:"Medium"},
  { q: "What is a random walk?", a: "Process where each step is independent and identically distributed. Simplest model of price movements.", category: "Probability",firm:"Two Sigma",difficulty:"Easy"},
  { q: "Probability at least one 6 in 4 rolls?", a: "1 - P(no 6 in 4 rolls) = 1 - (5/6)⁴ ≈ 1 - 0.482 = 0.518.", category: "Probability",firm:"DE Shaw",difficulty:"Easy"},
  { q: "What is a moment generating function?", a: "M(t) = E[e^(tX)]. Uniquely determines a distribution and simplifies computing moments.", category: "Probability",firm:"Jane Street, Citadel, Jump Trading",difficulty:"Easy"},
  { q: "Sum of two independent Poisson(λ₁) and Poisson(λ₂)?", a: "Poisson(λ₁ + λ₂). Poisson is closed under addition of independent variables.", category: "Probability",firm:"Jane Street",difficulty:"Medium"},
  { q: "What is the variance of a sum of independent RVs?", a: "Var(X+Y) = Var(X) + Var(Y) if independent. If not: add 2·Cov(X,Y).", category: "Probability",firm:"Citadel, Renaissance Technologies",difficulty:"Easy"},
  // STATISTICS (30)
  { q: "What is overfitting?", a: "Model captures noise in training data, performs well in-sample but poorly out-of-sample. Common in finance due to low SNR.", category: "Statistics",firm:"Renaissance Technologies, Akuna Capital",difficulty:"Easy"},
  { q: "What is bias-variance trade-off?", a: "Bias = systematic error from simplification. Variance = sensitivity to noise. Balance is key.", category: "Statistics",firm:"Millennium",difficulty:"Easy"},
  { q: "What is a p-value?", a: "P(observing data this extreme | null is true). Not P(null is true). Low p-value → reject null.", category: "Statistics",firm:"Citadel, Hudson River Trading",difficulty:"Easy"},
  { q: "What is the Sharpe ratio?", a: "(E[return] - Rf) / σ. Return per unit of volatility. Can be misleading for tail-risk strategies.", category: "Statistics",firm:"Five Rings Capital",difficulty:"Easy"},
  { q: "Common backtest biases?", a: "Look-ahead, survivorship, data snooping, selection bias, ignoring costs, information leakage.", category: "Statistics",firm:"Five Rings Capital, Hudson River Trading",difficulty:"Easy"},
  { q: "What is stationarity?", a: "Statistical properties (mean, variance) constant over time. Many financial series are non-stationary.", category: "Statistics",firm:"Millennium, Five Rings Capital",difficulty:"Easy"},
  { q: "Why can high Sharpe be dangerous?", a: "Sharpe uses vol as risk. Short-vol strategies show high Sharpe until catastrophic tail event.", category: "Statistics",firm:"Virtu Financial",difficulty:"Easy"},
  { q: "What is heteroskedasticity?", a: "Variance of residuals changes across observations. Common in finance — vol clusters.", category: "Statistics",firm:"Akuna Capital, Renaissance Technologies",difficulty:"Easy"},
  { q: "What is R²?", a: "Proportion of variance explained by model. High R² ≠ causation or good prediction.", category: "Statistics",firm:"Akuna Capital, Two Sigma, Citadel",difficulty:"Easy"},
  { q: "What is autocorrelation?", a: "Correlation of series with its lagged values. Present in momentum, mean reversion, vol clustering.", category: "Statistics",firm:"SIG, Hudson River Trading",difficulty:"Easy"},
  { q: "Type I vs Type II error?", a: "Type I: false positive (reject true null). Type II: false negative (fail to reject false null).", category: "Statistics",firm:"Renaissance Technologies, SIG",difficulty:"Easy"},
  { q: "What is maximum likelihood estimation?", a: "Find parameters that maximize the probability of observing the data. Common for fitting distributions.", category: "Statistics",firm:"Five Rings Capital",difficulty:"Easy"},
  { q: "What is regression to the mean?", a: "Extreme observations tend to be followed by less extreme ones. Not causation — statistical phenomenon.", category: "Statistics",firm:"Five Rings Capital, Citadel",difficulty:"Easy"},
  { q: "What is multicollinearity?", a: "High correlation among independent variables in regression. Makes coefficients unstable and hard to interpret.", category: "Statistics",firm:"IMC Trading, DRW",difficulty:"Easy"},
  { q: "What is the information ratio?", a: "Excess return / tracking error. Measures active management efficiency relative to benchmark.", category: "Statistics",firm:"Point72",difficulty:"Easy"},
  { q: "Statistical significance vs economic significance?", a: "A tiny alpha can be statistically significant but untradable after costs. Always check economic relevance.", category: "Statistics",firm:"Jane Street",difficulty:"Medium"},
  { q: "What is cross-validation?", a: "Splitting data into train/test sets to estimate out-of-sample performance. In finance, must respect time order.", category: "Statistics",firm:"Jane Street, Millennium",difficulty:"Easy"},
  { q: "What is Durbin-Watson test?", a: "Tests for autocorrelation in regression residuals. Value near 2 = no autocorrelation.", category: "Statistics",firm:"Point72, Virtu Financial, Two Sigma",difficulty:"Easy"},
  // DERIVATIVES (30)
  { q: "What is Black-Scholes?", a: "Closed-form European option pricing: lognormal prices, constant vol/rates, no arbitrage, continuous hedging.", category: "Derivatives",firm:"Renaissance Technologies",difficulty:"Hard"},
  { q: "What is implied volatility?", a: "Vol input making model price = market price. Market's pricing convention, not realized vol.", category: "Derivatives",firm:"Akuna Capital, Hudson River Trading",difficulty:"Easy"},
  { q: "Why does higher vol increase option value?", a: "Asymmetric payoffs + convexity. More vol = more probability of large favorable moves; downside limited for long options.", category: "Derivatives",firm:"AQR Capital",difficulty:"Medium"},
  { q: "What is delta?", a: "∂Option/∂Underlying. Ranges 0-1 (calls), -1-0 (puts). Approximates ITM probability.", category: "Derivatives",firm:"Millennium, Point72, Hudson River Trading",difficulty:"Easy"},
  { q: "What is gamma?", a: "∂Delta/∂Underlying. Measures convexity. Highest ATM near expiry.", category: "Derivatives",firm:"Akuna Capital, Jump Trading",difficulty:"Easy"},
  { q: "What is theta?", a: "Time decay rate. Long options lose theta; short options earn it. Accelerates near expiry for ATM.", category: "Derivatives",firm:"Jane Street",difficulty:"Easy"},
  { q: "What is vega?", a: "∂Option/∂ImpliedVol. Long options = long vega. Benefits from rising vol.", category: "Derivatives",firm:"SIG, DRW",difficulty:"Easy"},
  { q: "What is rho?", a: "∂Option/∂Rate. Usually small impact. Calls: positive rho. Puts: negative rho.", category: "Derivatives",firm:"Optiver",difficulty:"Easy"},
  { q: "Put-call parity?", a: "C - P = S - Ke^(-rT). Core no-arbitrage identity for European options.", category: "Derivatives",firm:"AQR Capital, Point72",difficulty:"Easy"},
  { q: "Why is delta hedging imperfect?", a: "Discrete rebalancing, transaction costs, jumps, model error, changing vol.", category: "Derivatives",firm:"DE Shaw, Hudson River Trading, Jump Trading",difficulty:"Easy"},
  { q: "What is a volatility smile?", a: "Implied vol varies by strike. Typically higher for OTM puts/calls vs ATM. Shows BS assumptions don't hold.", category: "Derivatives",firm:"DRW",difficulty:"Easy"},
  { q: "What is risk-neutral pricing?", a: "Price derivatives using expected discounted payoffs under risk-neutral measure. Not 'true' probabilities.", category: "Derivatives",firm:"Citadel, DE Shaw, IMC Trading",difficulty:"Easy"},
  { q: "What is Ito's Lemma?", a: "Stochastic chain rule. In stochastic systems, second-order terms matter due to quadratic variation.", category: "Derivatives",firm:"Citadel, Tower Research",difficulty:"Hard"},
  { q: "What is GBM?", a: "dS = μS dt + σS dW. Implies lognormal prices. Foundation of Black-Scholes.", category: "Derivatives",firm:"AQR Capital, Hudson River Trading",difficulty:"Easy"},
  { q: "What is Brownian motion?", a: "Continuous-time process: B(0)=0, independent increments, normally distributed increments, continuous paths.", category: "Derivatives",firm:"Virtu Financial, Five Rings Capital",difficulty:"Easy"},
  { q: "What is a straddle?", a: "Long call + long put, same strike. Profits from large moves either direction. Buying volatility.", category: "Derivatives",firm:"DRW, SIG, DE Shaw",difficulty:"Easy"},
  { q: "What is a strangle?", a: "Long OTM call + long OTM put. Cheaper than straddle but needs larger move to profit.", category: "Derivatives",firm:"Citadel",difficulty:"Easy"},
  { q: "What is a butterfly spread?", a: "Buy 1 low strike call, sell 2 ATM calls, buy 1 high strike call. Profits if underlying stays near ATM.", category: "Derivatives",firm:"SIG, Millennium",difficulty:"Easy"},
  { q: "What is a calendar spread?", a: "Same strike, different expirations. Profits from time decay differential and vol term structure.", category: "Derivatives",firm:"Jump Trading, IMC Trading",difficulty:"Easy"},
  { q: "What is early exercise for American options?", a: "American call on non-dividend stock: never exercise early (preserve time value). Put: may exercise early for interest.", category: "Derivatives",firm:"AQR Capital, IMC Trading",difficulty:"Easy"},
  { q: "What is the risk-neutral drift?", a: "Under Q-measure, assets grow at risk-free rate r, not real-world drift μ. Required for no-arbitrage pricing.", category: "Derivatives",firm:"Renaissance Technologies, DRW",difficulty:"Easy"},
  { q: "What is mean reversion in rates?", a: "Interest rates tend to revert to long-run levels. Modeled by Ornstein-Uhlenbeck / Vasicek processes.", category: "Derivatives",firm:"Tower Research",difficulty:"Easy"},
  // BRAINTEASERS (15)
  { q: "100 coins, 30 heads, blindfolded. Split into equal-heads groups.", a: "Move any 30 to new pile, flip them all. Original: (30-x) heads. New: 30 flipped → x tails become heads = 30-x. Equal!", category: "Brainteasers",firm:"Renaissance Technologies, DE Shaw",difficulty:"Medium"},
  { q: "Clock hands overlap in 12 hours?", a: "11 times. Minute hand laps hour hand every 12/11 hours ≈ 65.45 min.", category: "Brainteasers",firm:"Jane Street",difficulty:"Easy"},
  { q: "Expected rolls to see all 6 die faces?", a: "Coupon collector: 6/6+6/5+6/4+6/3+6/2+6/1 = 14.7.", category: "Brainteasers",firm:"DE Shaw, Jump Trading",difficulty:"Easy"},
  { q: "You have 12 balls, one is heavier. Find it in 3 weighings.", a: "Split into 3 groups of 4. Weigh 4v4. If equal, heavy ball is in remaining 4. Repeat subdivision.", category: "Brainteasers",firm:"Jump Trading",difficulty:"Medium"},
  { q: "Two trains 100 miles apart, each 50 mph. A fly at 75 mph bounces between. How far does fly travel?", a: "Trains meet in 1 hour (100mi / 100mph combined). Fly travels 75 mph × 1 hr = 75 miles.", category: "Brainteasers",firm:"Hudson River Trading, Jump Trading, Citadel",difficulty:"Medium"},
  { q: "Expected value of a fair die roll?", a: "E[X] = (1+2+3+4+5+6)/6 = 3.5.", category: "Brainteasers",firm:"Jump Trading, Citadel",difficulty:"Easy"},
  { q: "You flip a coin until you get HH or HT. Which comes first on average?", a: "HT comes first on average. After first H: HH needs another H (p=½), but HT needs T (p=½) and if H comes, you're still 'in play' for HH but HT restarts.", category: "Brainteasers",firm:"DE Shaw",difficulty:"Medium"},
  { q: "100 lockers problem. Toggle every nth locker for n=1..100. Which stay open?", a: "Perfect squares: 1,4,9,16,25,36,49,64,81,100. They have odd number of factors.", category: "Brainteasers",firm:"Two Sigma",difficulty:"Medium"},
  { q: "Monty Hall problem.", a: "Always switch. Switching wins 2/3 of the time. Staying wins 1/3. The reveal changes conditional probabilities.", category: "Brainteasers",firm:"Jump Trading, Two Sigma",difficulty:"Easy"},
  { q: "Expected tosses to get two consecutive heads?", a: "E = 6. Let E = expected tosses. After T: restart. After H then T: restart. After HH: done. Solve recursive equations.", category: "Brainteasers",firm:"Two Sigma, DE Shaw",difficulty:"Medium"},
  // CODING & SYSTEMS (20)
  { q: "Python vs C++ in quant finance?", a: "Python: fast iteration, data analysis, ML. C++: low latency, memory control, production. Trade-off: dev speed vs runtime.", category: "Coding",firm:"SIG",difficulty:"Easy"},
  { q: "What is time complexity?", a: "How runtime scales with input. O(1) constant, O(n) linear, O(n log n) efficient sort, O(n²) quadratic.", category: "Coding",firm:"Akuna Capital, DE Shaw",difficulty:"Easy"},
  { q: "What is a hash map?", a: "Key→value mapping with O(1) average lookup. Fundamental for fast data retrieval.", category: "Coding",firm:"Point72",difficulty:"Easy"},
  { q: "What is Monte Carlo simulation?", a: "Simulate many random paths to estimate expectations. Flexible but 1/√N convergence is slow.", category: "Coding",firm:"DE Shaw, Hudson River Trading, Tower Research",difficulty:"Easy"},
  { q: "What is numerical stability?", a: "Correct formulas can fail due to floating-point error, cancellation, overflow. Careful with matrix inversions.", category: "Coding",firm:"DE Shaw, IMC Trading, Citadel",difficulty:"Easy"},
  { q: "What is dynamic programming?", a: "Solving problems by breaking into overlapping subproblems, storing results. Fibonacci, knapsack, option pricing trees.", category: "Coding",firm:"Jane Street, Akuna Capital",difficulty:"Easy"},
  { q: "What is vectorization?", a: "Performing operations on entire arrays rather than element-by-element loops. Dramatically faster in NumPy/pandas.", category: "Coding",firm:"IMC Trading, Virtu Financial",difficulty:"Easy"},
  { q: "What is a priority queue / heap?", a: "Data structure providing O(1) access to min/max and O(log n) insertion. Useful for order book simulation.", category: "Coding",firm:"Hudson River Trading, Two Sigma",difficulty:"Easy"},
  { q: "Binary search complexity?", a: "O(log n). Requires sorted data. Halves search space each step.", category: "Coding",firm:"Two Sigma",difficulty:"Easy"},
  { q: "Research code vs production code?", a: "Research: fast iteration, exploratory. Production: reliable, tested, monitored, maintainable. 'Works in notebook' ≠ 'safe with capital'.", category: "Coding",firm:"Jump Trading",difficulty:"Easy"},
  { q: "What is variance reduction in MC?", a: "Antithetic variates, control variates, stratified sampling, importance sampling. Improve simulation efficiency.", category: "Coding",firm:"Jane Street, Hudson River Trading",difficulty:"Easy"},
  { q: "What is a control variate?", a: "Use a correlated variable with known expectation to reduce variance of your MC estimate.", category: "Coding",firm:"Millennium, Hudson River Trading",difficulty:"Easy"},
  { q: "How would you compute rolling volatility efficiently?", a: "Maintain rolling sum and sum-of-squares. Update in O(1) per new observation instead of recomputing full window.", category: "Coding",firm:"IMC Trading, SIG",difficulty:"Hard"},
  // BEHAVIORAL (15)
  { q: "Why quant finance?", a: "Quantitative problem-solving, uncertainty, feedback loops, combining theory with implementation in markets.", category: "Behavioral",firm:"DE Shaw, Hudson River Trading",difficulty:"Easy"},
  { q: "Why trading vs research vs dev?", a: "Trading: fast decisions, market intuition. Research: deep modeling, signal discovery. Dev: systems, performance. Know which you want and why.", category: "Behavioral",firm:"Citadel, Two Sigma",difficulty:"Easy"},
  { q: "Tell me about a project that failed.", a: "Objective, what went wrong, what you learned, what you'd do differently. Show growth mindset.", category: "Behavioral",firm:"Jump Trading",difficulty:"Easy"},
  { q: "How do you handle 'I don't know'?", a: "State what you know, what assumptions you'd make, how you'd approach it. Shows judgment over bluffing.", category: "Behavioral",firm:"Renaissance Technologies",difficulty:"Easy"},
  { q: "Describe a research project.", a: "Objective → data → method → result → limitations → what you learned. Mention robustness, not just accuracy.", category: "Behavioral",firm:"IMC Trading, DE Shaw",difficulty:"Easy"},
  { q: "What makes a good trading signal?", a: "Economic rationale, statistical significance, out-of-sample stability, survives transaction costs, capacity, and regime changes.", category: "Behavioral",firm:"DRW, SIG",difficulty:"Easy"},
  { q: "Why do signals decay?", a: "Competition, crowding, market structure changes, rising costs, or the signal was noise all along.", category: "Behavioral",firm:"Jump Trading, DRW",difficulty:"Easy"},
  // ── ADDITIONAL PROBABILITY (25) ──
  { q: "What is a Markov chain?", a: "Discrete-time process where future state depends only on current state. Transition matrix defines probabilities.", category: "Probability",firm:"Jump Trading",difficulty:"Easy"},
  { q: "What is a stopping time?", a: "Random time to stop a process based on observed info. Key in optimal stopping problems and options.", category: "Probability",firm:"Jane Street, Renaissance Technologies",difficulty:"Easy"},
  { q: "What is the secretary problem?", a: "Optimal stopping: review first ~37% (1/e) of candidates, then pick next one better than all seen. Classic interview puzzle.", category: "Probability",firm:"DE Shaw",difficulty:"Easy"},
  { q: "What is a binomial distribution?", a: "Number of successes in n independent Bernoulli trials. P(X=k) = C(n,k)p^k(1-p)^(n-k).", category: "Probability",firm:"Citadel, Two Sigma, Jump Trading",difficulty:"Easy"},
  { q: "What is the normal distribution characterized by?", a: "Mean μ and variance σ². Bell-shaped, symmetric. 68-95-99.7 rule for 1-2-3 standard deviations.", category: "Probability",firm:"Jump Trading, Two Sigma",difficulty:"Easy"},
  { q: "What is a chi-squared distribution?", a: "Sum of squared standard normals. Used in hypothesis testing, goodness of fit.", category: "Probability",firm:"Two Sigma",difficulty:"Easy"},
  { q: "What is a t-distribution?", a: "Similar to normal but heavier tails. Used when sample size is small and population variance unknown.", category: "Probability",firm:"Jane Street, Hudson River Trading",difficulty:"Easy"},
  { q: "What is the tower property?", a: "E[E[X|Y]] = E[X]. Iterated expectations. Useful for simplifying complex conditional expectations.", category: "Probability",firm:"Jump Trading, DE Shaw",difficulty:"Easy"},
  { q: "What is tail risk?", a: "Risk of extreme outcomes beyond normal expectations. Real distributions often have fatter tails than Gaussian.", category: "Probability",firm:"Jane Street",difficulty:"Easy"},
  { q: "What is kurtosis?", a: "Measures tail heaviness. Excess kurtosis > 0 = fat tails (leptokurtic). Financial returns are typically leptokurtic.", category: "Probability",firm:"Jump Trading",difficulty:"Easy"},
  { q: "What is skewness?", a: "Measures asymmetry. Negative skew = left tail longer (equity returns). Positive skew = right tail longer.", category: "Probability",firm:"Renaissance Technologies, DE Shaw",difficulty:"Easy"},
  { q: "Probability of getting exactly 3 heads in 5 fair coin flips?", a: "C(5,3) × (0.5)³ × (0.5)² = 10 × 0.03125 = 0.3125 = 31.25%.", category: "Probability",firm:"Jane Street",difficulty:"Medium"},
  { q: "What is the exponential distribution?", a: "Time between Poisson events. Memoryless: P(X>s+t|X>s) = P(X>t). Rate λ, mean 1/λ.", category: "Probability",firm:"Two Sigma, DE Shaw",difficulty:"Easy"},
  { q: "What is a random variable transformation?", a: "If Y = g(X), find PDF of Y using change of variables: fY(y) = fX(g⁻¹(y)) × |d/dy g⁻¹(y)|.", category: "Probability",firm:"Renaissance Technologies",difficulty:"Easy"},
  { q: "What is the strong law of large numbers?", a: "Sample average converges almost surely to expected value. Stronger than weak LLN (convergence in probability).", category: "Probability",firm:"Two Sigma, Citadel",difficulty:"Easy"},
  // ── ADDITIONAL STATISTICS (15) ──
  { q: "What is LASSO regression?", a: "L1 regularization: adds |β| penalty. Performs feature selection by shrinking some coefficients to exactly zero.", category: "Statistics",firm:"AQR Capital",difficulty:"Easy"},
  { q: "What is Ridge regression?", a: "L2 regularization: adds β² penalty. Shrinks coefficients but doesn't zero them. Handles multicollinearity.", category: "Statistics",firm:"Millennium",difficulty:"Easy"},
  { q: "What is AIC/BIC?", a: "Information criteria balancing model fit and complexity. Lower = better. BIC penalizes complexity more than AIC.", category: "Statistics",firm:"Two Sigma, Millennium",difficulty:"Easy"},
  { q: "What is bootstrapping?", a: "Resampling with replacement to estimate distribution of a statistic. Non-parametric, flexible.", category: "Statistics",firm:"Hudson River Trading",difficulty:"Easy"},
  { q: "What is a Kalman filter?", a: "Recursive algorithm for estimating hidden states from noisy observations. Used in signal extraction and tracking.", category: "Statistics",firm:"AQR Capital",difficulty:"Easy"},
  { q: "What is cointegration?", a: "Two non-stationary series whose linear combination is stationary. Basis for pairs trading and stat arb.", category: "Statistics",firm:"Akuna Capital, Millennium",difficulty:"Easy"},
  { q: "What is Granger causality?", a: "X Granger-causes Y if past X values improve prediction of Y beyond Y's own past. Not true causality.", category: "Statistics",firm:"SIG",difficulty:"Easy"},
  { q: "What is a Sharpe ratio of 2 considered?", a: "Excellent. Sharpe >1 is good, >2 is exceptional. Most long-term strategies are 0.3-0.8.", category: "Statistics",firm:"Tower Research, Citadel",difficulty:"Easy"},
  { q: "What is maximum drawdown?", a: "Largest peak-to-trough decline. Measures worst-case loss experience. Important for risk-averse investors.", category: "Statistics",firm:"DRW",difficulty:"Easy"},
  { q: "What is the Kelly criterion?", a: "Optimal bet size = edge / odds. Maximizes long-run growth. Full Kelly often too aggressive; fractional Kelly used.", category: "Statistics",firm:"Renaissance Technologies, Optiver",difficulty:"Easy"},
  // ── ADDITIONAL DERIVATIVES (15) ──
  { q: "What is a swaption?", a: "Option to enter into an interest rate swap. Used for hedging future rate exposure and structured products.", category: "Derivatives",firm:"Five Rings Capital, DRW",difficulty:"Easy"},
  { q: "What is a cap and floor?", a: "Cap: limits maximum rate on floating debt. Floor: limits minimum rate. Cap = portfolio of caplets (call options on rates).", category: "Derivatives",firm:"Jump Trading, Citadel",difficulty:"Easy"},
  { q: "What is a forward rate agreement (FRA)?", a: "Contract locking in interest rate for future period. Cash-settled based on difference between FRA rate and actual rate.", category: "Derivatives",firm:"Point72, Two Sigma",difficulty:"Easy"},
  { q: "What is a credit default swap (CDS)?", a: "Insurance against default. Buyer pays premium, seller pays out if reference entity defaults.", category: "Derivatives",firm:"Tower Research",difficulty:"Easy"},
  { q: "What is a total return swap?", a: "One party pays total return of an asset, other pays a fixed/floating rate. Synthetic exposure without owning the asset.", category: "Derivatives",firm:"Jane Street, Virtu Financial",difficulty:"Easy"},
  { q: "What is basis risk?", a: "Risk that hedge instrument doesn't perfectly track the exposure being hedged. Important in practice.", category: "Derivatives",firm:"Hudson River Trading, Jump Trading",difficulty:"Easy"},
  { q: "What is the Black model?", a: "Adaptation of Black-Scholes for pricing options on futures/forwards. Uses forward price instead of spot.", category: "Derivatives",firm:"SIG",difficulty:"Easy"},
  { q: "What is the Heston model?", a: "Stochastic volatility model. Vol follows its own mean-reverting process. Captures smile/skew better than BS.", category: "Derivatives",firm:"Tower Research",difficulty:"Hard"},
  { q: "What is local volatility?", a: "Volatility as a function of spot and time that reproduces market prices. Dupire model.", category: "Derivatives",firm:"Millennium, Two Sigma",difficulty:"Easy"},
  { q: "What is a barrier option?", a: "Option that activates (knock-in) or deactivates (knock-out) when underlying crosses a level. Path-dependent.", category: "Derivatives",firm:"DRW, Five Rings Capital, Millennium",difficulty:"Easy"},
  // ── ADDITIONAL BRAINTEASERS (15) ──
  { q: "What is the expected number of dice rolls to get a 1 then a 2?", a: "Expected: 6 rolls for the 1, then 6 more for the 2 = 12. But if you roll a 1 while waiting for 2, you don't restart the 1 part.", category: "Brainteasers",firm:"Jump Trading, Jane Street, Hudson River Trading",difficulty:"Medium"},
  { q: "You have 3 switches and 3 bulbs in another room. How to identify which switch controls which?", a: "Turn switch 1 on for 10 min, turn off. Turn switch 2 on. Go to room: hot bulb = switch 1, lit = switch 2, cold/off = switch 3.", category: "Brainteasers",firm:"Jane Street, Renaissance Technologies",difficulty:"Medium"},
  { q: "Expected value of max(X,Y) where X,Y are independent U[0,1]?", a: "E[max] = 2/3. CDF of max = x². PDF = 2x. E = integral of 2x² dx from 0 to 1 = 2/3.", category: "Brainteasers",firm:"DE Shaw, Two Sigma",difficulty:"Medium"},
  { q: "A stick is broken at two random points. Probability the pieces form a triangle?", a: "1/4. Triangle inequality must hold for all three pieces. Geometric probability argument.", category: "Brainteasers",firm:"Citadel",difficulty:"Medium"},
  { q: "What is the expected number of people needed to find a birthday match?", a: "~23 for >50% probability. Expected value ≈ 24.6 people (slightly different from the threshold).", category: "Brainteasers",firm:"Renaissance Technologies, Jane Street",difficulty:"Medium"},
  { q: "Two players alternate flipping a coin. First to flip heads wins. P(player 1 wins)?", a: "P₁ = 1/2 + (1/2)(1/2)P₁ → P₁ = 1/2 + 1/4 P₁ → P₁ = 2/3.", category: "Brainteasers",firm:"Jump Trading, Citadel",difficulty:"Medium"},
  { q: "Expected number of uniform [0,1] draws needed to exceed 1?", a: "e ≈ 2.718. A beautiful result connecting uniform random variables to Euler's number.", category: "Brainteasers",firm:"DE Shaw, Renaissance Technologies",difficulty:"Medium"},
  { q: "You have a biased coin (unknown p). How do you generate fair outcomes?", a: "Von Neumann trick: flip twice. HT = heads, TH = tails, HH or TT = redo. P(HT) = P(TH) = p(1-p).", category: "Brainteasers",firm:"Citadel, Jump Trading, DE Shaw",difficulty:"Medium"},
  // ── ADDITIONAL CODING (10) ──
  { q: "What is a binary search tree?", a: "Tree where left children < parent < right children. O(log n) search/insert if balanced. O(n) if degenerate.", category: "Coding",firm:"SIG",difficulty:"Easy"},
  { q: "What is memoization?", a: "Caching results of expensive function calls. Key technique in dynamic programming.", category: "Coding",firm:"SIG",difficulty:"Easy"},
  { q: "What is a streaming algorithm?", a: "Processes data in one pass with limited memory. Important for real-time market data processing.", category: "Coding",firm:"Virtu Financial, DE Shaw, Tower Research",difficulty:"Easy"},
  { q: "What is Big-O notation?", a: "Describes upper bound of algorithm growth rate. O(n) = linear, O(n²) = quadratic, O(log n) = logarithmic.", category: "Coding",firm:"Citadel, Jump Trading",difficulty:"Easy"},
  { q: "What is recursion?", a: "Function calls itself with smaller input until base case. Used in tree traversal, divide-and-conquer, many puzzles.", category: "Coding",firm:"Point72",difficulty:"Easy"},
  { q: "What is a queue vs stack?", a: "Queue: FIFO (first in, first out). Stack: LIFO (last in, first out). Different access patterns.", category: "Coding",firm:"Optiver",difficulty:"Easy"},
  { q: "What is parallel computing?", a: "Multiple computations simultaneously. Important for Monte Carlo, backtesting, real-time pricing.", category: "Coding",firm:"DRW",difficulty:"Easy"},
  { q: "What is SQL used for in quant finance?", a: "Querying databases for market data, trades, positions, risk metrics. Essential for data pipelines.", category: "Coding",firm:"Jane Street",difficulty:"Easy"},
  { q: "What is a graph data structure?", a: "Nodes and edges. Models relationships. Used for network analysis, dependency graphs, order routing.", category: "Coding",firm:"Point72",difficulty:"Easy"},
  { q: "What is amortized complexity?", a: "Average cost per operation over many operations. A few expensive ops amortized by many cheap ones.", category: "Coding",firm:"AQR Capital, Virtu Financial",difficulty:"Easy"},
];

