import { Flashcard } from './ib-flashcard-data';
export const QUANT_FLASHCARDS: Flashcard[] = [
  // Probability
  { q: "What is the expected number of coin flips to get heads?", a: "For a fair coin, E[X] = 1/p = 2. Recursively: E = ½·1 + ½·(1+E) → E = 2.", category: "Probability" },
  { q: "What is Bayes' Rule?", a: "P(A|B) = P(B|A)P(A)/P(B). It updates the probability of a hypothesis when new evidence arrives.", category: "Probability" },
  { q: "What is a martingale?", a: "A stochastic process whose expected future value, conditional on current information, equals its current value. A fair game under current info.", category: "Probability" },
  { q: "What is the expected value of the maximum of two independent U[0,1] draws?", a: "E[max(X₁,X₂)] = 2/3. For n draws from U[0,1], E[max] = n/(n+1).", category: "Probability" },
  { q: "What is the birthday problem threshold?", a: "With 23 people, there's a >50% chance two share a birthday. With 70 people, it's >99.9%. Illustrates counterintuitive combinatorics.", category: "Probability" },
  { q: "What is the Central Limit Theorem?", a: "Sums/averages of many independent random variables tend toward a normal distribution. Justifies using normal approximations in many settings.", category: "Probability" },
  { q: "When does CLT fail?", a: "When independence is violated, sample size is too small, or the underlying distribution has infinite variance (heavy tails).", category: "Probability" },
  { q: "What is the Law of Large Numbers?", a: "Sample averages converge to the true expectation as sample size increases. Foundation for Monte Carlo and empirical estimation.", category: "Probability" },
  { q: "What is the difference between PDF and CDF?", a: "PDF gives the density/probability at a point. CDF gives P(X ≤ x) — the cumulative probability up to x.", category: "Probability" },
  { q: "What is the variance of a Bernoulli(p)?", a: "Var(X) = p(1-p). Maximum at p = 0.5.", category: "Probability" },
  { q: "What is conditional expectation?", a: "E[X|Y] is the expected value of X given knowledge of Y. Key tool in pricing, filtering, and Bayesian updating.", category: "Probability" },
  { q: "What is the Poisson distribution used for?", a: "Counting events in a time interval (trade arrivals, defaults, jumps). Parameter λ = mean = variance.", category: "Probability" },
  { q: "What is independence in probability?", a: "P(A∩B) = P(A)P(B). Events don't influence each other. A strong assumption — often violated in finance (correlations spike in crises).", category: "Probability" },
  { q: "What is the gambler's ruin problem?", a: "A random walk starting at k with absorbing barriers at 0 and N. With fair coin, probability of ruin (reaching 0) = 1 - k/N.", category: "Probability" },
  { q: "Expected value of a geometric distribution?", a: "E[X] = 1/p where X is number of trials until first success.", category: "Probability" },
  // Statistics
  { q: "What is overfitting?", a: "A model captures noise/idiosyncrasies in training data rather than stable patterns, performing well in-sample but poorly out-of-sample.", category: "Statistics" },
  { q: "What is the bias-variance trade-off?", a: "Bias = error from oversimplification. Variance = sensitivity to noise. Flexible models have low bias but high variance. Balance is key.", category: "Statistics" },
  { q: "What is a p-value?", a: "Probability of observing data at least as extreme as what occurred, assuming the null hypothesis is true. Not the probability the null is true.", category: "Statistics" },
  { q: "What is the Sharpe ratio?", a: "(Expected return - risk-free rate) / volatility. Measures return per unit of risk. Can be misleading for strategies with tail risk.", category: "Statistics" },
  { q: "What are common backtest biases?", a: "Look-ahead bias, survivorship bias, data snooping, selection bias, ignoring transaction costs, leaking future info into validation.", category: "Statistics" },
  { q: "What is stationarity?", a: "A time series whose statistical properties (mean, variance) don't change over time. Many financial series are non-stationary.", category: "Statistics" },
  { q: "Why can a high Sharpe strategy still be dangerous?", a: "Sharpe uses volatility as risk. A strategy with smooth gains and rare catastrophic losses (short vol) can show high Sharpe until the tail event hits.", category: "Statistics" },
  { q: "What is heteroskedasticity?", a: "When variance of residuals changes across observations. Common in finance — volatility clusters. Violates standard OLS assumptions.", category: "Statistics" },
  { q: "What does R² measure?", a: "Proportion of variance in Y explained by the model. High R² doesn't mean causation or good out-of-sample prediction.", category: "Statistics" },
  { q: "What is autocorrelation?", a: "Correlation of a time series with its own lagged values. Present in momentum, mean reversion, and volatility clustering.", category: "Statistics" },
  // Derivatives
  { q: "What is Black-Scholes?", a: "A closed-form pricing model for European options assuming lognormal prices, constant vol, constant rates, no arbitrage, and continuous hedging.", category: "Derivatives" },
  { q: "What is implied volatility?", a: "The vol input that makes a model price match the market price. Not realized vol — it's the market's pricing convention.", category: "Derivatives" },
  { q: "Why does higher vol increase option value?", a: "Options have asymmetric payoffs. More vol = higher probability of large favorable moves, while downside is limited for long options. Convexity makes vol valuable.", category: "Derivatives" },
  { q: "What is delta?", a: "Sensitivity of option price to underlying price. Ranges from 0 to 1 for calls, -1 to 0 for puts. Approximates probability of finishing ITM.", category: "Derivatives" },
  { q: "What is gamma?", a: "Rate of change of delta with respect to underlying price. Measures convexity. Highest for ATM options near expiry.", category: "Derivatives" },
  { q: "What is theta?", a: "Time decay — the rate at which option value decreases as time passes, all else equal. Long options lose theta; short options earn it.", category: "Derivatives" },
  { q: "What is vega?", a: "Sensitivity of option price to implied volatility. Long options are long vega; they benefit from rising vol.", category: "Derivatives" },
  { q: "What is put-call parity?", a: "C - P = S - Ke^(-rT). A fundamental no-arbitrage relationship for European options.", category: "Derivatives" },
  { q: "Why is delta hedging imperfect?", a: "Discrete rebalancing, transaction costs, jumps, model error, and changing volatility all prevent perfect continuous hedging.", category: "Derivatives" },
  { q: "What is a volatility smile?", a: "Implied vol varies by strike — typically higher for OTM puts and calls vs ATM. Shows Black-Scholes constant vol assumption doesn't hold.", category: "Derivatives" },
  { q: "What is risk-neutral pricing?", a: "Pricing derivatives using expected discounted payoffs under a risk-neutral measure where assets grow at the risk-free rate. Not 'true' probabilities.", category: "Derivatives" },
  // Brainteasers
  { q: "You have 100 coins on a table, 30 heads up. Blindfolded, split into two groups so each has equal heads.", a: "Move 30 coins to a new pile and flip them all. Original pile: 70 coins with (30-x) heads. New pile: 30 coins flipped, so x tails become x heads = 30-x heads. Equal!", category: "Brainteasers" },
  { q: "How many times do clock hands overlap in 12 hours?", a: "11 times. The minute hand laps the hour hand every 12/11 hours ≈ 65.45 minutes.", category: "Brainteasers" },
  { q: "Expected number of rolls of a fair die to see all 6 faces?", a: "Using coupon collector: 6/6 + 6/5 + 6/4 + 6/3 + 6/2 + 6/1 = 14.7 rolls.", category: "Brainteasers" },
  { q: "What is the expected number of rolls to get two consecutive 6s?", a: "E = 42. Recursion: E = 1/6·(1 + 1/6·0 + 5/6·E) + 5/6·(1+E). Solve for E = 42.", category: "Brainteasers" },
  // Coding & Systems
  { q: "Why might a quant use Python for research and C++ for production?", a: "Python: fast iteration, data analysis, ML libraries. C++: low latency, memory control, computational performance. Trade-off is developer speed vs runtime efficiency.", category: "Coding" },
  { q: "What is time complexity?", a: "How an algorithm's runtime scales with input size. O(1) constant, O(n) linear, O(n log n) efficient sort, O(n²) quadratic.", category: "Coding" },
  { q: "What is a hash map?", a: "Data structure mapping keys to values with O(1) average lookup. Fundamental for fast data retrieval in trading systems.", category: "Coding" },
  { q: "What is Monte Carlo simulation?", a: "Simulating many random paths to estimate expectations/distributions. Flexible but convergence is slow (1/√N error rate).", category: "Coding" },
  { q: "What is numerical stability?", a: "Correct formulas can fail computationally due to floating-point error, cancellation, overflow. Must be careful with matrix inversions and small differences.", category: "Coding" },
  // Behavioral
  { q: "Why quant finance?", a: "Love of quantitative problem-solving, attraction to uncertainty and feedback loops, interest in markets, enjoyment of combining theory with implementation.", category: "Behavioral" },
  { q: "How do you handle 'I don't know'?", a: "State what you know, what assumptions you'd make, how you'd approach the missing part. Shows judgment, not bluffing.", category: "Behavioral" },
  { q: "Tell me about a project that failed.", a: "Describe the objective, what went wrong, what you learned, and what you'd do differently. Show humility and growth mindset.", category: "Behavioral" },
];
