import { Flashcard } from './ib-flashcard-data';
export const ST_FLASHCARDS: Flashcard[] = [
// MARKET STRUCTURE (35)
{q:"What is the bid-ask spread?",a:"Difference between highest buy (bid) and lowest sell (ask). Compensates for inventory risk and adverse selection.",category:"Market Structure",firm:"Mizuho",difficulty:"Hard"},
{q:"Market order vs limit order?",a:"Market: immediate, pays spread. Limit: posts liquidity, may earn spread but faces fill uncertainty.",category:"Market Structure",firm:"HSBC",difficulty:"Medium"},
{q:"What is adverse selection?",a:"Informed traders trade against you when your quote is stale. Key risk for market makers.",category:"Market Structure",firm:"UBS",difficulty:"Medium"},
{q:"What is VWAP?",a:"Volume-Weighted Average Price. Execution benchmark. Sum(price × volume) / total volume.",category:"Market Structure",firm:"UBS",difficulty:"Medium"},
{q:"What is a dark pool?",a:"Private exchange with no pre-trade transparency. Reduces market impact for large orders.",category:"Market Structure",firm:"BNP Paribas",difficulty:"Hard"},
{q:"What is market impact?",a:"Your trade moves the price. Larger orders in illiquid markets have more impact.",category:"Market Structure",firm:"Goldman Sachs",difficulty:"Medium"},
{q:"What is slippage?",a:"Difference between expected and actual execution price. Due to market movement, impact, or delay.",category:"Market Structure",firm:"Goldman Sachs",difficulty:"Hard"},
{q:"What is a market maker?",a:"Quotes bid and ask, provides liquidity. Earns spread but bears inventory and adverse selection risk.",category:"Market Structure",firm:"Nomura",difficulty:"Hard"},
{q:"What is an order book?",a:"Electronic list of buy and sell orders at various prices. Shows market depth.",category:"Market Structure",firm:"Mizuho",difficulty:"Hard"},
{q:"What is price-time priority?",a:"Orders filled by best price first, then earliest arrival. Standard exchange matching.",category:"Market Structure",firm:"Deutsche Bank",difficulty:"Medium"},
{q:"What is a block trade?",a:"Large transaction negotiated privately to minimize impact. Often via dealers or dark pools.",category:"Market Structure",firm:"Macquarie",difficulty:"Medium"},
{q:"What is implementation shortfall?",a:"Difference between paper return (decision price) and actual return after execution. Captures all costs.",category:"Market Structure",firm:"Macquarie",difficulty:"Medium"},
{q:"What is TWAP?",a:"Time-Weighted Average Price algorithm. Spreads orders evenly over time.",category:"Market Structure",firm:"Credit Agricole",difficulty:"Medium"},
{q:"What is liquidity?",a:"Ability to buy/sell without significantly moving price. Measured by spread, depth, volume.",category:"Market Structure",firm:"UBS",difficulty:"Easy"},
{q:"What is a crossing network?",a:"Matches buys and sells at a reference price (midpoint) without price discovery.",category:"Market Structure",firm:"BMO Capital",difficulty:"Hard"},
{q:"What is a specialist vs DMM?",a:"Designated Market Maker: assigned to specific securities, obligated to quote and maintain orderly markets.",category:"Market Structure",firm:"Wells Fargo",difficulty:"Medium"},
{q:"What is high-frequency trading?",a:"Algorithmic trading at microsecond speeds. Earns from market making, arbitrage, and speed advantages.",category:"Market Structure",firm:"Jefferies",difficulty:"Hard"},
{q:"What is co-location?",a:"Placing trading servers physically near exchange matching engines. Reduces latency by microseconds.",category:"Market Structure",firm:"Societe Generale",difficulty:"Easy"},
{q:"What is a circuit breaker?",a:"Trading halts triggered by large price moves. Prevents cascading sell-offs. Level 1/2/3 in US markets.",category:"Market Structure",firm:"Deutsche Bank",difficulty:"Hard"},
{q:"What is Reg NMS?",a:"National Market System rules. Requires best price execution across exchanges. Order protection rule.",category:"Market Structure",firm:"Jefferies",difficulty:"Easy"},
{q:"What is payment for order flow?",a:"Broker routes retail orders to market makers who pay for the flow. Controversial: conflict of interest vs price improvement.",category:"Market Structure",firm:"J.P. Morgan",difficulty:"Easy"},
{q:"What is the bid-ask bounce?",a:"Trades alternating between bid and ask create apparent volatility even without true price change.",category:"Market Structure",firm:"Citi",difficulty:"Medium"},
{q:"What is a fill rate?",a:"Percentage of limit orders that execute. Higher for aggressive (closer to market) orders.",category:"Market Structure",firm:"Deutsche Bank",difficulty:"Hard"},
{q:"What is a market-on-close order?",a:"Executes at closing auction price. Important for benchmarking and index rebalancing.",category:"Market Structure",firm:"J.P. Morgan",difficulty:"Hard"},
{q:"What is an iceberg order?",a:"Large order with only a small portion visible on the book. Rest hidden. Reduces market impact.",category:"Market Structure",firm:"BMO Capital",difficulty:"Easy"},
// FIXED INCOME (40)
{q:"What is duration?",a:"Bond price sensitivity to rate changes. Longer duration = more sensitivity.",category:"Fixed Income",firm:"Morgan Stanley",difficulty:"Medium"},
{q:"What is modified duration?",a:"Approximate % price change for 1% rate change. Duration / (1 + yield).",category:"Fixed Income",firm:"Citi",difficulty:"Hard"},
{q:"What is convexity?",a:"Second-order price sensitivity. Positive convexity: price rises more for rate falls than drops for rate rises.",category:"Fixed Income",firm:"Macquarie",difficulty:"Easy"},
{q:"What is a yield curve?",a:"Yields across maturities. Normal = upward. Inverted = short > long, signals recession.",category:"Fixed Income",firm:"Mizuho",difficulty:"Easy"},
{q:"What is credit spread?",a:"Yield premium over risk-free for default/liquidity risk. Widening = stress.",category:"Fixed Income",firm:"BNP Paribas",difficulty:"Easy"},
{q:"What is repo?",a:"Short-term borrowing collateralized by securities. Fundamental to bond financing.",category:"Fixed Income",firm:"HSBC",difficulty:"Medium"},
{q:"What is carry?",a:"Income from holding position over time. Bond carry = coupon minus funding cost.",category:"Fixed Income",firm:"BNP Paribas",difficulty:"Medium"},
{q:"What is roll-down?",a:"Price gain as bond ages and moves down a normal yield curve to lower yields.",category:"Fixed Income",firm:"Credit Agricole",difficulty:"Hard"},
{q:"What is DV01?",a:"Dollar value of 1 basis point yield move. Key risk metric.",category:"Fixed Income",firm:"Macquarie",difficulty:"Easy"},
{q:"What is a basis point?",a:"1/100th of 1%. 100 bps = 1%.",category:"Fixed Income",firm:"Wells Fargo",difficulty:"Medium"},
{q:"What is yield to maturity?",a:"Total return if held to maturity assuming reinvestment. Bond's IRR.",category:"Fixed Income",firm:"Goldman Sachs",difficulty:"Easy"},
{q:"Current yield vs YTM?",a:"Current = coupon/price. YTM includes gain/loss and reinvestment. YTM more complete.",category:"Fixed Income",firm:"Morgan Stanley",difficulty:"Medium"},
{q:"What is a callable bond?",a:"Issuer can redeem early. Benefits issuer if rates fall. Buyer demands higher yield.",category:"Fixed Income",firm:"Macquarie",difficulty:"Medium"},
{q:"What is a zero-coupon bond?",a:"No coupons. Sold at discount, matures at par. All return from appreciation.",category:"Fixed Income",firm:"Mizuho",difficulty:"Hard"},
{q:"Treasury vs corporate bond?",a:"Treasury: US gov, risk-free benchmark. Corporate: credit risk, higher yield.",category:"Fixed Income",firm:"Goldman Sachs",difficulty:"Hard"},
{q:"Price and yield relationship?",a:"Inverse. Rates up → prices down. Rates down → prices up.",category:"Fixed Income",firm:"BNP Paribas",difficulty:"Hard"},
{q:"What is a CDS?",a:"Credit Default Swap. Insurance against default. Buyer pays premium, seller pays on credit event.",category:"Fixed Income",firm:"BMO Capital",difficulty:"Hard"},
{q:"High yield vs investment grade?",a:"IG: BBB-/Baa3 and above. HY: below. Higher yield, higher default risk.",category:"Fixed Income",firm:"Nomura",difficulty:"Easy"},
{q:"Inverted yield curve signal?",a:"Short rates > long rates. Historically signals recession expectations.",category:"Fixed Income",firm:"HSBC",difficulty:"Hard"},
{q:"What is a steepener trade?",a:"Bet curve steepens (long rates rise vs short). Often uses futures or swaps.",category:"Fixed Income",firm:"BNP Paribas",difficulty:"Easy"},
{q:"What is a flattener trade?",a:"Bet curve flattens. Short long-end, long short-end.",category:"Fixed Income",firm:"RBC Capital",difficulty:"Easy"},
{q:"What is negative convexity?",a:"Price appreciation slows as rates fall (callable bonds, MBS). Hurts holders.",category:"Fixed Income",firm:"Goldman Sachs",difficulty:"Easy"},
{q:"What is spread duration?",a:"Sensitivity to credit spread changes. Separate from rate duration.",category:"Fixed Income",firm:"Credit Agricole",difficulty:"Easy"},
{q:"What is a TIP (TIPS)?",a:"Treasury Inflation-Protected Securities. Principal adjusts with CPI. Protects against inflation.",category:"Fixed Income",firm:"Citi",difficulty:"Hard"},
{q:"What is a floating rate note?",a:"Coupon resets periodically (SOFR + spread). Low duration risk.",category:"Fixed Income",firm:"Bank of America",difficulty:"Easy"},
{q:"What is a mortgage-backed security?",a:"Bond backed by pool of mortgages. Prepayment risk is unique feature.",category:"Fixed Income",firm:"Macquarie",difficulty:"Medium"},
{q:"What is prepayment risk?",a:"Borrowers refinance when rates fall, returning principal early. Investor loses high-coupon cash flows.",category:"Fixed Income",firm:"Macquarie",difficulty:"Medium"},
{q:"What is a swap?",a:"Exchange of cash flows. Interest rate swap: fixed for floating. Key for hedging and expressing rate views.",category:"Fixed Income",firm:"Barclays",difficulty:"Hard"},
{q:"What is the swap rate?",a:"Fixed rate in a swap. Benchmark for credit markets. Swap spread = swap rate minus Treasury.",category:"Fixed Income",firm:"UBS",difficulty:"Easy"},
{q:"What is SOFR?",a:"Secured Overnight Financing Rate. Replaced LIBOR as benchmark for floating-rate instruments.",category:"Fixed Income",firm:"Credit Agricole",difficulty:"Medium"},
{q:"What is a bond auction?",a:"Government issues new bonds. Primary dealers bid. Sets market clearing yield.",category:"Fixed Income",firm:"BMO Capital",difficulty:"Easy"},
{q:"What is a term premium?",a:"Extra yield for holding longer-maturity bonds. Compensates for duration risk and uncertainty.",category:"Fixed Income",firm:"BNP Paribas",difficulty:"Easy"},
{q:"What is a real vs nominal yield?",a:"Nominal = stated yield. Real = nominal minus inflation. TIPS yield is a real yield.",category:"Fixed Income",firm:"Wells Fargo",difficulty:"Medium"},
{q:"What is a basis trade?",a:"Trading difference between cash bond and futures. Arbitrage relationship.",category:"Fixed Income",firm:"Macquarie",difficulty:"Medium"},
{q:"What is an asset swap?",a:"Combining bond with swap to convert fixed coupon to floating. Isolates credit spread.",category:"Fixed Income",firm:"Nomura",difficulty:"Hard"},
// OPTIONS (30)
{q:"What is delta?",a:"Option price sensitivity to underlying. Calls: 0 to 1. Puts: -1 to 0.",category:"Options",firm:"J.P. Morgan",difficulty:"Hard"},
{q:"What is gamma?",a:"Rate of change of delta. Highest ATM near expiry. Measures convexity.",category:"Options",firm:"Goldman Sachs",difficulty:"Medium"},
{q:"What is theta?",a:"Time decay. Options lose value as time passes. Short options benefit.",category:"Options",firm:"Nomura",difficulty:"Medium"},
{q:"What is vega?",a:"Sensitivity to implied vol. Long options = long vega.",category:"Options",firm:"Macquarie",difficulty:"Easy"},
{q:"What is implied vol?",a:"Vol making model price = market price. Market's pricing language.",category:"Options",firm:"Mizuho",difficulty:"Medium"},
{q:"What is a straddle?",a:"Long call + long put, same strike. Profits from large moves. Buying vol.",category:"Options",firm:"Deutsche Bank",difficulty:"Medium"},
{q:"What is a strangle?",a:"Long OTM call + OTM put. Cheaper than straddle, needs bigger move.",category:"Options",firm:"Jefferies",difficulty:"Medium"},
{q:"What is a butterfly?",a:"Buy low + high strike, sell 2 ATM. Profits if underlying stays near ATM.",category:"Options",firm:"Bank of America",difficulty:"Medium"},
{q:"What is a covered call?",a:"Long stock + short call. Earns premium, caps upside. Income strategy.",category:"Options",firm:"BMO Capital",difficulty:"Medium"},
{q:"What is a protective put?",a:"Long stock + long put. Insurance against downside.",category:"Options",firm:"HSBC",difficulty:"Easy"},
{q:"Put-call parity?",a:"C - P = S - Ke^(-rT). Core no-arbitrage identity.",category:"Options",firm:"Macquarie",difficulty:"Easy"},
{q:"What is a collar?",a:"Long stock + long OTM put + short OTM call. Limits both sides.",category:"Options",firm:"J.P. Morgan",difficulty:"Easy"},
{q:"What is a calendar spread?",a:"Same strike, different expirations. Profits from time decay differential.",category:"Options",firm:"Goldman Sachs",difficulty:"Medium"},
{q:"What is a risk reversal?",a:"Long OTM call + short OTM put (or vice versa). Directional using options.",category:"Options",firm:"HSBC",difficulty:"Hard"},
{q:"What is gamma scalping?",a:"Delta-hedging long gamma position. Profit from realized > implied vol.",category:"Options",firm:"Societe Generale",difficulty:"Hard"},
{q:"Intrinsic vs time value?",a:"Intrinsic = ITM amount. Time value = premium minus intrinsic. Decays to zero.",category:"Options",firm:"HSBC",difficulty:"Hard"},
{q:"What is the vol surface?",a:"3D: implied vol across strikes and expirations. Shows skew and term structure.",category:"Options",firm:"Nomura",difficulty:"Easy"},
{q:"What is skew?",a:"Implied vol difference across strikes. Downside puts typically higher vol.",category:"Options",firm:"BMO Capital",difficulty:"Medium"},
{q:"What is term structure of vol?",a:"How implied vol varies across expirations. Can slope up, flat, or inverted.",category:"Options",firm:"RBC Capital",difficulty:"Medium"},
{q:"What is a variance swap?",a:"Swap paying realized minus implied variance. Pure vol bet, no delta.",category:"Options",firm:"Morgan Stanley",difficulty:"Easy"},
{q:"What is a vol-of-vol?",a:"Volatility of implied volatility itself. Matters for exotic options pricing.",category:"Options",firm:"Mizuho",difficulty:"Medium"},
{q:"What is a digital/binary option?",a:"Pays fixed amount if condition met (e.g., above strike), zero otherwise.",category:"Options",firm:"Macquarie",difficulty:"Medium"},
{q:"What is an iron condor?",a:"Short strangle + long further OTM strangle. Profits from low vol, limited risk.",category:"Options",firm:"Goldman Sachs",difficulty:"Medium"},
{q:"What is a ratio spread?",a:"Unequal number of long and short options. Directional with skew exposure.",category:"Options",firm:"J.P. Morgan",difficulty:"Hard"},
{q:"What is early exercise?",a:"American option exercised before expiry. Calls: rarely optimal (non-dividend). Puts: may be optimal.",category:"Options",firm:"Barclays",difficulty:"Medium"},
{q:"What is pin risk?",a:"Risk near expiry when underlying is close to strike. Uncertainty about exercise.",category:"Options",firm:"Goldman Sachs",difficulty:"Medium"},
{q:"What is a VIX future?",a:"Futures on expected 30-day S&P vol. Usually in contango (futures > spot).",category:"Options",firm:"Mizuho",difficulty:"Easy"},
{q:"What is contango vs backwardation in vol?",a:"Contango: future vol > spot vol (normal). Backwardation: spot > future (during stress).",category:"Options",firm:"Bank of America",difficulty:"Hard"},
// TRADE IDEAS & MACRO (25)
{q:"Pitch me a trade.",a:"Thesis → instrument → entry/target/stop → risk management → catalyst. Be specific, acknowledge risks.",category:"Trade Ideas",firm:"Macquarie",difficulty:"Easy"},
{q:"$1M to invest — what would you do?",a:"Macro view, asset allocation, specific ideas with risk/reward. Show sizing and what's priced in.",category:"Trade Ideas",firm:"Societe Generale",difficulty:"Easy"},
{q:"What is a carry trade?",a:"Borrow low-yield, invest high-yield. Profitable if stable. Exposed to reversals.",category:"Trade Ideas",firm:"BNP Paribas",difficulty:"Easy"},
{q:"What is a pairs trade?",a:"Long one, short correlated other. Bet on relative performance. Market-neutral.",category:"Trade Ideas",firm:"Jefferies",difficulty:"Hard"},
{q:"What is a convergence trade?",a:"Bet two prices will converge. Common in arb strategies.",category:"Trade Ideas",firm:"HSBC",difficulty:"Easy"},
{q:"What macro theme are you following?",a:"Pick something current. Show depth — transmission mechanism and positioning implications.",category:"Trade Ideas",firm:"Macquarie",difficulty:"Easy"},
{q:"Central bank decisions affect markets how?",a:"Rate changes affect discount rates, credit, currency, risk appetite. Guidance shapes expectations.",category:"Trade Ideas",firm:"HSBC",difficulty:"Hard"},
{q:"Risk-on vs risk-off?",a:"Risk-on: equities up, spreads tight, vol low. Risk-off: flight to quality, vol spike, spreads widen.",category:"Trade Ideas",firm:"Credit Agricole",difficulty:"Easy"},
{q:"What is a short squeeze?",a:"Sharp rise forces shorts to cover, creating more buying pressure.",category:"Trade Ideas",firm:"Societe Generale",difficulty:"Hard"},
{q:"What drives FX rates?",a:"Rate differentials, trade balances, capital flows, inflation, policy, risk sentiment.",category:"Trade Ideas",firm:"Barclays",difficulty:"Easy"},
{q:"What is a tail risk hedge?",a:"Position protecting against extremes — deep OTM puts, VIX calls. Insurance with negative carry.",category:"Trade Ideas",firm:"TD Securities",difficulty:"Medium"},
{q:"What is momentum?",a:"Trend continuation: recent winners keep winning. Works across assets but can reverse sharply.",category:"Trade Ideas",firm:"BNP Paribas",difficulty:"Medium"},
{q:"What is mean reversion?",a:"Prices tend toward long-run average. Basis for relative value strategies.",category:"Trade Ideas",firm:"BMO Capital",difficulty:"Hard"},
{q:"What is the VIX?",a:"S&P 500 implied vol index. 'Fear gauge.' Spikes during stress.",category:"Trade Ideas",firm:"UBS",difficulty:"Medium"},
{q:"What is a relative value trade?",a:"Exploiting mispricing between related securities rather than taking directional risk.",category:"Trade Ideas",firm:"Barclays",difficulty:"Hard"},
{q:"What is a curve trade?",a:"Positioning on yield curve shape: steepener, flattener, butterfly.",category:"Trade Ideas",firm:"Societe Generale",difficulty:"Medium"},
{q:"What is a cross-asset trade?",a:"Trading relationship between asset classes: equity vs credit, rates vs FX.",category:"Trade Ideas",firm:"Wells Fargo",difficulty:"Hard"},
{q:"What is an event-driven trade?",a:"Positioning around earnings, central bank meetings, elections, regulatory decisions.",category:"Trade Ideas",firm:"Citi",difficulty:"Medium"},
{q:"What is a regime change?",a:"Shift in market dynamics: inflation to deflation, risk-on to risk-off, growth to recession.",category:"Trade Ideas",firm:"J.P. Morgan",difficulty:"Easy"},
{q:"What is positioning data?",a:"Shows how traders are positioned (COT reports, fund flows). Extreme positioning can signal reversals.",category:"Trade Ideas",firm:"BNP Paribas",difficulty:"Hard"},
// BEHAVIORAL (20)
{q:"Why sales and trading?",a:"Fast-paced, markets-focused, immediate feedback, analytical + intuition + risk management.",category:"Behavioral",firm:"Goldman Sachs",difficulty:"Hard"},
{q:"Sales vs trading difference?",a:"Sales: client relationships, market color. Trading: risk-taking, position management.",category:"Behavioral",firm:"J.P. Morgan",difficulty:"Hard"},
{q:"How do you handle a losing trade?",a:"Re-evaluate thesis. If broken, cut. If thesis holds and risk manageable, may hold. Never denial.",category:"Behavioral",firm:"Goldman Sachs",difficulty:"Easy"},
{q:"Tell me about a trade you'd put on.",a:"Specific, well-reasoned. Know instrument, risk/reward, what goes wrong.",category:"Behavioral",firm:"Mizuho",difficulty:"Medium"},
{q:"What markets do you follow?",a:"Be specific: equities, rates, credit, FX, commodities. Know recent moves and drivers.",category:"Behavioral",firm:"Societe Generale",difficulty:"Easy"},
{q:"How do you stay informed?",a:"Bloomberg, WSJ, FT, research, earnings calls, central bank comms. Show genuine engagement.",category:"Behavioral",firm:"Wells Fargo",difficulty:"Hard"},
{q:"Tell me about a calculated risk.",a:"Risk assessment, decision process, outcome, learning. Disciplined risk-taking.",category:"Behavioral",firm:"Societe Generale",difficulty:"Hard"},
{q:"What's your edge?",a:"Be honest. Speed, pattern recognition, discipline, specific knowledge. Don't overclaim.",category:"Behavioral",firm:"Mizuho",difficulty:"Easy"},
{q:"How do you size a position?",a:"Conviction, vol, liquidity, correlation, max loss tolerance. Risk-based sizing.",category:"Behavioral",firm:"J.P. Morgan",difficulty:"Easy"},
{q:"Tell me about yourself.",a:"Markets interest → experience → quantitative/analytical skills → why S&T.",category:"Behavioral",firm:"Wells Fargo",difficulty:"Easy"},
{q:"How do you manage risk?",a:"Position limits, stop-losses, diversification, correlation awareness, scenario analysis.",category:"Behavioral",firm:"BNP Paribas",difficulty:"Medium"},
{q:"What is the most important quality for a trader?",a:"Discipline. Cutting losses, sticking to process, not chasing, managing emotions.",category:"Behavioral",firm:"Macquarie",difficulty:"Medium"},
{q:"Tell me about a time you were wrong.",a:"What was the thesis, what happened, how you managed it, what you learned.",category:"Behavioral",firm:"Barclays",difficulty:"Medium"},
{q:"What would you do on your first day?",a:"Learn the desk, understand positions, observe, ask questions, build relationships.",category:"Behavioral",firm:"BNP Paribas",difficulty:"Medium"},
{q:"How do you handle stress?",a:"Stay calm, focus on process not outcome, take breaks, maintain perspective.",category:"Behavioral",firm:"BNP Paribas",difficulty:"Medium"},
];
