export const ER_FUNDAMENTALS_SECTIONS = [
  { title: '1.1 What Equity Research Analysts Do', content: `<p>ER analysts are the sell-side's opinion engine. They cover a universe of 10-20 public companies within a sector, building detailed financial models, publishing research reports, and issuing buy/hold/sell ratings.</p><p>Your value as an ER analyst = <strong>the quality of your investment insights and the accuracy of your earnings estimates</strong>. Top-ranked analysts move markets when they publish.</p>` },
  { title: '1.2 The Research Report Hierarchy', content: `<ul><li><strong>Initiation Report (30-50 pages):</strong> Deep dive when first picking up coverage. Industry overview, company analysis, valuation, rating, and price target.</li><li><strong>Earnings Preview:</strong> Published before a company reports. States expectations vs. consensus.</li><li><strong>Earnings Reaction Note:</strong> Published within hours of earnings. Analyzes the beat/miss and updates the model.</li><li><strong>Thematic / Industry Report:</strong> Sector-wide analysis on trends affecting multiple companies.</li><li><strong>Company Update:</strong> Brief notes on news events, management changes, or guidance updates.</li></ul>` },
  { title: '1.3 Sell-Side vs. Buy-Side Research', content: `<p><strong>Sell-side (you):</strong> Published research accessible to institutional clients. Revenue comes from trading commissions and client relationships. You cover many companies broadly.</p><p><strong>Buy-side:</strong> Internal research at hedge funds and asset managers. Not published. Deeper, more conviction-driven. Analysts often cover fewer names but with greater depth and a clear P&L attached.</p><p>ER is the most common pathway from sell-side to buy-side roles at hedge funds and long-only asset managers.</p>` },
];

export const ER_MODELING_SECTIONS = [
  { title: '2.1 Building an ER Financial Model', content: `<p>ER models are more granular than IB models. You build a <strong>bottom-up revenue model</strong> that ties to industry drivers.</p><p>For a retailer: model by segment → same-store sales growth + new store openings → revenue. For SaaS: model by ARR → new bookings + upsell - churn → revenue.</p><p>Key outputs: Revenue, EBITDA, EPS (the most important metric in ER), and Free Cash Flow.</p>` },
  { title: '2.2 Earnings Per Share (EPS) Forecasting', content: `<p>EPS is king in equity research. Institutional investors compare your EPS estimate against consensus. Being right when consensus is wrong = career-making.</p><p><strong>Basic EPS</strong> = Net Income / Shares Outstanding<br/><strong>Diluted EPS</strong> = Net Income / (Shares Outstanding + dilutive options/warrants)</p><p>You must understand: how share buybacks affect EPS, how one-time charges are excluded for "adjusted" EPS, and why companies guide to specific EPS ranges.</p>` },
  { title: '2.3 Valuation in ER Context', content: `<p><strong>P/E (Price-to-Earnings):</strong> The most commonly used metric in ER. Forward P/E = Current Stock Price / Next Year's EPS Estimate.</p><p><strong>EV/EBITDA:</strong> Used for capital-structure-neutral comparisons.</p><p><strong>DCF:</strong> Used as a sanity check, especially for high-growth companies where P/E is distorted.</p><p><strong>Sum-of-the-Parts (SOTP):</strong> For conglomerates — value each division separately.</p><p><strong>Price Target:</strong> Your 12-month target price, derived from applying a target multiple to your forward estimates. This is what the market cares about most.</p>` },
];

export const ER_STOCK_PITCH_SECTIONS = [
  { title: '3.1 The Stock Pitch (The #1 ER Interview Question)', content: `<p>Every ER interview will ask: <strong>"Pitch me a stock."</strong> This is the single most important thing you prepare.</p><h4>Structure:</h4><ol><li><strong>Company overview:</strong> What they do, 1 sentence. Market cap, sector.</li><li><strong>Investment thesis:</strong> Why is this stock mispriced? What does the market not see?</li><li><strong>Key drivers:</strong> 2-3 catalysts that will unlock value (earnings beat, new product, margin expansion).</li><li><strong>Valuation:</strong> Current multiple vs. where you think it should trade. Your price target.</li><li><strong>Risks:</strong> What could go wrong and why you're still comfortable.</li></ol>` },
  { title: '3.2 What Makes a Great Pitch', content: `<p><strong>Variant perception:</strong> Your thesis must differ from consensus. If the market already agrees with you, there's no alpha.</p><p><strong>Specific catalysts:</strong> "The stock is cheap" is not a thesis. "The stock is cheap because the market is mispricing their SaaS transition, and when they report 30%+ ARR growth next quarter, the multiple will re-rate from 8x to 12x" — that's a thesis.</p><p><strong>Show your work:</strong> Reference specific financial data. "Revenue grew 15% last quarter, but operating leverage drove 25% EBITDA growth." Numbers make you credible.</p>` },
  { title: '3.3 Sample Stock Pitch Framework', content: `<p><em>"I'd recommend buying [Company X], a $5B market cap specialty chemical company trading at 11x forward EBITDA, which is a 20% discount to peers. The market is penalizing them for a one-time plant shutdown that depressed last quarter's margins. My thesis is that margins will normalize to 25%+ as the plant ramps back to full capacity in Q2, driving EPS ~15% above consensus. At a peer-average 14x multiple on my estimates, the stock has 30% upside to $85. Key risk is raw material inflation, but they've locked in contracts through year-end."</em></p>` },
];

export const ER_BEHAVIORAL_SECTIONS = [
  { title: '4.1 "Why Equity Research?"', content: `<p><strong>Weak:</strong> "I like analyzing stocks and following the market."</p><p><strong>Elite:</strong> "I'm drawn to equity research because it combines deep fundamental analysis with the intellectual challenge of forming a differentiated view. What excites me is the idea that you can study a company more thoroughly than anyone else and be rewarded when your thesis plays out. I've been building my own models on [sector] companies and publishing analysis on [blog/platform], and I want to do this professionally at scale."</p>` },
  { title: '4.2 "What Sector Would You Want to Cover?"', content: `<p>Pick a sector you genuinely follow and can speak intelligently about. Name 3-5 public companies, their recent performance, and one insight about the sector.</p><p><em>"I'd love to cover enterprise software. I've been following companies like Salesforce, ServiceNow, and Datadog closely. What fascinates me is the transition from license to subscription models and how that changes the way we should value these businesses — traditional P/E ratios are misleading during high-growth transitions, and I think there's an edge in building models that properly capture unit economics."</em></p>` },
  { title: '4.3 Preparing a Writing Sample', content: `<p>Some firms ask for a sample research report. Structure:</p><ol><li><strong>Executive summary:</strong> Rating, price target, key thesis (1 paragraph)</li><li><strong>Investment thesis:</strong> 3 key points with supporting evidence</li><li><strong>Financial overview:</strong> Revenue, margins, EPS trends</li><li><strong>Valuation:</strong> Comps table, DCF summary, price target derivation</li><li><strong>Risks:</strong> 2-3 key risks with mitigants</li></ol><p>Keep it to 5-8 pages. Quality of insight matters more than length.</p>` },
  { title: '4.4 Practice Drills', content: `<p><strong>Daily:</strong> Read one earnings call transcript and summarize the 3 key takeaways in writing.</p><p><strong>Weekly:</strong> Build or update a financial model for a public company you follow.</p><p><strong>Before interviews:</strong> Prepare 2 polished stock pitches (1 long, 1 short). Practice delivering each in 2 minutes. Have a friend push back on your thesis.</p><p><strong>Resources:</strong> SEC EDGAR (10-K filings), company investor relations pages, Bloomberg/FactSet (if you have access), Seeking Alpha for learning to read bull/bear debates.</p>` },
];
