export const RX_FUNDAMENTALS_SECTIONS = [
  { title: '1.1 What Restructuring Is', content: `<p>Restructuring is the process of reorganizing a company's capital structure when it cannot meet its financial obligations. This happens when a company has too much debt relative to its cash flow — it can't make interest payments, violates loan covenants, or faces imminent bankruptcy.</p><p>RX professionals advise either the <strong>debtor</strong> (the company in trouble) or the <strong>creditors</strong> (the banks and bondholders owed money). The goal is to find a solution that maximizes value recovery for all parties — or, failing that, to manage an orderly liquidation.</p>` },
  { title: '1.2 Chapter 11 vs. Chapter 7', content: `<p><strong>Chapter 11 (Reorganization):</strong> The company continues operating while it restructures its debt under court supervision. A Plan of Reorganization is negotiated among debtors, creditors, and equity holders. The company emerges from bankruptcy as a going concern with a cleaned-up balance sheet.</p><p><strong>Chapter 7 (Liquidation):</strong> The company ceases operations entirely. Assets are sold off and proceeds are distributed to creditors according to the priority of claims. Equity holders almost always get wiped out.</p><p>Most RX advisory work involves Chapter 11 — keeping the business alive while renegotiating who takes losses.</p>` },
  { title: '1.3 Priority of Claims (The Waterfall)', content: `<p>In bankruptcy, creditors are paid in strict order of seniority. Memorize this:</p><ol><li><strong>DIP Financing (Debtor-in-Possession):</strong> New loans provided during bankruptcy. Super-priority — paid first.</li><li><strong>Secured Creditors:</strong> Banks with collateral (real estate, inventory, equipment). Paid from the value of their collateral.</li><li><strong>Unsecured Creditors:</strong> Bondholders, trade creditors, landlords with no collateral.</li><li><strong>Subordinated Debt:</strong> Junior bonds, mezzanine lenders.</li><li><strong>Preferred Equity:</strong> Hybrid security between debt and equity.</li><li><strong>Common Equity:</strong> Shareholders. Almost always wiped out in bankruptcy.</li></ol><p><strong>The "Fulcrum Security":</strong> The tranche of debt that is partially impaired — meaning it doesn't get fully repaid but doesn't get completely wiped out either. Identifying the fulcrum security is one of the most important analytical exercises in restructuring.</p>` },
  { title: '1.4 Key Restructuring Concepts', content: `<p><strong>Liquidity Analysis (13-Week Cash Flow):</strong> A week-by-week projection of cash inflows and outflows. Used to determine how long the company can survive without additional financing. This is the most time-critical deliverable in RX.</p><p><strong>DIP Financing:</strong> Emergency loans provided to companies in Chapter 11. Lenders accept because DIP loans have super-priority status — they get paid before everyone else.</p><p><strong>Cramdown:</strong> When the court forces a reorganization plan on dissenting creditors if the plan meets certain fairness standards.</p><p><strong>Section 363 Sale:</strong> A bankruptcy court-supervised asset sale. Often used to sell the company's assets quickly to preserve value (e.g., the Lehman Brothers asset sales).</p><p><strong>Equitization:</strong> Converting debt into equity. Creditors give up their debt claims and receive ownership shares in the reorganized company instead.</p>` },
];

export const RX_TECHNICALS_SECTIONS = [
  { title: '2.1 Valuation in Distress', content: `<p>Traditional valuation (DCF, comps) breaks down for distressed companies. Cash flows are unreliable, the capital structure is in flux, and the company may not survive.</p><h4>Approaches used in RX:</h4><ul><li><strong>Liquidation Analysis:</strong> What are the assets worth if sold piecemeal? Apply recovery rates to each asset class (e.g., inventory at 50-70% of book, real estate at appraised value, receivables at 80-90%).</li><li><strong>Reorganization Valuation:</strong> What is the enterprise value of the company if it emerges from bankruptcy as a going concern? Use a DCF or comps, but with a normalized capital structure.</li><li><strong>Claims Analysis:</strong> Map the enterprise value against the priority waterfall to determine which creditors are impaired and what each class recovers.</li></ul>` },
  { title: '2.2 The Fulcrum Security Analysis', content: `<p>The fulcrum security is where the enterprise value "runs out" as you move down the capital stack.</p><h4>Example:</h4><p>Enterprise Value = $500M. Senior Secured Debt = $300M. Unsecured Bonds = $400M. Equity = $200M.</p><p>Secured creditors are fully covered ($300M < $500M). Unsecured bondholders are the fulcrum — only $200M is left for their $400M claim, so they recover 50 cents on the dollar. Equity is wiped out entirely.</p><p><strong>Why this matters:</strong> Distressed debt investors buy the fulcrum security at a discount (say 40 cents on the dollar) because they know that in a reorganization, they'll receive equity in the new company. If the new equity is worth 50+ cents, they profit.</p>` },
  { title: '2.3 Credit Analysis & Covenant Review', content: `<p><strong>Leverage Ratios:</strong> Total Debt / EBITDA. Above 6-7x is considered highly leveraged. Above 8-10x is distressed territory.</p><p><strong>Interest Coverage:</strong> EBITDA / Interest Expense. Below 1.0x means the company can't cover its interest from operations — a major red flag.</p><p><strong>Fixed Charge Coverage:</strong> (EBITDA - CapEx) / (Interest + Mandatory Amortization). More conservative than interest coverage because it includes maintenance CapEx and debt repayment.</p><p><strong>Covenant breaches:</strong> When a company violates a financial covenant (e.g., leverage exceeds the maximum allowed ratio), it triggers a technical default. Lenders can then accelerate the debt — demanding immediate full repayment. This is often the event that forces a company into restructuring negotiations.</p>` },
  { title: '2.4 Key Technical Interview Questions', content: `<p><strong>"Walk me through a Chapter 11 process."</strong></p><p><em>"The company files a voluntary petition. An automatic stay prevents creditors from collecting. The company obtains DIP financing to fund operations during bankruptcy. A Plan of Reorganization is proposed, negotiated with creditor committees, and voted on. If approved by creditors and confirmed by the court, the company emerges with a new capital structure. If not, the company may be forced into a 363 sale or Chapter 7 liquidation."</em></p><p><strong>"What is DIP financing and why would a lender provide it?"</strong></p><p><em>"DIP financing is a loan provided to a company already in Chapter 11 bankruptcy. Lenders are willing to provide it because DIP loans have super-priority status — they are repaid before all pre-petition debt, including secured creditors. The risk is low because the lender has first claim on all assets, and the terms (high interest rates, tight covenants) compensate for the distressed situation."</em></p><p><strong>"What happens to equity holders in a Chapter 11?"</strong></p><p><em>"In most Chapter 11 cases, equity holders are wiped out because the company's enterprise value is insufficient to fully repay creditors. Under the Absolute Priority Rule, no junior class can receive any recovery until all senior classes are paid in full. Since equity is the most junior claim, it is typically cancelled and replaced with new equity issued to the creditors who converted their debt."</em></p>` },
];

export const RX_BEHAVIORAL_SECTIONS = [
  { title: '3.1 "Why Restructuring?"', content: `<p><strong>Weak:</strong> "I think distressed situations are interesting and I like complex problems."</p><p><strong>Elite:</strong> "I'm drawn to restructuring because it sits at the intersection of finance, law, and business strategy in the most high-stakes environment possible. What excites me is that the work requires you to understand the entire capital structure — not just one slice — and to think about value from every stakeholder's perspective simultaneously. I also appreciate that restructuring is counter-cyclical: when the broader market struggles, the intellectual and analytical demands of the work intensify. I thrive under that kind of pressure."</p>` },
  { title: '3.2 "Why RX Over M&A?"', content: `<p><em>"In M&A, the deal thesis is usually about growth and value creation. In restructuring, the thesis is about value preservation under extreme constraints. I find the analytical challenge more compelling — you're working with broken capital structures, conflicting creditor incentives, and real urgency. Every dollar matters because there isn't enough to go around. The negotiation dynamics are also more complex: in M&A, buyer and seller ultimately want the deal to happen. In RX, creditors are fighting over a shrinking pie. That dynamic requires sharper analysis and more creative problem-solving."</em></p>` },
  { title: '3.3 Distressed Situations to Follow', content: `<p>Before any RX interview, be prepared to discuss 2-3 recent or notable restructurings:</p><ul><li>Know the company, why it filed, who the key creditors were, and the outcome.</li><li>Have a view on whether the restructuring was handled well.</li><li>Follow distressed situations in real time via Reorg Research, Debtwire, or Bloomberg bankruptcy coverage.</li></ul><p>Classic cases to study: Lehman Brothers (2008), Hertz (2020), J.Crew (2020), Revlon (2022), SVB/Signature Bank (2023).</p>` },
  { title: '3.4 Practice Drills', content: `<p><strong>Technical drill:</strong> Given a capital structure ($200M secured, $300M unsecured, $100M equity) and an enterprise value ($350M), determine the fulcrum security and recovery for each class.</p><p><strong>Weekly:</strong> Read one bankruptcy court filing or restructuring press release. Summarize the situation, the proposed plan, and who wins/loses.</p><p><strong>Daily:</strong> Review credit spreads (high yield index), default rates, and distressed debt prices. These indicate the health of the credit markets.</p><p><strong>Mock interview:</strong> Practice explaining Chapter 11, DIP financing, and the priority of claims in under 2 minutes each. Record yourself and assess clarity.</p>` },
];
