export const VC_FUNDAMENTALS_SECTIONS = [
  { title: '1.1 How Venture Capital Works', content: `<p>VC funds raise capital from LPs (endowments, pensions, family offices), deploy it into startups over a 3-5 year investment period, and return capital over a 10-year fund life. The math is fundamentally different from PE.</p><p><strong>The Power Law:</strong> Most VC investments fail. Returns are driven by a tiny number of massive winners. In a portfolio of 30 companies, 1-2 investments may return 50x+ and carry the entire fund. This means VCs need to swing for home runs, not base hits.</p>` },
  { title: '1.2 Fund Economics', content: `<p><strong>Management Fee:</strong> Typically 2% of committed capital per year. This covers salaries and operations.</p><p><strong>Carried Interest:</strong> 20% of profits above a hurdle rate (usually 8%). This is where GPs get rich.</p><p><strong>Fund Math Example:</strong> A $200M fund needs to return $600M (3x) to be considered successful. If 1 company returns 100x on a $5M investment = $500M. That one company nearly returns the entire fund.</p><p><strong>Ownership targets:</strong> Early-stage VCs typically want 15-25% ownership per deal. This dilutes over subsequent rounds but the goal is to maintain meaningful ownership through the IPO.</p>` },
  { title: '1.3 Stages of Venture Investing', content: `<ul><li><strong>Pre-Seed ($100K-$1M):</strong> Investing in a team and an idea. No product, no revenue. Pure bet on founders.</li><li><strong>Seed ($1-$5M):</strong> Early product, initial users. Demonstrating that someone wants what you're building.</li><li><strong>Series A ($5-$20M):</strong> Product-market fit proven. Now it's about scaling go-to-market.</li><li><strong>Series B ($20-$60M):</strong> Rapid scaling. Hiring aggressively, expanding to new markets.</li><li><strong>Series C+ ($50-$200M+):</strong> Growth stage. Preparing for IPO or strategic exit.</li><li><strong>Late-Stage / Pre-IPO ($100M+):</strong> Near-public companies. Lower risk, lower multiple, but still meaningful returns if you pick right.</li></ul>` },
  { title: '1.4 What Makes a Great VC Investment', content: `<p>VCs evaluate deals across five dimensions:</p><ol><li><strong>Team:</strong> Is the founding team exceptional? Do they have domain expertise, resilience, and the ability to recruit top talent?</li><li><strong>Market:</strong> Is the TAM (Total Addressable Market) large enough to support a $1B+ outcome? Is the market growing?</li><li><strong>Product:</strong> Does the product solve a real, urgent problem? Is there evidence of product-market fit (retention, NPS, organic growth)?</li><li><strong>Business Model:</strong> Is the unit economics attractive? Is CAC < LTV? Is there a path to profitability?</li><li><strong>Timing:</strong> Why now? What has changed (technology, regulation, behavior) that makes this possible today but not 5 years ago?</li></ol>` },
];

export const VC_EVALUATION_SECTIONS = [
  { title: '2.1 Evaluating a Pitch Deck', content: `<p>In interviews, you may be given a pitch deck and asked "Would you invest?" Use this framework:</p><ol><li><strong>Problem:</strong> Is the problem real and painful? Or is this a "nice to have"?</li><li><strong>Solution:</strong> Does the product actually solve the problem elegantly?</li><li><strong>Market size:</strong> Is the TAM credible? (Beware of inflated "top-down" TAM calculations.)</li><li><strong>Traction:</strong> What metrics demonstrate product-market fit? Revenue growth, user retention, engagement.</li><li><strong>Team:</strong> What makes these founders uniquely qualified?</li><li><strong>Business model:</strong> How do they make money? Is it scalable?</li><li><strong>Competition:</strong> Who else is doing this? What's the defensible moat?</li><li><strong>Ask:</strong> How much are they raising, at what valuation, and what will they do with the money?</li></ol>` },
  { title: '2.2 Key Metrics for Startups', content: `<p><strong>SaaS Metrics:</strong></p><ul><li><strong>ARR (Annual Recurring Revenue):</strong> The gold standard. Growing 2-3x year-over-year is "good" at Series A.</li><li><strong>Net Revenue Retention (NRR):</strong> >120% means existing customers are spending more each year. Best-in-class is 130%+.</li><li><strong>CAC Payback:</strong> How many months to recoup customer acquisition cost. <12 months is ideal.</li><li><strong>LTV/CAC:</strong> Lifetime value divided by acquisition cost. >3x is the benchmark.</li><li><strong>Gross Margin:</strong> SaaS should be 70-80%+.</li><li><strong>Burn Multiple:</strong> Net burn / net new ARR. <1.5x is efficient.</li></ul><p><strong>Consumer Metrics:</strong> DAU/MAU ratio (>25% is strong), retention curves, virality coefficient, average revenue per user (ARPU).</p>` },
  { title: '2.3 Valuation in VC', content: `<p>VC valuation is more art than science at the early stage.</p><p><strong>Pre-money valuation:</strong> What the company is worth before the new investment.</p><p><strong>Post-money valuation:</strong> Pre-money + new investment.</p><p><strong>Example:</strong> A company raises $5M at a $20M pre-money valuation. Post-money = $25M. The investor owns $5M / $25M = 20%.</p><p><strong>Common valuation methods:</strong></p><ul><li><strong>Revenue multiples:</strong> 10-30x ARR for high-growth SaaS at Series A/B.</li><li><strong>Comparable transactions:</strong> What did similar companies raise at?</li><li><strong>Ownership-driven:</strong> VC works backward — "We want 20% ownership, the company needs $5M, so the pre-money must be $20M."</li></ul>` },
];

export const VC_BEHAVIORAL_SECTIONS = [
  { title: '3.1 "Why Venture Capital?"', content: `<p><strong>Weak:</strong> "I love startups and innovation."</p><p><strong>Elite:</strong> "I want to be in venture capital because I'm fascinated by the intersection of technology trends and business model innovation. What draws me specifically is the intellectual challenge of pattern recognition — evaluating founding teams and markets before there's definitive data, and making conviction-driven bets. I've been actively tracking [specific sector] for the past year, writing investment memos on companies like [X] and [Y], and I've developed a thesis on [trend]. I want to do this full-time, with real capital and real consequences."</p>` },
  { title: '3.2 "What Sectors Excite You?"', content: `<p>You MUST have a sector thesis. Pick 1-2 areas you follow deeply and can discuss for 20 minutes.</p><p><strong>Good answer structure:</strong></p><ol><li>Name the sector and why it's interesting now (what changed?)</li><li>Identify 2-3 companies leading the space</li><li>Explain what you'd look for in an investment</li><li>Name one risk or debate in the space</li></ol><p><em>"I'm most excited about vertical AI applications in healthcare. The combination of LLM capabilities and the massive inefficiency in clinical documentation creates a perfect setup. Companies like Abridge and Ambience Healthcare are leading — they're embedding AI into the physician workflow, not creating a separate tool. I'd invest in teams with deep clinical domain expertise, not just ML talent. The key debate is whether large health systems will build vs. buy."</em></p>` },
  { title: '3.3 "Tell Me About a Company You Think Is Interesting"', content: `<p>This is the VC equivalent of a stock pitch. Structure:</p><ol><li><strong>What they do</strong> (1 sentence)</li><li><strong>Why they're winning</strong> (product, team, timing)</li><li><strong>Key metrics</strong> (if public or known)</li><li><strong>What excites you</strong> (the insight the market is missing)</li><li><strong>Risks</strong></li></ol><p>Pick a private company if possible — it shows you're plugged into the ecosystem, not just reading public stock tickers.</p>` },
  { title: '3.4 Practice Drills', content: `<p><strong>Weekly:</strong> Read 5 startup pitch decks (available on sites like Pitch Deck Hunt or DocSend examples). For each, write a 1-page investment memo: would you invest and why?</p><p><strong>Daily:</strong> Read TechCrunch, The Information, or Stratechery. Follow 5-10 VCs on Twitter/X for real-time deal flow and market commentary.</p><p><strong>Before interviews:</strong> Prepare 3 company deep-dives you can discuss for 10+ minutes each. Know their funding history, key metrics, competitive landscape, and your thesis on their future.</p><p><strong>Build in public:</strong> Start a blog, Substack, or Twitter thread analyzing startups. Many VC firms hire people who demonstrate public thinking about markets.</p>` },
];
